/* Generated By:JavaCC: Do not edit this line. MPReduceParserConstants.java */
package fi.wiskopdr.expressies.repr;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MPReduceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int MULTIPLY = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int POWER = 17;
  /** RegularExpression Id. */
  int EQ = 18;
  /** RegularExpression Id. */
  int NEQ = 19;
  /** RegularExpression Id. */
  int LE = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int GE = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int DOLLAR = 24;
  /** RegularExpression Id. */
  int INTERVAL = 25;
  /** RegularExpression Id. */
  int LPAR = 26;
  /** RegularExpression Id. */
  int RPAR = 27;
  /** RegularExpression Id. */
  int KOMMA = 28;
  /** RegularExpression Id. */
  int LBC = 29;
  /** RegularExpression Id. */
  int RBC = 30;
  /** RegularExpression Id. */
  int CONSTANT = 31;
  /** RegularExpression Id. */
  int DECFLOAT = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int LETTERORDIGIT = 35;
  /** RegularExpression Id. */
  int ABS = 36;
  /** RegularExpression Id. */
  int ACOS = 37;
  /** RegularExpression Id. */
  int ASIN = 38;
  /** RegularExpression Id. */
  int ATAN = 39;
  /** RegularExpression Id. */
  int BIN = 40;
  /** RegularExpression Id. */
  int CSC = 41;
  /** RegularExpression Id. */
  int COS = 42;
  /** RegularExpression Id. */
  int COT = 43;
  /** RegularExpression Id. */
  int DIFF = 44;
  /** RegularExpression Id. */
  int E = 45;
  /** RegularExpression Id. */
  int FAC = 46;
  /** RegularExpression Id. */
  int INFINITY = 47;
  /** RegularExpression Id. */
  int INT = 48;
  /** RegularExpression Id. */
  int LOG = 49;
  /** RegularExpression Id. */
  int NDELOG = 50;
  /** RegularExpression Id. */
  int PI = 51;
  /** RegularExpression Id. */
  int SQRT = 52;
  /** RegularExpression Id. */
  int SIN = 53;
  /** RegularExpression Id. */
  int SEC = 54;
  /** RegularExpression Id. */
  int SUM = 55;
  /** RegularExpression Id. */
  int TAN = 56;
  /** RegularExpression Id. */
  int ARBINT = 57;
  /** RegularExpression Id. */
  int ARBCOMPLEX = 58;
  /** RegularExpression Id. */
  int LIMIT = 59;
  /** RegularExpression Id. */
  int UP = 60;
  /** RegularExpression Id. */
  int DOWN = 61;
  /** RegularExpression Id. */
  int ID = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;
  /** Lexical state. */
  int WithinString = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"! \"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"\\\"\"",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "<token of kind 12>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<POWER>",
    "<EQ>",
    "\"neq\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"$\"",
    "<INTERVAL>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "<CONSTANT>",
    "<DECFLOAT>",
    "<DIGIT>",
    "<LETTER>",
    "<LETTERORDIGIT>",
    "\"abs\"",
    "\"acos\"",
    "\"asin\"",
    "\"atan\"",
    "\"binomial\"",
    "\"csc\"",
    "\"cos\"",
    "\"cot\"",
    "\"df\"",
    "\"e\"",
    "\"factorial\"",
    "\"infinity\"",
    "\"int\"",
    "\"log\"",
    "\"logd\"",
    "\"pi\"",
    "\"sqrt\"",
    "\"sin\"",
    "\"sec\"",
    "\"sum\"",
    "\"tan\"",
    "\"arbint\"",
    "\"arbcomplex\"",
    "\"limit\"",
    "\"!-\"",
    "\"!+\"",
    "<ID>",
  };

}
