package fi.graphtool.text;

import fi.graphtool.GraphTool;

public class Text_gr extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            {	"welkomTekst" , "Welcome to Java" },
            {	"GTIEP_opdrachten", "Tasks"},
            {	"GTIEP_schuifparameters", "Drag parameters"},
            {	"GTIEP_varLabel", "Variables"},
            {	"GTIEP_assenLabel", "Visible in coordinate system"},
            { 	"GTIEP_grafiekOptiesLabel", "Options for graphs"},
            {	"GTIEP_varXLabel", "Variable x-axis:"},
            {	"GTIEP_varYLabel", "Variable y-axis:"},
            {	"GTIEP_schaalDefCB", "Scale definition"},
            {	"GTIEP_schaalXLabel", "Scale x-axis:"},
            {	"GTIEP_schaalYLabel", "Scale y-axis:"},
            {	"GTIEP_schaalMinLabel", "Min"},
            {	"GTIEP_schaalMaxLabel", "Max"},
            {	"GTIEP_schaalStapLabel", "Step"},
            {	"GTIEP_varEditable", "Adjustable by student"},
            {	"GTIEP_assenZichtbaar", "Axes"},
            {	"GTIEP_roosterZichtbaar", "Grid"},
            { 	"GTIEP_roosterGrof", "Larger distance"},
            { 	"GTIEP_schaalZichtbaar", "Scale"},
            {	"GTIEP_xAs", "x-axis"},
            {	"GTIEP_yAs", "y-axis"},
            {	"GTIEP_piLijnenZichtbaar", "Pi on x-axis"},
            {	"GTIEP_xPositief", "Only positive x"},
            {	"GTIEP_yPositief", "Only positive y"},
            {	"GTIEP_xAsLog", "x-axis logarithmic"},
            {	"GTIEP_yAsLog", "y-axis logarithmic"},
            {	"GTIEP_zoomOptie", "Zoom option"},
            {	"GTIEP_volgOptie", "Trace option"},
            {	"GTIEP_sleepOptie", "Drag option"},
            {	"GTIEP_tekenComponentAan", "Graph drawing tool"},
            {	"GTIEP_tabelComponentAan", "Table tool"},
            {	"GTIEP_zoomInTabelOptie", "Zoom option in table"},
            {	"GTIEP_tabelTekenToolOptie", "Table as drawing tool"},
            {	"GTIEP_formuleComponentAan", "Formula editor"},
            {	"GTIEP_grafiekKleurenOptie", "Different colors"},
            {	"GTIEP_grafiekKleurInstelbaar", "Graph color adjustable"},
            {	"GTIEP_functieBeginZichtbaar", "Function prefix on new line"},
            {	"GTIEP_functieBeginAanpasbaar", "Function prefix adjustable by student"},
            {	"GTIEP_formeleFuncties", "Formal function notation"},
            {	"GTIEP_domeinInstelbaar", "Domain adjustable"},
            {	"GTIEP_hoogte", "Height formula editor"},
            {	"GTIEP_snapToGridPoints", "Snap to gridpoints"},
            {	"GTIEP_geenExtrapolatie", "Curve without extrapolation"},
            {	"GTIEP_welExtrapolatie", "Curve with extrapolation"},
            //{	"GTIEP_tekenGrafiekAan", "Button Draw graph"},
            {	"GTIEP_tekenGrafiekNauwk", "Accuracy"},
            //{	"TFEB_normaal", "Regular functions"},
            //{	"TFEB_ongelijkheden", "Inequalities"},
            //{	"TFEB_parametrisaties", "Parametrizations"},
            //{	"TFEB_impliciet", "Implicit curves"},
            {	"GTIEP_formuleEditorOpties", "Options formula editor"},
            {	"GTIEP_toegestaneTypes", "Allowed types of formulas:"},
            {	"GTIEP_functieToegestaan", "Functions"},
            {	"GTIEP_ongelijkheidToegestaan", "Inequalities"},
            {	"GTIEP_implicieteFunctieToegestaan", "Implicit functions"},
            {	"GTIEP_verticaleLijnToegestaan", "Vertical lines"},
            {	"GTIEP_parametrisatieToegestaan", "Parametrizations"},
            {	"GTIEP_voegtoe", "Add"},
            {	"GTIEP_wijzig", "Edit"},
            {	"GTIEP_verwijder", "Remove"},
            {	"GTIEP_naam", "Name"},
            {	"GTIEP_ondergrens", "Lower bound"},
            {	"GTIEP_bovengrens", "Upper bound"},
            {	"GTIEP_beginstand", "Initial position"},
            {	"GTIEP_sliderlengte", "Length slider"},
            
            {	"GTIEP_fout_stapKleinerGelijk0", "The stepsize needs to be greater than zero."},
            {	"GTIEP_fout_minGroterGelijkMax", "The minimum needs to be smaller than the maximum."},
            {	"GTIEP_fout_maxKleinerGelijkMin", "The maximum needs to be greater than the minimum."},
            {	"GTIEP_fout_geenGetal", "The input needs to be a number."},
            
            {	"GTIEP_veldComponentAan", "Field graph editor"},
            {	"GTIEP_veldGrafiekType", "Field graph plot type"},
            {	"GTIEP_veldGrafiekType_Quiver", "Quiver"}, 
            {	"GTIEP_veldGrafiekType_Streamline", "Streamline"}, 

            {	"GTIEP_veldEditorOpties", "Options field graph editor"},
            {	"GTIEP_veldComponentHoogte", "Height field graph editor"},
            
            {	"GTIEP_veldGrafiek_PijlGrootteModus", "Arrow size mode"}, 
            {	"GTIEP_veldGrafiek_PijlGrootteModus_RealValue", "Real value"}, 
            {	"GTIEP_veldGrafiek_PijlGrootteModus_FixedSize", "Fixed size (pixels)"}, 
            {	"GTIEP_veldGrafiek_PijlGrootteModus_ScaledSize", "Scaled Size"}, 
            
            {	"GTIEP_veldGrafiek_PijlGrootte", "Arrow size"}, 
            {	"GTIEP_veldGrafiek_PijlSchaalFactor", "Arrow scale factor"}, 
            
            {	"GTIEP_veldGrafiek_GroterGridStartPunten", "Startpoints on larger grid"}, 
            
            {	"Opdr_kiesOpdracht", "Choose the task type"},
            {	"Opdr_Opdracht1", "Find the formula(s) for the given graph(s)"},
            {	"Opdr_Opdracht2", "Find the formula for the given graph points"},
            {	"Opdr_Opdracht3", "Draw points or graph(s) for the given formula(s)"},
            {	"Opdr_Opdracht4", "Draw the points from the table in the graph"},
            {	"Opdr_maximumScore", "Maximum score"},
            {	"Opdr_nauwkeurigheid", "Accuracy"},
            {	"Opdr_minimumPunten", "Minimum number of points"},
            {	"Opdr_domeinControleren", "Check student domain"},
            {	"Opdr_leerlingZietTabel", "Table visible to student"},
            {	"Opdr_antwoordFormule", "Fill in the answer formula in the formula editor below."},
            {	"Opdr_tabelPuntenX", "Fill in the x-values of the graph points in the table below."},
            {	"Opdr_tabelPunten", "Fill in the graph points in the table below."},
            {	"Opdr_tekenRechte", "Student draws graph (straight lines)"},
            {	"Opdr_tekenMetExtrapolatie", "Student draws graph (with extrapolation)"},
            {	"Opdr_tekenZonderExtrapolatie", "Student draws graph (without extrapolation)"},
            
            {	"feedbackTekstPuntenDeels", "Not all points are drawn correctly (yet)."},
            {	"feedbackTekstGrafiekenDeels", "Not all graphs are drawn correctly (yet)."},
            {	"feedbackTekstLabelsAssen", "Put the correct labels at the axes."},
            {	"feedbackTekstTekenGrafiek", "Also draw the graph."},
            
            {	"fc_huidigDomein", "Current domain is: "},
            {	"fc_domeinBijFunctie", "Domain for function"},
            {	"fc_nieuwDomein", "Set domain to: "},
            
            {	"kijkNaButton", "Check"},
            {	"tekenGrafiekButton", "Draw graph"},
            {	"verbergGrafiekButton", "Hide graph"},
            {	"domeinButtonText", "Domain"},
            {	"enOfButton_En", "and"},
            {	"enOfButton_Of", "or"},
            {	"kleurKiezer", "Choose color"},
        //	{	"button1Label" , "text1_en" },
		//	{ 	"button2Label" , "text2_en" },
		//	....
		
		};
}


