package fi.graphtool.text;

public class Text_nl extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            {	"welkomTekst" , "Welkom bij Java" },
            {	"GTIEP_opdrachten", "Opdrachten" },
            {	"GTIEP_schuifparameters", "Schuifparameters"},
            {	"GTIEP_varLabel", "Variabelen"},
            {	"GTIEP_assenLabel", "Zichtbaar in assenstelsel"},
            { 	"GTIEP_grafiekOptiesLabel", "Opties voor grafieken"},
            {	"GTIEP_varXLabel", "Variabele x-as:"},
            {	"GTIEP_varYLabel", "Variabele y-as:"},
            {	"GTIEP_schaalDefCB", "Schaal definitie"},
            {	"GTIEP_schaalXLabel", "Schaal x-as:"},
            {	"GTIEP_schaalYLabel", "Schaal y-as:"},
            {	"GTIEP_schaalMinLabel", "Min"},
            {	"GTIEP_schaalMaxLabel", "Max"},
            {	"GTIEP_schaalStapLabel", "Stap"},
            {	"GTIEP_varEditable", "Aanpasbaar voor leerling"},
            {	"GTIEP_assenZichtbaar", "Assen"},
            {	"GTIEP_roosterZichtbaar", "Rooster"},
            { 	"GTIEP_roosterGrof", "Grof"},
            { 	"GTIEP_schaalZichtbaar", "Schaalverdeling"},
            {	"GTIEP_xAs", "x-as"},
            {	"GTIEP_yAs", "y-as"},
            {	"GTIEP_piLijnenZichtbaar", "Pi op x-as"},
            {	"GTIEP_xPositief", "Alleen positieve x"},
            {	"GTIEP_yPositief", "Alleen positieve y"},
            {	"GTIEP_xAsLog", "x-as logaritmisch"},
            {	"GTIEP_yAsLog", "y-as logaritmisch"},
            {	"GTIEP_zoomOptie", "Zoom-optie"},
            {	"GTIEP_volgOptie", "Volg-optie"},
            {	"GTIEP_sleepOptie", "Sleep-optie"},
            {	"GTIEP_tekenComponentAan", "Grafiek-tekentool"},
            {	"GTIEP_tabelComponentAan", "Tabeltool"},
            {	"GTIEP_zoomInTabelOptie", "Zoom-optie in tabel"},
            {	"GTIEP_tabelTekenToolOptie", "Tabel als tekentool"},
            {	"GTIEP_formuleComponentAan", "Formule-editor"},
            {	"GTIEP_grafiekKleurenOptie", "Verschillende kleuren"},
            {	"GTIEP_grafiekKleurInstelbaar", "Grafiekkleur instelbaar"},
            {	"GTIEP_functieBeginZichtbaar", "Functiebegin op nieuwe regel"},
            {	"GTIEP_functieBeginAanpasbaar", "Functiebegin aanpasbaar voor leerling"},
            {	"GTIEP_formeleFuncties", "Formele functie-notatie"},
            {	"GTIEP_domeinInstelbaar", "Domein instelbaar"},
            {	"GTIEP_hoogte", "Hoogte formule-editor"},
            {	"GTIEP_snapToGridPoints", "Magnetische roosterpunten"},
            {	"GTIEP_geenExtrapolatie", "Kromme zonder extrapolatie"},
            {	"GTIEP_welExtrapolatie", "Kromme met extrapolatie"},
            //{	"GTIEP_tekenGrafiekAan", "Knop Teken grafiek"},
            {	"GTIEP_tekenGrafiekNauwk", "Nauwkeurigheid"},
            //{	"TFEB_normaal", "Gewone functies"},
            //{	"TFEB_ongelijkheden", "Ongelijkheden"},
            //{	"TFEB_parametrisaties", "Parametrisaties"},
            //{	"TFEB_impliciet", "Impliciete krommen"},
            {	"GTIEP_formuleEditorOpties", "Opties formule-editor"},
            {	"GTIEP_toegestaneTypes", "Toegestane types formules:"},
            {	"GTIEP_functieToegestaan", "Functies"},
            {	"GTIEP_ongelijkheidToegestaan", "Ongelijkheden"},
            {	"GTIEP_implicieteFunctieToegestaan", "Impliciete functies"},
            {	"GTIEP_verticaleLijnToegestaan", "Verticale lijnen"},
            {	"GTIEP_parametrisatieToegestaan", "Parametrisaties"},
            {	"GTIEP_voegtoe", "Voeg toe"},
            {	"GTIEP_wijzig", "Wijzig"},
            {	"GTIEP_verwijder", "Verwijder"},
            {	"GTIEP_naam", "Naam"},
            {	"GTIEP_ondergrens", "Ondergrens"},
            {	"GTIEP_bovengrens", "Bovengrens"},
            {	"GTIEP_beginstand", "Beginstand"},
            {	"GTIEP_stapgrootte", "Stapgrootte"},
            {	"GTIEP_sliderlengte", "Lengte slider"},
            {	"GTIEP_dubbeleNaam", "De naam van deze parameter is al in gebruik"},
            {	"GTIEP_waarschuwing", "Waarschuwing"},
            
            {	"GTIEP_fout_stapKleinerGelijk0", "De stapgrootte dient groter te zijn dan nul."},
            {	"GTIEP_fout_minGroterGelijkMax", "Het minimum dient kleiner te zijn dan het maximum."},
            {	"GTIEP_fout_maxKleinerGelijkMin", "Het maximum dient groter te zijn dan het minimum."},
            {	"GTIEP_fout_geenGetal", "De invoer hoort een getal te zijn."},
            
            {	"GTIEP_veldComponentAan", "Veldgrafiek-editor"},
            {	"GTIEP_veldGrafiekType", "Veldgrafiek plot type"},
            {	"GTIEP_veldGrafiekType_Quiver", "Pijlen"}, 
            {	"GTIEP_veldGrafiekType_Streamline", "Streamline"}, 

            {	"GTIEP_veldEditorOpties", "Opties veldgrafiek-editor"},
            {	"GTIEP_veldComponentHoogte", "Hoogte veldgrafiek-editor"},
            
            {	"GTIEP_veldGrafiek_PijlGrootteModus", "Pijlgrootte modus"}, 
            {	"GTIEP_veldGrafiek_PijlGrootteModus_RealValue", "Werkelijke waarde"}, 
            {	"GTIEP_veldGrafiek_PijlGrootteModus_FixedSize", "Vaste grootte (beeldpunten)"}, 
            {	"GTIEP_veldGrafiek_PijlGrootteModus_ScaledSize", "Geschaalde grootte"}, 
            
            {	"GTIEP_veldGrafiek_PijlGrootte", "Pijlgrootte"}, 
            {	"GTIEP_veldGrafiek_PijlSchaalFactor", "Pijlgrootte schaalfactor"}, 
            
            {	"GTIEP_veldGrafiek_GroterGridStartPunten", "Startpunten op grof grid"}, 
            
            {	"Opdr_kiesOpdracht", "Kies het type opdracht"},
            {	"Opdr_Opdracht1", "Vind de formule(s) bij de gegeven grafiek(en)"},
            {	"Opdr_Opdracht2", "Vind de formule bij de gegeven grafiekpunten"},
            {	"Opdr_Opdracht3", "Teken een aantal punten/de grafiek(en) bij de gegeven formule(s)"},
            {	"Opdr_Opdracht4", "Teken de punten uit de tabel in de grafiek"},
            {	"Opdr_maximumScore", "Maximale score"},
            {	"Opdr_nauwkeurigheid", "Nauwkeurigheid"},
            {	"Opdr_minimumPunten", "Minimaal aantal punten"},
            {	"Opdr_domeinControleren", "Kijk leerlingdomein na"},
            {	"Opdr_leerlingZietTabel", "Leerling ziet tabel"},
            {	"Opdr_antwoordFormule", "Voer in de formule-editor hieronder de antwoordformule in."},
            {	"Opdr_tabelPuntenX", "Vul in de tabel hieronder de x-waarden van de grafiekpunten in."},
            {	"Opdr_tabelPunten", "Vul in de tabel hieronder de te tekenen punten in."},    
            {	"Opdr_tekenRechte", "Leerling tekent grafiek (rechte verbindingen)"},
            {	"Opdr_tekenMetExtrapolatie", "Leerling tekent grafiek (met extrapolatie)"},
            {	"Opdr_tekenZonderExtrapolatie", "Leerling tekent grafiek (zonder extrapolatie)"},
            {	"Opdr_checkExternal", "Extern controleren"},
            
            {	"feedbackTekstPuntenDeels", "Nog niet alle punten zijn (goed) getekend."},
            {	"feedbackTekstGrafiekenDeels", "Nog niet alle grafieken zijn goed getekend."},
            {	"feedbackTekstLabelsAssen", "Zet de juiste letters bij de assen."},
            {	"feedbackTekstTekenGrafiek", "Let op: teken ook de grafiek."},
            {	"feedbackTekstTeWeinigPunten", "Let op: je hebt nog niet voldoende punten getekend."},
            
            {	"fc_huidigDomein", "Domein is nu: "},
            {	"fc_domeinBijFunctie", "Domein bij functie"},
            {	"fc_nieuwDomein", "Nieuw domein: "},
            
            {	"kijkNaButton", "Klaar"},
            {	"tekenGrafiekButton", "Teken grafiek"},
            {	"verbergGrafiekButton", "Verberg grafiek"},
            {	"domeinButtonText", "Domein"},
            {	"enOfButton_En", "en"},
            {	"enOfButton_Of", "of"},
            {	"kleurKiezer", "Kies kleur"},
        //	{	"button1Label" , "text1_nl" },
		//	{ 	"button2Label" , "text2_nl" },
		//	....
		
            {  "CBA_input", "invoer" },
            {  "CBA_equation.twoGraphs", "twee grafieken" },
            {  "CBA_double.parameter", "parameterwaarde" },
            {  "CBA_double.trace", "tracewaarde" },
            {  "CBA_expression.1", "functie 1" },
            {  "CBA_expression.2", "functie 2" },
            {  "CBA_expression.3", "functie 3" },
            {  "CBA_expression.4", "functie 4" },
            {  "CBA_expression.5", "functie 5" },
            
		};
}


