<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>fi.wiskopdr</groupId>
	<artifactId>wiskopdr</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<build>
		<finalName>${project.artifactId}</finalName>
		<sourceDirectory>src</sourceDirectory>
		<testSourceDirectory>test</testSourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<phase>process-classes</phase>
						<configuration>
							<outputDirectory>${project.build.directory}</outputDirectory>
							<includeScope>compile</includeScope>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>fi.wiskopdr.WiskOpdr</mainClass>
 						</manifest>
						<index>true</index>
					</archive>
				</configuration>
			</plugin>
                   <plugin>
                        <groupId>com.github.wvengen</groupId>
                        <artifactId>proguard-maven-plugin</artifactId>
                        <version>2.0.8</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>proguard</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <proguardVersion>5.2</proguardVersion>
                            <options>
                                <option>-verbose</option>
                                <option>-dontwarn</option> 
                                <option>-printconfiguration mapping.txt</option>
                            </options>
                            <obfuscate>true</obfuscate>                    
                            <inputDirectory>${project.build.directory}</inputDirectory>
<!--                             <injar>${project.build.finalName}.jar</injar> -->
                            <!-- uncomment to change the output file 
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <outjar>${project.build.finalName}.jar</outjar>
                            -->
                            <exclusions>
                            		<exclusion><groupId>fi.graphtool</groupId><artifactId>graphtool</artifactId></exclusion>
                            		<exclusion><groupId>fi.balansfruitapplet</groupId><artifactId>balansfruitapplet</artifactId></exclusion>
                            </exclusions>
                            <proguardInclude>toolfiles/config.pro</proguardInclude>
                            <libs>
                                <lib>${java.home}/lib/rt.jar</lib>
                                <lib>${java.home}/lib/jsse.jar</lib>
                            </libs>
                            <addMavenDescriptor>false</addMavenDescriptor>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>net.sf.proguard</groupId>
                                <artifactId>proguard-base</artifactId>
                                <version>5.2</version>
                                <scope>runtime</scope>
                            </dependency>
                        </dependencies>
                    </plugin>
 		</plugins>
	</build>
	<properties>
		<project.build.sourceEncoding>ISO-8859-1</project.build.sourceEncoding>
		<maven.test.skip>true</maven.test.skip>
	</properties>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.geogebra</groupId>
			<artifactId>geogebra3</artifactId>
			<version>3.2</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/output/jar/geogebra3.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>org.geogebra</groupId>
			<artifactId>geogebra</artifactId>
			<version>4.0.29</version>
		</dependency>
		<dependency>
			<groupId>org.geogebra</groupId>
			<artifactId>geogebra_cas</artifactId>
			<version>4.0.29</version>
		</dependency>
		<dependency>
			<groupId>org.geogebra</groupId>
			<artifactId>geogebra_main</artifactId>
			<version>4.0.29</version>
		</dependency>
		<dependency>
			<groupId>fi.balansfruitapplet</groupId>
			<artifactId>balansfruitapplet</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.graphtool</groupId>
			<artifactId>graphtool</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.github.lookfirst</groupId>
			<artifactId>sardine</artifactId>
			<version>5.1</version>
		</dependency>
	</dependencies>
	<name>WiskOpdr</name>
</project>
