<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fi.previewhtml</groupId>
  <artifactId>PreviewHTML</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>HTML Previewer with Scorm support</name>
  <properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <dependencies>
  	<dependency>
  		<groupId>nl.uu.fi.dwo</groupId>
  		<artifactId>DWO-commons-lib</artifactId>
  		<version>2.3.11</version>
  	</dependency>
	<dependency>
		<groupId>org.osgi</groupId>
		<artifactId>osgi.promise</artifactId>
		<version>6.0.0</version>
	</dependency>
	<dependency>
		<groupId>nl.numworx.swingbrowser</groupId>
		<artifactId>swingbrowser-api</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>nl.numworx.swingbrowser</groupId>
		<artifactId>swingbrowser-jxb</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<scope>test</scope>
		<exclusions>
			<exclusion>
				<groupId>com.teamdev.jxbrowser</groupId>
				<artifactId>jxbrowser-cross-platform</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.teamdev.jxbrowser</groupId>
				<artifactId>jxbrowser-swing</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>nl.numworx.swingbrowser</groupId>
		<artifactId>swingbrowser-jfx</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<scope>test</scope>
	</dependency>
  </dependencies>
  <build>
  	<finalName>previewhtml</finalName>
  	<plugins>
  	<plugin>
  		<artifactId>maven-compiler-plugin</artifactId>
  		<version>3.1</version>
  	</plugin>
	  <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.5.3</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
					<Trusted-Only>true</Trusted-Only>
					<Permissions>all-permissions</Permissions>
					<Codebase>*.uu.nl spindle.fisme.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl localhost dme.mathhouse.org</Codebase>
					<Caller-Allowable-Codebase>*.uu.nl spindle.fisme.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl localhost dme.mathhouse.org</Caller-Allowable-Codebase>
					<Application-Name>Preview HTML</Application-Name>
					<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
					<Export-Package>fi.previewhtml</Export-Package>
          </instructions>
        </configuration>
      </plugin>	
 <!--      <plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-jar-plugin</artifactId>
		<version>2.5</version>
		<configuration>
			<archive>
				<manifest>
					<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
					<addClasspath>false</addClasspath>
				</manifest>
				<manifestEntries>
					<Trusted-Only>true</Trusted-Only>
					<Permissions>all-permissions</Permissions>
					<Codebase>*.uu.nl spindle.fisme.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl localhost dme.mathhouse.org</Codebase>
					<Caller-Allowable-Codebase>*.uu.nl spindle.fisme.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl localhost dme.mathhouse.org</Caller-Allowable-Codebase>
					<Application-Name>Preview HTML</Application-Name>
					<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
				</manifestEntries>
			</archive>
		</configuration>
	</plugin>
 -->	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-jarsigner-plugin</artifactId>
		<version>1.4</version>
		<executions>
			<execution>
				<phase>package</phase>
				<goals>
					<goal>sign</goal>
				</goals>
			</execution>
			<execution>
				<id>verify</id>
				<goals>
					<goal>verify</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<keystore>${dwoKeyStore}</keystore>
			<alias>${dwoCertKeyAlias}</alias>
			<storepass>${dwoCertKeyStorePassword}</storepass>
			<keypass>${dwoCertKeyPassword}</keypass>
			<sigfile>UU</sigfile>
			<tsa>http://sha256timestamp.ws.symantec.com/sha256/timestamp</tsa>
		</configuration>
	</plugin>  

  	
  	</plugins>
  
  
  
  </build>
  <packaging>bundle</packaging>
      <distributionManagement>
        <repository>
            <id>snapshots</id>
            <!--<name>libs-snapshot</name>-->
            <url>https://repos.dwo.nl/artifactory/libs-snapshot-local</url>    
        </repository>
    </distributionManagement>    
  
</project>