<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>nl.numworx.geodefiner</groupId>
	<artifactId>geodefiner-common</artifactId>
	<version>0.0.3-SNAPSHOT</version>
	<properties>
		<maven.compiler.source>1.7</maven.compiler.source>
		<maven.compiler.target>1.7</maven.compiler.target>
		<euclidesVersion>0.0.3</euclidesVersion>
	</properties>
	<dependencies>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-core</artifactId>
			<version>${euclidesVersion}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-util</artifactId>
			<version>${euclidesVersion}</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-expr</artifactId>
			<version>${euclidesVersion}</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.mobile</groupId>
			<artifactId>interaction</artifactId>
			<version>0.0.3</version>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>2.7.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdrgwt</groupId>
			<artifactId>WiskOpdrGWT</artifactId>
			<version>0.0.1</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
	</build>
	<distributionManagement>
		<repository>
			<id>release</id>
			<url>https://repos.dwo.nl/artifactory/libs-release-local</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<name>libs-snapshot</name>
			<url>https://repos.dwo.nl/artifactory/libs-snapshot-local</url>
		</snapshotRepository>
	</distributionManagement>
	<scm>
		<developerConnection>scm:svn:https://svn.science.uu.nl/repos/sci.velth101.numworx/geodefiner-common/trunk</developerConnection>
	</scm>
</project>
