<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fi.binomverdeling</groupId>
  <artifactId>binomverdeling</artifactId>
  <name>BinomVerdeling</name>
  <description>BinomVerdeling</description>
	<parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>wiskopdr-parent</artifactId>
	  <version>2.5.49-SNAPSHOT</version>
	  <relativePath>../WiskOpdrParent</relativePath>
	</parent>
   <build>
	<finalName>${project.artifactId}</finalName>
     <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
   				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>fi.binomverdeling.BinomVerdeling</Bundle-SymbolicName>
 				<Main-Class>fi.binomverdeling.BinomVerdeling</Main-Class>
				<Bundle-Name>BinomVerdeling</Bundle-Name>
				<Bundle-Description />
 				<Export-Package>fi.binomverdeling</Export-Package>
 				<Import-Package>fi.beans.mainframe,fi.beans.scorm,fi.beans.wiskopdrbeans,*</Import-Package>
          	</instructions>
          </configuration>
         </plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
 			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<version>2.0.14</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<proguardVersion>6.1</proguardVersion>
					<options>
						<option>-verbose</option>
						<option>-dontwarn</option>
						<option>-printconfiguration target/mapping.txt</option>
					</options>
					<obfuscate>true</obfuscate>
					<inputDirectory>${project.build.directory}</inputDirectory>
					<proguardInclude>toolfiles/config.pro</proguardInclude>
					<libs>
						<lib>${proguard.lib}</lib>
					</libs>
					<addMavenDescriptor>false</addMavenDescriptor>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>net.sf.proguard</groupId>
						<artifactId>proguard-base</artifactId>
						<version>6.1.0</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
			</plugin>
                    <plugin>
                        <groupId>com.github.batkinson.plugins</groupId>
                        <artifactId>maven-pack200-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <id>pack-jars</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>pack</goal>
                                </goals>
                                <configuration>
                                    <normalizeOnly>false</normalizeOnly>
                            		<processMainArtifact>true</processMainArtifact>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>        
    </plugins>
  </build>
	<dependencies>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwo-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdr.beans</groupId>
			<artifactId>wiskopdrbeans</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
	</dependencies>
	<properties>
		<project.build.sourceEncoding>ISO-8859-1</project.build.sourceEncoding>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
	</properties>
</project>
