#nooit, gebruikt serialized objects in launchdata
#fi.verknippen
#fi.mozarch
#fi.tegels
#fi.geomalgebra
#deze geen serialized objects in launchdata
nl.numworx.geodefiner.GeoDefiner: geodefiner.jar
fi.algebrapijlenopdr.AlgebraPijlenOpdr: algebrapijlenopdr.jar
fi.javalogoweb3d.JavaLogoWeb3d: javalogoweb3d.jar
fi.stroomdiagrammen.Stroomdiagrammen: stroomdiagrammen.jar
fi.sliderwidget.SliderWidget: sliderwidget.jar
