#nooit, gebruikt serialized objects in launchdata
#fi.verknippen
#fi.mozarch
#fi.tegels
#fi.geomalgebra
#fi.stroomdiagrammen
#fi.statistiek
#deze geen serialized objects in launchdata
nl.numworx.geodefiner.GeoDefiner: geodefiner.jar
fi.algebrapijlenopdr.AlgebraPijlenOpdr: algebrapijlenopdr.jar
fi.binomverdeling.BinomVerdeling: binomverdeling.jar
#fi.doorziendwo.DoorzienDWO: doorziendwo.jar
fi.figuursnijden.Snijden: figuursnijden.jar
fi.flowdiagrams.FlowDiagrams: flowdiagrams.jar
fi.geodefull.GeodeFull: geodefull.jar
fi.geomalgebra1d.GeomAlgebra1d: geomalgebra1d.jar
fi.javalogoweb3d.JavaLogoWeb3d: javalogoweb3d.jar
fi.nabouwenaanzichten.NabouwenAanzichten: nabouwenaanzichten.jar
fi.normaleverdeling.NormaleVerdeling: normaleverdeling.jar
fi.omtrekapplet.OmtrekApplet: optrekapplet.jar
fi.oppervlaktealgebra.OppervlakteAlgebra: oppervlaktealgebra.jar
fi.sliderwidget.SliderWidget: sliderwidget.jar
#fi.statistiek.Statistiek: statistiek.jar
#fi.stroomdiagrammen.Stroomdiagrammen: stroomdiagrammen.jar
#fi.tegels.Tegels: tegels.jar
fi.tekenveelvlakopdr.TekenVeelvlakOpdr: tekenveelvlakopdr.jar
fi.vangen.Vangen: vangen.jar
fi.vergroten.Vergroten: vergroten.jar
