<?xml version="1.0" encoding="UTF-8"?>
<!--
Deze XSD bevat het content-zoekprofiel PO-VO v1.0. De volledige specificatie wordt beheerd door de vereniging EduStandaard (http://www.edustandaard.nl).
Auteursrecht en vrijwaring:
Dit bestand is vrij te verspreiden, te publiceren of te hergebruiken, mits de bron duidelijk vermeld wordt. Dit bestand valt onder de Nederlandse versie van de Creative Commons licentie "Naamsvermelding 2.0 Nederland ". Zie http://creativecommons.org/licenses/by/2.0/nl/
Disclaimer:
De organisatie, medewerkers, auteurs, ontwerpers en bouwers van www.edustandaard.nl spannen zich in en handelen naar beste weten om de informatie, de hyperlinks en de downloads op www.edustandaard.nl zo volledig en actueel mogelijk te houden. Ondanks deze zorg is het mogelijk dat de inhoud onvolledig en/of onjuist is. Ook kan de informatie zonder vooraankondiging en op ieder moment worden gewijzigd en/of ingetrokken. Om deze redenen kunnen aan deze website geen rechten worden ontleend. Door deze website te gebruiken stemt u in met deze disclaimer.
-->
<xsd:schema targetNamespace="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.w3.org/XML/1998/namespace">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.imsglobal.org/xsd/ims_xml.xsd"/>
	<!-- ************************************************* -->
	<!-- **    Root Container Type Declaration    ** -->
	<!-- ************************************************* -->
	<xsd:redefine schemaLocation="http://www.imsglobal.org/xsd/imsmd_rootv1p2p1.xsd">
		<xsd:complexType name="lomType">
			<xsd:complexContent>
				<xsd:restriction base="lomType">
					<xsd:sequence>
						<xsd:element ref="general"/>
						<xsd:element ref="lifecycle"/>
						<xsd:element ref="metametadata" minOccurs="0"/>
						<xsd:element ref="technical"/>
						<xsd:element ref="educational"/>
						<xsd:element ref="rights"/>
						<xsd:element ref="relation" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="classification" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<!-- ************************************************* -->
		<!-- ** Complex Container Type Declaration ** -->
		<!-- ************************************************* -->
		<xsd:complexType name="generalType">
			<xsd:complexContent>
				<xsd:restriction base="generalType">
					<xsd:sequence>
						<xsd:element ref="identifier" minOccurs="0"/>
						<xsd:element name="title" type="titleType"/>
						<xsd:element name="catalogentry" type="catalogentryType" maxOccurs="unbounded"/>
						<xsd:element name="language" maxOccurs="unbounded">
							<xsd:complexType name="languageType">
								<xsd:simpleContent>
									<xsd:extension base="language"/>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="description" type="descriptionType" maxOccurs="unbounded"/>
						<xsd:element name="keyword" type="keywordType" maxOccurs="unbounded"/>
						<xsd:element ref="coverage" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="structure" minOccurs="0"/>
						<xsd:element name="aggregationlevel" type="aggregationlevelType"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="catalogentryType">
			<xsd:complexContent>
				<xsd:restriction base="catalogentryType">
					<xsd:sequence>
						<xsd:element ref="catalog"/>
						<xsd:element ref="entry"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="lifecycleType">
			<xsd:complexContent>
				<xsd:restriction base="lifecycleType">
					<xsd:sequence>
						<xsd:element name="version" type="versionType"/>
						<xsd:element name="status" type="statusType"/>
						<xsd:element ref="contribute" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="technicalType">
			<xsd:complexContent>
				<xsd:restriction base="technicalType">
					<xsd:sequence>
						<xsd:element ref="format" maxOccurs="unbounded"/>
						<xsd:element ref="size" minOccurs="0"/>
						<xsd:element ref="location" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="requirement" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="installationremarks" minOccurs="0"/>
						<xsd:element ref="otherplatformrequirements" minOccurs="0"/>
						<xsd:element ref="duration" minOccurs="0"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="educationalType">
			<xsd:complexContent>
				<xsd:restriction base="educationalType">
					<xsd:sequence>
						<xsd:element ref="interactivitytype" minOccurs="0"/>
						<xsd:element name="learningresourcetype" type="learningresourcetypeType" maxOccurs="unbounded"/>
						<xsd:element ref="interactivitylevel" minOccurs="0"/>
						<xsd:element ref="semanticdensity" minOccurs="0"/>
						<xsd:element name="intendedenduserrole" type="intendedenduserroleType" maxOccurs="unbounded"/>
						<xsd:element name="context" type="contextType" maxOccurs="unbounded"/>
						<xsd:element name="typicalagerange" type="typicalagerangeType" maxOccurs="unbounded"/>
						<xsd:element ref="difficulty" minOccurs="0"/>
						<xsd:element ref="typicallearningtime" minOccurs="0"/>
						<xsd:element ref="description" minOccurs="0"/>
						<xsd:element ref="language" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="rightsType">
			<xsd:complexContent>
				<xsd:restriction base="rightsType">
					<xsd:sequence>
						<xsd:element name="cost" type="costType"/>
						<xsd:element name="copyrightandotherrestrictions" type="copyrightandotherrestrictionsType"/>
						<xsd:element name="description" type="descriptionType"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="classificationType">
			<xsd:complexContent>
				<xsd:restriction base="classificationType">
					<xsd:sequence>
						<xsd:element name="purpose" type="purposeType"/>
						<xsd:element ref="taxonpath" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="description" minOccurs="0"/>
						<xsd:element ref="keyword" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:group ref="grp.any"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<!-- ************************************* -->
		<!-- ** Complex Type Declaration ** -->
		<!-- ************************************* -->
		<xsd:complexType name="aggregationlevelType">
			<xsd:complexContent>
				<xsd:restriction base="aggregationlevelType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="aggregationlevelSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="aggregationlevelValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="contextType">
			<xsd:complexContent>
				<xsd:restriction base="contextType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="contextSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="contextValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="copyrightandotherrestrictionsType">
			<xsd:complexContent>
				<xsd:restriction base="copyrightandotherrestrictionsType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="copyrightandotherrestrictionsSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="copyrightandotherrestrictionsValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="costType">
			<xsd:complexContent>
				<xsd:restriction base="costType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="costSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="costValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="descriptionType">
			<xsd:complexContent>
				<xsd:restriction base="descriptionType">
					<xsd:sequence>
						<xsd:element ref="langstring"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="intendedenduserroleType">
			<xsd:complexContent>
				<xsd:restriction base="intendedenduserroleType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="intendedenduserroleSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="intendedenduserroleValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="keywordType">
			<xsd:complexContent>
				<xsd:restriction base="keywordType">
					<xsd:sequence>
						<xsd:element ref="langstring"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="learningresourcetypeType">
			<xsd:complexContent>
				<xsd:restriction base="learningresourcetypeType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="learningresourcetypeSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="learningresourcetypeValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="purposeType">
			<xsd:complexContent>
				<xsd:restriction base="purposeType">
					<xsd:choice>
						<xsd:sequence>
							<xsd:element name="source">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="langstring">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="purposeSource_CKS">
														<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="value">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="langstring">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="purposeValue_CKS">
														<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:sequence>
							<xsd:element name="source">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="langstring">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="purposeSource_anders">
														<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="value">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="langstring">
											<xsd:complexType>
												<xsd:simpleContent>
													<xsd:extension base="xsd:string">
														<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
													</xsd:extension>
												</xsd:simpleContent>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:choice>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="statusType">
			<xsd:complexContent>
				<xsd:restriction base="statusType">
					<xsd:sequence>
						<xsd:element name="source">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="statusSource">
													<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="value">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="langstring">
										<xsd:complexType>
											<xsd:simpleContent>
												<xsd:extension base="statusValue">
													<xsd:attribute ref="xml:lang" use="required" fixed="nl"/>
												</xsd:extension>
											</xsd:simpleContent>
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="titleType">
			<xsd:complexContent>
				<xsd:restriction base="titleType">
					<xsd:sequence>
						<xsd:element ref="langstring"/>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="typicalagerangeType">
			<xsd:complexContent>
				<xsd:restriction base="typicalagerangeType">
					<xsd:sequence>
						<xsd:element name="langstring">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="typicalagerange">
										<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
		<xsd:complexType name="versionType">
			<xsd:complexContent>
				<xsd:restriction base="versionType">
					<xsd:sequence>
						<xsd:element name="langstring">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="version">
										<xsd:attribute ref="xml:lang" use="required" fixed="x-none"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:redefine>
	<!-- ********************************** -->
	<!-- ** Vocabulary Declaration ** -->
	<!-- ********************************** -->
	<xsd:simpleType name="aggregationlevelSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="LOMv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="aggregationlevelValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="1"/>
			<xsd:enumeration value="2"/>
			<xsd:enumeration value="3"/>
			<xsd:enumeration value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="contextSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPPOVOv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="contextValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="cluster 1 (visuele beperkingen)"/>
			<xsd:enumeration value="cluster 2 (auditieve beperkingen)"/>
			<xsd:enumeration value="cluster 3 (motorische/verstandelijke beperkingen)"/>
			<xsd:enumeration value="cluster 4 (ontwikkelingsachterstand)"/>
			<xsd:enumeration value="VVE"/>
			<xsd:enumeration value="PO onderbouw"/>
			<xsd:enumeration value="PO middenbouw"/>
			<xsd:enumeration value="PO bovenbouw"/>
			<xsd:enumeration value="VMBO, 1"/>
			<xsd:enumeration value="VMBO, 2"/>
			<xsd:enumeration value="VMBO theoretische leerweg, 3"/>
			<xsd:enumeration value="VMBO theoretische leerweg, 4"/>
			<xsd:enumeration value="VMBO kaderberoepsgerichte leerweg, 3"/>
			<xsd:enumeration value="VMBO kaderberoepsgerichte leerweg, 4"/>
			<xsd:enumeration value="VMBO basisberoepsgerichte leerweg, 3"/>
			<xsd:enumeration value="VMBO basisberoepsgerichte leerweg, 4"/>
			<xsd:enumeration value="VMBO gemengde leerweg, 3"/>
			<xsd:enumeration value="VMBO gemengde leerweg, 4"/>
			<xsd:enumeration value="VMBO leerwegondersteunend"/>
			<xsd:enumeration value="VMBO praktijkonderwijs, 1"/>
			<xsd:enumeration value="VMBO praktijkonderwijs, 2"/>
			<xsd:enumeration value="VMBO praktijkonderwijs, 3"/>
			<xsd:enumeration value="VMBO praktijkonderwijs, 4"/>
			<xsd:enumeration value="VMBO praktijkonderwijs, 5"/>
			<xsd:enumeration value="VMBO praktijkonderwijs, 6"/>
			<xsd:enumeration value="HAVO, 1"/>
			<xsd:enumeration value="HAVO, 2"/>
			<xsd:enumeration value="HAVO, 3"/>
			<xsd:enumeration value="HAVO, studiehuis"/>
			<xsd:enumeration value="VWO, 1"/>
			<xsd:enumeration value="VWO, 2"/>
			<xsd:enumeration value="VWO, 3"/>
			<xsd:enumeration value="VWO, studiehuis"/>
			<xsd:enumeration value="BVE"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="copyrightandotherrestrictionsSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPPOVOv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="copyrightandotherrestrictionsValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ja"/>
			<xsd:enumeration value="nee"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="costSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPPOVOv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="costValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ja"/>
			<xsd:enumeration value="nee"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="format">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="niet digitaal"/>
			<xsd:enumeration value="application/x-base64"/>
			<xsd:enumeration value="application/x-binary"/>
			<xsd:enumeration value="application/x-java-applet"/>
			<xsd:enumeration value="application/mac-binhex40"/>
			<xsd:enumeration value="application/vnd.ms-excel"/>
			<xsd:enumeration value="application/msword"/>
			<xsd:enumeration value="application/pdf"/>
			<xsd:enumeration value="application/postscript"/>
			<xsd:enumeration value="application/x-ppt"/>
			<xsd:enumeration value="application/rtf"/>
			<xsd:enumeration value="application/sdp"/>
			<xsd:enumeration value="application/x-smil"/>
			<xsd:enumeration value="application/x-uue"/>
			<xsd:enumeration value="application/x-compressed"/>
			<xsd:enumeration value="application/x-gzip-compressed"/>
			<xsd:enumeration value="application/x-pn-realmedia"/>
			<xsd:enumeration value="application/x-shockwave-flash"/>
			<xsd:enumeration value="application/x-stuffit"/>
			<xsd:enumeration value="application/x-zip-compressed"/>
			<xsd:enumeration value="application/zip"/>
			<xsd:enumeration value="audio/basic"/>
			<xsd:enumeration value="audio/x-midi"/>
			<xsd:enumeration value="audio/x-mp3"/>
			<xsd:enumeration value="audio/mpeg"/>
			<xsd:enumeration value="audio/x-pn-realaudio"/>
			<xsd:enumeration value="audio/x-pn-realaudio-plugin"/>
			<xsd:enumeration value="audio/x-wav"/>
			<xsd:enumeration value="image/bmp"/>
			<xsd:enumeration value="image/gif"/>
			<xsd:enumeration value="image/jpeg"/>
			<xsd:enumeration value="image/png"/>
			<xsd:enumeration value="image/tiff"/>
			<xsd:enumeration value="image/x-wmf"/>
			<xsd:enumeration value="model/vrml"/>
			<xsd:enumeration value="text/html"/>
			<xsd:enumeration value="text/plain"/>
			<xsd:enumeration value="text/richtext"/>
			<xsd:enumeration value="text/xml"/>
			<xsd:enumeration value="video/x-avi"/>
			<xsd:enumeration value="video/x-pn-realvideo"/>
			<xsd:enumeration value="video/x-pn-realvideo-plugin"/>
			<xsd:enumeration value="video/quicktime"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="intendedenduserroleSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPPOVOv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="intendedenduserroleValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="leerling"/>
			<xsd:enumeration value="docent"/>
			<xsd:enumeration value="begeleider"/>
			<xsd:enumeration value="ouder/verzorger"/>
			<xsd:enumeration value="management/administratie"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="language">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="x-none"/>
			<xsd:enumeration value="aa"/>
			<xsd:enumeration value="ab"/>
			<xsd:enumeration value="af"/>
			<xsd:enumeration value="am"/>
			<xsd:enumeration value="ar"/>
			<xsd:enumeration value="as"/>
			<xsd:enumeration value="ay"/>
			<xsd:enumeration value="az"/>
			<xsd:enumeration value="ba"/>
			<xsd:enumeration value="be"/>
			<xsd:enumeration value="bg"/>
			<xsd:enumeration value="bh"/>
			<xsd:enumeration value="bi"/>
			<xsd:enumeration value="bn"/>
			<xsd:enumeration value="bo"/>
			<xsd:enumeration value="br"/>
			<xsd:enumeration value="ca"/>
			<xsd:enumeration value="co"/>
			<xsd:enumeration value="cs"/>
			<xsd:enumeration value="cy"/>
			<xsd:enumeration value="da"/>
			<xsd:enumeration value="de"/>
			<xsd:enumeration value="dz"/>
			<xsd:enumeration value="el"/>
			<xsd:enumeration value="en"/>
			<xsd:enumeration value="eo"/>
			<xsd:enumeration value="es"/>
			<xsd:enumeration value="et"/>
			<xsd:enumeration value="eu"/>
			<xsd:enumeration value="fa"/>
			<xsd:enumeration value="fi"/>
			<xsd:enumeration value="fj"/>
			<xsd:enumeration value="fo"/>
			<xsd:enumeration value="fr"/>
			<xsd:enumeration value="fy"/>
			<xsd:enumeration value="ga"/>
			<xsd:enumeration value="gd"/>
			<xsd:enumeration value="gl"/>
			<xsd:enumeration value="gn"/>
			<xsd:enumeration value="gu"/>
			<xsd:enumeration value="ha"/>
			<xsd:enumeration value="he"/>
			<xsd:enumeration value="hi"/>
			<xsd:enumeration value="hr"/>
			<xsd:enumeration value="hu"/>
			<xsd:enumeration value="hy"/>
			<xsd:enumeration value="ia"/>
			<xsd:enumeration value="id"/>
			<xsd:enumeration value="ie"/>
			<xsd:enumeration value="ik"/>
			<xsd:enumeration value="is"/>
			<xsd:enumeration value="it"/>
			<xsd:enumeration value="iu"/>
			<xsd:enumeration value="ja"/>
			<xsd:enumeration value="jw"/>
			<xsd:enumeration value="ka"/>
			<xsd:enumeration value="kk"/>
			<xsd:enumeration value="kl"/>
			<xsd:enumeration value="km"/>
			<xsd:enumeration value="kn"/>
			<xsd:enumeration value="ko"/>
			<xsd:enumeration value="ks"/>
			<xsd:enumeration value="ku"/>
			<xsd:enumeration value="ky"/>
			<xsd:enumeration value="la"/>
			<xsd:enumeration value="ln"/>
			<xsd:enumeration value="lo"/>
			<xsd:enumeration value="lt"/>
			<xsd:enumeration value="lv"/>
			<xsd:enumeration value="mg"/>
			<xsd:enumeration value="mi"/>
			<xsd:enumeration value="mk"/>
			<xsd:enumeration value="ml"/>
			<xsd:enumeration value="mn"/>
			<xsd:enumeration value="mo"/>
			<xsd:enumeration value="mr"/>
			<xsd:enumeration value="ms"/>
			<xsd:enumeration value="mt"/>
			<xsd:enumeration value="my"/>
			<xsd:enumeration value="na"/>
			<xsd:enumeration value="ne"/>
			<xsd:enumeration value="nl">
				<xsd:annotation>
					<xsd:documentation>Nederlands</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="no"/>
			<xsd:enumeration value="oc"/>
			<xsd:enumeration value="om"/>
			<xsd:enumeration value="or"/>
			<xsd:enumeration value="pa"/>
			<xsd:enumeration value="pl"/>
			<xsd:enumeration value="ps"/>
			<xsd:enumeration value="pt"/>
			<xsd:enumeration value="qu"/>
			<xsd:enumeration value="rm"/>
			<xsd:enumeration value="rn"/>
			<xsd:enumeration value="ro"/>
			<xsd:enumeration value="ru"/>
			<xsd:enumeration value="rw"/>
			<xsd:enumeration value="sa"/>
			<xsd:enumeration value="sd"/>
			<xsd:enumeration value="sg"/>
			<xsd:enumeration value="sh"/>
			<xsd:enumeration value="si"/>
			<xsd:enumeration value="sk"/>
			<xsd:enumeration value="sl"/>
			<xsd:enumeration value="sm"/>
			<xsd:enumeration value="sn"/>
			<xsd:enumeration value="so"/>
			<xsd:enumeration value="sq"/>
			<xsd:enumeration value="sr"/>
			<xsd:enumeration value="ss"/>
			<xsd:enumeration value="st"/>
			<xsd:enumeration value="su"/>
			<xsd:enumeration value="sv"/>
			<xsd:enumeration value="sw"/>
			<xsd:enumeration value="ta"/>
			<xsd:enumeration value="te"/>
			<xsd:enumeration value="tg"/>
			<xsd:enumeration value="th"/>
			<xsd:enumeration value="ti"/>
			<xsd:enumeration value="tk"/>
			<xsd:enumeration value="tl"/>
			<xsd:enumeration value="tn"/>
			<xsd:enumeration value="to"/>
			<xsd:enumeration value="tr"/>
			<xsd:enumeration value="ts"/>
			<xsd:enumeration value="tt"/>
			<xsd:enumeration value="tw"/>
			<xsd:enumeration value="ug"/>
			<xsd:enumeration value="uk"/>
			<xsd:enumeration value="ur"/>
			<xsd:enumeration value="uz"/>
			<xsd:enumeration value="vi"/>
			<xsd:enumeration value="vo"/>
			<xsd:enumeration value="wo"/>
			<xsd:enumeration value="xh"/>
			<xsd:enumeration value="yi"/>
			<xsd:enumeration value="yo"/>
			<xsd:enumeration value="za"/>
			<xsd:enumeration value="zh"/>
			<xsd:enumeration value="zu"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="learningresourcetypeSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPPOVOv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="learningresourcetypeValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="evaluatie- en toetsmateriaal"/>
			<xsd:enumeration value="gesloten opdracht"/>
			<xsd:enumeration value="open opdracht"/>
			<xsd:enumeration value="verkennings- en onderzoeksmateriaal"/>
			<xsd:enumeration value="handleiding"/>
			<xsd:enumeration value="informatiebron"/>
			<xsd:enumeration value="gereedschap"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="purposeSource_CKS">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPv1.0.2_CKS"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="purposeValue_CKS">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="competentiegerichte kwalificatiestructuur"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="purposeSource_anders">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPv1.0.2_anders"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="statusSource">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TPPOVOv1.0"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="statusValue">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="prototype"/>
			<xsd:enumeration value="definitief"/>
			<xsd:enumeration value="revisie"/>
			<xsd:enumeration value="niet beschikbaar"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="typicalagerange">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]|[1-9][0-9]|1[0-4][0-9]"/>
			<xsd:pattern value="([0-9]|[1-9][0-9]|1[0-4][0-9])-([0-9]|[1-9][0-9]|1[0-4][0-9])"/>
			<xsd:pattern value="([1-9]?[0-9]|1[0-4][0-9])-|([0-9]|[1-9][0-9]|1[0-4][0-9])\+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="version">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(0[1-9]|1\d|2\d|3[01])(01|03|05|07|08|10|12)\d\d\d\d\s(\d)+|(0[1-9]|1\d|2\d|30)(04|06|09|11)\d\d\d\d\s(\d)+|(0[1-9]|1\d|2[0-8])02\d\d\d\d\s(\d)+|2902(\d\d[2468][048]|\d\d[0][48]|\d\d[13579][26]|[02468][048][0][0]|[13579][26][0][0])\s(\d)+|(\d)+\.(\d)+|(\d)+\.(\d)+\.(\d)+"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
