package fi.wiskopdr.text;


public class Text_fr extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
                    { "terugKnopLabel" , "Retour" },
                                
                                { "terugKnopToolTip" , "Retour" },
                                { "gelijkwaardigKnopToolTip" , "Entrez une  expression équivalente" },
                                { "opdrachtToolTip" , "Selectionnez un problème" },
                                { "zelfKnopToolTip" , "Entrez votre propre expression \n et simplifiez la." },
                                
                                
                                { "haakjesLabel0" , "  développez" },
                                { "haakjesLabel1" , "" },
                                { "herleidLabel0" , "   simplifiez" },
                                { "herleidLabel1" , "" },
                                { "ontbindLabel0" , "  factorisez" },
                                { "wortelLabel0" , "  racines" },
                                { "splitsLabel0" , "  séparez" },
                                { "hulpKnopLabel" , "Aide" },
                                { "gelijkwaardigLabel0" , "  égal" },
                                { "gelijkwaardigLabel1" , "    avec:" },
                                { "ofLabel" , "ou" },
                                { "enLabel" , "et" },
                                { "subLabel" , "Substituez:" },
                { "meerLabel" , "plus" },
                                
                { "klaarKnopLabel" , "Vérifiez" },
                                { "nakijkKnopLabel" , "Vérifiez" },
                                { "eindeKnopLabel", "Fin" },
                                { "nakijkLabel1" , "Vérifi�: " },
                                { "nakijkLabel2" , " fois " },
                                { "opnieuwKnopLabel" , "Reprendre" },
                                { "allesOpnieuwKnopLabel" , "Reprendre tout" },
                                { "opdrachtLabel" , "Problème:" },
                                { "paginaLabel" , "Page:" },
                                { "onderdeelLabel" , "Partie:" },
                                { "scoreLabel" , "Score:" },
                                { "score" , "Score: " },
                                { "totaal", "Total: " },
                                { "voortgang" , "Progrès: "},
                                { "deelscores", "Scores partiels"},
                                { "optiesButtonLabel" , "Options" },
                                { "standaardActiviteitNaam" , "Niveau" },
                                { "standaardOpdrachtNaam" , "Problème" },
                                { "opnieuwPanelTekstMW" , "Vous allez perdre vos scores si vous reprenez tout.\n\nVoulez-vous tout recommencer?"},
                                { "opnieuwPanelTekst" , "Vous allez perdre vos scores si vous reprenez tout.\n\nVoulez-vous tout recommencer?"},
                                { "opnieuwPanelTitel" , "Reprendre?"},
                                { "lockToetsCBLabel" , "Bloquez le test"},
                                { "lockToetsLabel" , "Test bloqué"},
                                                                
                                { "choiceOefenen" , "S'exercer" },
                                { "choiceOefenenEindloos" , "S'exercer sans fin" },
                                { "choiceOefenenStraf" , "S'entraîner" },
                                { "choiceZelfToets" , "Se tester" },
                                { "choiceEindToets" , "Test" },
                                
                                { "opdrachtTitelLabel" , "Titre:" },
                                { "opdrachtTekstLabel" , "Texte:" },
                                { "randVarLabel" , "Variables des paramètres aléatoires:" },
                                { "startExpLabel" , "Expression de départ:" },
                                { "startVergLabel" , "Equation de départ:" },
                                { "antwoordLabel" , "Modèle de réponse:" },
                                { "scoringLabel" , "Score de la réponse:" },
                                { "puntenLabel" , "Points:" },
                                { "checkTotaalLabel" , "Attention! Score total 10" },
                                { "gelijkwaardigCBLabel" , "Equivalent" },
                                { "herleidingCBLabel" , "Simplifiez" },
                                { "exactCBLabel" , "Exact" },
                                { "significantCBLabel" , "Significatif" },
                                { "stappenCBLabel" , "Multi-étapes" },
                                { "bewerkingKnoppenCBLabel" , "Boutons d'opération" },
                                { "bewerkingKnoppenExtraCBLabel" , "Boutons extra" },
                { "abcCBLabel" , "discr" },
                                { "subKnopCBLabel" , "subst." },
                                { "subKnopExtraCBLabel" , "subst. étendue" },
                                
                                { "grafiekToolCBLabel" , "Outil graphique" },
                                { "grafiekToolKnopLabel" , "Outil graphique" },
                                { "vergelijkingCBLabel" , "Equation" },
                                { "eindOplossingCBLabel" , "Réponse requise" },
                                { "checkCBLabel" , "Cochable(ou pas)" },
                                { "teltMeeCBLabel" , "Inclure dans la notation (ou pas)" },
                                { "logCBLabel" , "logID" },
                                { "rmCBLabel" , "Calculatrice" },
                                { "pijlCBLabel" , "Flèche" },
                                { "substitutiesButtonLabel" , "substitutions" },
                                { "strategieVersieLabel" , "Stratégie version" },
                                { "oefenVersieLabel" , "Stratégie+ version" },
                                { "bordjesVersieLabel" , "Méthode de masque version" },
                                
                                { "herleidingKeuze_0" , "Aucune" },
                                { "herleidingKeuze_1" , "Polynôme développé et simplifié" },
                                { "herleidingKeuze_2" , "Une puissance" },
                                { "herleidingKeuze_3" , "Sans puissance négative ou fractionnaire" },
                                { "herleidingKeuze_4" , "Une fraction" },
                                { "herleidingKeuze_5" , "Un logarithme" },
                                { "herleidingKeuze_6" , "Ecrit comme un simple log (comme log(x)+log(3) )" },
                                
                                { "feedbackTekst01" , "Cette étape contient des parties correctes et incorrectes. Changez ou éliminez les parties incorrectes." },
                                { "feedbackTekst02" , "Les solutions ne vérifient pas toutes l'équation originale. Eliminez la/les solution(s) qui ne la vérifient pas." },
                                { "feedbackTekst03" , "L'inéquation est résolue correctement." },
                                { "feedbackTekst04" , "L'équation est résolue correctement." },
                                { "feedbackTekst05" , "Donnez l'approximation demandée." },
                                { "feedbackTekst06" , "Donnez les solutions de l'inéquation." },
                                { "feedbackTekst07" , "Une ou des solution(s) manquent. Ajoutez les." },
                                { "feedbackTekst08" , "N'utilisez pas les caractères |- ." },
                                { "feedbackTekst09" , "La syntaxe n'est pas correcte." },
                                { "feedbackTekst10" , "La solution est correcte, mais pas encore dans la forme correcte." },
                                { "feedbackTekst11" , "C'est une approximation correcte." },
                                { "feedbackTekst12" , "La réponse est correcte." },
                                { "feedbackTekst13" , "La réponse attendue est équivalente, mais pas sous cette forme." },
                                { "feedbackTekst14" , "La syntaxe n'est pas correcte." },
                { "feedbackTekst15" , "Réponse correcte." },
                { "feedbackTekst16" , "C'est une équation correcte" },
                { "feedbackTekst17" , "Cette équation n'a pas encore la forme souhaitée" },
                { "feedbackTekst18" , "La réponse est correcte, mais le nombre de chiffres significatifs ne l'est pas." },
                { "feedbackTekst19" , "La réponse est correcte mais n'a pas la bonne forme et le nombre de chiffres significatifs est faux." },
                { "feedbackTekst20" , "La réponse est correcte, le nombre de chiffres significatifs aussi mais pas sa forme." },
                { "xVarMessage1" , "La variable indépendante est toujours\n" 
                                                                        + "une lettre.\n " 
                                                                        + "Dans le cas des noms de variables de\n" 
                                                                        + "plusieurs caractères, le premier\n" 
                                                                        + "est toujours une lettre." },
                                { "xVarMessage2" , "La variable indépendante ne peut être \n" 
                                                                        + "représentée que par une lettre.\n" 
                                                                        + "Seulement quand l'option \"variables multi-caractères\" \n" 
                                                                        + "est sélectionnée, la variable peut être\n" 
                                                                        + "représentée par plusieurs lettres." },
                                { "xVarMessage3" , "La lettre e est utilisée pour  \n" 
                                                                        + "la fonction exponentielle.\n" 
                                                                        + "Cette lettre ne peut pas être utilisée comme nom\n" 
                                                                        + "pour une variable indépendante." },                                                                        
                                { "xVarMessage4a" , "Le texte:  \"" },
                                { "xVarMessage4b" , "\" pour la fonction mathématique connue \n," 
                                                                        + "et ne peut pas être utilisé comme nom de variable"},
                                                                        
                                { "gelijkwaardigKnopLabelGR" , "Ligne suivante" },
                                { "terugKnopLabelGR" , "Ligne précédente" },
                                
                                { "editorVersieKnopLabel1" , "Editeur nouvelle version" },
                                { "editorVersieKnopLabel2" , "Editeur ancienne version" },
                                
                                {"antwoordVakLabel" , "boîte de réponse"},
                                {"interactieVakLabel" , "composant interactif"},
                                {"tekstVakLabel" , "boîte texte"},
                                {"grafiekComponentLabel" , "composant graphique"},
                                
                                
                                
                                {"interactieKeuzeLabel" , "Choisir le type de "},
                                {"okKnopLabel" , "OK"},
                                {"annuleerKnopLabel" , "Abandon"},
                                {"breedteLabel" , "Largeur:"},
                                {"hoogteLabel" , "Hauteur:"},
                                {"volleBreedteLabel" , "Largeur totale"},
                                {"popupLabel" , "Fenêtre"},
                                
                                {"feedbackCBLabel" , "Retour"},
                                {"uitwCBLabel" , "Fenêtre d'étape"},
                                {"casAntwCBLabel" , "Calcul Formel"},
                                {"eigenOpdrCBLabel" , "Vos "},
                                {"feedbackLabel" , "retours"},
                                {"ideasButtonLabel" , "options"},
                                {"substitutiesButtonLabel" , "substitutions"},
                                {"antwoordmodelButtonLabel" , "réponse possible"},
                                {"formuleInvoerModeCBLabel" , "Mode d'entrée de formule"},
                                {"aantalKeuzesLabel" , "Nombre de choix"},
                                {"aantalSelectieObjLabel" , "Nombre d'objets sélectionnés"},
                                {"randomPosLabel" , "Choisir les positions aléatoirement"},
                                {"meervSelectiesLabel" , "Sélections multiples possible"},
                                {"checkViaFormuleLabel" , "Vérifiez en utilisant une formule"},
                                {"aantalSleepObjLabel" , "Nombre d'objets sources"},
                                {"aantalDoelObjLabel" , "Nombre d'objets buts"},
                                {"snapToTargetLabel" , "Coller aux objets buts"},
                                {"snapMargeLabel" , "Marge \"magnétique\""},
                                {"checkVasteDoelenLabel" , "Vérifier les paires source/but"},
                                {"checkWaardeOpDoelLabel" , "Vérifier en utilisant les valeurs des objets déplacés"},
                                {"relocateCBLabel" , "Revenir"},
                                {"viewCBLabel" , "Vue"},
                                {"aantalValueObjectenLabel" , "Nombre d’objets"},
                                {"checkAfzonderlijkLabel" , "Vérifier séparément"},
                                {"checkOpSamenhangLabel" , "Vérifier la cohérence"},
                                {"boxMetRand" , "Boîte"},
                                {"keuzeVakKiesLabel" , "Choisir"},
                                {"verzamelDoelCBLabel" , "Objets cible comme collection"},
                
                                
                                {"vormCBLabel" , "Forme"},
                                {"formuleToolCBLabel" , "Éditeur de formules"},
                                {"goedLabel" , "Correct"},
                                {"doorLabel" , "Continuez"},
                                {"foutLabel" , "Faux"},
                                {"halfLabel" , "Moitié"},
                                
                                {"geenOplossingen" , "pas de solution"},
                                {"allesOplossing" , "tout est solution"},
                                {"antwoordModelGeen" , "aucune"},
                                {"abc" , "discr"},
                                
                                // TekstVakInteractiePanel
                                {"formuleAntwVakLabel" , "Champ de formule et étapes"},
                {"vergelijkingAntwVakLabel" , "Champ d’équation et étapes"},
                {"simpelFormuleAntwVakLabel" , "Champ pour petite formule"},
                {"simpelVergelijkingAntwVakLabel" , "Champ pour petite équation"},
                {"tekstAntwVakLabel" , "Champ de texte"},
                {"algebraPijlenLabel" , "Flèches algebriques"},
                {"blokkenbouwenLabel" , "Construire avec des blocs"},
                {"stroomdiagrammenLabel" , "Diagrammes"},
                {"grafiekenToolLabel" , "Outil de tracé graphique"},
                {"tekstVakLabelH" , "Boîte de texte"},
                                {"geogebraIpLabel" , "Geogebra 4"},
                                {"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "Balance à fruits"},
                                {"checkSelectieUnitLabel" , "Vérification de sélection"},
                                {"checkTekstAntwoordVakLabel" ,"Vérification de texte"},
                                {"keuzeAntwoordVakLabel" , "Choix d’un mot"},
                                {"doorzienIpLabel" , "Composant de construction 3D"},
                                {"checkSleepUnitLabel" , "Vérification de glisser-déposer"},
                                {"vergrotenIpLabel" , "PE Enlargement"},
                                {"vangenIpLabel" , "PE Catching"},
                                {"verknippenIpLabel" , "PE Cutting"},
                                {"geomAlgebra2dIpLabel" , "Geom.algebra 2d"},
                                {"geomAlgebra1dIpLabel" , "Geom.algebra 1d"},
                                {"normaleVerdelingIpLabel" , "Distribution normale"},
                                {"mp3PlayerIpLabel" , "Mp3-player"},
                                {"binominaleVerdelingIpLabel" , "Distribution binominale"},
                                {"getallenlijnIpLabel" , "Numberline (jump)"},
                                {"tekenVeelvlakIpLabel" , "Dessiner dans l’espace"},
                                {"mozaikIpLabel" , "Mosaïque"},
                                {"veelvlakkenIpLabel" , "Polyhèdre"},
                                {"eerlijkVerdelenIpLabel" , "PE Equal sharing"},
                                {"statistiekIpLabel" , "[test] Représentations statistiques"},
                                {"stroomdiagrammenIpLabel" , "[test] Diagrammes"},
                                {"tegelsIpLabel" , "pavages"},
                                {"checkWaardeUnitLabel" , "[test] Validation d’une valeur"},
                                {"omtrekAppletIpLabel" , "PE circonférence"},
                                {"algebraExpressiesIpLabel" , "[test] Expression algébrique en arbre"},
                                {"oppervlakteAlgebraIpLabel" , "[test] Aire algébrique"},
                                {"blokkenProgrammaIpLabel" , "[test] Programmation par bloc"},
                                {"grafieken3DIpLabel" , "[test] Graphes 3D"},
                                {"spotProblemsIpLabel" , "[test] Problèmes de points"},
                                {"kladjeIpLabel" , "[test] Note"},
                                {"kansbomenIpLabel" , "[test] Arbres de probabilité"},
                                {"rekenmachineIpLabel" , "[test] Calculatrice"},
                                {"formStructIpLabel" , "[test] FormStruct"},
                                {"graphToolIpLabel" , "[test] GraphTool"},
                                {"draabankIpLabel" , "[test] Fraiseuse"}, 
                                
                                //InstellingenPanel
                                {"OPT_wiskundeLabel" , "Mathématique"},
                {"OPT_navigatieLabel" , "Navigation"},
                {"OPT_layoutLabel" , "Affichage"},
                {"OPT_nakijkenLabel" , "Options de vérification"},
                                {"OPT_vermenigvTeken" , "Signe de multiplication: X"},
                                {"OPT_woordformules" , "Variables"},
                                {"OPT_tweeHoofdletterVars" , "Variables comme AB, BC etc."},
                                {"OPT_tempoToets" , "Temps restreint"},
                                {"OPT_opnieuwKnop" , "Bouton 'répéter tous'"},
                                {"OPT_itemOpnieuwKnop" , "Bouton 'répéter un'"},
                                {"OPT_checkPerOpdracht" , "Vérifier par page"},
                                {"OPT_hoekInGraden" , "Unité d’angles: degrés"},
                                {"OPT_opdrachtBolletjes" , "Sélecteur"},
                                {"OPT_volgendeKnop" , "Bouton 'suivant'"},        
                                {"OPT_VorigeKnop" , "Bouton 'précédent'"},
                                {"OPT_paginaIpvOpdracht" , "Étiquette: 'Page' plutôt que 'Problème'"},
                                {"OPT_fontFormaat" , "Taille "},
                                {"OPT_fontNaam" , "Fonte de base"},
                                {"OPT_tijdsLimiet" , "Compte à rebours (sec)"},
                                {"OPT_formTimes" , "Formules en Times Roman"},
                                {"OPT_navigatieFormaat" , "Barre de navigation Taille"},
                                {"OPT_margesLabel" , "Marges:"},
                                {"OPT_margeLinksLabel" , "Gauche"},
                                {"OPT_margeRechtsLabel" , "Droite"},
                                {"OPT_margeBovenLabel" , "Au-dessus"},
                                {"OPT_margeOnderLabel" , "En-dessous"},
                                {"OPT_fToets" , "Formules F-keys"},
                                {"OPT_globalParam" , "Paramètres globaux"},
                                {"OPT_voortgangKnop", "'Progression' au lieu de 'Total'"},
                                {"OPT_conditionalNav" , "Navigation conditionnelle"},
                                {"OPT_conditionalPercLabel" , "Pourcentage"},
                                {"OPT_voorwaarden", "Conditions par page"},
                                {"OPT_allesCorrect", "Page quand tout est correct (vert)"},
                                {"OPT_deelOpdr" , "Items a,b,c etc"},
                                {"OPT_zelftoetsGeenCorr" , "Auto-correction"},
                                {"OPT_eerderGeenCorr" , "Pas de correction pages précédentes"},
                                {"OPT_significantie" , "Option nombres significatifs"},
                                {"OPT_objectives" , "Objectifs"},
                                {"OBJ_leerdoel", "Objectif"},
                                {"OBJ_categorie", "Catégorie"},
                                {"OBJ_categorieBox", "Objectifs dans différentes catégories"},
                                {"OBJ_kolomMeerButton", "Ajouter une colonne"},
                                {"OBJ_kolomMinderButton", "Enlever une colonne"},
                                
                                //grafiekenEditPanel
                                {"GEP_varLabel" , "Variables de la fonction"},
                                {"GEP_assenLabel" , "Montrer les axes"},
                                {"GEP_grafiekOptiesLabel" , "Options de l’outil de graphe"},
                                
                                {"GEP_varXLabel" , "Variable axe des x"},
                                {"GEP_varYLabel" , "Variable axe des y"},
                                
                                {"GEP_assenOptie" , "Axes"},
                                {"GEP_roosterOptie" , "Grille"},
                                {"GEP_roosterGrofOptie" , "large"},
                                {"GEP_schaalverdelingOptie" , "Nombres sur les axes"},
                                {"GEP_piOptie" , "Grille pour Pi"},                                
                                
                                {"GEP_zoomOptie" , "Option de zoom"},
                                {"GEP_traceOptie" , "Option de trace"},
                                {"GEP_dragOptie" , "Option de glisser-déposer"},
                                {"GEP_tekenOptie" , "Outil de graphe"},
                                
                                {"GEP_tabelOptie" , "Outil table"},
                                {"GEP_zoomInTabelOptie" , "Zoom sur la table"},
                                {"GEP_tabelTekenToolOptie" , "Table pour dessiner"},


                                {"GEP_functieEditOptie" , "Éditeur de fonction"},
                                {"GEP_grafiekKleurenOptie" , "Différente couleurs"},
                                
                                {"GEP_formeleFunctieNotatieOptie" , "Notation fonctionnelle f(x), g(x) etc."},
                                
                                {"GEP_popupWeergave" , "Ouvrir une nouvelle fenêtre"},
                                
                                {"GEP_xPositief" , "x positif"},
                                {"GEP_yPositief" , "y positif"},
                                {"GEP_xEditable" , "x éditable"},
                                {"GEP_yEditable" , "y éditable"},
                                
                                
                                {"GEP_opdrachten" , "tâches"},
                                
                                {"GEP_kiesOpdracht" , "choisir le type de tâche"},
                                {"GEP_opdracht1" , "trouver la formule pour un graph en ligne"},
                                {"GEP_opdracht2" , "trouver la formule pour un certain nombre de points"},
                                {"GEP_opdracht3" , "tracer des points étant donnée la formule"},
                                {"GEP_opdracht4" , "tracer des points étant donnée une table de valeurs"},
                                
                                {"GEP_antwoordFormule" , "entrer la formule solution dans l’éditeur ci-dessous"},
                                {"GEP_tabelPuntenX" , "entrer les valeurs de x dans la table ci-dessous" },
                                {"GEP_tabelPunten" , "entrer les points dans la table ci-dessous" },
                                
                                {"GEP_nauwkeurigheid" , "Précision (pixels)"},
                                {"GEP_minimumPunten" , "Nombre minimum de points"},
                                {"GEP_maximumScore" , "Score maximum"},
                                {"GEP_leerlingZietTabel" , "Les utilisateurs peuvent voir la table"},
                                
                                {"GE_kijkNa" , "Vérifier" },
                                
                                //linkEditPanel
                                {"LEP_linkTekst" , "Texte"},
                                {"LEP_url" , "URL"},
                                {"LEP_vensterBreedte" , "Largeur de la fenêtre"},
                                {"LEP_vensterHoogte" , "Hauteur de la fenêtre"},
                                
                                //ImageEditPanel
                                {"IEP_toevoegen" , "Ajouter"},
                                {"IEP_verwijderen" , "Enlever"},
                                {"IEP_ok" , "OK"},
                                {"IEP_cancel" , "Annuler"},
                                
                                //TekstVakEditPanel
                                {"TVEP_randZichtbaar" , "Bordure"},
                                {"TVEP_achtergrondKleurAanwezig" , "Couleur de fond"},
                                {"TVEP_zwevend" , "Au-dessus du texte"},
                                {"TVEP_anderFont" , "Autre fonte"},
                                {"TVEP_rondingHoeken" , "Coins arrondis"},
                                {"TVEP_rotatieHoek" , "Angle de rotation"},
                                {"TVEP_centreerHor" , "Centrer horizontalement"},
                                {"TVEP_centreerVert" , "Centrer verticalement"},
                                {"TVEP_pasAanH" , "Ajuster la hauteur"},
                                {"TVEP_pasAanB" , "Ajuster la largeur"},
                                {"TVEP_aantalRijen" , "Nombre de lignes"},
                                {"TVEP_aantalKolommen" , "Nombre de colonnes"},
                                {"TVEP_tabelRanden" , "Bords de table"},
                                {"TVEP_celMarge" , "Marge gauche"},
                                {"TVEP_bovenMarge" , "Marge supérieure"},
                                {"TVEP_fontType" , "Fonte"},
                                {"TVEP_achtergrondKleur" , "Couleur"},
                                {"TVEP_interlinie" , "Interligne"},
                                {"TVEP_cellSpaceColumn" , "Espace"},
                                {"TVEP_cellSpaceRow" , "Espace"},
                                {"TVEP_layoutLabel" , "Affichage de texte"},
                                {"TVEP_gebruikersInteractieLabel" , "Interaction utilisateur"},
                                {"TVEP_selectieObject" , "Sélection d’objet"},
                {"TVEP_selectieKleur" , "Couleur"},
                {"TVEP_sleepObject" , "Tirer l’objet"},
                {"TVEP_sleepDoel" , "Tirer la cible"},
                {"TVEP_sleepHandle" , "poignée"},
                {"TVEP_selectieSleepWaarde" , "valeur    ("},
                {"TVEP_fgKleurKnopLabel" , "couleur"},
                {"TVEP_zichtbaarNaNakijken" , "Visible après vérification"},
                {"TVEP_balansVergCom" , "Communication Balance-Équation"},
                {"TVEP_aftrekPopup" , "Diminuer le score avec l’aide"},
                {"TVEP_callOut" , "Call out box"},
                {"TVEP_uitwerkingenPopup" , "Étapes"},
                {"TVEP_random" , "aléatoire"},
                {"TVEP_linkObject" , "Lier l’objet"},
                {"TVEP_editLink" , "Éditer le lien"},
                {"TVEP_defaultBijNull" , "par défaut  )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                                
                                //GeogebraEditPanel
                                {"GEP_bewaarOptie" , "Option Sauvegarder"},
                                {"GEP_alsTool" , "Comme outil"},
                                {"GEP_rand" , "Bordure"},
                                {"GEP_resetIcon" , "Option Remise-à-zéro"},
                                {"GEP_checkMetCheckDWO" , "Utiliser checkDWO"},
                                {"GEP_checkMetObjecten" , "Utiliser les objets créés"},
                                
                                //GetallenLijnSprongEditPanel
                                {"GSEP_minValue" , "Valeur minimale"},
                                {"GSEP_maxValue" , "Valeur maximale"},
                                {"GSEP_eenheden" , "Unités visibles"},
                                {"GSEP_getallen" , "Nombres"},
                                {"GSEP_10tallen" , "Marque des dizaines"},
                                {"GSEP_5tallen" , "Marques des 5"},
                                {"GSEP_nul" , "Zéro"},
                                {"GSEP_pijl" , "Flêche visible"},
                                {"GSEP_pijlTerug" , "Flêche retour"},
                                {"GSEP_horizontaal" , "Horizontal"},
                                {"GSEP_eenheid" , "Unité"},
                                
                                
                                
                                //TekstEditorEditPanel
                                {"TEEP_menuBalkOptie" , "Bar de menu"},
                                {"TEEP_rekenToolOptie" , "Calculatrice"},
                                {"TEEP_grafToolOptie" , "Outil de graphe"},
                                
                                //Ideas
                                
                                {"ideasTip",                "suggestion"},
                                {"ideasHelp",                "aide"},
                                {"ideasStap",                "étape"},
                                {"ideasLosop",                "résoudre"},
                                {"ideasWordtDan",                "devient"},
                                
                                {"algebra.equations.coverup.denominator"                ,"mettre au même dénominateur"        },
                                {"algebra.equations.coverup.minus-left"                        ,"déplacer la constante à droite"        },
                                {"algebra.equations.coverup.minus-right"                ,"mettre au même dénominateur"        },
                                {"algebra.equations.coverup.negate"                                ,"multiplier par -1"        },
                                {"algebra.equations.coverup.numerator"                        ,"cover up the nominator"        },
                                {"algebra.equations.coverup.plus"                                ,"déplacer la constante à droite"        },
                                {"algebra.equations.coverup.power"                                ,"prendre la racine carrée"        },
                                {"algebra.equations.coverup.sqrt"                                ,"mettre au carré"        },
                                {"algebra.equations.coverup.times"                                ,"isoler la variable en divisant des deux côtés"        },
                                {"algebra.equations.coverup.times-positive"                ,"isoler la variable en divisant des deux côtés"        },
                                {"algebra.equations.coverup.onevar.minus-left"        ,"déplacer la constante à droite en ajoutant un nombre aux deux termes"        },
                                {"algebra.equations.coverup.onevar.plus"                ,"déplacer la constante à droite en soustrayant un nombre aux deux termes"        },
                                
                                {"algebra.equations.linear.distr-times"                ,"enlever les parenthèses"        },
                                {"algebra.equations.linear.flip"                        ,"échanger l’équation"        },
                                {"algebra.equations.linear.merge"                        ,"simplifier"        },
                                {"algebra.equations.linear.remove-div"                ,"simplifier la fraction en mulitpliant par un nombre"        },
                                {"algebra.equations.linear.var-left"                ,"déplacer l’expression contenant la variable à droite"        },
                                
                                {"algebra.equations.buggy.cancel-minus"                                ,"vous ne pouvez pas simplifier car les signes sont différents"        },
                                {"algebra.equations.buggy.distr-times-denom"                ,"en enlevant les parenthèses, prenez garde à la fraction: le facteur est multiplié par le numérateur."        },
                                {"algebra.equations.buggy.distr-times-plus"                        ,"en enlevant les parenthèses, distribuez bien la multiplication sur tous les termes"        },
                                {"algebra.equations.buggy.distr-times-plus-forget"        ,"en enlevant la parenthèse, vous avez oublié un terme"        },
                                {"algebra.equations.buggy.distr-times-plus-sign"        ,"en enlevant la parenthèse, prenez garde au signe"        },
                                {"algebra.equations.buggy.distr-times-too-many"                ,"en enlevant la parenthèse, ne distribuez que sur les termes entre parenthèse"        },
                                {"algebra.equations.buggy.divide-negate"                        ,"prenez garde au signe en divisant"        },
                                {"algebra.equations.buggy.divide-numdenom"                        ,"En inversant la fraction, prenez garde au nombre par lequel diviser"        },
                                {"algebra.equations.buggy.flip-negate-one-side"                ,"changez le signe de chaque côté"        },
                                {"algebra.equations.buggy.multiply-one-side"                ,"multipliez de chaque côté"        },
                                {"algebra.equations.buggy.minus-minus"                                ,"en enlevant une parenthèse, le produit de deux négatifs est un nombre positif"        },
                                {"algebra.equations.buggy.multiply-forget-one"                ,"en multipliant, un terme a été oublié"        },
                                {"algebra.equations.buggy.negate-all"                                ,"en changeant le signe, un terme a été oublié"        },
                                {"algebra.equations.buggy.negate-one-side"                        ,"un des côté a été oublié en changeant le signe"        },
                                {"algebra.equations.buggy.plus"                                                ,"prenez garde au signe quand vous déplacez un terme d’un côté à l’autre"        },
                                {"algebra.equations.buggy.priority-times"                        ,"prenez garde aux priorités en enlevant les parenthèses"        },
                                
                                {"algebra.equations.buggy.abc.minus-4ac"                                ,"dans la formule du carré, le déterminant vaut D=b^2-4ac et non pas D=b^2+4ac"        },
                                {"algebra.equations.buggy.abc.minus-b"                                        ,"pas de signe moins devant b: "        },
                                {"algebra.equations.buggy.abc.one-solution"                                ,"il y a une seconde solution"        },
                                {"algebra.equations.buggy.abc.two-a"                                        ,"divisez par 2a et non pas a"        },
                                {"algebra.equations.buggy.coverup.even-power"                        ,"vous avez oublié l’autre racine (négative)"        },
                                {"algebra.equations.buggy.coverup.even-power-forget"        ,"before taking square roots you need to perform another action"        },
                                {"algebra.equations.buggy.coverup.even-power-too-early"        ,"il y a une autre étape avant de prendre la racine carrée"        },
                                {"algebra.equations.buggy.coverup.square-minus"                        ,"dans les réels, vous ne pouvez pas prendre la racine carrée d’un nombre négatif"        },
                                {"algebra.equations.buggy.coverup.times-mul"                        ,"vous avez multiplié au lieu de diviser"        },
                                {"algebra.equations.buggy.coverup.times-with-plus"                ,"divisez tous les termes"        },
                                {"algebra.equations.buggy.distr-square"                                        ,"en prenant le carré d’une somme, vous avez oublié le terme croisé"        },
                                {"algebra.equations.buggy.distr-square-forget"                        ,"en prenant le carré, vous avez oublié un terme"        },
                                {"algebra.equations.buggy.square-multiplication"                ,"votre carré est incorrect"        },
                                {"algebra.equations.buggy.division-by-var-both"                ,"en divisant, prenez garde à la valeur nulle"        },
                                {"algebra.equations.buggy.division-by-var-zero"                ,"en divisant, prenez garde à la valeur nulle"        },
                                
                                {"algebra.equations.linear.balance.collect"                        ,"combiner"        },
                                {"algebra.equations.linear.balance.calculate"                ,"calculer"        },
                                {"algebra.equations.linear.balance.div-to-fraction"                ,"écrire une division comme une multiplication par une fraction"        },
                                {"algebra.equations.linear.balance.smart-div"                ,"diviser par un facteur commun"        },
                                {"algebra.equations.linear.balance.con-right-minus"        ,"soustraire {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.con-left-minus"        ,"soustraire {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.var-right-minus"        ,"soustraire {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.var-left-minus"        ,"soustraire {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.con-right-plus"        ,"ajouter {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.con-left-plus"        ,"ajouter {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.var-right-plus"        ,"ajouter {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.var-left-plus"        ,"ajouter {?} des deux côtés"        },
                                {"algebra.equations.linear.balance.distribute"                ,"enlever les parenthèses"        },
                                {"algebra.equations.linear.balance.remove-div"                ,"multiplier les deux côtés par {?}"        },
                                {"algebra.equations.linear.balance.scale-to-one"        ,"diviser  les deux côtés par  {?}"        },
                                {"algebra.equations.linear.balance.negate"    ,"changer le signe de chaque côté"  },
                                {"algebra.equations.linear.balance.intro-false"    ,"impossible"  },
                                {"algebra.equations.linear.balance.intro-true"    ,"toujours vrai"  },
                
               
                                {"algebra.equations.quadratic.abc"                                ,"utiliser une formule du second degré"        },
                                {"algebra.equations.quadratic.approx"                        ,"approcher"        },
                                {"algebra.equations.quadratic.cancel"                        ,"enlever une expression de chaque côté de l’égalité"        },
                                {"algebra.equations.quadratic.common-factor"        ,"factoriser en utilisant le facteur commun"        },
                                {"algebra.equations.quadratic.distr-div"                ,"diviser"        },
                                {"algebra.equations.quadratic.distr-square"                ,"calculer square"        },
                                {"algebra.equations.quadratic.left-square"                ,"écrire le terme de gauche comme un carré"        },
                                {"algebra.equations.quadratic.move-left"                ,"déplacer tous les termes à gauche"        },
                                {"algebra.equations.quadratic.nice-factors"                ,"factoriser les trois expressions"        },
                                {"algebra.equations.quadratic.no-lin"                        ,"écrire comme un carré"        },
                                {"algebra.equations.quadratic.prepare-split"        ,"compléteren un carré"        },
                                {"algebra.equations.quadratic.product-zero"                ,"si le produit est nul, un des facteur est nul"        },
                                {"algebra.equations.quadratic.same-con-factor"        ,"diviser chaque terme par un facteur commun"        },
                                {"algebra.equations.quadratic.same-factor"                ,"A*B=A*C implique A=0 ou B=C"        },
                                {"algebra.equations.quadratic.simpler-poly"                ,"simplifier en divisant par un facteur commun"        },
                                {"algebra.equations.quadratic.simpler-sqrt"                ,"simplifier les racines carrées"        },
                                {"algebra.equations.quadratic.square-both"                ,"mettre chaque côté au carré"        },
                                
                                
                                
                                {"algebra.equations.polynomial.back-subst"                        ,"appliquer la substitution à l’envers"        },
                                {"algebra.equations.polynomial.expose-factor"                ,"isoler le facteur commun"        },
                                {"algebra.equations.polynomial.power-factors"                ,"x facteur commun"        },
                                {"algebra.equations.polynomial.subst"                                ,"substituer"        },
                                {"algebra.equations.polynomial.def-power-nat"           ,"la puissance est une multiplication itérée"},
                                
                                
                                {"algebra.equations.rational.check-solution"        ,"vérifier la solution"        },
                                {"algebra.equations.rational.cross-multiply"        ,"multiplication croisée"        },
                                {"algebra.equations.rational.division-one"                ,"quand une fraction vaut 1, le numérateur et le dénominateur sont égaux"        },
                                {"algebra.equations.rational.division-zero"                ,"quand une fraction est nulle, son numérateur est nul (si le dénominateur n’est pas nul)"        },
                                {"algebra.equations.rational.multiply-one-div"        ,"mulitplier chaque côté par le dénominateur de la fraction"        },
                                {"algebra.equations.rational.same-dividend"                ,"A/B=A/C implqiue A=0 ou B=C"        },
                                {"algebra.equations.rational.same-divisor"                ,"dénominateurs égaux, égaliser les numérateurs"        },
                                
                                {"algebra.inequalities.flip-sign"                ,"changer le signe"        },
                                {"algebra.inequalities.give-solution"        ,"résoudre l’inégalité"        },
                                {"algebra.inequalities.to-equation"                ,"transformer tout d’abord en une équation"        },
                                
                                {"algebra.manipulation.exponents.add-exponents"                        ,"multiplier les puissances en ajoutant les exposants"        },
                                {"algebra.manipulation.exponents.factor-as-power"                ,"faire apparaitre une puissance"        },
                                {"algebra.manipulation.exponents.mul-exponents"                        ,"prendre la puissance d’une puissance en multipliant les exposants"        },
                                {"algebra.manipulation.exponents.reciprocal"                        ,"L’inverse s’écrit aussi ^-1"        },
                                {"algebra.manipulation.exponents.simple-add-exponents"        ,"écrire comme une puissance en ajoutant les exposants"        },
                                {"algebra.manipulation.exponents.sub-exponents"                        ,"diviser les termes en soustrayant les exposants"        },
                                {"algebra.manipulation.exponents.write-as-power"                ,"écrire comme une puissance"        },
                                {"algebra.manipulation.exponents.distr-power"                        ,"le produit d’une puissance est la puissance du produit"        },
                                {"algebra.manipulation.exponents.reciprocal-inverse"        ,"écrire la puissance expression^-1 comme la fraction inverse 1/expression"        },
                                {"algebra.manipulation.exponents.write-as-root"                        ,"écrire comme une racine carrée"        },
                                {"algebra.manipulation.exponents.reciprocal-var"                ,"écrire l’inverse d’une puissance comme une puissance de signe opposé"        },
                                {"algebra.manipulation.exponents.push-negation-out"                ,"quand l’exposant est impair, sortir le signe de la puissance"        },
                                {"algebra.manipulation.exponents.root"                                        ,"prendre la racine carrée"        },
                                
                                {"algebra.manipulation.exponents.equation.equals-one"                ,"le nombre 1 correspond à un exposant nul"        },
                                {"algebra.manipulation.exponents.equation.same-base"                ,"même nombre de base"        },
                                {"algebra.manipulation.exponents.equation.approx-power"                ,"approcher cette puissance ou racine"        },
                                {"algebra.manipulation.exponents.equation.common-power"                ,"puissance commune"        },
                                {"algebra.manipulation.exponents.equation.greatest-power"        ,"utiliser la puissance commune maximale"        },
                                {"algebra.manipulation.exponents.equation.nth-root"                        ,"racine n-ième"        },
                                
                                {"algebra.manipulation.logarithmic.logarithm"                ,"Utiliser  log_b(x)=a équivaut à x=b^a"        },
                                
                                {"calculus.differentiation.deriv-of-poly"                ,"dériver une fonction polynomiale"        },
                                {"calculus.differentiation.min"                ,"appliquer la règle de la différence"        },
                                {"calculus.differentiation.negate"                ,"sortir le signe avant la dérivation"        },
                                {"calculus.differentiation.plus"                ,"appliquer la règle de la somme"        },
                                {"calculus.differentiation.product"                ,"appliquer la règle du produit"        },
                                {"calculus.differentiation.quotient"                ,"appliquer la règle du quotient"        },
                                {""                ,""        },
                                
                                {"algebra.equations.linear.balance.buggy.addbal1"                ,"vous soustrayez {?} du membre gauche mais ajoutez {?} à celui de droite"        },
                                {"algebra.equations.linear.balance.buggy.addbal2"                ,"vous ajoutez {?} au membre de gauche mais soustrayez {?} à celui de droite"        },
                                {"algebra.equations.linear.balance.buggy.addbal3"                ,"vous soustrayez {?} du membre de droite mais ajoutez {?} à celui de gauche"        },
                                {"algebra.equations.linear.balance.buggy.addbal4"                ,"vous ajoutez {?} au membre de gauche mais soustrayez {?} à celui de droite"        },
                                {"algebra.equations.linear.balance.buggy.addbal5"                ,"vous soustrayez {?} au membre de gauche mais pas à celui de droite"        },
                                {"algebra.equations.linear.balance.buggy.addbal6"                ,"vous ajoutez {?} au membre de gauche mais pas à celui de droite"        },
                                {"algebra.equations.linear.balance.buggy.addbal7"                ,"vous soustrayez {?} du membre de gauche mais ajoutez {?} à celui de droite"},
                                {"algebra.equations.linear.balance.buggy.addbal8"                ,"vous ajoutez {?} au membre de gauche mais soustrayez {?} à celui de droite"} ,
                                {"algebra.equations.linear.balance.buggy.addbal9"       ,"vous soustrayez {?} du membre de droite mais ajoutez {?} à celui de gauche"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"vous ajoutez {?} au membre de droite mais soustrayez {?} à celui de gauche"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"vous soustrayez {?} au membre de droite mais pas à celui de gauche"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"vous ajoutez {?} au membre de droite mais pas à celui de gauche"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"vous soustrayez {?} au membre de gauche mais pas à celui de droite"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"vous ajoutez {?} au membre de gauche mais pas à celui de droite"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"vous soustrayez {?} au membre de droite mais pas à celui de gauche"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"vous ajoutez {?} au membre de droite mais pas à celui de gauche"},
                {"algebra.equations.linear.balance.buggy.flip1"                ,"vous avez échangé les termes mais changé le signe d’un côté"        },
                                {"algebra.equations.linear.balance.buggy.misc1"                ,"vous soustrayez au membre de droite, que faites vous à celui de gauche?"        },
                                {"algebra.equations.linear.balance.buggy.misc2"                ,"vous multipliez par un nombre mais pas tout le terme de gauche"        },
                                {"algebra.equations.linear.balance.buggy.misc3"                ,"vous changez le signe mais pas tout le terme de gauche"        },
                                {"algebra.equations.linear.balance.buggy.misc4"                ,"vous divisez par un nombre mais pas tout le terme de gauche"        },
                                {"algebra.equations.linear.balance.buggy.mulbal1"                ,"vous multipliez le terme de gauche par {?}, mais le terme de droite par son inverse"        },
                                {"algebra.equations.linear.balance.buggy.mulbal2"                ,"vous multipliez les deux termes par des nombres différents"        },
                                {"algebra.equations.linear.balance.buggy.mulbal3"                ,"vous multipliez le terme de gauche par {?}, mais pas le terme de droite"        },
                                {"algebra.equations.linear.balance.buggy.mulbal4"                ,"vous divisez le terme de gauche par {?}, mais pas le terme de droite"        },
                                {"algebra.equations.linear.balance.buggy.mulbal5"                ,"vous changez le signe du terme de gauche, mais pas le terme de droite"        },
                                {"algebra.equations.linear.balance.buggy.mulbal6"                ,"vous divisez un terme par {?}, mais pas l’autre"        },
                                {"algebra.equations.linear.balance.buggy.multiply1"                ,"erreur de multiplication (1)"        },
                                {"algebra.equations.linear.balance.buggy.multiply2"                ,"erreur de multiplication (2)"        },
                                {"algebra.equations.linear.balance.buggy.multiply3"                ,"erreur de multiplication, oubli du signe moins"        },
                                {"algebra.equations.linear.balance.buggy.multiply4"                ,"erreur de multiplication, moins par moins font plus"        },
                                {"algebra.equations.linear.balance.buggy.multiply5"                ,"erreur de division, vous divisez par un nombre négatif"        },
                                {"algebra.equations.linear.balance.buggy.par1"                ,"erreur de parenthésage, multipliez chacun des termes dans la parenthèse (1)"        },
                                {"algebra.equations.linear.balance.buggy.par10"                ,"les règles de prioroté: d’abord multiplier, puis ajouter"        },
                                {"algebra.equations.linear.balance.buggy.par11"                ,"le symbole moins entre parenthèse n’a pas été traité correctement"        },
                                {"algebra.equations.linear.balance.buggy.par2"                ,"erreur en enlevant les parenthèses, multipliez chacun des termes entre parenthèse (2)"        },
                                {"algebra.equations.linear.balance.buggy.par4"                ,"erreur en enlevant les parenthèses, erreur de multiplication (1)"        },
                                {"algebra.equations.linear.balance.buggy.par5"                ,"erreur en enlevant les parenthèses, multipliez chacun des termes entre parenthèse (3)"        },
                                {"algebra.equations.linear.balance.buggy.par6"                ,"erreur en enlevant les parenthèses, multipliez chacun des termes entre parenthèse (4)"        },
                                {"algebra.equations.linear.balance.buggy.par7"                ,"erreur en enlevant les parenthèses, multipliez chacun des termes entre parenthèse par -1"        },
                                {"algebra.equations.linear.balance.buggy.par8"                ,"erreur en enlevant les parenthèses, regardez bien où sont les parenthèses"        },
                                {"algebra.equations.linear.balance.buggy.par9"                ,"erreur en enlevant les parenthèses, erreur de multiplication (2)"        },
                                
                                //conditionele navigatie-panels
                                {"CN_voorwaarden", "Conditions"},
                                {"CN_vanPagina","De la page"},
                                {"CN_naarPagina","à la page"},
                                {"CN_scorePagina","Pages pour notation"},
                                {"CN_grensPercentage","Pourcentage de sélection"},
                                {"CN_sorteer","Trier"},
                                {"CN_regelMeer", "Ajouter une ligne"},
                                {"CN_regelMinder", "Enlever une ligne"},
                };
}