package fi.wiskopdr.text;

import fi.wiskopdr.tekstobjects.ShareAction;

public class Text_en extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "Back" },
				
				{ "terugKnopToolTip" , "Back" },
				{ "gelijkwaardigKnopToolTip" , "Enter an equivalent expression" },
				{ "opdrachtToolTip" , "Select problem" },
				{ "zelfKnopToolTip" , "Enter your own expression \n and symplify it." },
				
				
				{ "haakjesLabel0" , "  expand" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "   simplify" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  factorize" },
				{ "wortelLabel0" , "  roots" },
				{ "splitsLabel0" , "  split" },
				{ "hulpKnopLabel" , "Help" },
				{ "gelijkwaardigLabel0" , "  equal" },
				{ "gelijkwaardigLabel1" , "    with:" },
				{ "ofLabel" , "or" },
				{ "enLabel" , "and" },
				{ "subLabel" , "Substitute:" },
                { "meerLabel" , "more" },
				
                { "klaarKnopLabel" , "CHECK" },
				{ "nakijkKnopLabel" , "CHECK" },
				{ "checkExternal" , "External check" },
				{ "eindeKnopLabel", "End" },
				{ "nakijkLabel1" , "Checked: " },
				{ "nakijkLabel2" , " times " },
				{ "opnieuwKnopLabel" , "Again" },
				{ "allesOpnieuwKnopLabel" , "All again" },
				{ "zelftoetsGeschiedenisKnopLabel", "score history"},
				{ "opdrachtLabel" , "Problem:" },
				{ "paginaLabel" , "Page:" },
				{ "onderdeelLabel" , "Part:" },
				{ "scoreLabel" , "Score:" },
				{ "score" , "Score: " },
				{ "totaal", "Total: " },
				{ "voortgang" , "Progress: "},
				{ "deelscores", "Partial scores"},
				{ "optiesButtonLabel" , "Activity settings" },
				{ "standaardActiviteitNaam" , "Level" },
				{ "standaardOpdrachtNaam" , "Problem" },
				{ "opnieuwPanelTekstMW" , "You will lose your scores if you start again.\n\nAre you sure you want to start again?"},
				{ "opnieuwPanelTekst" , "You will lose your scores if you start again.\n\nAre you sure you want to start again?"},
				{ "opnieuwPanelTitel" , "Again?"},
				{ "lockToetsCBLabel" , "Lock test"},
				{ "lockToetsLabel" , "Test locked"},
				{ "newPageMenuItem" ,  "New (insert)"},
				{ "deletePageMenuItem" ,  "Delete"},
				{ "copyPageMenuItem" ,  "Copy"},
				{ "cutPageMenuItem" ,  "Cut"},
				{ "pastePageMenuItem" ,  "Paste (insert)"},
				{ "copyMenuItem" ,  "Copy"},
				{ "cutMenuItem" ,  "Cut"},
				{ "pasteMenuItem" ,  "Paste"},
				{ "editMenuItem" ,  "Edit text box"},
				{ "selectMenuItem" ,  "Select text box"},
				{ "insertCopyMenuItem" ,  "Copy (insert)"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
				{ "imagesButtonLabel", "Images"},
				{ "settingsLabel", "Settings"},
				{ "helpTitelLabel", "Help"},
				
				{ "linkDialogUrlGegevensWijzigen", "Edit URL information"},
				{ "linkDialogLinkGegevens", "Link information"},
								
				{ "choiceOefenen" , "Practice" },
				{ "choiceOefenenEindloos" , "Practice endless" },
				{ "choiceOefenenStraf" , "Practice game" },
				{ "choiceZelfToets" , "Self test" },
				{ "choiceEindToets" , "Test" },
				
				{ "opdrachtTitelLabel" , "Title:" },
				{ "opdrachtTekstLabel" , "Text:" },
				{ "randVarLabel" , "Variables for random parameters:" },
				{ "startExpLabel" , "Start expression:" },
				{ "startVergLabel" , "Start equation:" },
				{ "variabelenLabel", "Variables (separated by commas): "},
				{ "antwoordLabel" , "Answer model:" },
				{ "antwoordLabelStelsel", "(tupels numbers, like (0,0),(1,1))"},
				{ "scoringLabel" , "Scoring of the answer:" },
				{ "puntenLabel" , "Points:" },
				{ "checkTotaalLabel" , "Attention! Total score 10" },
				{ "gelijkwaardigCBLabel" , "Equivalent" },
				{ "herleidingCBLabel" , "Symplify" },
				{ "exactCBLabel" , "Exact" },
				{ "significantCBLabel" , "Significant" },
				{ "stappenCBLabel" , "Using more steps" },
				{ "bewerkingKnoppenCBLabel" , "Operation buttons" },
				{ "bewerkingKnoppenExtraCBLabel" , "Operation buttons extra" },
                { "abcCBLabel" , "discr" },
				{ "subKnopCBLabel" , "Substitutions" },
				{ "subKnopExtraCBLabel" , "Substitutions extra" },
				
				{ "grafiekToolCBLabel" , "Graph tool" },
				{ "grafiekToolKnopLabel" , "Graph tool" },
				{ "vergelijkingCBLabel" , "Equation" },
				{ "eindOplossingCBLabel" , "Answer needed" },
				{ "onafhankelijkCBLabel", "Independent"},
				{ "checkCBLabel" , "Checkable" },
				{ "teltMeeCBLabel" , "Include in grading" },
				{ "logCBLabel" , "LogID" },
				{ "rmCBLabel" , "Calculator" },
				{ "pijlCBLabel" , "Arrow" },
				{ "substitutiesButtonLabel" , "substitutions" },
				{ "functiesButtonLabel" , "defined functions" },
				{ "strategieVersieLabel" , "Strategy version" },
				{ "oefenVersieLabel" , "Strategy+ version" },
				{ "bordjesVersieLabel" , "Cover-up method version" },
				
				{ "titelKeuzeTestwaarden" , "Choose test values" },
				{ "tekstKeuzeTestwaarden" , "Test value interval is now " },
				{ "titelDefVariabelen" , "Definitions variables" },
				{ "titelDefFuncties" , "Definitions functions" },
				
				{ "herleidingKeuze_0" , "None" },
				{ "herleidingKeuze_1" , "Polynom expanded and symplified" },
				{ "herleidingKeuze_2" , "One power" },
				{ "herleidingKeuze_3" , "Without negative or fractioned power" },
				{ "herleidingKeuze_4" , "One fraction" },
				{ "herleidingKeuze_5" , "One logaritme" },
				{ "herleidingKeuze_6" , "Written as simple log's (fe log(x)+log(3))" },
				
				{ "feedbackTekst01" , "This step contains correct and incorrect parts. Change or delete the parts that are not correct." },
				{ "feedbackTekst02" , "Not all the solutions fulfill the original equation. Delete the solution(s) that don't fulfill." },
				{ "feedbackTekst03" , "The inequality is solved correctly." },
				{ "feedbackTekst04" , "The equation is solved correctly." },
				{ "feedbackTekst05" , "Give the asked approximation." },
				{ "feedbackTekst06" , "Give the solutions of the inequality." },
				{ "feedbackTekst07" , "Solution(s) are missing. Add the missing one(s)." },
				{ "feedbackTekst08" , "Don't use |- marks." },
				{ "feedbackTekst09" , "The syntax is not correct." },
				{ "feedbackTekst10" , "The solution is correct, but not yet in the right form." },
				{ "feedbackTekst11" , "This is a correct approximation" },
				{ "feedbackTekst12" , "The answer is correct." },
				{ "feedbackTekst13" , "The anser is equivalent, but not yet in the right form." },
				{ "feedbackTekst14" , "The syntax is not correct." },
                { "feedbackTekst15" , "Correct answer." },
                { "feedbackTekst16" , "The is a correct equation" },
                { "feedbackTekst17" , "This equation doesn't have the right form yet" },
                { "feedbackTekst18" , "The answer is correct, but the number of significant figures isn't right." },
                { "feedbackTekst19" , "The answer is correct, but doesn't have the right form and the number of significant figures isn't right." },
                { "feedbackTekst20" , "The answer is correct, number of significant figures is right, but doesn't have the right form." },
                { "feedbackTekst21a" , "You have found all solutions, fill them in in the solution bar."},
                { "feedbackTekst21b" , "You have found all solutions."},
                { "feedbackTekst22" , "You have found all solutions in this branch, continue with a different branch."},                
                
                { "feedbackReactieVerg01" , "Je reactievergelijking bevat nog niet de juiste moleculen."},
                { "feedbackReactieVerg02" , "De elementenbalans van je reactievergelijking klopt niet."},
                { "feedbackReactieVerg03" , "De ladingen bij de moleculen kloppen niet."},
                { "feedbackReactieVerg04" , "De ladingenbalans van je reactievergelijking klopt niet."},
                { "feedbackReactieVerg05" , "Is het een evenwichtsreactie of een aflopende reactie?" },
                { "feedbackReactieVerg06" , "Je kunt de vergelijking eenvoudiger schrijven."},
                { "feedbackReactieVerg07" , "Dit is een kloppende reactie, maar niet die waar om werd gevraagd."},

                { "xVarMessage1" , "The independent variable is alway\n" 
									+ "a letter.\n " 
									+ "In the case of word variables\n" 
									+ "the first character of a word variable\n" 
									+ "is alway a letter." },
				{ "xVarMessage2" , "The independent variable can only be \n" 
									+ "represented by one letter.\n" 
									+ "Only when the option \"word variables\" \n" 
									+ "is selected, the independent variable \n" 
									+ "can be represented by more letters." },
				{ "xVarMessage3" , "The letter e is used for  \n" 
									+ "the exponential function.\n" 
									+ "This letter can not be used for the name\n" 
									+ "of an independent variable." },									
				{ "xVarMessage4a" , "The tekst:  \"" },
				{ "xVarMessage4b" , "\" for the known mathematical function \n," 
									+ "de betreffende wiskundige functie en mag dus"
									+ "so cannot be used in the name of a variable"},
									
				{ "gelijkwaardigKnopLabelGR" , "Next line" },
				{ "terugKnopLabelGR" , "Previous line" },
				
				{ "editorVersieKnopLabel1" , "New editor version" },
				{ "editorVersieKnopLabel2" , "Old editor version" },
				
				{"antwoordVakLabel" , "answer box"},
				{"interactieVakLabel" , "interactive component"},
				{"tekstVakLabel" , "text box"},
				{"grafiekComponentLabel" , "graph component"},
				
				
				
				{"interactieKeuzeLabel" , "Choose type of "},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "Cancel"},
				{"sluitKnopLabel" , "Close"},
				{"verwijderKnopLabel" , "Remove"},
				{"wijzigKnopLabel" , "Change"},
				{"fileKnopLabel" , "File"},
				{"editUrlLabel" , "URL of image"},
				{"kiesAfbeeldingLabel" , "Choose an image"},
				{"afbeeldingenBeherenLabel" , "Manage images"},
				{"urlKnopLabel" , "URL"},
				{"bewerkenLabel" , "Edit"},
				{"toevoegenLabel" , "Add"},
				{"breedteLabel" , "Width:"},
				{"hoogteLabel" , "Height:"},
				{"volleBreedteLabel" , "Full width"},
				{"popupLabel" , "Popup"},
				
				{"feedbackCBLabel" , "Feedback/partial scores"},
				{"feedbackSizeCBLabel" , "Popup size"},
				{"uitwCBLabel" , "Popup for steps"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "Your own"},
				{"feedbackLabel" , "feedback"},
				{"ideasButtonLabel" , "options"},
				{"substitutiesButtonLabel" , "substitutions"},
				{"antwoordmodelButtonLabel" , "possible answer"},
				{"formuleInvoerModeCBLabel" , "Formula input mode"},
				{"aantalKeuzesLabel" , "Number of choices"},
				{"aantalSelectieObjLabel" , "Number of selection objects"},
				{"randomPosLabel" , "Randomize positions"},
				{"meervSelectiesLabel" , "Multiple selections possible"},
				{"checkViaFormuleLabel" , "Check by using a formula"},
				{"aantalSleepObjLabel" , "Number of drag objects"},
				{"aantalDoelObjLabel" , "Number of target objects"},
				{"snapToTargetLabel" , "Snap to target object"},
				{"snapMargeLabel" , "Snap margin"},
				{"checkVasteDoelenLabel" , "Check on fixed targets for drag objects"},
				{"checkWaardeOpDoelLabel" , "Check using values of drag objects"},
				{"relocateCBLabel" , "Jumps back"},
				{"viewCBLabel" , "Show wrong drag object"},
				{"aantalValueObjectenLabel" , "Number of objects"},
				{"checkAfzonderlijkLabel" , "Check separately"},
				{"checkOpSamenhangLabel" , "Check in coherence"},
				{"boxMetRand" , "Border"},
				{"meerregelig" , "More rules possible"},
				{"keuzeVakKiesLabel" , "Choose"},
				{"verzamelDoelCBLabel" , "Target object as collection area"},
				{"oplossingenRegelZichtbaar", "Solution bar visible"},
				{"rekenVakZichtbaar", "Equation box visible"},
				{"scoreCumulatiefCBLabel","Score cumulative"},
				
				{"vormCBLabel" , "Form"},
				{"formuleToolCBLabel" , "Formula input editor"},
				{"goedLabel" , "Correct"},
				{"doorLabel" , "Go on"},
				{"foutLabel" , "Wrong"},
				{"halfLabel" , "Half"},
				
				{"geenOplossingen" , "no solutions"},
				{"allesOplossing" , "all is solution"},
				{"antwoordModelGeen" , "none"},
				{"abc" , "discr"},
				
				{"checkExternalCBLabel" , "check external"},
				{"contextVarCBLabel", "Use contextvariables"},
				{"rmAantalDecLabel", "Number of decimals"},
				
				{"FEV_titleStartLabel", "Start equation"},
				{"FEF_titleStartLabel", "Start expression"},
				{"FEV_titleAntwoordLabel", "Correct answer"},
				{"FEV_titleAntwoordNrLabel", "Answer"},
				{"FEV_titleContextLabel", "Context variables"},
				{"FEV_titleFeedbackLabel", "Feedback text"},
				{"FEV_titleVerificatieLabel", "Verification"},
				{"FEV_titleHulpLabel", "Help solving"},
				{"FEV_titleOpmaakLabel", "Layout"},
				{"FEV_titleLoggingLabel", "Checking / logging"},
				{"FEV_titleScoringLabel", "Score"},
				{"FEV_titleVormLabel", "Correct forms"},
				
				{"AKV_titleTekstenLabel", "List of choices"},
				
				// TekstVakInteractiePanel
				{"titleFormuleAntwVakLabel" , "Settings formula answer box with steps"},
                {"titleVergelijkingAntwVakLabel" , "Settings equation answer box with steps"},
                {"titleSimpelFormuleAntwVakLabel" , "Settings small formula answer box"},
                {"titleSimpelVergelijkingAntwVakLabel" , "Settings small equation answer box"},
				{"formuleAntwVakLabel" , "Formula answer box with steps"},
                {"vergelijkingAntwVakLabel" , "Equation answer box with steps"},
                {"simpelFormuleAntwVakLabel" , "Small formula answer box"},
                {"simpelVergelijkingAntwVakLabel" , "Small equation answer box"},
                {"tekstAntwVakLabel" , "Text-answer box"},
                {"algebraPijlenLabel" , "Algebra Arrows"},
                {"blokkenbouwenLabel" , "Building with blocks"},
                {"stroomdiagrammenLabel" , "Flow diagrams"},
                {"grafiekenToolLabel" , "Graphing tool"},
                {"tekstVakLabelH" , "Text box"},
				{"geogebraIpLabel" , "Geogebra 4 (coming soon)"},
				{"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "Fruit balance"},
				{"checkSelectieUnitLabel" , "Check selection unit"},
				{"checkTekstAntwoordVakLabel" , "Check-text answer box"},
				{"keuzeAntwoordVakLabel" , "Choice answer box"},
				{"doorzienIpLabel" , "3D construction-component"},
				{"checkSleepUnitLabel" , "Check drag/drop unit"},
				{"vergrotenIpLabel" , "PE Enlargement"},
				{"vangenIpLabel" , "PE Catching"},
				{"verknippenIpLabel" , "Cutting"},
				{"geomAlgebra2dIpLabel" , "Geom.algebra 2d"},
				{"geomAlgebra1dIpLabel" , "Geom.algebra 1d"},
				{"normaleVerdelingIpLabel" , "Normal distribution"},
				{"mp3PlayerIpLabel" , "Mp3-player"},
				{"binominaleVerdelingIpLabel" , "Binomial distribution"},
				{"getallenlijnIpLabel" , "Number line (jump)"},
				{"tekenVeelvlakIpLabel" , "Drawing in space"},
				{"mozaikIpLabel" , "Mozaik"},
				{"veelvlakkenIpLabel" , "Polyhedra"},
				{"eerlijkVerdelenIpLabel" , "PE Equal sharing"},
				{"statistiekIpLabel" , "Statistical representations"},
				{"stroomdiagrammenIpLabel" , "Flow diagrams"},
				{"tegelsIpLabel" , "Tilings"},
				{"checkWaardeUnitLabel" , "Check value unit"},
				{"omtrekAppletIpLabel" , "PE circumference applet"},
				{"algebraExpressiesIpLabel" , "Algebra trees"},
				{"oppervlakteAlgebraIpLabel" , "[test] Area algebra"},
				{"blokkenProgrammaIpLabel" , "[test] Block programs"},
				{"grafieken3DIpLabel" , "Graphs 3D"},
				{"spotProblemsIpLabel" , "Spot problems"},
				{"kladjeIpLabel" , "Note"},
				{"kansbomenIpLabel" , "Probability trees"},
				{"rekenmachineIpLabel" , "Calculator"},
				{"formStructIpLabel" , "[test] FormStruct"},
				{"graphToolIpLabel" , "GraphTool"},
				{"draaibankIpLabel" , "Turning lathe"}, 
				{"waarmakersIpLabel" , "[test] Truemakers"},
				{"statSimIpLabel" , "Statistics Simulations"},
				{"stelselVakLabel", "System of equations"},
	            {"javaLogoIpLabel", "Programming JavaLogo"},
	            {"symboolIpLabel", "Shape"},
	            {"samengesteldeStappenIpLabel", "Composite steps"},
	            {"checkButtonIpLabel", "Check button"},
                {"sliderIpLabel", "Slider"},
                {"heksIpLabel", "Witch"},
                {"geoDefinerIpLabel", "GeoDefiner"},
                {"javaLogo3DIpLabel", "Programming JavaLogo 3D"},
                
                {"checkButtonsMenuLabel", "Check buttons"},
                
                {"kiesKoppelingLabel", "Choose linkage"},
                {"koppelingLabel", "Linkage"},
                {"popupTitelLabel", "Title"},
                

	            //CheckButtonEditor
                {"CB_kijkNaOptieLabel", "Check" },
                {"CB_bewaarOptieLabel", "Save" },
                {"CB_rondAfOptieLabel", "set completed" },
                {"CB_nextPageOptieLabel", "To next page" },
                {"CB_eigenVakOptieLabel","All in same box"},
                {"CB_opPaginaOptieLabel","All on page"},
                {"CB_viaXWidgetOptieLabel","All connected via x-widget"},
                
				
				//InstellingenPanel
                {"OPT_instellingenActiviteitTitel", "Settings activity"},
				{"OPT_wiskundeLabel" , "Mathematics"},
                {"OPT_navigatieLabel" , "Navigation"},
                {"OPT_layoutLabel" , "Layout"},
                {"OPT_nakijkenLabel" , "Check-options"},
				{"OPT_vermenigvTeken" , "Multiplication sign: X"},
				{"OPT_woordformules" , "Word variables "},
				{"OPT_tweeHoofdletterVars" , "Variables like AB, BC etc."},
				{"OPT_tempoToets" , "Restricted time"},
				{"OPT_opnieuwKnop" , "'All again'-button"},
				{"OPT_itemOpnieuwKnop" , "'Item again'-button"},
				{"OPT_checkPerOpdracht" , "Check per page"},
				{"OPT_hoekInGraden" , "Angle unit: degrees"},
				{"OPT_opdrachtBolletjes" , "Item selector"},
				{"OPT_volgendeKnop" , "Next-button"},	
				{"OPT_VorigeKnop" , "Previous-button"},
				{"OPT_paginaIpvOpdracht" , "Label: 'Page' instead of 'Problem'"},
				{"OPT_fontFormaat" , "Size "},
				{"OPT_fontNaam" , "Basic Font"},
				{"OPT_tijdsLimiet" , "Time limit (sec)"},
				{"OPT_formTimes" , "Formulas in Times Roman font"},
				{"OPT_navigatieFormaat" , "Size navigation bar"},
				{"OPT_margesLabel" , "Margins:"},
				{"OPT_margeLinksLabel" , "Left"},
				{"OPT_margeRechtsLabel" , "Right"},
				{"OPT_margeBovenLabel" , "Above"},
				{"OPT_margeOnderLabel" , "Below"},
				{"OPT_fToets" , "F-keys for formulas"},
				{"OPT_globalParam" , "Global parameters"},
				{"OPT_diffOperatoren" , "Differential operators"},
				{"OPT_voortgangKnop", "'Progress' instead of 'Total'"},
				{"OPT_conditionalNav" , "Conditional navigation"},
				{"OPT_conditionalPercLabel" , "Percentage"},
				{"OPT_voorwaarden", "Conditions per page"},
				{"OPT_allesCorrect", "Next page only if everything correct (green)"},
				{"OPT_deelOpdr" , "Item numbers a,b,c etc"},
				{"OPT_zelftoetsGeenCorr" , "No correction self test"},
				{"OPT_zelftoetsGeschiedenis" , "self-test history"},
				{"OPT_zelftoetsHighScore" , "highscore"},
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_eerderGeenCorr" , "No correction previous pages"},
				{"OPT_significantie" , "Check option significant numbers"},
				{"OPT_objectives" , "Learning objectives"},
				{"OPT_objectivesButton" , "Choose learning domain"},
				{"OPT_objectivesViewButton" , "Linked learning objectives"},
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_fontOvererving" , "Font-inheritance text boxes"},
				{"OPT_fontOverervingForm" , "Font-inheritance formula boxes"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Use styles"},
				{"OPT_importStyles" , "Import"},
				{"OPT_exportStyles" , "Export"},
				{"OPT_layers" , "Use layers"},
				{"OPT_pageLabel" , "Page:"},
				{"OPT_docWidthLabel" , "Page: Width"},
                {"OPT_docHeightLabel" , "Height (min)"},
                {"OPT_combCompNav" , "Combined components"},
                {"OPT_stylesWarnDialog" , "All styles will be lost. Ok?"},
                
                {"OPT_styleInteractionsLabel" , "Style answerboxes"},
                {"OPT_TemplateGeenLabel" , "No template"},
				{"OPT_TemplateBasisLabel" , "Template Basic style"},
                {"OPT_TemplateNumworxLabel" , "Template Numworx style"},
                
				{"OBJ_leerdoel", "Objective"},
				{"OBJ_categorie", "Category"},
				{"OBJ_categorieBox", "Objectives in multiple categories"},
				{"OBJ_kolomMeerButton", "Add column"},
				{"OBJ_kolomMinderButton", "Remove column"},
				{"OBJ_leerdoelInstellingen", "Settings learning objectives"},
				{"OBJ_gebruikAanwezigLeerdomein", "Use present learning domain"},
				{"OBJ_gebruikEigenLeerdoelen", "Your own learning objectives for this activity"},
				{"OBJ_koppelLeerdoelTitel", "Link to learning objectives"},
				
				{"MCC_misconception", "Error type"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "Variables of the function"},
				{"GEP_assenLabel" , "Show axes"},
				{"GEP_grafiekOptiesLabel" , "Options graphing tool"},
				
				{"GEP_varXLabel" , "Variable x-axis"},
				{"GEP_varYLabel" , "Variable y-axis"},
				
				{"GEP_assenOptie" , "Axes"},
				{"GEP_roosterOptie" , "Grid"},
				{"GEP_roosterGrofOptie" , "wide"},
				{"GEP_schaalverdelingOptie" , "Axis numbers"},
				{"GEP_piOptie" , "Grid for Pi"},				
				
				{"GEP_zoomOptie" , "Zoom-option"},
				{"GEP_traceOptie" , "Trace-option"},
				{"GEP_dragOptie" , "Drag-option"},
				{"GEP_tekenOptie" , "Graph-drawing tool"},
				
				{"GEP_tabelOptie" , "Table-tool"},
				{"GEP_zoomInTabelOptie" , "Zoom in table"},
				{"GEP_tabelTekenToolOptie" , "Table as drawing tool"},

				{"GEP_functieEditOptie" , "Function editor"},
				{"GEP_grafiekKleurenOptie" , "Different colors"},
				
				{"GEP_formeleFunctieNotatieOptie" , "Formal function notation f(x), g(x) etc."},
				
				{"GEP_popupWeergave" , "Show through pop-up"},
				
				{"GEP_xPositief" , "x positive"},
				{"GEP_yPositief" , "y positive"},
				{"GEP_xEditable" , "x editable"},
				{"GEP_yEditable" , "y editable"},
				
				
				{"GEP_opdrachten" , "tasks"},
				
				{"GEP_kiesOpdracht" , "choose the type of task"},
				{"GEP_opdracht1" , "find the formula for a given line graph"},
				{"GEP_opdracht2" , "find the formula for a number of graph points"},
				{"GEP_opdracht3" , "draw a number of points for a given formula"},
				{"GEP_opdracht4" , "draw the points from the table in the graph"},
				
				{"GEP_antwoordFormule" , "enter the solution formula in the function editor below"},
				{"GEP_tabelPuntenX" , "enter the x-values of the graph points in the table below" },
				{"GEP_tabelPunten" , "enter the points in the table below" },
				
				{"GEP_nauwkeurigheid" , "Accuracy (pixels)"},
				{"GEP_minimumPunten" , "Minimum number of points"},
				{"GEP_maximumScore" , "Maximum score"},
				{"GEP_leerlingZietTabel" , "Pupil can see table"},
				
				{"GE_kijkNa" , "Check" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "Text"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "Window width"},
				{"LEP_vensterHoogte" , "Window height"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "Add"},
				{"IEP_verwijderen" , "Remove"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "Cancel"},
				{"editImageKnopLabel" , "Image checkButton"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "Border"},
				{"TVEP_achtergrondKleurAanwezig" , "Background Color"},
				{"TVEP_zwevend" , "Floating above text"},
				{"TVEP_anderFont" , "Other font"},
				{"TVEP_rondingHoeken" , "Rounding corners"},
				{"TVEP_rotatieHoek" , "Rotation angle"},
				{"TVEP_centreerLabel" , "Center"},
				{"TVEP_centreerHor" , "Horizontally"},
				{"TVEP_centreerVert" , "Vertically"},
				{"TVEP_pasAanH" , "Adjust height"},
				{"TVEP_pasAanB" , "Adjust width"},
				{"TVEP_aantalRijen" , "Number of rows"},
				{"TVEP_aantalKolommen" , "Number of columns"},
				{"TVEP_tabelRanden" , "Inner borders table"},
				{"TVEP_celMarge" , "Margin left"},
				{"TVEP_bovenMarge" , "Margin up"},
				{"TVEP_fontType" , "Font"},
				{"TVEP_achtergrondKleur" , "Color"},
				{"TVEP_interlinie" , "Line spacing"},
				{"TVEP_cellSpaceColumn" , "Space"},
				{"TVEP_cellSpaceRow" , "Space"},
				{"TVEP_layoutLabel" , "Layout text box"},
				{"TVEP_gebruikersInteractieLabel" , "User interaction"},
				{"TVEP_selectieObject" , "Selection object"},
                {"TVEP_selectieKleur" , ""},
                {"TVEP_selectieKleurKnopLabel" , "Color"},
                {"TVEP_sleepObject" , "Drag object"},
                {"TVEP_draaiObject" , "Rotating object"},
                {"TVEP_sleepDoel" , "Drag target"},
                {"TVEP_sleepHandle" , "handle"},
                {"TVEP_selectieSleepWaarde" , "value    ("},
                {"TVEP_fgKleurKnopLabel" , "color"},
                {"TVEP_zichtbaarNaNakijken" , "Visible after check test"},
                {"TVEP_balansVergCom" , "Balance-Equation box communication"},
                {"TVEP_aftrekPopup" , "Detect using popup"},
                {"TVEP_callOut" , "Call out box"},
                {"TVEP_vulHoogte" , "Fill up height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "Steps"},
                {"TVEP_random" , "random"},
                {"TVEP_linkObject" , "Link object"},
                {"TVEP_editLink" , "Edit link"},
                {"TVEP_defaultBijNull" , "default  )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_puntenaftrek" , "Deduction of points"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
                {"TVEP_noStyleChoiceLabel", "No Style"},
                {"TVEP_styleSettingsLabel", "Settings"},
                {"TVEP_stylesLabel", "Style:"},
                {"TVEP_editStylesButton", "Edit"},
                {"TVEP_bewerkStijlLabel", "Edit style"},
                
                {"TVEP_lineText_OpmaakTekst", "Layout text"},
                {"TVEP_lineText_OpmaakVak", "Layout box"},
                {"TVEP_lineText_OpmaakTabel", "Layout table"},
                {"TVEP_lineText_OpmaakExtra", "Layout extra"},
                {"TVEP_lineText_InteractieKenmerken", "Interaction attributes"},
                {"TVEP_lineText_InteractieSoorten", "Interaction types"},
                {"TVEP_lineText_InteractieVerwerking", "Interaction processing"},
                
                {"TVEP_respToggleWidthLabel", "minimum total width"},
                {"TVEP_respMinLabel", "min"},
                {"TVEP_respMaxLabel", "max"},
                {"TVEP_respConstantLabel", "constant"},
                {"TVEP_respFactorLabel", "factor"},
                
                //Style Manager
                {"SM_titelLabel", "Manage Styles"},
                {"SM_addStyleButton", "Save settings as new style"},
                {"SM_saveStyleButton", "Save style"},
                {"SM_removeStyleButton", "Remove style"},
                {"SM_closeButton", "Close"},
                {"SM_addStyleAction", "Give style name"},
                
                //Text Editor + tooltips
                {"TE_menuTemplateComponents", "Template components"},
                {"TE_menuWidgets", "Widgets"},
                {"TE_menuAntwoordTypes", "Answer types"},
                {"TE_menuTekstvakken", "Text boxes"},
                
                {"TE_formuleButtonTooltip", "Add Formula"},
                {"TE_graphButtonTooltip", "Add graph tool"},
                {"TE_linkButtonTooltip", "Add link"},
                {"TE_imageButtonTooltip", "add image"},
                {"TE_answerboxButtonTooltip", "add answer box"},
                {"TE_widgetButtonTooltip", "Add widget"},
                {"TE_geogebraButtonTooltip", "Add GeoGebra"},
                {"TE_tekstVakButtonTooltip", "Add text box"},
                {"TE_compositeButtonTooltip", "Add composite component"},
                {"TE_templateCompButtonTooltip", "Add component with template skin"},
                {"TE_templateButtonTooltip", "Choose template page"},
                {"TE_x-widgetButtonTooltip", "Cross-widget connections"},
                {"TE_parameterButtonTooltip", "Use random parameters"},
                {"TE_opsommingButtonTooltip", "Add list"},
                {"TE_vormenButtonTooltip", "Add shape"},
                {"TE_geodefinerButtonTooltip", "Add GeoDefiner"},
               				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "Save option"},
				{"GEP_alsTool" , "As tool"},
				{"GEP_rand" , "Border"},
				{"GEP_resetIcon" , "Reset-option"},
				{"GEP_checkMetCheckDWO" , "Using checkDWO"},
				{"GEP_checkMetObjecten" , "Using created objects"},
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "Minimum value"},
				{"GSEP_maxValue" , "Maximum value"},
				{"GSEP_eenheden" , "Units visible"},
				{"GSEP_getallen" , "Numbers"},
				{"GSEP_10tallen" , "Mark for tens"},
				{"GSEP_5tallen" , "Marh for fives"},
				{"GSEP_nul" , "Zero"},
				{"GSEP_pijl" , "Arrow visible"},
				{"GSEP_pijlTerug" , "Arrow back"},
				{"GSEP_horizontaal" , "Horizontal"},
				{"GSEP_eenheid" , "Unit"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "Formula editor"},
				{"TEEP_rekenToolOptie" , "Calculator"},
				{"TEEP_grafToolOptie" , "Graph tool"},
				{"TEEP_titleStartLabel", "Tekst-answer-box"},
				{"TEEP_checkDocentCBLabel", "Check (by teacher)"},
				{"TEEP_maxScoreLabel", "Maximum score"},
				{"TEEP_editorOptiesLabel", "Editor options"},
				
				//Ideas
				
				{"ideasTip",		"hint"},
				{"ideasHelp",		"help"},
				{"ideasStap",		"step"},
				{"ideasLosop",		"solve"},
				{"ideasWordtDan",		"becomes"},
				
				{"algebra.equations.coverup.denominator"		,"cover up the denominator"	},
				{"algebra.equations.coverup.minus-left"			,"move constant expressions to the right"	},
				{"algebra.equations.coverup.minus-right"		,"use the coverup method"	},
				{"algebra.equations.coverup.negate"				,"divide by -1"	},
				{"algebra.equations.coverup.numerator"			,"cover up the nominator"	},
				{"algebra.equations.coverup.plus"				,"move constant expressions to the right"	},
				{"algebra.equations.coverup.power"				,"take the square root"	},
				{"algebra.equations.coverup.sqrt"				,"square both sides"	},
				{"algebra.equations.coverup.times"				,"isolate the variable by dividing both sides"	},
				{"algebra.equations.coverup.times-positive"		,"isolate the variable by dividing both sides"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"move constant terms to the right by adding a number to both sides"	},
				{"algebra.equations.coverup.onevar.plus"		,"move constant terms to the right by subtracting a number from both sides"	},
				
				{"algebra.equations.linear.distr-times"		,"remove parentheses"	},
				{"algebra.equations.linear.flip"			,"swap the equation"	},
				{"algebra.equations.linear.merge"			,"simplify by taking expression together or calculation"	},
				{"algebra.equations.linear.remove-div"		,"remove fractions by multiplying with a number"	},
				{"algebra.equations.linear.var-left"		,"move expression with variables to the left"	},
				
				{"algebra.equations.buggy.cancel-minus"				,"you cannot cancel terms because the sign is not the same"	},
				{"algebra.equations.buggy.distr-times-denom"		,"mistake in removing parentheses: one of the terms is a fraction, and the factor is multiplied with the nominator of the fraction."	},
				{"algebra.equations.buggy.distr-times-plus"			,"when removing parentheses one term has not been multiplied"	},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"when removing parentheses one term has been forgotten"	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"remember the signs when removing parentheses"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"when removing parentheses only multiply the terms in between parentheses"	},
				{"algebra.equations.buggy.divide-negate"			,"note the sign when dividing"	},
				{"algebra.equations.buggy.divide-numdenom"			,"fraction inverted. Think about the number you have to use for dividing"	},
				{"algebra.equations.buggy.flip-negate-one-side"		,"you have to change the sign on both sides"	},
				{"algebra.equations.buggy.multiply-one-side"		,"you have to multiply both sides"	},
				{"algebra.equations.buggy.minus-minus"				,"when removing parentheses: multiplying two negative numbers gives a positive number"	},
				{"algebra.equations.buggy.multiply-forget-one"		,"one of the terms has been forgotten when multiplying both sides"	},
				{"algebra.equations.buggy.negate-all"				,"one of the terms has been forgotten when changing the sign"	},
				{"algebra.equations.buggy.negate-one-side"			,"one of the sides has been forgotten when changing the sign"	},
				{"algebra.equations.buggy.plus"						,"think about the sign when you move a term from one side to the other"	},
				{"algebra.equations.buggy.priority-times"			,"remember rules for priorities and parentheses"	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"in the square formula D=b^2-4ac and not D=b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"not the negation in front of b: "	},
				{"algebra.equations.buggy.abc.one-solution"				,"there is a second solution"	},
				{"algebra.equations.buggy.abc.two-a"					,"divide by 2a and not a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"you have forgotten the other (negative) square root"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"before taking square roots you need to perform another action"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"before taking square roots you need to perform another action"	},
				{"algebra.equations.buggy.coverup.square-minus"			,"you cannot take a square root from a negative number"	},
				{"algebra.equations.buggy.coverup.times-mul"			,"instead of dividing the right-hand side you multiply it"	},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"when you divide you have to divide all terms"	},
				{"algebra.equations.buggy.distr-square"					,"when taking the square of two terms you have forgotten the two cross products"	},
				{"algebra.equations.buggy.distr-square-forget"			,"when taking the square of two terms you have forgotten one of the terms"	},
				{"algebra.equations.buggy.square-multiplication"		,"incorrect square of two terms"	},
				{"algebra.equations.buggy.division-by-var-both"		,"when dividing by a variable you lose the solution var=0"	},
				{"algebra.equations.buggy.division-by-var-zero"		,"when dividing by a variable you lose the solution var=0"	},
				
				{"algebra.equations.linear.balance.collect"			,"combine"	},
				{"algebra.equations.linear.balance.calculate"		,"calculate"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"write division as multiplication with a fraction"	},
				{"algebra.equations.linear.balance.smart-div"		,"divide by a common factor"	},
				{"algebra.equations.linear.balance.con-right-minus"	,"subtract {?} from both sides"	},
				{"algebra.equations.linear.balance.con-left-minus"	,"subtract {?} from both sides"	},
				{"algebra.equations.linear.balance.var-right-minus"	,"subtract {?} from both sides"	},
				{"algebra.equations.linear.balance.var-left-minus"	,"subtract {?} from both sides"	},
				{"algebra.equations.linear.balance.con-right-plus"	,"add {?} to both sides"	},
				{"algebra.equations.linear.balance.con-left-plus"	,"add {?} to both sides"	},
				{"algebra.equations.linear.balance.var-right-plus"	,"add {?} to both sides"	},
				{"algebra.equations.linear.balance.var-left-plus"	,"add {?} to both sides"	},
				{"algebra.equations.linear.balance.distribute"		,"remove parentheses"	},
				{"algebra.equations.linear.balance.remove-div"		,"multiply both sides with {?}"	},
				{"algebra.equations.linear.balance.scale-to-one"	,"divide both sides by {?}"	},
				{"algebra.equations.linear.balance.negate"    ,"change the sign on both sides"  },
				{"algebra.equations.linear.balance.intro-false"    ,"not possible"  },
				{"algebra.equations.linear.balance.intro-true"    ,"alway true"  },
                
               
				{"algebra.equations.quadratic.abc"				,"use the quadratic formula"	},
				{"algebra.equations.quadratic.approx"			,"approximate"	},
				{"algebra.equations.quadratic.cancel"			,"remove expressions from both sides of the =-symbol"	},
				{"algebra.equations.quadratic.common-factor"	,"factorize using the common factor"	},
				{"algebra.equations.quadratic.distr-div"		,"divide"	},
				{"algebra.equations.quadratic.distr-square"		,"calculate square"	},
				{"algebra.equations.quadratic.left-square"		,"write left-hand side as a square"	},
				{"algebra.equations.quadratic.move-left"		,"move everything to the left"	},
				{"algebra.equations.quadratic.nice-factors"		,"factorize the three expressions"	},
				{"algebra.equations.quadratic.no-lin"			,"write as square=number"	},
				{"algebra.equations.quadratic.prepare-split"	,"complete to a square"	},
				{"algebra.equations.quadratic.product-zero"		,"product=0, equate factors to 0"	},
				{"algebra.equations.quadratic.same-con-factor"	,"divide both sides through a common factor"	},
				{"algebra.equations.quadratic.same-factor"		,"A*B=A*C implies A=0 or B=C"	},
				{"algebra.equations.quadratic.simpler-poly"		,"simplify by dividing through a common factor"	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"simplify square roots"	},
				{"algebra.equations.quadratic.square-both"		,"square both sides"	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"apply the substitution backwards"	},
				{"algebra.equations.polynomial.expose-factor"		,"isolate the common factor"	},
				{"algebra.equations.polynomial.power-factors"		,"common factor x"	},
				{"algebra.equations.polynomial.subst"				,"use substitution"	},
				{"algebra.equations.polynomial.def-power-nat"   	,"write power as repeated multiplication"},
				
				
				{"algebra.equations.rational.check-solution"	,"check the solution"	},
				{"algebra.equations.rational.cross-multiply"	,"cross multiply"	},
				{"algebra.equations.rational.division-one"		,"when fraction=1 we have nominator = denominator"	},
				{"algebra.equations.rational.division-zero"		,"when fraction=0 we have nominator=0 (if denominator is not zero)"	},
				{"algebra.equations.rational.multiply-one-div"	,"multiply both sides with the deonimnator of the fraction"	},
				{"algebra.equations.rational.same-dividend"		,"A/B=A/C implies A=0 or B=C"	},
				{"algebra.equations.rational.same-divisor"		,"denominators the same, equate nominators"	},
				
				{"algebra.inequalities.flip-sign"		,"change the sign"	},
				{"algebra.inequalities.give-solution"	,"solve the inequality"	},
				{"algebra.inequalities.to-equation"		,"turn it first into an equation"	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"multiply the powers by adding the exponents"	},
				{"algebra.manipulation.exponents.factor-as-power"		,"write (parts) as a power"	},
				{"algebra.manipulation.exponents.mul-exponents"			,"a power of a power: multiply the exponents"	},
				{"algebra.manipulation.exponents.reciprocal"			,"write 1/expression as expression^-1"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"write as a power by adding exponents"	},
				{"algebra.manipulation.exponents.sub-exponents"			,"divide the powers by subtracting the exponents"	},
				{"algebra.manipulation.exponents.write-as-power"		,"write as power"	},
				{"algebra.manipulation.exponents.distr-power"			,"use power of a product is a product of powers"	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"write the power expression^-1 as a fraction: 1/expression"	},
				{"algebra.manipulation.exponents.write-as-root"			,"write as square root"	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"write 1/power as another power in which the sign of the exponent has changed"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"move the negation out of the power (when exponent is odd)"	},
				{"algebra.manipulation.exponents.root"					,"give square root"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"power=1 implies exponent=0"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"same base number"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"approximate this power or square root"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"common power"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"write using the greatest common power"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"nth square root"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		,"use the definition glog(x)=a implies x=g^a"	},
				
				{"calculus.differentiation.deriv-of-poly"		,"differentiate a power function"	},
				{"calculus.differentiation.min"		,"apply the rule for subtraction"	},
				{"calculus.differentiation.negate"		,"move the negation out before differentiating"	},
				{"calculus.differentiation.plus"		,"apply the sum rule"	},
				{"calculus.differentiation.product"		,"apply the product rule"	},
				{"calculus.differentiation.quotient"		,"apply the quotient rule"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"you subtract {?} from the left but add {?} to the right"	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"you add {?} to the left but subtract {?} from the right"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"you subtract {?} from the right but add {?} to the left"	},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"you add {?} to the right but subtract {?} from the left"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"you subtract {?} from the left but don't do that to the right"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"you add {?} to the left but don't do that to the right"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"you subtract {?} from the left but add {?} to the right"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"you add {?} to the left but subtract {?} from the right"} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"you subtract {?} from the right but add {?} to the left"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"you add {?} to the right but subtract {?} from the left"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"you subtract {?} from the right but don't do that to the left"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"you add {?} to the right but don't do that to the left"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"you subtract {?} from the left but don't do that to the right"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"you add {?} to the left but don't do that to the right"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"you subtract {?} from the right but don't do that to the left"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"you add {?} to the right but don't do that to the left"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"not only have you swapped the left and right-hand sides, but also changed the sign in one side"	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"you subtracted to the right, did you do the same to the left?"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"you multiply with a number, but not the complete left-hand side"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"you negate, but not the complete left-hand side"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"you divide by a number, but not the complete left-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"you divide the left-hand side by {?}, but the right-hand side by the inverse"	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"you multiply the left-hand and right-hand sides with different numbers"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"you multiply the left-hand side with {?}, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"you divide the left-hand side by {?}, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"you negate the left-hand side, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"you divide one side by {?}, but not the other side"	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"multiplication mistake (1)"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"multiplication mistake (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"multiplication mistake, you loose the minus symbol"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"multiplication mistake, minus times minus is positive"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"division mistake, you divide by a negative number"	},
				{"algebra.equations.linear.balance.buggy.par1"		,"error in removing parentheses, multiply both terms in between parentheses (1)"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"remember the priority rules: first multiply, then add"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"minus symbol not moved correctly in between parentheses"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"error in removing parentheses, multiply both terms in between parentheses (2)"	},
				{"algebra.equations.linear.balance.buggy.par4"		,"error in removing parentheses, multiplication mistake (1)"	},
				{"algebra.equations.linear.balance.buggy.par5"		,"error in removing parentheses, multiply both terms in between parentheses (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		,"error in removing parentheses, multiply both terms in between parentheses (4)"	},
				{"algebra.equations.linear.balance.buggy.par7"		,"error in removing parentheses, multiply both terms in between parentheses with -1"	},
				{"algebra.equations.linear.balance.buggy.par8"		,"error in removing parentheses, look carefully at where the parentheses are"	},
				{"algebra.equations.linear.balance.buggy.par9"		,"error in removing parentheses, multiplication mistake (2)"	},
				
				//conditionele navigatie-panels
				{"CN_voorwaarden", "Conditions"},
				{"CN_vanPagina","From page"},
				{"CN_naarPagina","To page"},
				{"CN_scorePagina","Pages for score"},
				{"CN_grensPercentage","Cut-off perc."},
				{"CN_sorteer","Sort"},
				{"CN_regelMeer", "Add line"},
				{"CN_regelMinder", "Remove line"},
				
				//layer panels
				{"L_layers", "Layers"},
				{"L_layerName", "Layer-name"},
				{"L_layerVisible","Visible"},
				
				// crossswidget commands
				{"CBA_input", "input"},
				{"CBA_int.index", "choice" },
				{"CBA_balansvergelijking", "balance equation"},
				{"CBA_zetOplossing", "set solution" },
				{"CBA_maakStap", "make step" },
				{"CBA_vergelijking", "equation" },
				{"CBA_double", "numerical value"},
				{"CBA_double.solution", "oplossing"},
				{"CBA_expression", "expression"},
				{"CBA_equation", "equation"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Action: 2x incorrect answer"},
				{"CBA_action.half", "Action: partial-correct answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				{"CBA_action.check", "Action: check"},
				{"CBA_action.click", "Action: click"},
				{"CBA_action.popup", "Action: popup"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_haak", "Bracket"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				{"Steps_statistics", "Domain reasoner statistics"},
                {"Steps_action", " Action"},
                {"Steps_nrOfSteps", "Number of different steps"},
                {"Steps_name", "Step name"},
                {"Steps_content", "Step content"},
                {"Steps_required", "Required"},
				
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},

				// shareAction
				{ ShareAction.SHARE_KEY, "Shared key" },
				{ ShareAction.SHARE_MAP, "Shared components" },
// tablet opties
				{ "Tablet keyboard", "Math keyboard" },
				{ "Onderbouw-keyboard", "Simple" },
				{ "Algebra-keyboard", "Extended" },
				{ "Gonio-keyboard", "Gonio keyboard" },
				{ "Statistiek-keyboard", "Statistics keyboard" },
				{ "Meetkunde-keyboard", "Geometry keyboard" },
				{ "versionKeyboard", "Type keyboard" },
				{ "keyBoardAutomatisch", "Automatic" },
				{ "keyBoardDesktop", "Only for desktop" },
				{ "keyBoardTablet", "Only tablet" },
				{ "Tablet handschriftset", "Tablet handwriting" },
				{ "Basis", "Basic" },
				{ "Uitgebreid", "Extended" },
				
				{ "needsPremium", "For this activity you need a premium subscription."},

				{ "LinkType_FALSE", "default (new window)" },
                { "LinkType_TRUE", "embedded" },
                { "LinkType_PLAYER", "own window"},
                { "LinkType_CLIENT", "parent window"},
                { "LinkType_TOP", "top window"},
                
                { "TCOMP_list" , "List"},
                { "TCOMP_list_settings" , "List settings"},
                { "TCOMP_list_rowCount" , "Number of items"},
                { "TCOMP_list_numberType" , "Item number type"},
                { "TCOMP_list_chooseType" , "Choose type"},
                { "TCOMP_list_tabWidth" , "Tab width"},
                { "TCOMP_list_rowSpace" , "Space between items"},
                { "TCOMP_first_list_number" , "Start number"},
                
                { "TCOMP_multip" , "Multiple Choice"},
                
                { "TCOMP_multip_0" , "Multiple Choice vertical"},
                { "TCOMP_multip_settings" , "Multiple Choice settings"},
                { "TCOMP_multip_rowCount" , "Number of items"},
                { "TCOMP_multip_numberType" , "Item number type"},
                { "TCOMP_multip_chooseType" , "Choose type"},
                { "TCOMP_multip_tabWidth" , "Tab width"},
                { "TCOMP_multip_rowSpace" , "Space between items"},
                { "TCOMP_multip_hasPrefix" , "Item number"},
                
                { "TCOMP_multip_1" , "Multiple Choice horizontal"},
                { "TCOMP_multip_1_settings" , "Multiple Choice settings"},
                
                { "TCOMP_drag" , "Drag and Drop"},
                
                { "TCOMP_drag_0" , "Drag and Drop (vertical)"},
                { "TCOMP_drag_settings" , "Drag and drop settings"},
                { "TCOMP_drag_rowCount" , "Number of drag objects"},
                { "TCOMP_drag_itemWidth" , "Width drag object"},
                { "TCOMP_drag_itemHeight" , "Height drag object"},
                { "TCOMP_drag_rowSpace" , "Distance items"},
                { "TCOMP_drag_descrWidth" , "Text width"},
                
                { "TCOMP_drag_1" , "Drag and Drop (horizontal)"},
				{ "TCOMP_drag_1_settings" , "Drag and drop settings"},
				{ "TCOMP_drag_1_descrWidth" , "Height item-text bottom"},
				{ "TCOMP_drag_1_rowSpace" , "Distance target-/dragobjects"},
                
                { "TCOMP_edit" , "Edit"},
                { "TCOMP_addItem" , "Add item"},
                { "TCOMP_removeItem" , "Remove item"},
                { "TCOMP_decompose" , "Decompose"},
                { "TCOMP_select" , "Select"},
                
             // Helpteksten (URL's)
				{ "HELP_0_URL_0" , "https://app.dwo.nl/dwo/apps/player.html?t=0&profile=106&locale=nl#670371"},
				{ "HELP_0_URL_2" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#670370"},
				{ "HELP_0_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#670372"},
				{ "HELP_0_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#670373"},
				{ "HELP_0_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#670374"},
				{ "HELP_0_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#670375"},
				{ "HELP_0_URL_REKENMACHINE" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#670376"},
				{ "HELP_0_URL_SUBSTITUTIES" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#670377"},
				{ "HELP_0_URL_CONTEXTVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#670378"},
				{ "HELP_0_URL_EIGENOPDR" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#670379"},
				{ "HELP_0_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#670380"},
				{ "HELP_0_URL_UITWERKING" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#670381"},
				{ "HELP_0_URL_RAND_0" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#670382"},
				{ "HELP_0_URL_RAND_2" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671705"},
				{ "HELP_0_URL_VERIFICATIE" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#671068"},
				{ "HELP_0_URL_ANTWOORD_0" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671069"},
				{ "HELP_0_URL_ANTWOORD_2" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671706"},
				{ "HELP_0_URL_STARTEXPRESSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671070"},
				{ "HELP_0_URL_SCORE" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=106&locale=nl#671071"},
				{ "HELP_0_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671072"},
				
				{ "HELP_1_URL_3" , "https://app.dwo.nl/dwo/apps/player.html?t=0&profile=106&locale=nl#671172"},
				{ "HELP_1_URL_1" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#671173"},
				{ "HELP_1_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671174"},
				{ "HELP_1_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671175"},
				{ "HELP_1_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671176"},
				{ "HELP_1_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671177"},
				{ "HELP_1_URL_LINSTRATEGIEVERSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#671178"},
				{ "HELP_1_URL_LINSTARTEGIEOEFENVERSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#671179"},
				{ "HELP_1_URL_BORDJESVERSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671180"},
				{ "HELP_1_URL_BEWERKINGSKNOPPEN" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671181"},
				{ "HELP_1_URL_UITWERKINGSKNOPPENEXTRA" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671182"},
				{ "HELP_1_URL_SUBSTITUTIES" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671183"},
				{ "HELP_1_URL_ABC" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671184"},
				{ "HELP_1_URL_CONTEXTVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#671185"},
				{ "HELP_1_URL_EIGENOPDR" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671186"},
				{ "HELP_1_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671187"},
				{ "HELP_1_URL_UITWERKING" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=106&locale=nl#671188"},
				{ "HELP_1_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671189"},
				{ "HELP_1_URL_PIJL" , "https://app.dwo.nl/dwo/apps/player.html?t=18&profile=106&locale=nl#671190"},
				{ "HELP_1_URL_VERIFICATIE" , "https://app.dwo.nl/dwo/apps/player.html?t=19&profile=106&locale=nl#671191"},
				{ "HELP_1_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=20&profile=106&locale=nl#671192"},
				{ "HELP_1_URL_BEREKENANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=21&profile=106&locale=nl#671193"},
				{ "HELP_1_URL_STARTVERGELIJKING" , "https://app.dwo.nl/dwo/apps/player.html?t=22&profile=106&locale=nl#671194"},
				{ "HELP_1_URL_SCORE" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=236&locale=nl#671195"},
				{ "HELP_1_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=24&profile=106&locale=nl#671196"},
				
				{ "HELP_53_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671221"},
				{ "HELP_53_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671222"},
				{ "HELP_53_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671223"},
				{ "HELP_53_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671224"},
				{ "HELP_53_URL_REKENVAKZICHTBAAR" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671225"},
				{ "HELP_53_URL_OPLOSSINGREGEL" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#671226"},
				{ "HELP_53_URL_CONTEXTVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#671227"},
				{ "HELP_53_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671228"},
				{ "HELP_53_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671229"},
				{ "HELP_53_URL_VERIFICATIE" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671230"},
				{ "HELP_53_URL_VARIABELEN" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671231"},
				{ "HELP_53_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671232"},
				
				{ "HELP_13_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671324"},
				{ "HELP_13_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671315"},
				{ "HELP_13_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671316"},
				{ "HELP_13_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671317"},
				{ "HELP_13_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671318"},
				{ "HELP_13_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671319"},
				{ "HELP_13_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671320"},
				{ "HELP_13_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671321"},
				{ "HELP_13_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671322"},
				
				{ "HELP_4_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671331"},
				{ "HELP_4_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671332"},
				{ "HELP_4_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671333"},
				{ "HELP_4_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671334"},
				{ "HELP_4_URL_REKENMACHINE" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671335"},
				{ "HELP_4_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671336"},
		
				{ "HELP_INST_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#671396"},
				{ "HELP_INST_URL_MAALTEKEN" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671397"},
				{ "HELP_INST_URL_WOORDFORMULE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671398"},
				{ "HELP_INST_URL_TWEEHLVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671399"},
				{ "HELP_INST_URL_HOEKGRADEN" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671400"},
				{ "HELP_INST_URL_SIGNIFICANTIE" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#671401"},
				{ "HELP_INST_URL_GLOBAALPARAM" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#671402"},
				{ "HELP_INST_URL_DIFFOPERATOREN" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671403"},
				{ "HELP_INST_URL_BOLLETJES" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671404"},
				{ "HELP_INST_URL_VOLGENDEKNOP" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671405"},
				{ "HELP_INST_URL_VORIGEKNOP" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671406"},
				{ "HELP_INST_URL_VOORTGANG" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671407"},
				{ "HELP_INST_URL_CONDNAV" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#671408"},
				{ "HELP_INST_URL_COMBINEDCOMPONENTS" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671409"},
				{ "HELP_INST_URL_FORMTIMES" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671410"},
				{ "HELP_INST_URL_FONTOVERERVING" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=106&locale=nl#671411"},
				{ "HELP_INST_URL_FONTOVERERVINGFORM" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671412"},
				{ "HELP_INST_URL_TEMPLATEEDIT" , "https://app.dwo.nl/dwo/apps/player.html?t=18&profile=106&locale=nl#671413"},
				{ "HELP_INST_URL_STYLES" , "https://app.dwo.nl/dwo/apps/player.html?t=19&profile=106&locale=nl#671414"},
				{ "HELP_INST_URL_LAYERS" , "https://app.dwo.nl/dwo/apps/player.html?t=20&profile=106&locale=nl#671415"},
				{ "HELP_INST_URL_SCORESZICHTBAAR" , "https://app.dwo.nl/dwo/apps/player.html?t=21&profile=106&locale=nl#671416"},
				{ "HELP_INST_URL_OPNIEUW" , "https://app.dwo.nl/dwo/apps/player.html?t=22&profile=106&locale=nl#671417"},
				{ "HELP_INST_URL_ITEMOPNIEUW" , "https://app.dwo.nl/dwo/apps/player.html?t=23&profile=106&locale=nl#671418"},
				{ "HELP_INST_URL_ZELFTOETSGEENCORR" , "https://app.dwo.nl/dwo/apps/player.html?t=24&profile=106&locale=nl#671419"},
				{ "HELP_INST_URL_ZELFTOETSGESCHIEDENIS" , "https://app.dwo.nl/dwo/apps/player.html?t=25&profile=106&locale=nl#671420"},
				{ "HELP_INST_URL_AFTREKCORRZELFTOETS" , "https://app.dwo.nl/dwo/apps/player.html?t=26&profile=106&locale=nl#671421"},
				{ "HELP_INST_URL_EERDERGEENCORR" , "https://app.dwo.nl/dwo/apps/player.html?t=27&profile=106&locale=nl#671422"},
				{ "HELP_INST_URL_TIMER" , "https://app.dwo.nl/dwo/apps/player.html?t=28&profile=106&locale=nl#671423"},
				{ "HELP_INST_URL_OBJECTIVES" , "https://app.dwo.nl/dwo/apps/player.html?t=29&profile=106&locale=nl#671424"},
				
				{ "HELP_14_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671838"},
				{ "HELP_14_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671839"},
				{ "HELP_14_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671840"},
				{ "HELP_14_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671841"},
				{ "HELP_14_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671842"},
				{ "HELP_14_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671843"},
				{ "HELP_14_URL_SCORE" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671844"},
				{ "HELP_14_URL_KEUZE" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671845"},
				{ "HELP_14_URL_EXTERN" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671846"},
				{ "HELP_14_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671847"},
				
				{ "HELP_12_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671857"},
				{ "HELP_12_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671858"},
				{ "HELP_12_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671859"},
				{ "HELP_12_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671860"},
				{ "HELP_12_URL_MEERVOUDIG" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671862"},
				{ "HELP_12_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671861"},
				{ "HELP_12_URL_RANDOM" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671863"},
				{ "HELP_12_URL_CHECKFORMULE" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671864"},
				{ "HELP_12_URL_KNOPIMAGE" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671865"},
				
				{ "HELP_16_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#671880"},
				{ "HELP_16_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671881"},
				{ "HELP_16_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671882"},
				{ "HELP_16_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671883"},
				{ "HELP_16_URL_RANDOM" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671884"},
				{ "HELP_16_URL_SNAP" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671885"},
				{ "HELP_16_URL_RELOCATE" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671886"},
				{ "HELP_16_URL_VAST" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671887"},
				{ "HELP_16_URL_CHECKFORMULE" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671888"},
				{ "HELP_16_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671889"},
				{ "HELP_16_URL_VERZAMEL" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#671890"},
				{ "HELP_16_URL_KNOPIMAGE" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671891"},
				{ "HELP_16_URL_VIEW" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671892"},
				
				{ "HELP_33_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671902"},
				{ "HELP_33_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671903"},
				{ "HELP_33_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671904"},
				{ "HELP_33_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671905"},
				{ "HELP_33_URL_CHECKAFZONDERLIJK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671906"},
				{ "HELP_33_URL_CHECKSAMEN" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671907"},
				{ "HELP_33_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671908"},
				{ "HELP_33_URL_KNOPIMAGE" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671909"},
				{ "HELP_33_URL_VIEW" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671910"},
				
				{ "HELP_MULTIPLECHOICE_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671914"},
				{ "HELP_MULTIPLECHOICE_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671858"},
				{ "HELP_MULTIPLECHOICE_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671859"},
				{ "HELP_MULTIPLECHOICE_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671860"},
				{ "HELP_MULTIPLECHOICE_URL_MEERVOUDIG" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671862"},
				{ "HELP_MULTIPLECHOICE_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671861"},
				{ "HELP_MULTIPLECHOICE_URL_RANDOM" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671863"},
				{ "HELP_MULTIPLECHOICE_URL_KNOPIMAGE" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671865"},
				
				{ "HELP_DRAGDROP_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671915"},
				{ "HELP_DRAGDROP_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671881"},
				{ "HELP_DRAGDROP_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671882"},
				{ "HELP_DRAGDROP_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671883"},
				{ "HELP_DRAGDROP_URL_RANDOM" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671884"},
				{ "HELP_DRAGDROP_URL_SNAP" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671885"},
				{ "HELP_DRAGDROP_URL_RELOCATE" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671886"},
				{ "HELP_DRAGDROP_URL_KNOPIMAGE" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671891"},
				{ "HELP_DRAGDROP_URL_VIEW" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671892"},
		
				{ "HELP_9_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=0&profile=106&locale=nl#672125"},
				{ "HELP_9_URL_STYLES" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#672126"},
				{ "HELP_9_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#672127"},
				{ "HELP_9_URL_BGCOLOR" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#672128"},
				{ "HELP_9_URL_ZWEVEND" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#672129"},
				{ "HELP_9_URL_FONT" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#672130"},
				{ "HELP_9_URL_RONDING" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#672131"},
				{ "HELP_9_URL_HOEK" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#672132"},
				{ "HELP_9_URL_CENTERH" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#672133"},
				{ "HELP_9_URL_CENTERV" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#672134"},
				{ "HELP_9_URL_PASAANHB" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#672135"},
				{ "HELP_9_URL_RIJEN" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#672136"},
				{ "HELP_9_URL_KOLOMMEN" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#672137"},
				{ "HELP_9_URL_TABLEBORDERS" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#672138"},
				{ "HELP_9_URL_MARGES" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#672139"},
				{ "HELP_9_URL_INTERLINIE" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=106&locale=nl#672140"},
				{ "HELP_9_URL_VULHOOGTE" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#672141"},
				{ "HELP_9_URL_UITKLAP" , "https://app.dwo.nl/dwo/apps/player.html?t=18&profile=106&locale=nl#672142"},
				{ "HELP_9_URL_CALLOUT" , "https://app.dwo.nl/dwo/apps/player.html?t=19&profile=106&locale=nl#672143"},
				{ "HELP_9_URL_ZICHTBAAR" , "https://app.dwo.nl/dwo/apps/player.html?t=20&profile=106&locale=nl#672144"},
				{ "HELP_9_URL_INTERACTIEPID" , "https://app.dwo.nl/dwo/apps/player.html?t=21&profile=106&locale=nl#672145"},
				{ "HELP_9_URL_WAARDE" , "https://app.dwo.nl/dwo/apps/player.html?t=22&profile=106&locale=nl#672146"},
				{ "HELP_9_URL_SELECTABLE" , "https://app.dwo.nl/dwo/apps/player.html?t=23&profile=106&locale=nl#672147"},
				{ "HELP_9_URL_SLEEPBAAR" , "https://app.dwo.nl/dwo/apps/player.html?t=24&profile=106&locale=nl#672148"},
				{ "HELP_9_URL_SLEEPDOEL" , "https://app.dwo.nl/dwo/apps/player.html?t=25&profile=106&locale=nl#672149"},
				{ "HELP_9_URL_DRAAIBAAR" , "https://app.dwo.nl/dwo/apps/player.html?t=26&profile=106&locale=nl#672150"},
				{ "HELP_9_URL_LINK" , "https://app.dwo.nl/dwo/apps/player.html?t=27&profile=106&locale=nl#672151"},
				{ "HELP_9_URL_ZICHTBAARNA" , "https://app.dwo.nl/dwo/apps/player.html?t=28&profile=106&locale=nl#672152"},
				{ "HELP_9_URL_AFTREKPOPUP" , "https://app.dwo.nl/dwo/apps/player.html?t=29&profile=106&locale=nl#672153"},
				{ "HELP_9_URL_LOG" , "https://app.dwo.nl/dwo/apps/player.html?t=30&profile=106&locale=nl#672154"},
				
				{ "HELP_EDITOR_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=99&profile=106&locale=nl#673124"},
				
		};
}




