package fi.wiskopdr.text;

public class Text_in extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "Back" },
				
				{ "terugKnopToolTip" , "Kembali" },
				{ "gelijkwaardigKnopToolTip" , "Enter bentuk aljabar yang ekivalen" },
				{ "opdrachtToolTip" , "Pilih soal" },
				{ "zelfKnopToolTip" , "Enter bentuk aljabar milikmu \n dan sederhanakanlah." },
				
				
				{ "haakjesLabel0" , "  uraikan" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "   sederhanakan" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  faktorkan" },
				{ "wortelLabel0" , "  akar-akar" },
				{ "splitsLabel0" , "  pisahkan" },
				{ "hulpKnopLabel" , "Bantuan" },
				{ "gelijkwaardigLabel0" , "  sama" },
				{ "gelijkwaardigLabel1" , "    dengan:" },
				{ "ofLabel" , "atau" },
				{ "enLabel" , "dan" },
				{ "subLabel" , "Substitusi:" },
                { "meerLabel" , "lagi" },
				
                { "klaarKnopLabel" , "Cek" },
				{ "nakijkKnopLabel" , "Cek" },
				{ "nakijkLabel1" , "Terperiksa: " },
				{ "nakijkLabel2" , " kali " },
				{ "opnieuwKnopLabel" , "Lagi" },
				{ "allesOpnieuwKnopLabel" , "Lagi semua" },
				{ "opdrachtLabel" , "Soal:" },
				{ "paginaLabel" , "Halaman:" },
				{ "onderdeelLabel" , "Bagian:" },
				{ "scoreLabel" , "Skor:" },
				{ "score" , "Skor: " },
				{ "optiesButtonLabel" , "Pilihan" },
				{ "standaardActiviteitNaam" , "Level" },
				{ "standaardOpdrachtNaam" , "Soal" },
				{ "opnieuwPanelTekstMW" , "Kamu akan kehilangan skor jika mulai dari awal lagi.\n\n Apakah kamu yakin untuk mulai dari awal lagi?"},
				{ "opnieuwPanelTekst" , "Kamu akan kehilangan skor jika mulai dari awal lagi.\n\n Apakah kamu yakin untuk mulai dari awal lagi?"},
				{ "opnieuwPanelTitel" , "Lagi?"},
				{ "lockToetsCBLabel" , "Mengunci tes"},
				{ "lockToetsLabel" , "Tes terkunci"},
				{ "newPageMenuItem" ,  "insert new"},
				{ "deletePageMenuItem" ,  "delete"},
				{ "copyPageMenuItem" ,  "copy"},
				{ "cutPageMenuItem" ,  "cut"},
				{ "pastePageMenuItem" ,  "paste"},
				{ "insertCopyMenuItem" ,  "copy (insert)"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
								
				{ "choiceOefenen" , "Latihan" },
				{ "choiceOefenenEindloos" , "Latihan Tiada Henti" },
				{ "choiceOefenenStraf" , "Latihan permainan" },
				{ "choiceZelfToets" , "Tes Mandiri" },
				{ "choiceEindToets" , "Tes" },
				
				{ "opdrachtTitelLabel" , "Judul:" },
				{ "opdrachtTekstLabel" , "Teks:" },
				{ "randVarLabel" , "Variabel untuk parameter acak:" },
				{ "startExpLabel" , "Mulai bentuk aljabar:" },
				{ "startVergLabel" , "Mulai persamaan:" },
				{ "antwoordLabel" , "Model jawaban:" },
				{ "scoringLabel" , "Penskoran jawaban:" },
				{ "puntenLabel" , "Nilai:" },
				{ "checkTotaalLabel" , "Perhatian! Skor total10" },
				{ "gelijkwaardigCBLabel" , "Ekivalen" },
				{ "herleidingCBLabel" , "sederhanakan" },
				{ "exactCBLabel" , "Tepat" },
				{ "significantCBLabel" , "Significant" },
				{ "stappenCBLabel" , "Menggunakan lebih banyak langkah" },
				{ "bewerkingKnoppenCBLabel" , "Tombol operasi" },
				{ "bewerkingKnoppenExtraCBLabel" , "Tombol operasi tambahan" },
                { "abcCBLabel" , "discr" },
				{ "subKnopCBLabel" , "subst." },
				{ "subKnopExtraCBLabel" , "subst. yang diperluas" },
				
				{ "grafiekToolCBLabel" , "Alat Grafik" },
				{ "grafiekToolKnopLabel" , "Alat Grafik" },
				{ "vergelijkingCBLabel" , "Persamaan" },
				{ "eindOplossingCBLabel" , "Jawaban diperlukan" },
				{ "checkCBLabel" , "Dapat dicek (atau tidak)" },
				{ "teltMeeCBLabel" , "Termasuk dalam penilaian (atau tidak)" },
				{ "logCBLabel" , "logID" },
				{ "rmCBLabel" , "Kalkulator" },
				{ "pijlCBLabel" , "Panah" },
				{ "substitutiesButtonLabel" , "pensubstitusian" },
				{ "functiesButtonLabel" , "defined functions" },
				{ "strategieVersieLabel" , "versi strategi" },
				{ "oefenVersieLabel" , "Strategi + versi" },
				{ "bordjesVersieLabel" , "versi metode Cover-up" },
				
				{ "herleidingKeuze_0" , "Tidak ada" },
				{ "herleidingKeuze_1" , "Polinom yang terurai dan tersederhanakan" },
				{ "herleidingKeuze_2" , "Pangkat satu" },
				{ "herleidingKeuze_3" , "Tanpa pangkat negatif atau pangkat pecahan" },
				{ "herleidingKeuze_4" , "Satu pecahan" },
				{ "herleidingKeuze_5" , "Satu logaritma" },
				{ "herleidingKeuze_6" , "Ditulis sebagai logaritma paling sederhana (fe log(x)+log(3))" },
				
				{ "feedbackTekst01" , "Langkah ini mengandung bagian yang benar dan bagian yang salah. Ubah atau hapuslah bagian yang salah." },
				{ "feedbackTekst02" , "Tidak semua penyelesaian memenuhi persamaan semula. Hapuslah penyelesaian yang tidak memenuhi itu." },
				{ "feedbackTekst03" , "Pertidaksamaan terselesaikan dengan benar." },
				{ "feedbackTekst04" , "Persamaan terselesaikan dengan benar." },
				{ "feedbackTekst05" , "Berikan nilai pendekatan yang diminta." },
				{ "feedbackTekst06" , "Berikan penyelesaian pertidaksamaan." },
				{ "feedbackTekst07" , "Penyelesaian belum lengkap. Tentukan penyelesaian yang belum lengkap itu." },
				{ "feedbackTekst08" , "Jangan gunakan tanda |- ." },
				{ "feedbackTekst09" , "Sintaksis tidak benar." },
				{ "feedbackTekst10" , "Penyelesaian sudah benar, tapi belum dalam bentuk yang benar." },
				{ "feedbackTekst11" , "Ini adalah nilai pendekatan yang benar" },
				{ "feedbackTekst12" , "Jawaban benar." },
				{ "feedbackTekst13" , "Jawaban ini ekivalen, tapi belum dalam bentuk yang benar." },
				{ "feedbackTekst14" , "Sintaksis tidak benar." },
                { "feedbackTekst15" , "Jawaban benar." },
                { "feedbackTekst16" , "Ini adalah persamaan yang benar" },
                { "feedbackTekst17" , "Persamaan ini belum dalam bentuk yang benar" },
                { "feedbackTekst18" , "The answer is correct, but the number of significant figures isn't right." },
                { "feedbackTekst19" , "The answer is correct, but doesn't have the right form and the number of significant figures isn't right." },
                { "feedbackTekst20" , "The answer is correct, number of significant figures is right, but doesn't have the right form." },
                { "xVarMessage1" , "Variabel bebas selalu\n" 
									+ "Sebuah huruf.\n " 
									+ "Dalam kasus variabel-variabel kata\n" 
									+ "karakter pertama dari sebuah variabel kata\n" 
									+ "adalah selalu sebuah huruf." },
				{ "xVarMessage2" , "Variable bebas dapat hanya berupa variabel\n" 
									+ "dinyatakan dengan sebuah huruf.\n" 
									+ "Hanya ketika pilihan\"variabel-variabel kata\" \n" 
									+ "dipilih, variable bebas dapat berupa\n" 
									+ "dinyatakan dengan huruf-huruf." },
				{ "xVarMessage3" , "Huruf e digunakan untuk \n" 
									+ "fungsi eksponensial\n" 
									+ "Huruf ini tidak dapat digunakan untuk menamai\n" 
									+ "sebuah variabel bebas." },									
				{ "xVarMessage4a" , "Teks:  \"" },
				{ "xVarMessage4b" , "\" untuk fungsi matematik yang diektahui \n," 
									+ "de betreffende wiskundige functie en mag dus"
									+ "jadi tak dapat digunakan untuk nama sebuah variabel"},
									
				{ "gelijkwaardigKnopLabelGR" , "Baris berikutnya" },
				{ "terugKnopLabelGR" , "Baris sebelumnya" },
				
				{ "editorVersieKnopLabel1" , "Versi editor baru" },
				{ "editorVersieKnopLabel2" , "Versi editor lama" },
				
				{"antwoordVakLabel" , "kotak jawaban"},
				{"interactieVakLabel" , "komponen interaktif"},
				{"tekstVakLabel" , "kotak teks"},
				{"grafiekComponentLabel" , "komponen grafik"},
				
				
				
				{"interactieKeuzeLabel" , "pilih tipe dari "},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "Batalkan"},
				{"breedteLabel" , "Lebar:"},
				{"hoogteLabel" , "Tinggi:"},
				{"volleBreedteLabel" , "Lebar penuh"},
				{"popupLabel" , "Popup"},
				
				{"feedbackCBLabel" , "Umpan balik"},
				{"feedbackSizeCBLabel" , "Popup size"},
				{"uitwCBLabel" , "Popup untuk langkah-langkah"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "Milik Anda"},
				{"feedbackLabel" , "umpan balik"},
				{"ideasButtonLabel" , "pilihan"},
				{"substitutiesButtonLabel" , "substitusi"},
				{"antwoordmodelButtonLabel" , "jawaban yang mungkin"},
				{"formuleInvoerModeCBLabel" , "Mode input rumus"},
				{"aantalKeuzesLabel" , "Jumlah pilihan"},
				{"aantalSelectieObjLabel" , "Jumlah pemilihan obyek"},
				{"randomPosLabel" , "Mengacak pilihan"},
				{"meervSelectiesLabel" , "Kemungkinan pilihan banyak"},
				{"checkViaFormuleLabel" , "Cek dengan menggunakan sebuah rumus"},
				{"aantalSleepObjLabel" , "Jumlah obyek yang didrag"},
				{"aantalDoelObjLabel" , "Jumlah obyek target"},
				{"snapToTargetLabel" , "Potret kepada obyek target"},
				{"snapMargeLabel" , "Potret marjin"},
				{"checkVasteDoelenLabel" , "Cek pada target tetap untuk obyek yang didrag"},
				{"checkWaardeOpDoelLabel" , "Cek menggunakan nilai dari obyek yang didrag"},
				{"relocateCBLabel" , "Kembali loncat"},
				{"viewCBLabel" , "View"},
				{"aantalValueObjectenLabel" , "Jumlah obyek"},
				{"checkAfzonderlijkLabel" , "Cek secara terpisah"},
				{"checkOpSamenhangLabel" , "Cek secara terpadu"},
				{"boxMetRand" , "Kontak"},
				{"keuzeVakKiesLabel" , "Pilih"},
				{"verzamelDoelCBLabel" , "targetobject as collection area"},
                
				
				{"vormCBLabel" , "Bentuk"},
				{"formuleToolCBLabel" , "Rumus masukan editor"},
				{"goedLabel" , "Benar"},
				{"doorLabel" , "Lanjut"},
				{"foutLabel" , "Salah"},
				{"halfLabel" , "Setengah"},
				
				{"geenOplossingen" , "Tidak ada penyelesaian"},
				{"allesOplossing" , "Semuanya adalah penyelesaian"},
				{"antwoordModelGeen" , "Tidak ada"},
				{"abc" , "discr"},
				
				{"checkExternalCBLabel" , "check external"},
				
				// TekstVakInteractiePanel
				{"formuleAntwVakLabel" , "Formula answer box with steps"},
                {"vergelijkingAntwVakLabel" , "Kotak jawaban persamaan dengan langkah-langkah"},
                {"simpelFormuleAntwVakLabel" , "Kotak jawaban rumus sederhana"},
                {"simpelVergelijkingAntwVakLabel" , "Kotak jawaban persamaan sederhana"},
                {"tekstAntwVakLabel" , "Kotak jawaban-teks"},
                {"algebraPijlenLabel" , "Panah aljabar"},
                {"blokkenbouwenLabel" , "Bangunan dengan balok"},
                {"stroomdiagrammenLabel" , "Diagram alir"},
                {"grafiekenToolLabel" , "Alat grafik"},
                {"tekstVakLabelH" , "Text box"},
				{"geogebraIpLabel" , "Geogebra 4 (segera hadir)"},
				{"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "Timbangan buah"},
				{"checkSelectieUnitLabel" , "Check selection unit "},
				{"checkTekstAntwoordVakLabel" , "Check-text answer box"},
				{"keuzeAntwoordVakLabel" , "Kotak pilihan jawaban"},
				{"doorzienIpLabel" , "Komponen-konstruksi 3D"},
				{"checkSleepUnitLabel" , "Check drag/drop unit"},
				{"vergrotenIpLabel" , "PE Pembesaran"},
				{"vangenIpLabel" , "PE Catching"},
				{"verknippenIpLabel" , "PE Cutting"},
				{"geomAlgebra2dIpLabel" , "Geom.algebra 2d"},
				{"geomAlgebra1dIpLabel" , "Geom.algebra 1d"},
				{"normaleVerdelingIpLabel" , "Distribusi normal"},
				{"mp3PlayerIpLabel" , "Mp3-player"},
				{"binominaleVerdelingIpLabel" , "Distribusi binomial"},
				{"getallenlijnIpLabel" , "Garis bilangan (loncat)"},
				{"tekenVeelvlakIpLabel" , "Menggambar dalam ruang"},
				{"mozaikIpLabel" , "Mozaik"},
				{"veelvlakkenIpLabel" , "Polyhedra"},
				{"eerlijkVerdelenIpLabel" , "PE  Berbagi adil"},
				{"statistiekIpLabel" , "[tes] representatsi statistik"},
				{"stroomdiagrammenIpLabel" , "[test]Diagram alir baru"},
				{"tegelsIpLabel" , "Pengubinan"},
				{"checkWaardeUnitLabel" , "[tes] Cek nilai satuan"},
				{"omtrekAppletIpLabel" , "PE applet keliling "},
				{"algebraExpressiesIpLabel" , "[tes] Pohon aljabar"},
				{"oppervlakteAlgebraIpLabel" , "[tes] Aljabar luas"},
				{"blokkenProgrammaIpLabel" , "[tes] Program block"},
				{"grafieken3DIpLabel" , "[tes] Grafik 3D"},
				{"spotProblemsIpLabel" , "[test] Spot problems"},
				{"kladjeIpLabel" , "[test] Note"},
				{"kansbomenIpLabel" , "[test] Probability trees"},
				{"rekenmachineIpLabel" , "[test] Calculator"},
				{"formStructIpLabel" , "[test] FormStruct"},
				{"graphToolIpLabel" , "[test] GraphTool"},
				{"draabankIpLabel" , "[test] Turning lathe"}, 
				{"waarmakersIpLabel" , "[test] Truemakers"},
				{"statSimIpLabel" , "[test] Statistics Simulations"},
				{"stelselVakLabel", "[test] Stelsel-antwoordvak"},
	            {"javaLogoIpLabel", "JavaLogo"},
				
				//InstellingenPanel
				{"OPT_vermenigvTeken" , "Tanda perkalian: X"},
				{"OPT_woordformules" , "Variabel-variabel kata "},
				{"OPT_tweeHoofdletterVars" , "Variabel seperti AB, BC dll."},
				{"OPT_tempoToets" , "Waktu terbatas"},
				{"OPT_opnieuwKnop" , "'Semua lagi'-tombol"},
				{"OPT_itemOpnieuwKnop" , "'Item lagi'-tombol"},
				{"OPT_checkPerOpdracht" , "Cek tiap halaman"},
				{"OPT_hoekInGraden" , "Satuan sudut: Derajat"},
				{"OPT_opdrachtBolletjes" , "Pemilih Item"},
				{"OPT_volgendeKnop" , "Tombol-selanjutnya"},	
				{"OPT_VorigeKnop" , "Tombol-sebelumnya"},
				{"OPT_paginaIpvOpdracht" , "Label: 'Halaman' daripada 'Soal'"},
				{"OPT_fontFormaat" , "Ukuran"},
				{"OPT_fontNaam" , "Font dasar"},
				{"OPT_tijdsLimiet" , "Batas waktu (detik)"},
				{"OPT_formTimes" , "Rumus dalam Font Times Roman"},
				{"OPT_navigatieFormaat" , "Ukuran bar navigasi"},
				{"OPT_margesLabel" , "Marges:"},
				{"OPT_margeLinksLabel" , "Kiri"},
				{"OPT_margeRechtsLabel" , "Kanan"},
				{"OPT_margeBovenLabel" , "Atas"},
				{"OPT_margeOnderLabel" , "Bawah"},
				{"OPT_fToets" , "Kunci-F untuk Rumus"},
				{"OPT_globalParam" , "Parameter global"},
				{"OPT_conditionalNav" , "Navigasi kondisional"},
				{"OPT_conditionalPercLabel" , "Perc."},
				{"OPT_deelOpdr" , "Bilangan-bilangan Item a,b,c dll"},
				{"OPT_zelftoetsGeenCorr" , "No correction self test"},
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_significantie" , "check option significant numbers"},
				{"OPT_objectives" , "Objectives"},
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_fontOvererving" , "Font-inheritance text boxes"},
				{"OPT_fontOverervingForm" , "Font-inheritance formula boxes"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				
				{"OBJ_leerdoel", "Objective"},
				{"OBJ_categorie", "Category"},
				{"OBJ_categorieBox", "Objectives in multiple categories"},
				{"OBJ_kolomMeerButton", "Add column"},
				{"OBJ_kolomMinderButton", "Remove column"},
				{"MCC_misconception", "Misconception"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "Variabel-variabel fungsi"},
				{"GEP_assenLabel" , "Perlihatkan sumbu"},
				{"GEP_grafiekOptiesLabel" , "Pilihan alat grafik"},
				
				{"GEP_varXLabel" , "Variabel sumbu-x"},
				{"GEP_varYLabel" , "Variabel sumbu-y"},
				
				{"GEP_assenOptie" , "Sumbu"},
				{"GEP_roosterOptie" , "Grid"},
				{"GEP_roosterGrofOptie" , "wide"},
				{"GEP_schaalverdelingOptie" , "Bilangan-bilangan sumbu"},
				{"GEP_piOptie" , "Grid untuk Pi"},				
				
				{"GEP_zoomOptie" , "Zoom-pilihan"},
				{"GEP_traceOptie" , "Trace-pilihan"},
				{"GEP_dragOptie" , "Drag-pilihan"},
				{"GEP_tekenOptie" , "Alat Grafik-Gambar"},
				{"GEP_functieEditOptie" , "Editor fungsi"},
				{"GEP_grafiekKleurenOptie" , "Different colors"},
				{"GEP_formeleFunctieNotatieOptie" , "Notasi formal fungsi f(x), g(x) dll."},
				
				//linkEditPanel
				{"LEP_linkTekst" , "Teks"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "Lebar Window"},
				{"LEP_vensterHoogte" , "Tinggi Window"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "Tambahkan"},
				{"IEP_verwijderen" , "Hapus"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "Batalkan"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "Batas"},
				{"TVEP_achtergrondKleurAanwezig" , "Warna Background"},
				{"TVEP_zwevend" , "Mengapung di atas teks"},
				{"TVEP_anderFont" , "Font lainnya"},
				{"TVEP_rondingHoeken" , "Rounding corners"},
				{"TVEP_rotatieHoek" , "Sudut perputaran"},
				{"TVEP_centreerHor" , "Pemusatan secara horizontal"},
				{"TVEP_centreerVert" , "Pemusatan secara vertikal"},
				{"TVEP_pasAanH" , "Sesuaikan tinggi"},
				{"TVEP_pasAanB" , "Sesuaikan lebar"},
				{"TVEP_aantalRijen" , "Jumlah baris"},
				{"TVEP_aantalKolommen" , "Jumlah kolom"},
				{"TVEP_tabelRanden" , "Batas tabel"},
				{"TVEP_celMarge" , "Marjin kiri"},
				{"TVEP_bovenMarge" , "Marjin atas"},
				{"TVEP_fontType" , "Font"},
				{"TVEP_achtergrondKleur" , "Warna"},
				{"TVEP_interlinie" , "Spasi baris"},
				{"TVEP_cellSpaceColumn" , "Spasi"},
				{"TVEP_cellSpaceRow" , "SPasi"},
				{"TVEP_layoutLabel" , "Layout kotak teks"},
				{"TVEP_gebruikersInteractieLabel" , "Interaksi pengguna"},
				{"TVEP_selectieObject" , "Pemilihan obyek"},
                {"TVEP_selectieKleur" , "Warna"},
                {"TVEP_selectieKleurKnopLabel" , "Selection color"},
                {"TVEP_sleepObject" , "Drag obyek"},
                {"TVEP_sleepDoel" , "Drag target"},
                {"TVEP_sleepHandle" , "pegangan"},
                {"TVEP_selectieSleepWaarde" , "Nilai   ("},
                {"TVEP_fgKleurKnopLabel" , "Warna"},
                {"TVEP_zichtbaarNaNakijken" , "Visible after check test"},
                {"TVEP_balansVergCom" , "Balance-Equation box communication"},
                {"TVEP_aftrekPopup" , "Decrease score using popup"},
                {"TVEP_callOut" , "Call out box"},
                {"TVEP_vulHoogte" , "Fill height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "Steps"},
                {"TVEP_random" , "random"},
                {"TVEP_linkObject" , "Link object"},
                {"TVEP_editLink" , "Edit link"},
                {"TVEP_defaultBijNull" , "default  )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "Pilihan Penyimpanan"},
				{"GEP_alsTool" , "Sebagai Alat"},
				{"GEP_rand" , "Batas"},
				{"GEP_resetIcon" , "Pilihan-Atur ulang"},
				{"GEP_checkMetCheckDWO" , "Menggunakan cek DWO"},
				{"GEP_checkMetObjecten" , "Menggunakan obyek yang dibuat"},
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "Nilai Minimum"},
				{"GSEP_maxValue" , "Nilai maksimum"},
				{"GSEP_eenheden" , "Units tampak"},
				{"GSEP_getallen" , "Bilangan"},
				{"GSEP_10tallen" , "Tanda untuk puluhan"},
				{"GSEP_5tallen" , "Tanda untuk limaan"},
				{"GSEP_nul" , "Nol"},
				{"GSEP_pijl" , "Panah tampak"},
				{"GSEP_pijlTerug" , "Panah kembali"},
				{"GSEP_horizontaal" , "Horizontal"},
				{"GSEP_eenheid" , "Unit"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "Menu Bar"},
				{"TEEP_rekenToolOptie" , "Kalkulator"},
				{"TEEP_grafToolOptie" , "Alat Grafik"},
				
				//Ideas
				
				{"ideasTip",		"Petunjuk"},
				{"ideasHelp",		"Bantuan"},
				{"ideasStap",		"Langkah"},
				{"ideasLosop",		"Selesaikan"},
				{"ideasWordtDan",		"Menjadi"},
				
				{"algebra.equations.coverup.denominator"		,"cover-up bagian penyebut"	},
				{"algebra.equations.coverup.minus-left"			,"Pindahkan bentuk konstan ke sebelah kanan"	},
				{"algebra.equations.coverup.minus-right"		,"Gunakan metode cover-up"	},
				{"algebra.equations.coverup.negate"				,"bagi dengan -1"	},
				{"algebra.equations.coverup.numerator"			,"cover-up bagian pembilang"	},
				{"algebra.equations.coverup.plus"				,"Pindahkan bentuk konstan ke sebelah kanan"	},
				{"algebra.equations.coverup.power"				,"tarik nilai akar kuadrat"	},
				{"algebra.equations.coverup.sqrt"				,"kuadratkan kedua ruas"	},
				{"algebra.equations.coverup.times"				,"isolasi variabel dengan membagi kedua ruas"	},
				{"algebra.equations.coverup.times-positive"		,"isolasi variabel dengan membagi kedua ruas"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"Pindahkan suku-suku konstan ke ruas kanan dengan menambahkan bilangan yang sama pada kedua ruas"	},
				{"algebra.equations.coverup.onevar.plus"		,"Pindahkan suku-suku konstan ke ruas kanan dengan cara mengurangkan dengan bilangan yang sama pada kedua ruas"	},
				
				{"algebra.equations.linear.distr-times"		,"buka kurung"	},
				{"algebra.equations.linear.flip"			,"Tukar persamaan"	},
				{"algebra.equations.linear.merge"			,"sederhanakan dengan menggunakan bentuk aljabar atau perhitungan"	},
				{"algebra.equations.linear.remove-div"		,"Hilangkan pecahan dengan cara mengalikan dengan sebuah bilangan"	},
				{"algebra.equations.linear.var-left"		,"Pindahkan bentuk aljabar mengandung variabel ke ruas kiri"	},
				
				{"algebra.equations.buggy.cancel-minus"				,"Anda tak dapat menghilangkan (kenselasi) suku-suku karena tandanya tidak sama"	},
				{"algebra.equations.buggy.distr-times-denom"		,"Kesalahan dalam membuka kurung: salah satu suku adalah pecahan, dan faktornya dikali dengan pembilang pecahan."	},
				{"algebra.equations.buggy.distr-times-plus"			,"Ketika membuka kurung salah satu suku belum dikalikan"	},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"Ketika membuka kurung salah satu suku terlupakan"	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"Ingat tanda ketika membuka kurung"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"Ketika membuka kurung, kalikan suku-suku yang hanya ada di antara kedua kurung"	},
				{"algebra.equations.buggy.divide-negate"			,"perhatikan tanda ketika melakukan pembagian"	},
				{"algebra.equations.buggy.divide-numdenom"			,"pecahan terbalik. Pikirkan tentang bilangan yang harus Anda gunakan untuk pembagian"	},
				{"algebra.equations.buggy.flip-negate-one-side"		,"Anda harus mengubah tanda pada kedua ruas"	},
				{"algebra.equations.buggy.multiply-one-side"		,"Anda harus mengalikan kedua ruas"	},
				{"algebra.equations.buggy.minus-minus"				,"ketika membuka kurung: perkalian dua bilangan negatif menghasilkan sebuah bilangan positif"	},
				{"algebra.equations.buggy.multiply-forget-one"		,"salah satu suku terlupakan ketika memgalikan kedua ruas"	},
				{"algebra.equations.buggy.negate-all"				,"salah satu suku telah terlupakan ketika mengubah tanda"	},
				{"algebra.equations.buggy.negate-one-side"			,"salah satu ruas telah terlupakan ketika mengubah tanda"	},
				{"algebra.equations.buggy.plus"						,"pikirkan tentang tanda ketika Anda memindahkan sebuah suku dari satu ruas ke ruas lainnya"	},
				{"algebra.equations.buggy.priority-times"			,"ingat aturan urutan perhitungan dan tanda kurung"	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"dalam rumus kuadrat  D=b^2-4ac dan tidak D=b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"bukan negasi dari b: "	},
				{"algebra.equations.buggy.abc.one-solution"				,"terdapat penyelesaian kedua"	},
				{"algebra.equations.buggy.abc.two-a"					,"bagi dengan 2a dan bukan a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"Anda telah melupakan akar (negatif) lainnya"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"sebelum menarik akar Anda perlu melakukan tindakan lain"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"sebelum menarik akar Anda perlu melakukan tindakan lain"	},
				{"algebra.equations.buggy.coverup.square-minus"			,"Anda tidak dapat menarik akar dari sebuah bilangan negatif"	},
				{"algebra.equations.buggy.coverup.times-mul"			,"daripada membagi ruas kanan Anda melakukan perkalian"	},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"Ketika Anda membagi, Anda perlu membagi semua suku"	},
				{"algebra.equations.buggy.distr-square"					,"Ketika menarik akar dari dua suku Anda telah melupakan perkalian silang keduanya"	},
				{"algebra.equations.buggy.distr-square-forget"			,"Ketika menarik akar dua suku Anda telah melupakan salah satu suku"	},
				{"algebra.equations.buggy.square-multiplication"		,"Kesalahan pengkuadratan dua suku"	},
				{"algebra.equations.buggy.division-by-var-both"		,"ketika membagi dengan sebuah variabel Anda akan kehilangan penyelesaian var=0"	},
				{"algebra.equations.buggy.division-by-var-zero"		,"Ketika membagi dengan sebuah variabel Anda akan kehilangan penyelesaian var=0"	},
				
				{"algebra.equations.linear.balance.collect"			,"kombinasikan"	},
				{"algebra.equations.linear.balance.calculate"		,"hitung"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"tulis pembagian sebagai perkalian dengan sebuah pecahan"	},
				{"algebra.equations.linear.balance.smart-div"		,"bagi dengan sebuah faktor yang sama"	},
				{"algebra.equations.linear.balance.con-right-minus"	,"kurangkan {?} dari kedua ruas"	},
				{"algebra.equations.linear.balance.con-left-minus"	,"kurangkan {?} dari kedua ruas"	},
				{"algebra.equations.linear.balance.var-right-minus"	,"kurangkan {?} dari kedua ruas"	},
				{"algebra.equations.linear.balance.var-left-minus"	,"kurangkan {?} dari kedua ruas"	},
				{"algebra.equations.linear.balance.con-right-plus"	,"tambahkan {?} pada kedua ruas"	},
				{"algebra.equations.linear.balance.con-left-plus"	,"tambahkan {?} pada kedua ruas"	},
				{"algebra.equations.linear.balance.var-right-plus"	,"tambahkan {?} pada kedua ruas"	},
				{"algebra.equations.linear.balance.var-left-plus"	,"tambahkan {?} pada kedua ruas"	},
				{"algebra.equations.linear.balance.distribute"		,"buka kurung"	},
				{"algebra.equations.linear.balance.remove-div"		,"kalikan kedua ruad dengan {?}"	},
				{"algebra.equations.linear.balance.scale-to-one"	,"bagi kedua ruas dengan {?}"	},
				{"algebra.equations.linear.balance.negate"    ,"ubah tanda pada kedua ruas"  },
				{"algebra.equations.linear.balance.intro-false"    ,"tidak mungkin"  },
				{"algebra.equations.linear.balance.intro-true"    ,"selalu benar"  },
                
               
				{"algebra.equations.quadratic.abc"				,"gunakan rumus kuadrat"	},
				{"algebra.equations.quadratic.approx"			,"aproksimasi"	},
				{"algebra.equations.quadratic.cancel"			,"hilangkan bentuk aljabar dari kedua ruas dari =-simbol"	},
				{"algebra.equations.quadratic.common-factor"	,"faktorkan dengan menggunakan faktor yang sama"	},
				{"algebra.equations.quadratic.distr-div"		,"bagi"	},
				{"algebra.equations.quadratic.distr-square"		,"hitung kuadrat dari"	},
				{"algebra.equations.quadratic.left-square"		,"tulis ruas kiri sebagai sebuah kuadrat"	},
				{"algebra.equations.quadratic.move-left"		,"pindahkan semua ke ruas kiri"	},
				{"algebra.equations.quadratic.nice-factors"		,"faktorkan tiga bentuk aljabar"	},
				{"algebra.equations.quadratic.no-lin"			,"tulis sebagai bentuk kuadrat = number"	},
				{"algebra.equations.quadratic.prepare-split"	,"lengkapkan ke bentuk kuadrat"	},
				{"algebra.equations.quadratic.product-zero"		,"0 hasil kali =0, samakan faktor-faktor sama dengan 0"	},
				{"algebra.equations.quadratic.same-con-factor"	,"bagi kedua ruas dengan faktor yang sama"	},
				{"algebra.equations.quadratic.same-factor"		,"A*B=A*C mengakibatkan A=0 atau B=C"	},
				{"algebra.equations.quadratic.simpler-poly"		,"sederhanakan dengan membagi dengan faktor yang sama"	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"sederhanakan akar kuadrat"	},
				{"algebra.equations.quadratic.square-both"		,"kuadratkan kedua ruas"	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"terapkan substitusi mundur"	},
				{"algebra.equations.polynomial.expose-factor"		,"isolasi faktor yang sama"	},
				{"algebra.equations.polynomial.power-factors"		,"faktor yang sama x"	},
				{"algebra.equations.polynomial.subst"				,"gunakan substitusi"	},
				{"algebra.equations.polynomial.def-power-nat"   	,"tulis bilangan berpangkat sebagai perkalian bilangan berulang"},
				
				
				{"algebra.equations.rational.check-solution"	,"cek penyelesaian"	},
				{"algebra.equations.rational.cross-multiply"	,"perkalian silang"	},
				{"algebra.equations.rational.division-one"		,"jika pecahan=1 kita mempunyai pembilang = penyebut"	},
				{"algebra.equations.rational.division-zero"		,"jika pecahan=0 kita memiliki pembilang=0 (jika penyebut tidak sama dengan nol)"	},
				{"algebra.equations.rational.multiply-one-div"	,"kalikan kedua ruas dengan penyebut pecahan"	},
				{"algebra.equations.rational.same-dividend"		,"A/B=A/C berakibat A=0 or B=C"	},
				{"algebra.equations.rational.same-divisor"		,"penyebut sama, samakan pembilang"	},
				
				{"algebra.inequalities.flip-sign"		,"ubah tanda"	},
				{"algebra.inequalities.give-solution"	,"selesaikan pertidaksamaan"	},
				{"algebra.inequalities.to-equation"		,"ubah pertama-tama ke dalam persamaan"	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"kalikan bilangan berpangkat dengan menambahkan eksponennya"	},
				{"algebra.manipulation.exponents.factor-as-power"		,"tulis (bagian) sebagai sebuah bilangan berpangkat"	},
				{"algebra.manipulation.exponents.mul-exponents"			,"pangkat dari bilangan pangkat: kalikan eksponennya"	},
				{"algebra.manipulation.exponents.reciprocal"			,"tulis 1/(bentuk aljabar) sebagai (bentuk aljabar)^-1"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"tulis sebagai sebuah bilangan berpangkat dengan menambahkan eksponennya"	},
				{"algebra.manipulation.exponents.sub-exponents"			,"pembagian bilangan berpangkat dengan cara mengurangkan eksponen-eksponennya"	},
				{"algebra.manipulation.exponents.write-as-power"		,"tulis sebagai bilangan berpangkat"	},
				{"algebra.manipulation.exponents.distr-power"			,"Gunakan bilangan pangkat dari hasil perkalian sebagai hasil kali pangkat"	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"tulis (bentuk aljabar pangkat)^-1 sebagai sebuah pecahan: 1/(bentuk aljabar)"	},
				{"algebra.manipulation.exponents.write-as-root"			,"tulis sebagai akar kuadrat"	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"tulis 1/bilangan berpangkat sebagai bentuk bilangan berpangkat lain dengan tanda pangkat diubah"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"pindahkan negasi dari pangkat (ketika eksponen ganjil)"	},
				{"algebra.manipulation.exponents.root"					,"berikan akar kuadrat"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"pangkat = 1 berarti eksponen = 0"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"bilangan dasar sama"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"aproksimasi pangkat ini atau akar kuadrat"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"pangkat sama"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"tulis dengan menggunakan faktor pangkat terbesar"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"akar kuadrat ke-n"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		,"gunakan definisi glog(x)=a berakibat x=g^a"	},
				
				{"calculus.differentiation.deriv-of-poly"		,"differensiasi fungsi pangkat"	},
				{"calculus.differentiation.min"		,"gunakan aturan untuk pengurangan"	},
				{"calculus.differentiation.negate"		,"pindahkan negasi sebelum differensiasi"	},
				{"calculus.differentiation.plus"		,"terapkan aturan jumlah"	},
				{"calculus.differentiation.product"		,"terapkan aturan hasil kali"	},
				{"calculus.differentiation.quotient"		,"terapkan aturan hasil bagi"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"Anda kurangkan {?} dari ruas kiri tapi tambahkan {?} ke ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"Anda tambahkan {?} pada ruas kiri tapi kurangkan {?} dari ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"Anda kurangkan {?} dari ruas kanan tapi tambahkan {?}ke ruas kiri"	},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"Anda tambahkan{?} pada ruas kanan tapi kurangkan {?} dari ruas kiri"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"Anda kurangkan{?} dari ruas kiri tapi jangan lakukan pada ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"Anda tambahkan {?} ke ruas kiri tapi jangan lakukan pada ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"Anda kurangkan {?} dari ruas kiri tapi tambahkan {?} pada ruas kanan"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"Anda tambahkan {?} pada ruas kiri tapi kurangkan {?} dari ruas kanan"} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"Anda kurangkan {?} dari ruas kanan tapi tambahkan {?} pada ruas kiri"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"Anda tambahkan {?} pada ruas kanan tapi kurangkan {?} dari ruas kiri"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"Anda kurangkan {?} dari ruas kanan tapi jangan lakukan itu pada ruas kiri"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"Anda tambahkan {?} pada ruas kanan tapi jangan lakukan itu pada ruas kiri"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"Anda kurangkan {?} dari ruas kiri tapi jangan lakukan itu pada ruas kanan"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"Anda tambahkan {?} pada ruas kiri tapi jangan lakukan itu pada ruas kanan"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"Anda kurangkan {?} dari ruas kanan tapi jangan lakukan itu pada ruas kiri"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"Anda tambagkan {?} pada ruas kanan tapi jangan lakukan itu pada ruas kiri"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"tak hanya Anda telah menukar ruas kiri dan ruas kanan, tapi juga Anda telah mengubah tanda di salah satu sisi"	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"Anda kurangkan pada ruas kanan, apakah Anda lakukan hal yang sama pada ruas kiri?"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"Anda kalikan dengan sebuah bilangan, tapi belum dilakukan pada ruas kiri"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"Anda menegasikan, tapi belum Anda lakukan pada ruas kiri"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"Anda membagi dengan sebuah bilangan, tapi belum dilakukan untuk ruas kiri"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"Anda membagi ruas kiri dengan {?}, tapi ruas kanan dengan inverse"	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"Anda mengalikan ruas kiri dan ruas kanan dengan bilangan yang berbeda"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"Anda kalikan ruas kiri dengan {?}, tapi belum Anda lakukan untuk ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"Anda membagi ruas kiri dengan {?}, tapi belum Anda lakukan untuk ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"Anda menegasikan ruas kiri, tapi belum Anda lakukan untuk ruas kanan"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"Anda membagi salah satu ruas dengan {?}, tapi tidak dilakukan untuk ruas lain "	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"Kesalahan perkalian(1)"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"Kesalahan perkalian (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"Kesalahan perkalian, Anda kehilangan simbol tanda negatif"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"Kesalahan perkalian, bilangan negatif dikali negatif adalah positif"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"Kesalahan pembagian, Anda membagi dengan bilangan negatif"	},
				{"algebra.equations.linear.balance.buggy.par1"		,"Kesalahan dalam membuka tanda kurung, kalikan kedua suku di antara tanda kurung (1)"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"ingat aturan urutan operasi: pertama perkalian, kemudian penjumlahan"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"tanda negatif tidak dipindahkan dengan benar di antara tanda kurung"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"Kesalahan dalam membuka tanda kurung, kalikan kedua suku di antara tanda kurung (2)"	},
				{"algebra.equations.linear.balance.buggy.par4"		,"Kesalahan dalam membuka tanda kurung, kesalahan perkalian"	},
				{"algebra.equations.linear.balance.buggy.par5"		,"Kesalahan dalam membuka tanda kurung, kalikan kedua suku di antara tanda kurung (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		,"Kesalahan dalam membuka tanda kurung, kalikan kedua suku di antara tanda kurung (4)"	},
				{"algebra.equations.linear.balance.buggy.par7"		,"Kesalahan dalam membuka tanda kurung, kalikan kedua suku di antara tanda kurung dengan -1"	},
				{"algebra.equations.linear.balance.buggy.par8"		,"Kesalahan dalam membuka tanda kurung, perhatikan dengan cermat di manakah tanda kurung itu"	},
				{"algebra.equations.linear.balance.buggy.par9"		,"Kesalahan dalam membuka tanda kurung, kesalahan perkalian (2)"	},
				
				// crossswidget commands
				{"CBA_input", "input"},
				{"CBA_int.index", "choice" },
				{"CBA_balansvergelijking", "balance equation"},
				{"CBA_zetOplossing", "set solution" },
				{"CBA_maakStap", "make step" },
				{"CBA_vergelijking", "equation" },
				{"CBA_double", "nummerical value"},
				{"CBA_expression", "expression"},
				{"CBA_equation", "equation"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Actie: 2x incorrect answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},
				
		};
}




