package fi.wiskopdr.text;

public class Text_es extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "Back" },
				
				{ "terugKnopToolTip" , "Volver" },
				{ "gelijkwaardigKnopToolTip" , "Introduce una expresión equivalente" },
				{ "opdrachtToolTip" , "Selecciona un problema" },
				{ "zelfKnopToolTip" , "Introduce tu propia expresión \n y simplifícala." },
				
				
				{ "haakjesLabel0" , "aumentar" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "   simplificar" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  factorizar" },
				{ "wortelLabel0" , "  raíces" },
				{ "splitsLabel0" , " dividir" },
				{ "hulpKnopLabel" , "Ayuda" },
				{ "gelijkwaardigLabel0" , "  igual" },
				{ "gelijkwaardigLabel1" , "    con:" },
				{ "ofLabel" , "o" },
				{ "enLabel" , "y" },
				{ "subLabel" , "Sustituir:" },
                { "meerLabel" , "más" },
				
                { "klaarKnopLabel" , "Comprobar" },
				{ "nakijkKnopLabel" , "Comprobar" },
				{ "checkExternal" , "external check" },
				{ "eindeKnopLabel", "Fin" },
				{ "nakijkLabel1" , "Comprobar " },
				{ "nakijkLabel2" , " veces " },
				{ "opnieuwKnopLabel" , "Otra vez" },
				{ "allesOpnieuwKnopLabel" , "Todo otra vez" },
				{ "zelftoetsGeschiedenisKnopLabel", "score history"},
				{ "opdrachtLabel" , "Problema:" },
				{ "paginaLabel" , "Página:" },
				{ "onderdeelLabel" , "Parte:" },
				{ "scoreLabel" , "Puntuación:" },
				{ "puntuación" , "Puntuación: " },
				{ "totaal", "Total: " },
				{ "voortgang" , "Progreso: "},
				{ "deelscores", "Puntuación parcial"},
				{ "optiesButtonLabel" , "Opciones" },
				{ "standaardActiviteitNaam" , "Nivel" },
				{ "standaardOpdrachtNaam" , "Problema" },
				{ "opnieuwPanelTekstMW" , "Perderás tu puntuación si comienzas de nuevo. \n\n¿Seguro que quieres volver a empezar?"},
				{ "opnieuwPanelTekst" , "Perderás tu puntuación si comienzas de nuevo. \n\n¿Seguro que quieres volver a empezar?"},
				{ "opnieuwPanelTitel" , "¿Otra vez?"},
				{ "lockToetsCBLabel" , "Prueba de bloqueo"},
				{ "lockToetsLabel" , "Prueba bloqueada"},
				{ "newPageMenuItem" ,  "insert new"},
				{ "deletePageMenuItem" ,  "delete"},
				{ "copyPageMenuItem" ,  "copy"},
				{ "cutPageMenuItem" ,  "cut"},
				{ "pastePageMenuItem" ,  "paste"},
				{ "insertCopyMenuItem" ,  "copy (insert)"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
								
				{ "choiceOefenen" , "Práctica" },
				{ "choiceOefenenEindloos" , "Práctica infinita" },
				{ "choiceOefenenStraf" , "Juego de práctica" },
				{ "choiceZelfToets" , "Auto-prueba" },
				{ "choiceEindToets" , "Prueba" },
				
				{ "opdrachtTitelLabel" , "Título:" },
				{ "opdrachtTekstLabel" , "Texto:" },
				{ "randVarLabel" , "Variables para los parámetros aleatorios:" },
				{ "startExpLabel" , "Expresión de inicio:" },
				{ "startVergLabel" , "Ecuación de inicio:" },
				{ "antwoordLabel" , "Modelo de respuesta:" },
				{ "scoringLabel" , "Puntuación de la respuesta:" },
				{ "puntenLabel" , "Puntos:" },
				{ "checkTotaalLabel" , "¡Atención!. La puntuación total es 10" },
				{ "gelijkwaardigCBLabel" , "Equivalente" },
				{ "herleidingCBLabel" , "Simplificar" },
				{ "exactCBLabel" , "Exacto" },
				{ "significantCBLabel" , "Significativo" },
				{ "stappenCBLabel" , "Incluir más pasos" },
				{ "bewerkingKnoppenCBLabel" , "Botones de operación" },
				{ "bewerkingKnoppenExtraCBLabel" , "Botones extra de operación" },
                { "abcCBLabel" , "discr" },
				{ "subKnopCBLabel" , "subst." },
				{ "subKnopExtraCBLabel" , "subst. extended" },
				
				{ "grafiekToolCBLabel" , "Herramienta para dibujar" },
				{ "grafiekToolKnopLabel" , "Herramienta para dibujar" },
				{ "vergelijkingCBLabel" , "Ecuación" },
				{ "eindOplossingCBLabel" , "Respuesta necesaria" },
				{ "checkCBLabel" , "Comprobable (o no)" },
				{ "teltMeeCBLabel" , "Incluir en la clasificación (o no)" },
				{ "logCBLabel" , "logID" }, 
				{ "rmCBLabel" , "Calculadora" },
				{ "pijlCBLabel" , "Flecha" },
				{ "substitutiesButtonLabel" , "sustituciones" },
				{ "functiesButtonLabel" , "defined functions" },
				{ "strategieVersieLabel" , "Versión estratégica" },
				{ "oefenVersieLabel" , "Estrategia + versión" },
				{ "bordjesVersieLabel" , "Método de encubrir la versión" },
				
				{ "herleidingKeuze_0" , "Ninguno" },
				{ "herleidingKeuze_1" , "Polinomio ampliado y simplificado" },
				{ "herleidingKeuze_2" , "Potencias" },
				{ "herleidingKeuze_3" , "Sin potencias negativas ni de fracciones " },
				{ "herleidingKeuze_4" , "Fracción" },
				{ "herleidingKeuze_5" , "Logaritmo" },
				{ "herleidingKeuze_6" , "Escrito como un logaritmo simple (pe log(x)+log(3))" },				
				{ "feedbackTekst01" , "Este paso incluye partes correctas e incorrectas. Cambia o elimina las partes que no son correctas." },
				{ "feedbackTekst02" , "No todas las soluciones cumplen la ecuación original. Elimina la solución o soluciones que no correspondan. " },
				{ "feedbackTekst03" , "La desigualdad se ha resuelto correctamente." },
				{ "feedbackTekst04" , "La ecuación se ha resuelto correctamente." },
				{ "feedbackTekst05" , "Haz una aproximación." },
				{ "feedbackTekst06" , "Da soluciones a la desigualdad." },
				{ "feedbackTekst07" , "Falta una o varias soluciones. Agrega la(s) que falta(n)." },
				{ "feedbackTekst08" , "Don't use |- marks." },				{ "feedbackTekst09" , "La sintaxis no es correcta" },
				{ "feedbackTekst10" , "La solución es correcta, pero todavía no tiene la forma adecuada." },
				{ "feedbackTekst11" , "La aproximación es correcta" },
				{ "feedbackTekst12" , "La respuesta es correcta." },
				{ "feedbackTekst13" , "La solución es equivalente, pero todavía no tiene la forma adecuada." },
				{ "feedbackTekst14" , "La sintaxis no es correcta" },
                { "feedbackTekst15" , "Respuesta correcta." },
                { "feedbackTekst16" , "Esta ecuación está correcta" },
                { "feedbackTekst17" , "Esta ecuación todavía no está en su forma correcta" },
                { "feedbackTekst18" , "La respuesta es correcta, pero el número de figuras significativas no es correcto." },
                { "feedbackTekst19" , "La respuesta es correcta, pero no tiene la forma correcta y el número de figuras significativas tampoco es el correcto." },
                { "feedbackTekst20" , "La respuesta es correcta, el número de figuras significativas es correcto pero la forma no es la correcta." },
                { "xVarMessage1" , "La variable independiente siempre es \n" 
									+ "una letra.\n " 
									+ "en el caso de una palabra variable \n" 
									+ "la primera letra de una palabra variable\n" 
									+ "siempre es una letra." },
				{ "xVarMessage2" , "La variable independiente sólo puede ser \n" 
									+ "representada por una letra.\n" 
									+ "Sólo cuando la opción \"palabra variable\" \n" 
									+ "es seleccionada, la independiente puede ser\n" 
									+ "representada por más letras." },
				{ "xVarMessage3" , "La letra e se usa para  \n" 
									+ "la función exponencial.\n" 
									+ "Esta letra no puede ser usada para el nombre \n" 
									+ "de una variable independiente." },									
				{ "xVarMessage4a" , "The tekst:  \"" }, 
				{ "xVarMessage4b" , "\" para la función matemática desconocida \n," 
									+ "de betreffende wiskundige functie en mag dus"
									+ "entonces no puede ser utilizada en el nombre de una varibale"},
									
				{ "gelijkwaardigKnopLabelGR" , "Siguiente línea" },
				{ "terugKnopLabelGR" , "Línea anterior" },
				
				{ "editorVersieKnopLabel1" , "Versión del nuevo editor" },
				{ "editorVersieKnopLabel2" , "Versión del antiguo editor" },
				
				{"antwoordVakLabel" , "caja de respuestas"},
				{"interactieVakLabel" , "componente interactivo"},
				{"tekstVakLabel" , "caja de respuestas"},
				{"grafiekComponentLabel" , "componente gráfico"},
				
				
				
				{"interactieKeuzeLabel" , "Escoger un tipo de "},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "Cancelar"},
				{"breedteLabel" , "Ancho:"},
				{"hoogteLabel" , "Alto:"},
				{"volleBreedteLabel" , "Ancho total"},
				{"popupLabel" , "Ventana emergente"},
				
				{"feedbackCBLabel" , "Retroalimentación"},
				{"uitwCBLabel" , "Popup for steps"}, 
				{"casAntwCBLabel" , "CAS"}, 
				{"eigenOpdrCBLabel" , "El tuyo"},
				{"feedbackLabel" , "retroalimentación"},
				{"ideasButtonLabel" , "opciones"},
				{"substitutiesButtonLabel" , "sustituciones"},
				{"antwoordmodelButtonLabel" , "posibles respuestas "},
				{"formuleInvoerModeCBLabel" , "Modo de entrada de fórmulas"},
				{"aantalKeuzesLabel" , "Número de opciones"},
				{"aantalSelectieObjLabel" , "Número de objetos seleccionados"},
				{"randomPosLabel" , "Selección aleatoria de posiciones"},
				{"meervSelectiesLabel" , "Múltiples opciones"},
				{"checkViaFormuleLabel" , "Verificación basada en una fórmula"},
				{"aantalSleepObjLabel" , "Número de objetos arrastrados"},
				{"aantalDoelObjLabel" , "Número de objetos objetivo"},
				{"snapToTargetLabel" , "Ajustar al objeto objetivo"},
				{"snapMargeLabel" , "Ajustar margen"},
				{"checkVasteDoelenLabel" , "Comprobar los objetos objetivo para arrastrarlos"},
				{"checkWaardeOpDoelLabel" , "Comprobar los valores de los objetos objetivo"},
				{"relocateCBLabel" , "Volver"},
				{"viewCBLabel" , "Vista"},
				{"aantalValueObjectenLabel" , "Número de objetos"},
				{"checkAfzonderlijkLabel" , "Comprobar de forma separada"},
				{"checkOpSamenhangLabel" , "Comprobar la coherencia"},
				{"boxMetRand" , "Caja"},
				{"keuzeVakKiesLabel" , "Escoge"},
				{"verzamelDoelCBLabel" , "Objeto objetivo como área de colección"},
                
				
				{"vormCBLabel" , "Formulario"},
				{"formuleToolCBLabel" , "Editor de entrada de fórmula"},
				{"goedLabel" , "Correcto"},
				{"doorLabel" , "Continuar"},
				{"foutLabel" , "Incorrecto"},
				{"halfLabel" , "Medio"},
				
				{"geenOplossingen" , "sin solución"},
				{"allesOplossing" , "todas son soluciones"},
				{"antwoordModelGeen" , "ninguno"},
				{"abc" , "discr"},
				
				{"checkExternalCBLabel" , "check external"},
				
				// TekstVakInteractiePanel
				{"formuleAntwVakLabel" , "Caja de respuesta de la fórmula con pasos"},
                {"vergelijkingAntwVakLabel" , "Caja de respuestas de la ecuación con pasos"},
                {"simpelFormuleAntwVakLabel" , "Caja pequeña de respuestas de la fórmula"},
                {"simpelVergelijkingAntwVakLabel" , "Caja pequeña de respuestas de la ecuación"},
                {"tekstAntwVakLabel" , "Caja de texto y respuesta"},
                {"algebraPijlenLabel" , "Flechas de álgebra"},
                {"blokkenbouwenLabel" , "Construir con bloques"},
                {"stroomdiagrammenLabel" , "Diagramas de flujo"},
                {"grafiekenToolLabel" , "Herramienta para graficar"},
                {"tekstVakLabelH" , "Caja de texto"},
				{"geogebraIpLabel" , "Geogebra 4 (próximamente)"},
				{"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "Frutas en equilibrio"},
				{"checkSelectieUnitLabel" , "Comprobar la unidad de selección"},
				{"checkTekstAntwoordVakLabel" , "Comprobar la caja de texto y respuesta"},
				{"keuzeAntwoordVakLabel" , "Caja de elección de respuestas "},
				{"doorzienIpLabel" , "componente para la construcción 3D "},
				{"checkSleepUnitLabel" , "Comprobar la unidad de arrastrar y pegart"},
				{"vergrotenIpLabel" , "PE Alargamiento"}, 
				{"vangenIpLabel" , "PE Atrapar"},
				{"verknippenIpLabel" , "PE Cortar"},
				{"geomAlgebra2dIpLabel" , "Geom.algebra 2d"},
				{"geomAlgebra1dIpLabel" , "Geom.algebra 1d"},
				{"normaleVerdelingIpLabel" , "Distribución normal"},
				{"mp3PlayerIpLabel" , "Reproductor Mp3"},
				{"binominaleVerdelingIpLabel" , "Distribución binomial"},
				{"getallenlijnIpLabel" , "Número de línea (Salto)"},
				{"tekenVeelvlakIpLabel" , "Dibujar en el espacio"},
				{"mozaikIpLabel" , "Mosaico"}, 
				{"veelvlakkenIpLabel" , "Poliedro"}, 
				{"eerlijkVerdelenIpLabel" , "PE Equal sharing"}, 
				{"statistiekIpLabel" , "[prueba] Representaciones estadísticas"},
				{"stroomdiagrammenIpLabel" , "[prueba] Nuevo diagrama de flujo"},
				{"tegelsIpLabel" , "Tilings"}, 
				{"checkWaardeUnitLabel" , "[prueba] Comprobar la unidad de valor"},
				{"omtrekAppletIpLabel" , "PE circumference applet"}, 
				{"algebraExpressiesIpLabel" , "[prueba] Algebra trees"}, 
				{"oppervlakteAlgebraIpLabel" , "[prueba] Area algebra"}, 
				{"blokkenProgrammaIpLabel" , "[prueba] Programas de los bloques"},
				{"grafieken3DIpLabel" , "[prueba] Gráficos 3D"},
				{"spotProblemsIpLabel" , "[prueba] Problemas puntuales"},
				{"kladjeIpLabel" , "[prueba] Nota"},
				{"kansbomenIpLabel" , "[prueba] Árboles de probabilidades"},
				{"rekenmachineIpLabel" , "[prueba] Calculadora"},
				{"formStructIpLabel" , "[prueba] FormStruct"}, 
				{"graphToolIpLabel" , "[prueba] GraphTool"}, 
				{"draabankIpLabel" , "[prueba] Turning lathe"},
				{"waarmakersIpLabel" , "[test] Truemakers"},
				{"statSimIpLabel" , "[test] Statistics Simulations"},
				{"stelselVakLabel", "[test] Stelsel-antwoordvak"},
	            {"javaLogoIpLabel", "JavaLogo"},

	            //CheckButtonEditor
                {"CB_kijkNaOptieLabel", "Check" },
                {"CB_bewaarOptieLabel", "Save" },
                {"CB_rondAfOptieLabel", "set completed" },
                {"CB_nextPageOptieLabel", "To next page" },
                {"CB_eigenVakOptieLabel","All in same box"},
                {"CB_opPaginaOptieLabel","All on page"},
                {"CB_viaXWidgetOptieLabel","All connected via x-widget"},
                
				
				//InstellingenPanel
				{"OPT_wiskundeLabel" , "Matemáticas"},
                {"OPT_navigatieLabel" , "Navegación"},
                {"OPT_layoutLabel" , "Disposición"},
                {"OPT_nakijkenLabel" , "Opciones a escoger"},
				{"OPT_vermenigvTeken" , "Signo de multiplicación: X"},
				{"OPT_woordformules" , "Palabras variables "},
				{"OPT_tweeHoofdletterVars" , "Variables como AB, BC etc."},
				{"OPT_tempoToets" , "Tiempo restringido"},
				{"OPT_opnieuwKnop" , "'Botón Todo de nuevo"},
				{"OPT_itemOpnieuwKnop" , "'Botón item de nuevo"},
				{"OPT_checkPerOpdracht" , "Comprobar por página"},
				{"OPT_hoekInGraden" , "Unidad de ángulos: grados"},
				{"OPT_opdrachtBolletjes" , "Selector de items"},
				{"OPT_volgendeKnop" , "Botón siguiente"},
				{"OPT_VorigeKnop" , "Botón anterior"},
				{"OPT_paginaIpvOpdracht" , "Etiqueta: 'Página' en vez de 'Problema'"},
				{"OPT_fontFormaat" , "Tamaño "},
				{"OPT_fontNaam" , "Fuente básica"},
				{"OPT_tijdsLimiet" , "Límite de tiempo (seg)"},
				{"OPT_formTimes" , "Fórmulas en fuente Times Roman"},
				{"OPT_navigatieFormaat" , "Tamaño de la barra de navegación"},
				{"OPT_margesLabel" , "Márgenes:"},
				{"OPT_margeLinksLabel" , "Izquierda"},
				{"OPT_margeRechtsLabel" , "Derecha"},
				{"OPT_margeBovenLabel" , "Arriba"},
				{"OPT_margeOnderLabel" , "Abajo"},
				{"OPT_fToets" , "F-keys for formulas"}, 
				{"OPT_globalParam" , "Parámetros globales"},
				{"OPT_voortgangKnop", "'Progreso en vez de 'Total'"},
				{"OPT_conditionalNav" , "Condicional de navegación"},
				{"OPT_conditionalPercLabel" , "Porcentaje"},
				{"OPT_voorwaarden", "Condiciones por página"},
				{"OPT_allesCorrect", "Siguiente página sólo si todo está correcto (verde)"},
				{"OPT_deelOpdr" , "número de ítems a,b,c etc"},
				{"OPT_zelftoetsGeenCorr" , "Test personalizado sin correcciones"},
				{"OPT_zelftoetsGeschiedenis" , "self-test history"},
				{"OPT_zelftoetsHighScore" , "highscore"},
				{"OPT_eerderGeenCorr" , "Páginas previas sin corrección"},
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_significantie" , "Comprobar la opción número significativo"},
				{"OPT_objectives" , "Objetivos"},
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_fontOvererving" , "Font-inheritance text boxes"},
				{"OPT_fontOverervingForm" , "Font-inheritance formula boxes"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Use styles"},
				{"OPT_importStyles" , "Import"},
				{"OPT_exportStyles" , "Export"},
				{"OPT_layers" , "Use layers"},
				
				{"OBJ_leerdoel", "Objetivo"},
				{"OBJ_categorie", "Categoría"},
				{"OBJ_categorieBox", "Objetivos en las múltiples categorías"},
				{"OBJ_kolomMeerButton", "Añadir columna"},
				{"OBJ_kolomMinderButton", "Eliminar columna"},
				{"MCC_misconception", "Misconception"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "Variables de la función"},
				{"GEP_assenLabel" , "Mostrar ejes"},
				{"GEP_grafiekOptiesLabel" , "Opciones de la herramienta gráfica"},
				
				{"GEP_varXLabel" , "Variable eje de las x"},
				{"GEP_varYLabel" , "Variable eje de las y"},
				
				{"GEP_assenOptie" , "Ejes"},
				{"GEP_roosterOptie" , "Cuadrícula"},
				{"GEP_roosterGrofOptie" , "Ancho"},
				{"GEP_schaalverdelingOptie" , "Números del eje"},
				{"GEP_piOptie" , "Cuadrícula para Pi"},				
				
				{"GEP_zoomOptie" , "Opción Zoom"},
				{"GEP_traceOptie" , "Opción trazo"},
				{"GEP_dragOptie" , "Opción arrastrar"},
				{"GEP_tekenOptie" , "Herramienta para dibujar gráficos"},
				
				{"GEP_tabelOptie" , "Herramienta Tabla"},
				{"GEP_zoomInTabelOptie" , "Zoom en la tabla"},
				{"GEP_tabelTekenToolOptie" , "Tabla como herramienta de dibujo"},

				{"GEP_functieEditOptie" , "Editor de funciones"},
				{"GEP_grafiekKleurenOptie" , "Diferentes colores"},
				
				{"GEP_formeleFunctieNotatieOptie" , "Notación formal de la función f(x), g(x) etc."},
				
				{"GEP_popupWeergave" , "Mostrar en una ventana emergente"},
				
				{"GEP_xPositief" , "x positivo"},
				{"GEP_yPositief" , "y positivo"},
				{"GEP_xEditable" , "x modificable"},
				{"GEP_yEditable" , "y modificable"},
				
				
				{"GEP_opdrachten" , "tareas"},
				
				{"GEP_kiesOpdracht" , "escoge el tipo de tarea"},
				{"GEP_opdracht1" , "encuentra la fórmula para un gráfico de línea dado"},
				{"GEP_opdracht2" , "encuentra la fórmula para un número de puntos del gráfico"},
				{"GEP_opdracht3" , "dibuja un número de puntos para la fórmula dada"},
				{"GEP_opdracht4" , "dibuja los puntos a partir de la tabla en el gráfico"},
				
				{"GEP_antwoordFormule" , "introduce la formula de la solución en el editor de funciones que se encuentra abajo"},
				{"GEP_tabelPuntenX" , "introduce los valores de x de los puntos del gráfico en la tabla de abajo" },
				{"GEP_tabelPunten" , "introduce los puntos en la tabla de abajo" },
				
				{"GEP_nauwkeurigheid" , "Precisión (píxeles)"},
				{"GEP_minimumPunten" , "Número mínimo de puntos"},
				{"GEP_maximumScore" , "Máxima puntuación"},
				{"GEP_leerlingZietTabel" , "El alumno podrá ver la tabla"},
				
				{"GE_kijkNa" , "Comprobar" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "Texto"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "Ancho de la ventana"},
				{"LEP_vensterHoogte" , "Alto de la ventana"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "Añadir"},
				{"IEP_verwijderen" , "Eliminar"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "Cancelar"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "Borde"},
				{"TVEP_achtergrondKleurAanwezig" , "Color de fondo"},
				{"TVEP_zwevend" , "Flotando sobre el texto"},
				{"TVEP_anderFont" , "Otra fuente"},
				{"TVEP_rondingHoeken" , "Esquinas redondeadas"},
				{"TVEP_rotatieHoek" , "Angulo de rotación"},
				{"TVEP_centreerHor" , "Centrar horizontalmente"},
				{"TVEP_centreerVert" , "Centrar verticalmente"},
				{"TVEP_pasAanH" , "Ajustar a lo alto"},
				{"TVEP_pasAanB" , "Ajustar a lo ancho"},
				{"TVEP_aantalRijen" , "Número de filas"},
				{"TVEP_aantalKolommen" , "Número de columnas"},
				{"TVEP_tabelRanden" , "Bordes de la tabla"},
				{"TVEP_celMarge" , "Margen izquierdo"},
				{"TVEP_bovenMarge" , "Margen superior"},
				{"TVEP_fontType" , "Fuente"},
				{"TVEP_achtergrondKleur" , "Color"},
				{"TVEP_interlinie" , "Espacio entre líneas"},
				{"TVEP_cellSpaceColumn" , "Espacio"},
				{"TVEP_cellSpaceRow" , "Espacio"},
				{"TVEP_layoutLabel" , "Disposición del cuadro de texto"},
				{"TVEP_gebruikersInteractieLabel" , "Interacción entre los usuarios"},
				{"TVEP_selectieObject" , "Selección del objeto"},
                {"TVEP_selectieKleur" , "Color"},
                {"TVEP_selectieKleurKnopLabel" , "Selection color"},
                {"TVEP_sleepObject" , "Arrastrar objeto"},
                {"TVEP_draaiObject" , "Rotating object"},
                {"TVEP_sleepDoel" , "Arrastrar objetivo"},
                {"TVEP_sleepHandle" , "Manipular"},
                {"TVEP_selectieSleepWaarde" , "valor    ("},
                {"TVEP_fgKleurKnopLabel" , "color"},
                {"TVEP_zichtbaarNaNakijken" , "Visible después de comprobar"},
                {"TVEP_balansVergCom" , "Caja de comunicación entre equilibrio y ecuación"},
                {"TVEP_aftrekPopup" , "Disminución de puntuación utilizando la ventana emergente"},
                {"TVEP_callOut" , "Caja de llamado"},
                {"TVEP_vulHoogte" , "Fill height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "Pasos"},
                {"TVEP_random" , "Selección aleatoria"},
                {"TVEP_linkObject" , "Objeto vinculante"},
                {"TVEP_editLink" , "Editar el vínculo"},
                {"TVEP_defaultBijNull" , "por defecto  )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "Opción guardar"},
				{"GEP_alsTool" , "Como herramienta"},
				{"GEP_rand" , "Borde"},
				{"GEP_resetIcon" , "Opción reiniciar"},
				{"GEP_checkMetCheckDWO" , "Using checkDWO"}, 
				{"GEP_checkMetObjecten" , "Utilizar objetos creados"},
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "Valor mínimo"},
				{"GSEP_maxValue" , "Valor máximo"},
				{"GSEP_eenheden" , "Unidades visibles"},
				{"GSEP_getallen" , "Números"},
				{"GSEP_10tallen" , "Marca para decenas"},
				{"GSEP_5tallen" , "Marca para centenas"},
				{"GSEP_nul" , "Cero"},
				{"GSEP_pijl" , "Flecha visible"},
				{"GSEP_pijlTerug" , "Flecha hacia atrás"},
				{"GSEP_horizontaal" , "Horizontal"},
				{"GSEP_eenheid" , "Unidad"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "Barra de menú"},
				{"TEEP_rekenToolOptie" , "Calculadora"},
				{"TEEP_grafToolOptie" , "Herramienta de gráficos"},
				
				//Ideas
				
				{"ideasTip",		"pista"},
				{"ideasHelp",		"ayuda"},
				{"ideasStap",		"paso"},
				{"ideasLosop",		"resolver"},
				{"ideasWordtDan",		"convertir"},
				
				{"algebra.equations.coverup.denominator"		,"Ocultar el denominador"	},
				{"algebra.equations.coverup.minus-left"			,"mover las expresiones constantes hacia la derecha"	},
				{"algebra.equations.coverup.minus-right"		,"utilizar el método de ocultar"	},
				{"algebra.equations.coverup.negate"				,"dividir entre 1"	},
				{"algebra.equations.coverup.numerator"			,"ocultar el numerador"	},
				{"algebra.equations.coverup.plus"				,"mover las expresiones constantes hacia la derecha"},
				{"algebra.equations.coverup.power"				,"toma la raíz cuadrada"	},
				{"algebra.equations.coverup.sqrt"				,"cuadrar en ambos lados"	},
				{"algebra.equations.coverup.times"				,"aislar la variable diviendo ambos lados"	},
				{"algebra.equations.coverup.times-positive"		,"aislar la variable diviendo ambos lados"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"mover los términos constantes hacia  la derecha mediante la adición de un número a cada lado"},
				{"algebra.equations.coverup.onevar.plus"		,"mover los términos constantes hacia la derecha restando un número de cada lado"},
				
				{"algebra.equations.linear.distr-times"	,"eliminar el paréntesis"},
				{"algebra.equations.linear.flip"			,"intercambiar la ecuación"},
				
{"algebra.equations.linear.merge"		,"simplificar tomando la expresión conjunta el cálculo"},
				{"algebra.equations.linear.remove-div"	,"eliminar las fracciones multiplicándolas por un número"},
				{"algebra.equations.linear.var-left"		,"mover las expresión con variable hacia la izquierda"},
				
				{"algebra.equations.buggy.cancel-minus"				,"no se pueden cancelar los términos por que la señal no es la misma" }, 
				{"algebra.equations.buggy.distr-times-denom","error al momento de eliminar el paréntesis: uno de los términos es una fracción y el factor que se multiplica  con el numerador de la fracción"},
				{"algebra.equations.buggy.distr-times-plus"			,"cuando se eliminan los paréntesis de un término que no ha sido multiplicado"},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"cuando se eliminan los paréntesis y un término ha sido olvidado"	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"recuerda los signos cuando remuevas los paréntesis"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"cuando se elimina el paréntesis solo se multiplican los términos entre paréntesis"},
				{"algebra.equations.buggy.divide-negate"			,"prestar atención al signo al dividir"	},
				{"algebra.equations.buggy.divide-numdenom"			,"fracción invertida. Piensa en el número que has utilizado al dividir"},
				{"algebra.equations.buggy.flip-negate-one-side"		,"tienes que cambiar los signos en ambos lados"	},
				{"algebra.equations.buggy.multiply-one-side"		,"tienes que multiplicar ambos lados"	},
				{"algebra.equations.buggy.minus-minus"				,"cuando se elimina el paréntesis: al multiplicar dos número negativos se obtiene un número positivo"},
				{"algebra.equations.buggy.multiply-forget-one"		,"se ha olvidado uno de los términos al multiplicar ambos lados"},
				{"algebra.equations.buggy.negate-all"				,"se ha olvidado cambiar uno de los signos de los términos"	},
				{"algebra.equations.buggy.negate-one-side"			,"se ha olvidado uno de los lados al cambiar el signo"	},
				{"algebra.equations.buggy.plus"						,"piensa en el signo cuando muevas un término de un lado al otro"	},
				{"algebra.equations.buggy.priority-times"			,"recuerda las reglas de prioridades y paréntesis"	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"en la fórmula del cuadrado D=b^2-4ac y no D=b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"el no de la negación en frente de b: "	},
				{"algebra.equations.buggy.abc.one-solution"				,"no hay una segunda solución"	},
				{"algebra.equations.buggy.abc.two-a"					,"dividido entre 2a y no a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"has olvidado la otra (negativa) raíz cuadrada"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"antes de calcular la raíz cuadrada necesitas llevar a cabo otra acción"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"antes de calcular la raíz cuadrada necesitas llevar a cabo otra acción"	},
				{"algebra.equations.buggy.coverup.square-minus"			,"no puedes calcular la raíz cuadrada de un número negativo"	},
				{"algebra.equations.buggy.coverup.times-mul"			,"en vez de dividir el lado derecho debes multiplicarlo"},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"cuando divides, debes dividir todos los términos"	},
				{"algebra.equations.buggy.distr-square"					,"cuando calculabas el cuadrado de dos términos has olvidado cruzar los dos productos"	},
				{"algebra.equations.buggy.distr-square-forget"			,"Al momento de de calcular el cuadrado de los dos términos has olvidado uno de ellos"	},
				{"algebra.equations.buggy.square-multiplication"		,"cuadrado incorrecto de los términos"	},
				{"algebra.equations.buggy.division-by-var-both"		,"al dividir entre la variable has perdido la solución var=0"	},
				{"algebra.equations.buggy.division-by-var-zero"		,"al dividir entre la variable has perdido la solución var=0"	},
				
				{"algebra.equations.linear.balance.collect"			,"combinar"	},
				{"algebra.equations.linear.balance.calculate"		,"calcular"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"escribe división como multiplicación con una fracción"	},
				{"algebra.equations.linear.balance.smart-div"		,"dividir entre un factor común"	},
				{"algebra.equations.linear.balance.con-right-minus"	,"sustraer {?} de ambos lados"	},
				{"algebra.equations.linear.balance.con-left-minus"	,"sustraer {?} de ambos lados"	},
				{"algebra.equations.linear.balance.var-right-minus"	,"sustraer {?} de ambos lados"	},
				{"algebra.equations.linear.balance.var-left-minus"	,"sustraer {?} de ambos lados"	},
				{"algebra.equations.linear.balance.con-right-plus"	,"añadir {?} de ambos lados"	},
				{"algebra.equations.linear.balance.con-left-plus"	,"añadir {?} de ambos lados"	},
				{"algebra.equations.linear.balance.var-right-plus"	,"añadir {?} de ambos lados"	},
				{"algebra.equations.linear.balance.var-left-plus"	,"añadir {?} de ambos lados"	},
				{"algebra.equations.linear.balance.distribute"		,"eliminar paréntesis"	},
				{"algebra.equations.linear.balance.remove-div"		,"multiplicar ambos lados por {?}"	},
				{"algebra.equations.linear.balance.scale-to-one"	,"dividir ambos lados entre {?}"	},
				{"algebra.equations.linear.balance.negate"    ,"cambiar el signo de los dos lados"  },
				{"algebra.equations.linear.balance.intro-false"    ,"no es posible"  },
				{"algebra.equations.linear.balance.intro-true"    ,"siempre es verdadero"  },
                
               
				{"algebra.equations.quadratic.abc"				,"utiliza la fórmula cuadrática"	},
				{"algebra.equations.quadratic.approx"			,"aproximado"	},
				{"algebra.equations.quadratic.cancel"			,"eliminar las expresiones de ambos lados del símbolo =-"	},
				{"algebra.equations.quadratic.common-factor"	,"factorizar utilizando el factor común"	},
				{"algebra.equations.quadratic.distr-div"		,"dividir"	},
				{"algebra.equations.quadratic.distr-square"		,"calcular el cuadrado"	},
				{"algebra.equations.quadratic.left-square"		,"escribe el lado izquierdo como un cuadrado"	},
				{"algebra.equations.quadratic.move-left"		,"mueve todo a la izquierda"	},
				{"algebra.equations.quadratic.nice-factors"		,"factoriza las tres expresiones"	},
				{"algebra.equations.quadratic.no-lin"			,"escribe como cuadrado=número"	},
				{"algebra.equations.quadratic.prepare-split"	,"completa al cuadrado"	},
				{"algebra.equations.quadratic.product-zero"		,"producto=0, equiparar los factores a 0"	},
				{"algebra.equations.quadratic.same-con-factor"	,"dividir ambos lados entre un factor común"	},
				{"algebra.equations.quadratic.same-factor"		,"A*B=A*C implica A=0 o B=C"	},
				{"algebra.equations.quadratic.simpler-poly"		,"simplificar dividiendo entre un factor común"	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"simplificar raíces cuadradas"	},
				{"algebra.equations.quadratic.square-both"		,"cuadrado ambos lados"	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"aplicar la sustitución hacia atrás"	},
				{"algebra.equations.polynomial.expose-factor"		,"aislar el factor común"	},
				{"algebra.equations.polynomial.power-factors"		,"factor común x"	},
				{"algebra.equations.polynomial.subst"				,"usar la sustitución"	},
				{"algebra.equations.polynomial.def-power-nat"   	,"escribir le poder como multiplicación repetida"},
				
				
				{"algebra.equations.rational.check-solution"	,"comprobar la solución"	},
				{"algebra.equations.rational.cross-multiply"	,"cruzar la multiplicación"	},
				{"algebra.equations.rational.division-one"		,"cuando la fracción=1 el numerador = denominador"	},
				{"algebra.equations.rational.division-zero"		,"cuando la fracción =0 el numerador es =0 (si el denominador no es cero)"	},
				{"algebra.equations.rational.multiply-one-div"	,"multiplicar ambos lados por el denominador de la fracción"	},
				{"algebra.equations.rational.same-dividend"		,"A/B=A/C implica A=0 o B=C"	},
				{"algebra.equations.rational.same-divisor"		,"denominadores igual a equiparar numeradores"	},
				
				{"algebra.inequalities.flip-sign"		,"cambiar el signo"	},
				{"algebra.inequalities.give-solution"	,"resolver la desigualdad"	},
				{"algebra.inequalities.to-equation"		,"convertirlo primero en una ecuación"	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"multiplicar las potencias sumando los exponentes"	},
				{"algebra.manipulation.exponents.factor-as-power"		,"escribe (partes) como una potencia"	},
				{"algebra.manipulation.exponents.mul-exponents"			,"una potencia de una potencia: multiplicar exponentes"	},
				{"algebra.manipulation.exponents.reciprocal"			,"escribe 1/expresión como expresión^-1"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"escribe como una potencia añadiendo exponentes"	},
				{"algebra.manipulation.exponents.sub-exponents"			,"divide las potencias sustrayendo los exponentes"	},
				{"algebra.manipulation.exponents.write-as-power"		,"escribe como potencia"	},
				{"algebra.manipulation.exponents.distr-power"			,"utiliza la potencia de un producto como producto de sus ponencias"	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"utiliza la expresión de la potencia^-1 como una fracción: 1/expresión"	},
				{"algebra.manipulation.exponents.write-as-root"			,"escribe como raíz cuadrada"	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"escribe  1/potencia como otra potencia en la que el signo del exponente ha cambiado"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"mueve la negación fuera de la potencia (cuando el exponente es impar)"	},
				{"algebra.manipulation.exponents.root"					,"obtén la raíz cuadrada"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"potencia=1 implica exponente=0"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"el mismo número base"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"aproximar esta potencia a la raíz cuadrada"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"potencia común"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"escribe la mayor potencia común"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"nth square root"	}, 
				
				{"algebra.manipulation.logarithmic.logarithm"		,"utilizar la definición glog(x)=a implica x=g^a"	}, 
				
				{"calculus.differentiation.deriv-of-poly"		,"diferenciar una potencia de una función"	},
				{"calculus.differentiation.min"		,"aplicar la regla por sustracción"	},
				{"calculus.differentiation.negate"		,"mover la negación antes de diferenciarla"	},
				{"calculus.differentiation.plus"		,"aplicar la regla de la suma"	},
				{"calculus.differentiation.product"		,"aplicar la regla del producto"	},
				{"calculus.differentiation.quotient"		,"aplicar la regla del cociente"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"resta {?} de la izquierda pero suma {?} de la derecha"	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"suma {?} a la izquierda pero resta {?} de la derecha"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"resta {?} de la derecha pero suma {?} a la izquierda"	},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"suma {?} a la derecha pero resta {?} de la izquierda"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"resta {?} de la izquierda pero no lo hagas con la derecha"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"suma {?} a la izquierda pero no lo hagas con la derecha"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"resta{?} de la izquierda pero suma {?} a la derecha"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"suma {?} a la izquierda pero resta {?} de la derecha"} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"resta {?} de la derecha pero suma {?} a la izquierda"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"suma {?} a la derecha pero resta {?} de la izquierda"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"resta {?} de la derecha pero no lo hagas de la izquierda"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"suma {?} a la derecha pero no lo hagas a la izquierda"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"resta {?} de la izquierda pero no lo hagas en la derecha"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"suma {?} de la izquierda pero no lo hagas en la derecha"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"resta{?} de la derecha pero no lo hagas de la izquierda"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"suma {?} a la derecha pero no lo hagas de la izquierda"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"No sólo han cambiado los lados derecho e izquierdo si no que también han cambiado los signos de cada lado "	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"has restado de la derecha,¿has hecho lo mismo con la izquierda?"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"has multiplicado por un número, pero no has completado el lado izquierdo"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"has anulado, pero no has completado el lado izquierdo"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"has dividido entre un número, pero no has completado el lado izquierdo"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"has divido el lado izquierdo entre {?}, pero el derecho por el inverso"

	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"multiplica el lado izquierdo y el derecho por números diferentes"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"multiplica el lado izquierdo  {?}, pero no el derecho"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"divide el lado izquierdo entre {?}, pero no el derecho"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"anula el lado izquierdo, pero no el derecho"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"divide un lado entre {?}, pero no el otro"	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"error al multiplicar (1)"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"error al multiplicar (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"error de multiplicación, has obviado el signo menos"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"error al multiplicar, menos veces menos es positivo"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"error al dividir, has dividido entre un número negativo "	},
				{"algebra.equations.linear.balance.buggy.par1"		,"error al eliminar el paréntesis, multiplica ambos términos entre paréntesis(1)"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"recuerda la principales reglas: primero multiplicar, luego añadir"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"el símbolo menos no ha sido movido de forma correcta entre paréntesis"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"error al eliminar el paréntesis, multiplica ambos términos entre paréntesis (2)"	},
				{"algebra.equations.linear.balance.buggy.par4"		,"error al eliminar el paréntesis, error de multiplicación (1)"	},
				{"algebra.equations.linear.balance.buggy.par5"		,"error al eliminar el paréntesis, multiplica ambos términos entre paréntesis (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		,"error al eliminar el paréntesis, multiplica ambos términos entre paréntesis (4)"	},
				{"algebra.equations.linear.balance.buggy.par7"		,"error al eliminar el paréntesis, multiplica ambos términos entre paréntesis por -1"	},
				{"algebra.equations.linear.balance.buggy.par8"		,"error al eliminar el paréntesis,mira cuidadosamente donde están ubicados los paréntesis"	},
				{"algebra.equations.linear.balance.buggy.par9"		,"error al eliminar el paréntesis, error de multiplicación (2)"	},
				
				//conditionele navigatie-panels
				{"CN_voorwaarden", "Condiciones"},
				{"CN_vanPagina","De la página"},
				{"CN_naarPagina","A la página"},
				{"CN_scorePagina","Páginas para puntuar"},
				{"CN_grensPercentage","Cut-off perc."}, 
				{"CN_sorteer","Ordenar"},
				{"CN_regelMeer", "Añadir línea"},
				{"CN_regelMinder", "Eliminar línea"},
				
				// crossswidget commands
				{"CBA_input", "input"},
				{"CBA_int.index", "choice" },
				{"CBA_balansvergelijking", "balance equation"},
				{"CBA_zetOplossing", "set solution" },
				{"CBA_maakStap", "make step" },
				{"CBA_vergelijking", "equation" },
				{"CBA_double", "numerical value"},
				{"CBA_expression", "expression"},
				{"CBA_equation", "equation"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Action: 2x incorrect answer"},
				{"CBA_action.half", "Action: partial-correct answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				{"CBA_action.check", "Action: check"},
				{"CBA_action.click", "Action: click"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_haak", "Bracket"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},
		};
}




