package fi.wiskopdr.text;

public class Text_fa extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "برگشت" },
				
				{ "terugKnopToolTip" , "برگشت" },
				{ "gelijkwaardigKnopToolTip" , "يک عبارت مشابه وارد کنيد" },
				{ "opdrachtToolTip" , "مساله انتخاب کنيد" },
				{ "zelfKnopToolTip" , "عبارت خود را وارد کنيد  \n و آن را ساده کنيد." },
				
				
				{ "haakjesLabel0" , "  بسط" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "   ساده کنيد" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  فاکتور گيري" },
				{ "wortelLabel0" , "  ريشه ها" },
				{ "splitsLabel0" , "  بسط" },
				{ "hulpKnopLabel" , "Help" },
				{ "gelijkwaardigLabel0" , "  مساوي" },
				{ "gelijkwaardigLabel1" , "    با:" },
				{ "ofLabel" , "يا" },
				{ "enLabel" , "و" },
				{ "subLabel" , "جايگزين:" },
                { "meerLabel" , "more" },
				
                { "klaarKnopLabel" , "Check" },
				{ "nakijkKnopLabel" , "چک کنيد" },
				{ "checkExternal" , "external check" },
				{ "nakijkLabel1" , ":چک شده " },
				{ "nakijkLabel2" , " ضرب " },
				{ "opnieuwKnopLabel" , "دوباره" },
				{ "allesOpnieuwKnopLabel" , "دوباره براي همه" },
				{ "zelftoetsGeschiedenisKnopLabel", "score history"},
				{ "opdrachtLabel" , ":مساله" },
				{ "paginaLabel" , ":صفحه" },
				{ "onderdeelLabel" , ":قسمت" },
				{ "scoreLabel" , ":نمره" },
				{ "score" , ":نمره " },
				{ "optiesButtonLabel" , "گزينه" },
				{ "standaardActiviteitNaam" , "سطح" },
				{ "standaardOpdrachtNaam" , "مساله" },
				{ "opnieuwPanelTekstMW" , "اگر دوباره شروع کنيد نمره خود را از دست ميدهيد.\n\nآيا مطمئنيد که ميخواهيد دوباره شروع کنيد؟"},
				{ "opnieuwPanelTekst" , "اگر دوباره شروع کنيد نمره خود را از دست ميدهيد.\n\nيا مطمئنيد که ميخواهيد دوباره شروع کنيد؟"},
				{ "opnieuwPanelTitel" , "دوباره؟"},
				{ "lockToetsCBLabel" , "تست را قفل کن"},
				{ "lockToetsLabel" , "تست قفل شد"},
				{ "newPageMenuItem" ,  "insert new"},
				{ "deletePageMenuItem" ,  "delete"},
				{ "copyPageMenuItem" ,  "copy"},
				{ "cutPageMenuItem" ,  "cut"},
				{ "pastePageMenuItem" ,  "paste"},
				{ "insertCopyMenuItem" ,  "copy (insert)"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
								
				{ "choiceOefenen" , "تمرين" },
				{ "choiceOefenenEindloos" , "تمرين نامحدود" },
				{ "choiceOefenenStraf" , "تمرين بازي" },
				{ "choiceZelfToets" , "خود ارزيابي" },
				{ "choiceEindToets" , "تست" },
				
				{ "opdrachtTitelLabel" , ":عنوان" },
				{ "opdrachtTekstLabel" , ":متن" },
				{ "randVarLabel" , "متغيرها براي پارامترهاي تصادفي" },
				{ "startExpLabel" , ":عبارت شروع" },
				{ "startVergLabel" , ":معادله شروع" },
				{ "antwoordLabel" , ":مدل پاسخ" },
				{ "scoringLabel" , "نمره دهي به پاسخ" },
				{ "puntenLabel" , ":گزينه ها" },
				{ "checkTotaalLabel" , "توجه! کل نمره 10 است" },
				{ "gelijkwaardigCBLabel" , "معادل" },
				{ "herleidingCBLabel" , "ساده کردن" },
				{ "exactCBLabel" , "دقيق" },
				{ "significantCBLabel" , "قابل توجه" },
				{ "stappenCBLabel" , "استفاده از مراحل بيشتر" },
				{ "bewerkingKnoppenCBLabel" , "دگمه هاي عمليات" },
				{ "bewerkingKnoppenExtraCBLabel" , "دگمه هاي عمليات اضافي" },
                { "abcCBLabel" , "discr" },
				{ "subKnopCBLabel" , "subst." },
				{ "subKnopExtraCBLabel" , "subst. بسط داده شده" },
				
				{ "grafiekToolCBLabel" , "ابزار گراف" },
				{ "grafiekToolKnopLabel" , "ابزار گراف" },
				{ "vergelijkingCBLabel" , "معادله" },
				{ "eindOplossingCBLabel" , "نيازمند پاسخ" },
				{ "checkCBLabel" , "Checkable(يا نه)" },
				{ "teltMeeCBLabel" , "Include in grading (با نه)" },
				{ "logCBLabel" , " شناسه ورود" },
				{ "rmCBLabel" , "ماشين حساب" },
				{ "pijlCBLabel" , "پيکان" },
				{ "substitutiesButtonLabel" , "جايگرين" },
				{ "functiesButtonLabel" , "defined functions" },
				{ "strategieVersieLabel" , "نسخه استراتژي" },
				{ "oefenVersieLabel" , "استراتژي+نسخه" },
				{ "bordjesVersieLabel" , "نسخه متد دفاعي" },
				
				{ "herleidingKeuze_0" , "هيچکدام" },
				{ "herleidingKeuze_1" , "چند جمله اي بسط داده شده و ساده شده" },
				{ "herleidingKeuze_2" , "يک توان" },
				{ "herleidingKeuze_3" , "بدون توان منفي يا کسري" },
				{ "herleidingKeuze_4" , "يک کسر" },
				{ "herleidingKeuze_5" , "يک لگاريتم" },
				{ "herleidingKeuze_6" , "نوشته به عنوان لگاريتمهاي ساده (fe log(x)+log(3))" },
				
				{ "feedbackTekst01" , "اين مرحله حاوي قسمتهاي درست و نادرست است. قسمتهاي نادرست را حذف يا تغيير دهيد." },
				{ "feedbackTekst02" , "همه راه حلها معادله را حل نميکند. آنها را حذف کنيد." },
				{ "feedbackTekst03" , "نامعادله درست حل شد" },
				{ "feedbackTekst04" , "معادله درست حل شد" },
				{ "feedbackTekst05" , "پاسخ تقريبي ارايه دهيد" },
				{ "feedbackTekst06" , "نامعادله را حل کنيد" },
				{ "feedbackTekst07" , "مراحل حل جا افتاده را پر کنيد" },
				{ "feedbackTekst08" , "از علامتهاي | - استفاده نکنيد" },
				{ "feedbackTekst09" , "ساختار نوشتن اشتباه است" },
				{ "feedbackTekst10" , "راه حل درست است ولي در قالب درست نيست" },
				{ "feedbackTekst11" , "تقريب درست است" },
				{ "feedbackTekst12" , "پاسخ صحيح است" },
				{ "feedbackTekst13" , "راه حل معادل است ولي در قالب درست نيست" },
				{ "feedbackTekst14" , "ساختار نوشتن اشتباه است" },
                { "feedbackTekst15" , "پاسخ صحيح است" },
                { "feedbackTekst16" , "اين معادله درست است" },
                { "feedbackTekst17" , "اين معادله هنور داراي قالب درست نيست" },
                { "feedbackTekst18" , "پاسخ صحيح است ولي تعداد اشکال درست نيست" },
                { "feedbackTekst19" , "پاسخ صحيح است ولي قالب درستي ندارد و تعداد اشکال درست نيست" },
                { "feedbackTekst20" , "پاسخ صحيح است و تعداد اشکال نيز درست است ولي قالب درستي ندارد " },
                { "xVarMessage1" , "متغير مستقل هميشه\n" 
	+ "يک حرف است.\n " 
	+ "به صورت متغير کلمه اي است\n" 
	+ "کاراکتر اول يک متغير کلمه اي است\n" 
	+ "هميشه يک حرف است" },


				{ "xVarMessage2" , " متغیر مستقل تنها می تواند\n" 
									+ "توسط یک حرف نمایش داده می شود.\n" 
									+ "تنها وقتی گزینه\"متغیرهای کلمه\" \n" 
									+ "انتخاب شده است, متغیر مستقل می تواند\n" 
									+ "حروف بیشتری را نمایش میدهد." },
				{ "xVarMessage3" , "e حرف \n" 
									+ "برای تابع نمایی مورد استفاده قرار می گیرد.\n" 
									+ "این حرف نمی تواند به عنوان \n" 
									+ "نام یک متغیر مستقل استفاده شود." },									
				{ "xVarMessage4a" , "The tekst:  \"" },
				{ "xVarMessage4b" , "\" برای تابع شناخته شده ریاضی\n," 
									+ "{de betreffende wiskundige functie en mag dus}"
									+ "بنابراین نمی تواند به عنوان یک متغیر مورد استفاده قرار گیرد"},
									
				{ "gelijkwaardigKnopLabelGR" , "خط بعد" },
				{ "terugKnopLabelGR" , "خط قبل" },
				
				{ "editorVersieKnopLabel1" , "نسخه جدید ویراستار" },
				{ "editorVersieKnopLabel2" , "نسخه قدیمی ویراستار" },
				
				{"antwoordVakLabel" , "مستطیل جواب"},
				{"interactieVakLabel" , "مولفه محاوره ای"},
				{"tekstVakLabel" , "مستطیل متنی"},
				{"grafiekComponentLabel" , "مولفه ترسیم"},
				
				
				
				{"interactieKeuzeLabel" , "انتخاب نوع"},
				{"okKnopLabel" , "تایید"},
				{"annuleerKnopLabel" , "لغو"},
				{"breedteLabel" , "عرض:"},
				{"hoogteLabel" , "ارتفاع:"},
				{"volleBreedteLabel" , "تمام عرض"},
				{"popupLabel" , "پنجره ظاهر شده"},
				
				{"feedbackCBLabel" , "بازگشت"},
				{"feedbackSizeCBLabel" , "Popup size"},
				{"uitwCBLabel" , "پنجره ظاهر شده برای مراحل"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "مربوط به شما"},
				{"feedbackLabel" , "بازگشت"},
				{"ideasButtonLabel" , "انتخاب ها"},
				{"substitutiesButtonLabel" , "تعویض ها"},
				{"antwoordmodelButtonLabel" , "جوابهای ممکن"},
				{"formuleInvoerModeCBLabel" , "حالت وارد کردن فرمول"},
				{"aantalKeuzesLabel" , "تعداد انتخابها"},
				{"aantalSelectieObjLabel" , "تعداد اشیاء انتخاب شده"},
				{"randomPosLabel" , "موقعیت های تصادفی"},
				{"meervSelectiesLabel" , "گزینه های انتخابی چند گانه"},
				{"checkViaFormuleLabel" , "بررسی با استفاده از یک فرمول"},
				{"aantalSleepObjLabel" , "تعداد اشیاء کشیده شده"},
				{"aantalDoelObjLabel" , "تعداد اشیاء هدف"},
				{"snapToTargetLabel" , "شکستن اشیاء هدف"},
				{"snapMargeLabel" , "حاشیه شکستن"},
				{"checkVasteDoelenLabel" , "بررسی اهداف ثابت برای اشیاء کشیده شده"},
				{"checkWaardeOpDoelLabel" , "بررسی با استفاده از مقدار اشیائ کشیده شده"},
				{"relocateCBLabel" , "پرش به عقب"},
				{"viewCBLabel" , "مشاهده"},
				{"aantalValueObjectenLabel" , "تعداد اشیاء"},
				{"checkAfzonderlijkLabel" , "بررسی به طور جداگانه"},
				{"checkOpSamenhangLabel" , "بررسی منطقی"},
				{"boxMetRand" , "مستطیل"},
				{"keuzeVakKiesLabel" , "انتخاب کردن"},
				{"verzamelDoelCBLabel" , "محیط جمع آوری اشیاء هدف"},
                
				
				{"vormCBLabel" , "فرم"},
				{"formuleToolCBLabel" , ",ویراستار مورد فرمول"},
				{"goedLabel" , "تحصیح"},
				{"doorLabel" , "ادامه دادن"},
				{"foutLabel" , "غلط"},
				{"halfLabel" , "نیمه"},
				
				{"geenOplossingen" , "بدون جواب"},
				{"allesOplossing" , "همه جواب هستند"},
				{"antwoordModelGeen" , "هیچکدام"},
				{"abc" , "discr"},
				
				{"checkExternalCBLabel" , "check external"},
				
				// TekstVakInteractiePanel
				{"formuleAntwVakLabel" , "مستطیل جواب فرمول ها با مراحل"},
                {"vergelijkingAntwVakLabel" , "مستطیل جواب معادلات با مراحل"},
                {"simpelFormuleAntwVakLabel" , "مستطیل جواب های کوتاه فرمول "},
                {"simpelVergelijkingAntwVakLabel" , "مستطیل جواب های کوتاه معادله"},
                {"tekstAntwVakLabel" , "مستطیل جواب متنی"},
                {"algebraPijlenLabel" , "نشانه گرهای جبری"},
                {"blokkenbouwenLabel" , "ساخت بوسیله بلوک ها"},
                {"stroomdiagrammenLabel" , "نمودار جریان"},
                {"grafiekenToolLabel" , "ابزار ترسیم"},
                {"tekstVakLabelH" , "مستطیل متن"},
				{"geogebraIpLabel" , "جئوجبرای نسخه 4 (به زودی)"},
				{"geogebra3IpLabel" , "جئوجبرای نسخه 3"},
                {"fruitBalansIpLabel" , "تعادل نتیجه"},
				{"checkSelectieUnitLabel" , "بررسی واحد انتخاب"},
				{"checkTekstAntwoordVakLabel" , "بررسی مستطیل جواب متنی"},
				{"keuzeAntwoordVakLabel" , "انتخاب مستطیل جواب"},
				{"doorzienIpLabel" , "ساخت-مولفه سه بعدی"},
				{"checkSleepUnitLabel" , "بررسی واحد کشیدن و انداختن"},
				{"vergrotenIpLabel" , "گسترش PE"},
				{"vangenIpLabel" , "رسیدن به PE"},
				{"verknippenIpLabel" , "برش PE"},
				{"geomAlgebra2dIpLabel" , "جئو جبرا 2 بعدی"},
				{"geomAlgebra1dIpLabel" , "جئو جبرا 1 بعدی"},
				{"normaleVerdelingIpLabel" , "توزیع نرمال"},
				{"mp3PlayerIpLabel" , "پخش MP3"},
				{"binominaleVerdelingIpLabel" , "توزیع دو جمله ای"},
				{"getallenlijnIpLabel" , "محور اعداد (پرش)"},
				{"tekenVeelvlakIpLabel" , "ترسیم فضایی"},
				{"mozaikIpLabel" , "کاشی"},
				{"veelvlakkenIpLabel" , "چند وجهی"},
				{"eerlijkVerdelenIpLabel" , "به اشتراگ گذاری هم مرتبه PE"},
				{"statistiekIpLabel" , " (آزمون) نمایش آماری"},
				{"stroomdiagrammenIpLabel" , "(آزمون) نمودار شار جدید"},
				{"tegelsIpLabel" , "کاشی کاری"},
				{"checkWaardeUnitLabel" , " (آزمون) بررسی واحد مقدار"},
				{"omtrekAppletIpLabel" , "محیط برنامه PE"},
				{"algebraExpressiesIpLabel" , " (آزمون) درختهای جبری"},
				{"oppervlakteAlgebraIpLabel" , " (آزمون) محیط جبری"},
				{"blokkenProgrammaIpLabel" , " (آزمون) برنامههای مسدود شده"},
				{"grafieken3DIpLabel" , " (آزمون) نمودارهای سه بعدی"},
				{"spotProblemsIpLabel" , " (آزمون) برنامه های ذره ای"},
				{"kladjeIpLabel" , " (آزمون) یادداشت"},
				{"kansbomenIpLabel" , "(آزمون) درختهای احتمالی"},
				{"rekenmachineIpLabel" , "[test] Calculator"},
				{"formStructIpLabel" , "[test] FormStruct"},
				{"graphToolIpLabel" , "[test] GraphTool"},
				{"draabankIpLabel" , "[test] Turning lathe"}, 
				{"waarmakersIpLabel" , "[test] Truemakers"},
				{"statSimIpLabel" , "[test] Statistics Simulations"},
				{"stelselVakLabel", "[test] Stelsel-antwoordvak"},
	            {"javaLogoIpLabel", "JavaLogo"},

	            //CheckButtonEditor
                {"CB_kijkNaOptieLabel", "Check" },
                {"CB_bewaarOptieLabel", "Save" },
                {"CB_rondAfOptieLabel", "set completed" },
                {"CB_nextPageOptieLabel", "To next page" },
                {"CB_eigenVakOptieLabel","All in same box"},
                {"CB_opPaginaOptieLabel","All on page"},
                {"CB_viaXWidgetOptieLabel","All connected via x-widget"},
                
				
				//InstellingenPanel
				{"OPT_vermenigvTeken" , "علامت ظرب: X"},
				{"OPT_woordformules" , "متغیرهای عددی"},
				{"OPT_tweeHoofdletterVars" , "متغیرهایی شبیه AB, BC, و غیره."},
				{"OPT_tempoToets" , "زمان محدود شده"},
				{"OPT_opnieuwKnop" , "'همه مجدداً'-دکمه"},
				{"OPT_itemOpnieuwKnop" , "''گزینه مجدد'-دکمه"},
				{"OPT_checkPerOpdracht" , "بررسی هر صفحه"},
				{"OPT_hoekInGraden" , "واحد زاویه: درجه "},
				{"OPT_opdrachtBolletjes" , "انتخاب کننده گزینه"},
				{"OPT_volgendeKnop" , "دکمه- بعدی"},	
				{"OPT_VorigeKnop" , "دکمه قبلی"},
				{"OPT_paginaIpvOpdracht" , "برچسب: صفحه  به جا مسئله"},
				{"OPT_fontFormaat" , "اندازه "},
				{"OPT_fontNaam" , "فونت پایه"},
				{"OPT_tijdsLimiet" , "(محدودیت زمان (ثانیه"},
				{"OPT_formTimes" , "فرمول ها در فونت لوتوس"},
				{"OPT_navigatieFormaat" , "اندازه نوار مرور"},
				{"OPT_margesLabel" , "چسباندن:"},
				{"OPT_margeLinksLabel" , "چپ"},
				{"OPT_margeRechtsLabel" , "راست"},
				{"OPT_margeBovenLabel" , "بالا"},
				{"OPT_margeOnderLabel" , "پایین"},
				{"OPT_fToets" , "کلیدهای تابعی برای فرمول ها"},
				{"OPT_globalParam" , "پارامترهای کلی"},
				{"OPT_conditionalNav" , "مرور وضعیت"},
				{"OPT_conditionalPercLabel" , "Perc."},
				{"OPT_deelOpdr" , "شماره گزینه ها: a,b,c و غیره"},
				{"OPT_zelftoetsGeenCorr" , "خود آزمون غیر اصلاح شونده"},
				{"OPT_zelftoetsGeschiedenis" , "self-test history"},
				{"OPT_zelftoetsHighScore" , "highscore"},
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_significantie" , "گزینه بررسی اعداد ویژه"},
				{"OPT_objectives" , "Objectives"},
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_fontOvererving" , "Font-inheritance text boxes"},
				{"OPT_fontOverervingForm" , "Font-inheritance formula boxes"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Use styles"},
				{"OPT_importStyles" , "Import"},
				{"OPT_exportStyles" , "Export"},
				{"OPT_layers" , "Use layers"},
				
				{"OBJ_leerdoel", "Objective"},
				{"OBJ_categorie", "Category"},
				{"OBJ_categorieBox", "Objectives in multiple categories"},
				{"OBJ_kolomMeerButton", "Add column"},
				{"OBJ_kolomMinderButton", "Remove column"},
				{"MCC_misconception", "Misconception"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "متغیرهای توابع"},
				{"GEP_assenLabel" , "محورهای نمایش"},
				{"GEP_grafiekOptiesLabel" , "گزینه های ابزار ترسیم"},
				
				{"GEP_varXLabel" , "متغیر محور x"},
				{"GEP_varYLabel" , "متغیر محور y"},
				
				{"GEP_assenOptie" , "محورها"},
				{"GEP_roosterOptie" , "شبکه"},
				{"GEP_roosterGrofOptie" , "عریض"},
				{"GEP_schaalverdelingOptie" , "اعداد محورها"},
				{"GEP_piOptie" , "شبکه عدد پی"},				
				
				{"GEP_zoomOptie" , "گزینه زوم"},
				{"GEP_traceOptie" , "گزینه ردیابی"},
				{"GEP_dragOptie" , "گزینه کشیدن"},
				{"GEP_tekenOptie" , "ابزار ترسیم شکل"},
				
				{"GEP_tabelOptie" , "ابزار جدول"},
				{"GEP_zoomInTabelOptie" , "بزرگنمایی جدول"},
				{"GEP_tabelTekenToolOptie" , "جدول به عنوان ابزار ترسیم"},

				{"GEP_functieEditOptie" , "ویرایشگر توابع"},
				{"GEP_grafiekKleurenOptie" , "رنگ های متفاوت"},
				
				{"GEP_formeleFunctieNotatieOptie" , "توابع مجرد مانند f(x), g(x) و غیره."},
				
				{"GEP_popupWeergave" , "نمایش از طریق پنجره ظاهر شده"},
				{"GEP_xPositief" , "x مثبت"},
				{"GEP_yPositief" , "y مثبت"},
				{"GEP_xEditable" , "x قابل ویرایش"},
				{"GEP_yEditable" , "y قابل ویرایش"},
				
				
				{"GEP_opdrachten" , "وظایف"},
				
				{"GEP_kiesOpdracht" , "انتخاب نوع تکلیف"},
				{"GEP_opdracht1" , "یافتن فرمول برای یک خط داده شده"},
				{"GEP_opdracht2" , "یافتن فرمول برای یک تعداد از نقاط نمودار"},
				{"GEP_opdracht3" , "ترسیم یک تعداد از نقاط فرمول داده شده"},
				{"GEP_opdracht4" , "ترسیم نقاط یک نمودار از بین اعداد یک جدول"},
				
				{"GEP_antwoordFormule" , "درج کردن راه حل در ویرایشگر تابع در زیر"},
				{"GEP_tabelPuntenX" , "درج کردن طول نقاط نمودار در جدول زیر" },
				{"GEP_tabelPunten" , "درج نقاط در جدول زیر" },
				
				{"GEP_nauwkeurigheid" , "صحت (پیکسل ها) "},
				{"GEP_minimumPunten" , "کمترین تعداد نقاط"},
				{"GEP_maximumScore" , "بیشترین امتیاز"},
				{"GEP_leerlingZietTabel" , "دانش آموزان می توانند جدول را ببینند"},
				
				{"GE_kijkNa" , "بررسی" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "متن"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "عرض پنجره"},
				{"LEP_vensterHoogte" , "ارتفاع پنجره"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "جمع"},
				{"IEP_verwijderen" , "حذف"},
				{"IEP_ok" , "تأیید"},
				{"IEP_cancel" , "لغو"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "مرز"},
				{"TVEP_achtergrondKleurAanwezig" , "رنگ پس زمینه"},
				{"TVEP_zwevend" , "متن بالایی شناور"},
				{"TVEP_anderFont" , "فونت دیگر"},
				{"TVEP_rondingHoeken" , "گوشه های گرد"},
				{"TVEP_rotatieHoek" , "زاویه چرخش"},
				{"TVEP_centreerHor" , "به طور افقی در وسط"},
				{"TVEP_centreerVert" , "به طور عمودی در وسط"},
				{"TVEP_pasAanH" , "تنظیم ارتفاع"},
				{"TVEP_pasAanB" , "تنظیم عرض"},
				{"TVEP_aantalRijen" , "تعداد سطرها"},
				{"TVEP_aantalKolommen" , "تعداد ستون ها"},
				{"TVEP_tabelRanden" , "مرز جدول"},
				{"TVEP_celMarge" , "حاشیه چپ"},
				{"TVEP_bovenMarge" , "حاشیه بالا"},
				{"TVEP_fontType" , "فونت"},
				{"TVEP_achtergrondKleur" , "رنگ"},
				{"TVEP_interlinie" , "فاصله خطوط"},
				{"TVEP_cellSpaceColumn" , "فاصله"},
				{"TVEP_cellSpaceRow" , "فاصله"},
				{"TVEP_layoutLabel" , "نمایه مستطیل متنی"},
				{"TVEP_gebruikersInteractieLabel" , "محاوره کاربر"},
				{"TVEP_selectieObject" , "شیء انتخابی"},
                {"TVEP_selectieKleur" , "رنگ"},
                {"TVEP_selectieKleurKnopLabel" , "Selection color"},
                {"TVEP_sleepObject" , "شیء کشیده شده"},
                {"TVEP_draaiObject" , "Rotating object"},
                {"TVEP_sleepDoel" , "مقصد کشیدن"},
                {"TVEP_sleepHandle" , "کنترل کردن"},
                {"TVEP_selectieSleepWaarde" , "مقدار"},
                {"TVEP_fgKleurKnopLabel" , "رنگ"},
                {"TVEP_zichtbaarNaNakijken" , "قابل مشاهده بعد چک کردن آزمون"},
                {"TVEP_balansVergCom" , "مستطیل ارتباطی معادله تعادلی"},
                {"TVEP_aftrekPopup" , "کمتر کردن امتیاز با ظاهر شدن پنجره جدید"},
                {"TVEP_callOut" , "جعبه احضار کردن"},
                {"TVEP_vulHoogte" , "Fill height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "مراحل"},
                {"TVEP_random" , "random"},
                {"TVEP_linkObject" , "Link object"},
                {"TVEP_editLink" , "Edit link"},
                {"TVEP_defaultBijNull" , "default  "},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "گزینه ذخیره کردن"},
				{"GEP_alsTool" , "به عنوان ابزار"},
				{"GEP_rand" , "مرز"},
				{"GEP_resetIcon" , "گزینه شروع مجدد"},
				{"GEP_checkMetCheckDWO" , "استفاده از checkDWO"},
				{"GEP_checkMetObjecten" , "استفاده از اشیاء ساخته شده"},
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "کمترین مقدار"},
				{"GSEP_maxValue" , "بیشترین مقدار"},
				{"GSEP_eenheden" , "واحدهای قابل مشاهده"},
				{"GSEP_getallen" , "اعداد"},
				{"GSEP_10tallen" , "علامت زدن برای توجه کردن"},
				{"GSEP_5tallen" , "}Marh for fives}"},
				{"GSEP_nul" , "صفر"},
				{"GSEP_pijl" , "فلش های قابل مشاده"},
				{"GSEP_pijlTerug" , "فلش برگشت"},
				{"GSEP_horizontaal" , "افقی"},
				{"GSEP_eenheid" , "واحد"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "نوار منو"},
				{"TEEP_rekenToolOptie" , "ماشین حساب"},
				{"TEEP_grafToolOptie" , "ابزار ترسیم"},
				
				//Ideas
				
				{"ideasTip",		"تذکر"},
				{"ideasHelp",		"{vhiklhdd}"},
				{"ideasStap",		"مرحله"},
				{"ideasLosop",		"حل"},
				{"ideasWordtDan",		"روی دادن"},
				
				{"algebra.equations.coverup.denominator"		,"پوشاندن مخرج کسر"	},
				{"algebra.equations.coverup.minus-left"			,"انتقال عبارت های ثابت به راست"	},
				{"algebra.equations.coverup.minus-right"		,"استفاده از روش پوشاندن"	},
				{"algebra.equations.coverup.negate"				,"تقسیم بر 1-"	},
				{"algebra.equations.coverup.numerator"			,"پوشاندن صورت کسر"	},
				{"algebra.equations.coverup.plus"				,"انتقال عبارت های ثابت به راست"	},
				{"algebra.equations.coverup.power"				,"ریشه دوم گرفتن"	},
				{"algebra.equations.coverup.sqrt"				,"جذر گرفتن از هر دوئطرف"	},
				{"algebra.equations.coverup.times"				,"جداسازی متغیر با تقسیم به طرفین"	},
				{"algebra.equations.coverup.times-positive"		,"جداسازی متغیر با تقسیم به طرفین"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"انتقال مقدار ثابت به سمت راست با اضافه کردن مقدار معین به هر دو طرف"	},
				{"algebra.equations.coverup.onevar.plus"		,"انتقال مقدار ثابت به سمت راست با کم کردن مقدار معین از هر دو طرف"	},
				
				{"algebra.equations.linear.distr-times"		,"پرانتزها را حذف کنید"	},
				{"algebra.equations.linear.flip"			,"مبادله معادله ها"	},
				{"algebra.equations.linear.merge"			,"ساده سازی عبارت های مشابه"	},
				{"algebra.equations.linear.remove-div"		,"حذف کسرها با ضرب یک مقدار معین"	},
				{"algebra.equations.linear.var-left"		,"انتقال عبارت های متغیر دار به سمت چپ"	},
				
				{"algebra.equations.buggy.cancel-minus"				,"نمی توانید عبارت های مشابه را حذف کنید زیرا علامت ها یکسان نیست"	},
				{"algebra.equations.buggy.distr-times-denom"		,"اشتباط در حذف پرانتزها: یکی از عبارات یک کسر است و مقدار فاکتور گرفته شده در صورت کسر ضرب شده است."	},
				{"algebra.equations.buggy.distr-times-plus"			,"زمانیکه پرانتزها را حذف می کنید یکی از عبارت ضرب نشده است."	},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"زمانیکه پرانتزها را حذف می کنید یکی از عبارت از قلم افتاده است. "	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"علامت ها را در زمان حذف پرانتزها به خاطر بسپارید"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"زمانی که پرانتزها را حذف می کنید تنها عبارت های درون پرانتز ضرب می شوند."	},
				{"algebra.equations.buggy.divide-negate"			,"در زمان تقسیم به علامت ها توجه کنید"	},
				{"algebra.equations.buggy.divide-numdenom"			,"کسر معکوس شده. به اعدادی که برای تقسیم باید استفاده کنید فکر کنید"	},
				{"algebra.equations.buggy.flip-negate-one-side"		,"می بایست علامت را در هر دو طرف تغییر دهید"	},
				{"algebra.equations.buggy.multiply-one-side"		,"می بایست در هر دو طرف ضرب کنید"	},
				{"algebra.equations.buggy.minus-minus"				,"در زمان حذف پرانتزها: حاصلضرب دو عدد منفی عددی مثبت می شود"	},
				{"algebra.equations.buggy.multiply-forget-one"		,"در زمان ضرب در هر دو طرف یکی از عبارات از قلم افتاده است"	},
				{"algebra.equations.buggy.negate-all"				,"در زمان تغییر علامت یکی از عبارات از قلم افتاده است"	},
				{"algebra.equations.buggy.negate-one-side"			,"در زمان تغییر علامت یکی از طرفین از قلم افتاده است"	},
				{"algebra.equations.buggy.plus"						,"به علامت یک عبارت هنگامیکه از یک طرف به طرف دیگر منتقل می شود فکر کنید"	},
				{"algebra.equations.buggy.priority-times"			," قواعد مربوط به اولیوت ها و پرانتزها را به خاطر آورید"	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"در معادله درجه دوم D=b^2-4ac  و نه D=b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"جلوی b منفی نمی شود"	},
				{"algebra.equations.buggy.abc.one-solution"				,"راه حل دومی وجود دارد"	},
				{"algebra.equations.buggy.abc.two-a"					,"تقسیم به 2a و نه a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"ریشه دوم (منفی) را فراموش کرده اید"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"قبل از ریشه گرفتن باید سایر عملیات را انجام دهید"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"قبل از ریشه گرفتن باید سایر عملیات را انجام دهید"	},
				{"algebra.equations.buggy.coverup.square-minus"			,"نمی توانید از یک عدد منفی ریشه دوم بگیرید"	},
				{"algebra.equations.buggy.coverup.times-mul"			,"به جای تقسیم به سمت راست باید در آن ضرب کنید"	},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"هنگامیکه تقسیم می کنید همه عبارات را تقسیم کنید"	},
				{"algebra.equations.buggy.distr-square"					,"هنگامیکه دو جمله را به توان دو می رسانید حاصلضرب تقاطعی دو جمله را فراموش کرده اید"	},
				{"algebra.equations.buggy.distr-square-forget"			,"هنگامیکه دو جمله را به توان دو می رسانید یکی از جملات را فراموش کرده اید"	},
				{"algebra.equations.buggy.square-multiplication"		,"توان دوم دو جمله ای اشتباه"	},
				{"algebra.equations.buggy.division-by-var-both"		,"  را در زمان تقسیم به یک متغیر فراموش کرده اید var=0"	},
				{"algebra.equations.buggy.division-by-var-zero"		,"را در زمان تقسیم به یک متغیر فراموش کرده اید var=0"	},
				
				{"algebra.equations.linear.balance.collect"			,"ترکیب"	},
				{"algebra.equations.linear.balance.calculate"		,"محاسبه"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"نوشتن تقسیم به عنوان حاصل ضرب کسری"	},
				{"algebra.equations.linear.balance.smart-div"		,"تقسیم به مخرج مشترک"	},
				{"algebra.equations.linear.balance.con-right-minus"	,"کسر {؟} از هر دو طرف"	},
				{"algebra.equations.linear.balance.con-left-minus"	,"کسر {؟} از هر دو طرف"	},
				{"algebra.equations.linear.balance.var-right-minus"	,"کسر {؟} از هر دو طرف"	},
				{"algebra.equations.linear.balance.var-left-minus"	,"کسر {؟} از هر دو طرف"	},
				{"algebra.equations.linear.balance.con-right-plus"	,"اضافه کردن {؟} به هر دو طرف"	},
				{"algebra.equations.linear.balance.con-left-plus"	,"اضافه کردن {؟} به هر دو طرف"	},
				{"algebra.equations.linear.balance.var-right-plus"	,"اضافه کردن {؟} به هر دو طرف"	},
				{"algebra.equations.linear.balance.var-left-plus"	,"اضافه کردن {؟} به هر دو طرف"	},
				{"algebra.equations.linear.balance.distribute"		,"حذف پرانتزها"	},
				{"algebra.equations.linear.balance.remove-div"		,"ضرب {؟} به هر دو طرف"	},
				{"algebra.equations.linear.balance.scale-to-one"	,"تقسیم {؟} به هر دو طرف"	},
				{"algebra.equations.linear.balance.negate"    ,"تغییر علامت هر دو طرف"  },
				{"algebra.equations.linear.balance.intro-false"    ,"غیر ممکن"  },
				{"algebra.equations.linear.balance.intro-true"    ,"همیشه صحیح"  },
                
               
				{"algebra.equations.quadratic.abc"				,"استفاده از فرمول درجه دوم"	},
				{"algebra.equations.quadratic.approx"			,"تقریب"	},
				{"algebra.equations.quadratic.cancel"			,"حذف عبارت ها از هر دو طرف=-symbol"	},
				{"algebra.equations.quadratic.common-factor"	,"فاکتورگیری با استفاده از عامل مشترک"	},
				{"algebra.equations.quadratic.distr-div"		,"تقسیم"	},
				{"algebra.equations.quadratic.distr-square"		,"محسابه مجذور"	},
				{"algebra.equations.quadratic.left-square"		,"سمت چپ را به عنوان یک مجذور بنویسید"	},
				{"algebra.equations.quadratic.move-left"		,"همه را به سمت چپ انتقال دهید"	},
				{"algebra.equations.quadratic.nice-factors"		,"از سه عبارت فاکتور بگیرید"	},
				{"algebra.equations.quadratic.no-lin"			,"به فرم مجذور=عدد بنویسید"	},
				{"algebra.equations.quadratic.prepare-split"	,"مجذور را کامل کنید"	},
				{"algebra.equations.quadratic.product-zero"		,"حاصلضرب=صفر  معادل است با فاکتور صفر است"	},
				{"algebra.equations.quadratic.same-con-factor"	,"هر دو طرف را به عامل مشترک تقسیم کنید"	},
				{"algebra.equations.quadratic.same-factor"		,"A*B=A*C نتیجه می دهد A=0 or B=C"	},
				{"algebra.equations.quadratic.simpler-poly"		,"ساده سازی بوسیله تقسیم به عامل مشترک"	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"ساده سازی ریشه ها"	},
				{"algebra.equations.quadratic.square-both"		,"مجذور کردن هر دو طرف"	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"به کار بردن تعویض وارونه"	},
				{"algebra.equations.polynomial.expose-factor"		,"تنها سازی عامل مشترک"	},
				{"algebra.equations.polynomial.power-factors"		,"عامل مشترک x"	},
				{"algebra.equations.polynomial.subst"				,"استفاده از تعویض"	},
				{"algebra.equations.polynomial.def-power-nat"   	,"نوشتن توان به عنوان تکرار ضرب"},
				
				
				{"algebra.equations.rational.check-solution"	,"بررسی جواب"	},
				{"algebra.equations.rational.cross-multiply"	,"ضرب تقاطعی"	},
				{"algebra.equations.rational.division-one"		,"هنگامی که کسر=1 آنگاه صورت=مخرج"	},
				{"algebra.equations.rational.division-zero"		,"هنگامی که کسر=صفر آنگاه صورت=صفر (اگر مخرج برابر صفر نباشد"	},
				{"algebra.equations.rational.multiply-one-div"	,"ضرب طرفین به مخرج کسر"	},
				{"algebra.equations.rational.same-dividend"		,"A/B=A/C نتیجه می دهد A=0 or B=C"	},
				{"algebra.equations.rational.same-divisor"		,"یکسان بودن مخرج برابری صورت را نتیجه می دهد"	},
				
				{"algebra.inequalities.flip-sign"		,"تغییر علامت"	},
				{"algebra.inequalities.give-solution"	,"حل نامساوی"	},
				{"algebra.inequalities.to-equation"		,"ابتدا به فرم معادله در آید"	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"ضرب علارت های نمایی با جمع کردن توان ها"	},
				{"algebra.manipulation.exponents.factor-as-power"		,"بنویسید (بخشی) از یک توان"	},
				{"algebra.manipulation.exponents.mul-exponents"			,"توان توان: ضرب کردن توانها"	},
				{"algebra.manipulation.exponents.reciprocal"			,"عبارت 1/عبارت را به صورت عبارت به توان 1- بنویسید"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"با اضافه کردن توان به صورت نمایی بنوسید"	},
				{"algebra.manipulation.exponents.sub-exponents"			,"تقسیم عبارات نمایی با کسر توان ها"	},
				{"algebra.manipulation.exponents.write-as-power"		,"به صورت نمایی بنویسید"	},
				{"algebra.manipulation.exponents.distr-power"			,"به توان رسیدن حاصل ضرب، ضرب توان هاست"	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"فرم نمایی عبارت به توان 1- را کسری بنویسید: 1/عبارت"	},
				{"algebra.manipulation.exponents.write-as-root"			,"به صورت ریشه دوم بنویسید"	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"عبارت 1 تقسیم بر نمایی خود عبارتی نمایید که علامت توان آن عوض شده است"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"منفی را به بیرون از عبارت نمایی منتقل کنید وقتی که توان فرد باشد"	},
				{"algebra.manipulation.exponents.root"					,"ریشه دوم بدهید"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"عبارت نمایی=1 نتیجه می دهد توان=صفر"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"پایه نمایی یکسان"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"تخمین عبارت نمایی یا ریش دوم"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"توان مشترک"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"بر اساس بزرگترین توان مشترک بنویسید"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"nمین ریشه دوم"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		," تعریفglog(x)=a نتیجه میدهد x=g^a"	},
				
				{"calculus.differentiation.deriv-of-poly"		,"مشتق گرفتن از تابع نمایی"	},
				{"calculus.differentiation.min"		,"به کار بردن قانون تفریق"	},
				{"calculus.differentiation.negate"		,"منتقل کردن منفی به بیرون قبل از مشتق گیری"	},
				{"calculus.differentiation.plus"		,"به کار بردن قاعده جمع"	},
				{"calculus.differentiation.product"		,"به کار بردن قاعده ضرب"	},
				{"calculus.differentiation.quotient"		,"به کار بردن قاعده تقسیم"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		," مقدار {؟} را از چپ کم کنید اما مقدار {؟} را به راست اضافه کنید"	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"مقدار {؟} را به چپ اضافه کنید اما مقدار {؟} را از راست کم کنید"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"مقدار {؟} را از راست کم کنید اما مقدار {؟} را به چپ اضافه کنید"	},
				{"algebra.equations.linear.balance.buggy.addbal4"		," مقدار {؟} را به راست اضافه کنید اما مقدار {؟} را از چپ کم کنید"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"مقدار {؟} را از چپ کم کنید اما چیزی به راست اضافه نکنید"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"مقدار {؟} را به چپ اضافه کنید اما چیزی از راست کم نکنید"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"مقدار {؟} را از چپ کم کنید اما مقدار {؟} را به راست اضافه کنید"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"مقدار {؟} را به چپ اضافه کنید اما مقدار {؟} را از راست کم کنید"} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"مقدار {؟} را از راست کم کنید اما مقدار {؟} را به چپ اضافه کنید"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"مقدار {؟} را به راست اضافه کنید اما مقدار {؟} را از چپ کم کنید"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"مقدار {؟} را از راست کم کنید اما چیزی به چپ اضافه نکنید"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"مقدار {؟} را به راست اضافه کنید اما چیزی از چپ کم نکنید"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"مقدار {؟} را از چپ کم کنید اما چیزی به راست اضافه نکنید"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"مقدار {؟} را به چپ اضافه کنید اما چیزی را از راست کم نکنید"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"مقدار {؟} را از راست کم کنید اما چیزی از چپ کم نکنید"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"مقدار {؟} را به راست اضافه کنید اما چیزی از چپ کم نکنید"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"نه تنها مبادله سمت چپ و راست را انجام میدهید، بلکه علامت یک طرف را تغییر بدهید"	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"از سمت راست کم کردید، آیا همین کار را هم برای سمت چپ انجام دادید؟"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"در عددی ضرب کردید اما نه سمت چپ را به طور کامل"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"منفی کردید اما نه سمت چپ را به طور کامل"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"به عددی تقسیم کردید اما نه سمت چپ را به طور کامل"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"سمت چپ را به عدد {؟} تقسیم کنید، اما سمت راست را به معکوس آن"	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"سمت راست و سمت چپ رادر اعداد مختلف ضرب کردید"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"سمت چپ را در مقدار {؟} ضرب کردید، اما سمت راست را نه"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"سمت چپ را در مقدار {؟} تقسیم کردید، اما سمت راست را نه"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"سمت چپ را منفی کردید، اما سمت راست را نه"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"یک سمت را در مقدار {؟} تقسیم کردید، اما سمت دیگر را نه"	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"(اشتباه ضربی (1"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"اشتباه ضربی (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"اشتباه در ضرب، علامت منفی از بین رفت"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"اشتباه در ضرب، منفی در منفی مثبت می شود"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"اشتباه در تقسیم، به عدد منفی تقسیم کردید"	},
				{"algebra.equations.linear.balance.buggy.par1"		,"خطا در حذف پرانتز، هر دو عبارت داخل پرانتز را ضرب کنید (1) "	},
				{"algebra.equations.linear.balance.buggy.par10"		,"به یاد آوری اولویت ها: ابتدا ضرب سپس جمع"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"علامت منفی به طور صحیح داخل پرانتز منتقل نشده است"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"خطا در حذف پرانتز، هر دو عبارت داخل پرانتز را ضرب کنید (2) "	},
				{"algebra.equations.linear.balance.buggy.par4"		,"خطا در حذف پرانتز، اشتباه در ضرب (1) "	},
				{"algebra.equations.linear.balance.buggy.par5"		,"خطا در حذف پرانتز، هر دو عبارت داخل پرانتز را ضرب کنید (3) "	},
				{"algebra.equations.linear.balance.buggy.par6"		,"خطا در حذف پرانتز، هر دو عبارت داخل پرانتز را ضرب کنید (4) "	},
				{"algebra.equations.linear.balance.buggy.par7"		,"خطا در حذف پرانتز، هر دو عبارت داخل پرانتز را در 1- ضرب کنید "	},
				{"algebra.equations.linear.balance.buggy.par8"		,"خطا در حذف پرانتزها، به دقت به مکان پرانتزها دقت کنید"	},
				{"algebra.equations.linear.balance.buggy.par9"		,"خطا در حذف پرانتز، اشتباه در ضرب (2) "	},
				
				// crossswidget commands
				{"CBA_input", "input"},
				{"CBA_int.index", "choice" },
				{"CBA_balansvergelijking", "balance equation"},
				{"CBA_zetOplossing", "set solution" },
				{"CBA_maakStap", "make step" },
				{"CBA_vergelijking", "equation" },
				{"CBA_double", "numerical value"},
				{"CBA_expression", "expression"},
				{"CBA_equation", "equation"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Actie: 2x incorrect answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_haak", "Bracket"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},
				
		};
}






