package fi.wiskopdr.text;

import fi.wiskopdr.tekstobjects.ShareAction;

public class Text_gr extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "Πίσω" },
				
				{ "terugKnopToolTip" , "Πίσω" },
				{ "gelijkwaardigKnopToolTip" , "Εισαγωγή μίας ισοδύναμης έκφραση" },
				{ "opdrachtToolTip" , "Επιλογή προβλήματος" },
				{ "zelfKnopToolTip" , "Εισαγωγή της δικής σας έκφρασης \n και απλοποιήστε την." },
				
				
				{ "haakjesLabel0" , "  ανάπτυξη" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "   απλοποίηση" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  παραγοντοποίηση" },
				{ "wortelLabel0" , "  ρίζες" },
				{ "splitsLabel0" , "  διαχωρισμός" },
				{ "hulpKnopLabel" , "Βοήθεια" },
				{ "gelijkwaardigLabel0" , "  ίσο" },
				{ "gelijkwaardigLabel1" , "    με:" },
				{ "ofLabel" , "ή" },
				{ "enLabel" , "και" },
				{ "subLabel" , "Αντικατάσταση:" },
                { "meerLabel" , "περισσότερα" },
				
                { "klaarKnopLabel" , "Επιβεβαίωση" },
				{ "nakijkKnopLabel" , "Επιβεβαίωση" },
				{ "checkExternal" , "external check" },
				{ "eindeKnopLabel", "Τέλος" },
				{ "nakijkLabel1" , "Επιβεβαιωμένο: " },
				{ "nakijkLabel2" , " φορές " },
				{ "opnieuwKnopLabel" , "Ξανά" },
				{ "allesOpnieuwKnopLabel" , "Όλα ξανά" },
				{ "zelftoetsGeschiedenisKnopLabel", "score history"},
				{ "opdrachtLabel" , "Πρόβλημα:" },
				{ "paginaLabel" , "Σελίδα:" },
				{ "onderdeelLabel" , "Μέρος:" },
				{ "scoreLabel" , "Βαθμολογία:" },
				{ "score" , "Βαθμολογία: " },
				{ "totaal", "Συνολικά: " },
				{ "voortgang" , "Πρόοδος: "},
				{ "deelscores", "Μερική βαθμολογία"},
				{ "optiesButtonLabel" , "Επιλογές" },
				{ "standaardActiviteitNaam" , "Επίπεδο" },
				{ "standaardOpdrachtNaam" , "Πρόβλημα" },
				{ "opnieuwPanelTekstMW" , "Αν ξεκινήσετε από την αρχή θα χάσετε τη βαθμολογία σας.\n\nΕίστε σίγουροι ότι θέλετε να ξεκινήσετε ξανά;"},
				{ "opnieuwPanelTekst" , "Αν ξεκινήσετε από την αρχή θα χάσετε τη βαθμολογία σας.\n\nΕίστε σίγουροι ότι θέλετε να ξεκινήσετε ξανά;"},
				{ "opnieuwPanelTitel" , "Ξανά;"},
				{ "lockToetsCBLabel" , "Κλείδωμα του τεστ"},
				{ "lockToetsLabel" , "Κλειδωμένο τεστ"},
				{ "newPageMenuItem" ,  "New (insert)"},
				{ "deletePageMenuItem" ,  "Delete"},
				{ "copyPageMenuItem" ,  "Copy"},
				{ "cutPageMenuItem" ,  "Cut"},
				{ "pastePageMenuItem" ,  "Paste (insert)"},
				{ "insertCopyMenuItem" ,  "Copy (insert)"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
				{ "imagesButtonLabel", "Images"},
								
				{ "choiceOefenen" , "Εξάσκηση" },
				{ "choiceOefenenEindloos" , "Ατελείωτη εξάσκηση" },
				{ "choiceOefenenStraf" , "Παιχνίδι εξάσκησης" },
				{ "choiceZelfToets" , "Τεστ στον εαυτό μου" },
				{ "choiceEindToets" , "Τεστ" },
				
				{ "opdrachtTitelLabel" , "Τίτλος:" },
				{ "opdrachtTekstLabel" , "Κείμενο:" },
				{ "randVarLabel" , "Μεταβλητές για τυχαίες παραμέτρους:" },
				{ "startExpLabel" , "Start expression:" },
				{ "startVergLabel" , "Εκκίνηση εξίσωσης:" },
				{ "antwoordLabel" , "Μοντέλο απάντησης:" },
				{ "scoringLabel" , "Βαθμολόγηση της απάντησης:" },
				{ "puntenLabel" , "Βαθμοί:" },
				{ "checkTotaalLabel" , "Προσοχή! Συνολική βαθμολογία 10" },
				{ "gelijkwaardigCBLabel" , "Ισοδύναμο" },
				{ "herleidingCBLabel" , "Απλοποίηση" },
				{ "exactCBLabel" , "Ακριβώς" },
				{ "significantCBLabel" , "Significant" },
				{ "stappenCBLabel" , "με χρήση περισσοτέρων βημάτων" },
				{ "bewerkingKnoppenCBLabel" , "Κουμπιά λειτουργίας" },
				{ "bewerkingKnoppenExtraCBLabel" , "Επιπλέον κουμπιά λειτουργίας" },
                { "abcCBLabel" , "discr" },
				{ "subKnopCBLabel" , "subst." },
				{ "subKnopExtraCBLabel" , "subst. extended" },
				
				{ "grafiekToolCBLabel" , "Εργαλείο Γραφήματος" },
				{ "grafiekToolKnopLabel" , "Εργαλείο Γραφήματος" },
				{ "vergelijkingCBLabel" , "Εξίσωση" },
				{ "eindOplossingCBLabel" , "Χρειάζεται απάντηση" },
				{ "checkCBLabel" , "Checkable(ή όχι)" },
				{ "teltMeeCBLabel" , "Συμπεριλαμβάνεται στη βαθμολόγηση (ή όχι)" },
				{ "logCBLabel" , "logID" },
				{ "rmCBLabel" , "Υπολογιστής" },
				{ "pijlCBLabel" , "Βέλος" },
				{ "substitutiesButtonLabel" , "αντικαταστάσεις" },
				{ "functiesButtonLabel" , "defined functions" },
				{ "strategieVersieLabel" , "Strategy version" },
				{ "oefenVersieLabel" , "Strategy+ version" },
				{ "bordjesVersieLabel" , "Cover-up method version" },
				
				{ "herleidingKeuze_0" , "Καμία" },
				{ "herleidingKeuze_1" , "Polynom expanded and symplified" },
				{ "herleidingKeuze_2" , "Μια δύναμη" },
				{ "herleidingKeuze_3" , "Without negative or fractioned power" },
				{ "herleidingKeuze_4" , "Ένα κλάσμα" },
				{ "herleidingKeuze_5" , "Ένας λογάριθμος" },
				{ "herleidingKeuze_6" , "Written as simple log's (fe log(x)+log(3))" },
				
				{ "feedbackTekst01" , "Αυτό το βήμα περιέχει και σωστά και λανθασμένα μέρη. Αλλάξετε ή διαγράψτε τα μέρη που δεν είναι σωστά." },
				{ "feedbackTekst02" , "Δεν ικανοποιούν όλες οι λύσεις την αρχική εξίσωση. Διαγράψτε τη λύση ή τις λύσεις που δεν την ικανοποιούν." },
				{ "feedbackTekst03" , "Η ανίσωση έχει λυθεί σωστά." },
				{ "feedbackTekst04" , "Η εξίσωση έχει λυθεί σωστά." },
				{ "feedbackTekst05" , "Δώστε την κατάλληλη προσέγγιση." },
				{ "feedbackTekst06" , "Δώστε τις λύσεις της ανίσωσης." },
				{ "feedbackTekst07" , "Λείπουν λύσεις. Προσθέστε τη λύση ή τις λύσεις που λείπουν." },
				{ "feedbackTekst08" , "Μην χρησιμοποιείτε |- σύμβολα." },
				{ "feedbackTekst09" , "Η σύνταξη δεν είναι σωστή." },
				{ "feedbackTekst10" , "Η σύνταξη είναι σωστή, αλλά δεν είναι ακόμα στη σωστή μορφή." },
				{ "feedbackTekst11" , "Αυτή είναι μία σωστή προσέγγιση" },
				{ "feedbackTekst12" , "Η απάντηση είνα σωστή." },
				{ "feedbackTekst13" , "Η απάντηση είναι ισοδύναμη, αλλά δεν είναι ακόμα στη σωστή μορφή." },
				{ "feedbackTekst14" , "Η σύνταξη δεν είναι σωστή." },
                { "feedbackTekst15" , "Σωστή απάντηση." },
                { "feedbackTekst16" , "Είναι μια σωστή εξίσωση" },
                { "feedbackTekst17" , "Η εξίσωση δεν έχει ακόμα τη σωστή μορφή" },
                { "feedbackTekst18" , "Η απάντηση είναι σωστή, but the number of significant figures isn't right." },
                { "feedbackTekst19" , "The answer is correct, but doesn't have the right form and the number of significant figures isn't right." },
                { "feedbackTekst20" , "The answer is correct, number of significant figures is right, but doesn't have the right form." },
                { "xVarMessage1" , "Η ανεξάρτητη μεταβλητή είναι πάντα\n" 
									+ "ένα γράμαμ.\n " 
									+ "Σε περίπτωση αλφαριθμητικής μεταβλητής\n" 
									+ "ο πρώτος χαρακτήρας μίας αλφαρηθμητικής μεταβλητής\n" 
									+ "είναι πάντοτε γράμμα." },
				{ "xVarMessage2" , "Η ανεξάρτητη μεταβλητή μπορεί μόνο να \n" 
									+ "αναπαρίσταται από ένα γράμμα.\n" 
									+ "Μόνο όταν η επιλογή \"αλφαρηθμητικές μεταβλητές\" \n" 
									+ "έχει ενεργοποιηθεί, η ανεξάρτητη μπορεί να\n" 
									+ "αναπαρίσταται με περισσόετρα γράμματα." },
				{ "xVarMessage3" , "Το γράμμα e χρησιμοποιείται για  \n" 
									+ "την εκθετική συνάρτηση.\n" 
									+ "Αυτό το γράμμα δεν μπορεί να χρησιμοποιηθεί ως γράμμα για το όνομα\n" 
									+ "μίας ανεξάρτητης μεταβλητής." },									
				{ "xVarMessage4a" , "The tekst:  \"" },
				{ "xVarMessage4b" , "\" για τη γνωστή μαθηματική συνάρτηση \n," 
									+ "de betreffende wiskundige functie en mag dus"
									+ "οπότε δεν μπρορεί να χρησιμοποιηθεί για τη μεταβλητή"},
									
				{ "gelijkwaardigKnopLabelGR" , "Επόμενη Γραμμή" },
				{ "terugKnopLabelGR" , "Προηγούμενη γραμμή" },
				
				{ "editorVersieKnopLabel1" , "New editor version" },
				{ "editorVersieKnopLabel2" , "Old editor version" },
				
				{"antwoordVakLabel" , "πλαίσιο απάντησης"},
				{"interactieVakLabel" , "interactive component"},
				{"tekstVakLabel" , "πλαίσιο κειμένου"},
				{"grafiekComponentLabel" , "graph component"},
				
				
				
				{"interactieKeuzeLabel" , "Επιλέξτε τύπο "},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "Άκυρο"},
				{"sluitKnopLabel" , "Close"},
				{"verwijderKnopLabel" , "Remove"},
				{"wijzigKnopLabel" , "Change"},
				{"fileKnopLabel" , "File"},
				{"editUrlLabel" , "URL of image"},
				{"kiesAfbeeldingLabel" , "Choose an image"},
				{"afbeeldingenBeherenLabel" , "Manage images"},
				{"urlKnopLabel" , "URL"},
				{"bewerkenLabel" , "Edit"},
				{"toevoegenLabel" , "Add"},
				{"breedteLabel" , "Πλάτος:"},
				{"hoogteLabel" , "Ύψος:"},
				{"volleBreedteLabel" , "Πλήρες πλάτος"},
				{"popupLabel" , "Popup"},
				
				{"feedbackCBLabel" , "Feedback"},
				{"uitwCBLabel" , "Popup για βήματα"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "Your own"},
				{"feedbackLabel" , "feedback"},
				{"ideasButtonLabel" , "επιλογές"},
				{"substitutiesButtonLabel" , "αντικαταστάσεις"},
				{"antwoordmodelButtonLabel" , "πιθανή απάντηση"},
				{"formuleInvoerModeCBLabel" , "τρόπος εισαγωγής τύπου"},
				{"aantalKeuzesLabel" , "Αριθμός επιλογών"},
				{"aantalSelectieObjLabel" , "Number of selection objects"},
				{"randomPosLabel" , "Τυχαίες θέσεις"},
				{"meervSelectiesLabel" , "Πολλαπλές επιλογές είναι δνατές"},
				{"checkViaFormuleLabel" , "Επιβεβαίωση με χρήση τύπου"},
				{"aantalSleepObjLabel" , "Number of drag objects"},
				{"aantalDoelObjLabel" , "Number of target objects"},
				{"snapToTargetLabel" , "Snap to target object"},
				{"snapMargeLabel" , "Snap margin"},
				{"checkVasteDoelenLabel" , "Check on fixed targets for drag objects"},
				{"checkWaardeOpDoelLabel" , "Check using values of drag objects"},
				{"relocateCBLabel" , "Jumps back"},
				{"viewCBLabel" , "View"},
				{"aantalValueObjectenLabel" , "Αριθμός αντικειμένων"},
				{"checkAfzonderlijkLabel" , "Επιβεβαίωση χωριστά"},
				{"checkOpSamenhangLabel" , "Check in coherence"},
				{"boxMetRand" , "Box"},
				{"keuzeVakKiesLabel" , "Επιλογή"},
				{"verzamelDoelCBLabel" , "targetobject as collection area"},
				{"scoreCumulatiefCBLabel","Score cumulative"},
				
				{"vormCBLabel" , "Μορφή"},
				{"formuleToolCBLabel" , "Συντάκτης ειαγωγής τύπου"},
				{"goedLabel" , "Σωστό"},
				{"doorLabel" , "Συνέχισε"},
				{"foutLabel" , "Λάθος"},
				{"halfLabel" , "Μισό"},
				
				{"geenOplossingen" , "καμία λύση"},
				{"allesOplossing" , "όλα είναι λύση"},
				{"antwoordModelGeen" , "κανένα"},
				{"abc" , "discr"},
				
				{"checkExternalCBLabel" , "check external"},
				{"contextVarCBLabel", "Use contextvariables"},
				{"rmAantalDecLabel", "Number of decimals"},
				
				{"FEV_titleStartLabel", "Start expression"},
				{"FEF_titleStartLabel", "Start equation"},
				{"FEV_titleAntwoordLabel", "Correct answer"},
				{"FEV_titleAntwoordNrLabel", "Answer"},
				{"FEV_titleContextLabel", "Context variables"},
				{"FEV_titleFeedbackLabel", "Feedback text"},
				{"FEV_titleVerificatieLabel", "Verificaton"},
				{"FEV_titleHulpLabel", "Help solving"},
				{"FEV_titleOpmaakLabel", "Layout"},
				{"FEV_titleLoggingLabel", "Logging / checking"},
				{"FEV_titleScoringLabel", "Score"},
				{"FEV_titleVormLabel", "Correct forms"},
				
				// TekstVakInteractiePanel
				{"titleFormuleAntwVakLabel" , "Settings formula answer box with steps"},
                {"titleVergelijkingAntwVakLabel" , "Settings equation answer box with steps"},
                {"titleSimpelFormuleAntwVakLabel" , "Settings small formula answer box"},
                {"titleSimpelVergelijkingAntwVakLabel" , "Settings small equation answer box"},	
				{"formuleAntwVakLabel" , "Πλαίσιο απάντησης για τύπο με βήματα"},
                {"vergelijkingAntwVakLabel" , "Πλαίσιο απάντηση για εξίσωση με βήματα"},
                {"simpelFormuleAntwVakLabel" , "Μικρό πλαίσιο απάντησης για τύπο"},
                {"simpelVergelijkingAntwVakLabel" , "Μικρό πλαίσιο απάντησης για εξίσωση"},
                {"tekstAntwVakLabel" , "Πλαίσο κειμένου-απάντησης"},
                {"algebraPijlenLabel" , "Αλγεβρικά βέλη"},
                {"blokkenbouwenLabel" , "Κατασκευή με blocks"},
                {"stroomdiagrammenLabel" , "Διαγράμματα ροής"},
                {"grafiekenToolLabel" , "Εργαλείο Γραφήματος"},
                {"tekstVakLabelH" , "Πλαίσιο κειμένου"},
				{"geogebraIpLabel" , "Geogebra 4 (coming soon)"},
				{"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "Ισορροπία με φρούτα"},
				{"checkSelectieUnitLabel" , "Check selection unit"},
				{"checkTekstAntwoordVakLabel" , "Check-text answer box"},
				{"keuzeAntwoordVakLabel" , "Choice answer box"},
				{"doorzienIpLabel" , "3D construction-component"},
				{"checkSleepUnitLabel" , "Check drag/drop unit"},
				{"vergrotenIpLabel" , "PE Enlargement"},
				{"vangenIpLabel" , "PE Catching"},
				{"verknippenIpLabel" , "PE Cutting"},
				{"geomAlgebra2dIpLabel" , "Geom.algebra 2d"},
				{"geomAlgebra1dIpLabel" , "Geom.algebra 1d"},
				{"normaleVerdelingIpLabel" , "Normal distribution"},
				{"mp3PlayerIpLabel" , "Mp3-player"},
				{"binominaleVerdelingIpLabel" , "Binominal distribution"},
				{"getallenlijnIpLabel" , "Numberline (jump)"},
				{"tekenVeelvlakIpLabel" , "Drawing in space"},
				{"mozaikIpLabel" , "Mozaik"},
				{"veelvlakkenIpLabel" , "Πολύεδρα"},
				{"eerlijkVerdelenIpLabel" , "PE Equal sharing"},
				{"statistiekIpLabel" , "[test] Statistical representations"},
				{"stroomdiagrammenIpLabel" , "[δοκιμή] Διαγράμματα ροής Νέο"},
				{"tegelsIpLabel" , "Tilings"},
				{"checkWaardeUnitLabel" , "[test] Check value unit"},
				{"omtrekAppletIpLabel" , "PE circumference applet"},
				{"algebraExpressiesIpLabel" , "[test] Algebra trees"},
				{"oppervlakteAlgebraIpLabel" , "[test] Area algebra"},
				{"blokkenProgrammaIpLabel" , "[test] Block programs"},
				{"grafieken3DIpLabel" , "[test] Graphs 3D"},
				{"spotProblemsIpLabel" , "[test] Spot problems"},
				{"kladjeIpLabel" , "[test] Note"},
				{"kansbomenIpLabel" , "[test] Probability trees"},
				{"rekenmachineIpLabel" , "[test] Calculator"},
				{"formStructIpLabel" , "[test] FormStruct"},
				{"graphToolIpLabel" , "[test] GraphTool"},
				{"draabankIpLabel" , "[test] Turning lathe"}, 
				{"waarmakersIpLabel" , "[test] Truemakers"},
				{"statSimIpLabel" , "[test] Statistics Simulations"},
				{"stelselVakLabel", "[test] Stelsel-antwoordvak"},
	            {"javaLogoIpLabel", "JavaLogo"},
	            {"symboolIpLabel", "Symbol"},
                {"samengesteldeStappenIpLabel", "Composite steps"},
                {"checkButtonIpLabel", "Check button"},
                {"sliderIpLabel", "Slider"},
                {"heksIpLabel", "Witch"},
                {"geoDefinerIpLabel", "GeoDefiner"},
                {"javaLogo3DIpLabel", "Programming JavaLogo 3D"},

                {"checkButtonsMenuLabel", "Check buttons"},
                
                {"kiesKoppelingLabel", "Choose linkage"},
                {"koppelingLabel", "Linkage"},
                {"popupTitelLabel", "Title"},

	            //CheckButtonEditor
                {"CB_kijkNaOptieLabel", "Check" },
                {"CB_bewaarOptieLabel", "Save" },
                {"CB_rondAfOptieLabel", "set completed" },
                {"CB_nextPageOptieLabel", "To next page" },
                {"CB_eigenVakOptieLabel","All in same box"},
                {"CB_opPaginaOptieLabel","All on page"},
                {"CB_viaXWidgetOptieLabel","All connected via x-widget"},
                
				
				//InstellingenPanel
				{"OPT_wiskundeLabel" , "Μαθηματικά"},
                {"OPT_navigatieLabel" , "Πλοήγηση"},
                {"OPT_layoutLabel" , "Layout"},
                {"OPT_nakijkenLabel" , "Επιβεβαίωση επιλογών"},
				{"OPT_vermenigvTeken" , "Σύμβολο πολλαπλασιασμού: X"},
				{"OPT_woordformules" , "Word variables "},
				{"OPT_tweeHoofdletterVars" , "Μεταβλητές όπως AB, BC κτλ."},
				{"OPT_tempoToets" , "Restricted time"},
				{"OPT_opnieuwKnop" , "'All again'-button"},
				{"OPT_itemOpnieuwKnop" , "'Item again'-button"},
				{"OPT_checkPerOpdracht" , "Επιβεβαίωση ανά σελίδα"},
				{"OPT_hoekInGraden" , "Μονάδα γωνίας: μοίρες"},
				{"OPT_opdrachtBolletjes" , "Επιλογέας αντικειμένων"},
				{"OPT_volgendeKnop" , "Κουμπί επόμενου"},	
				{"OPT_VorigeKnop" , "Κουμπί προηγούμενου"},
				{"OPT_paginaIpvOpdracht" , "Label: 'Page' instead of 'Problem'"},
				{"OPT_fontFormaat" , "Μέγεθος"},
				{"OPT_fontNaam" , "Βασική Γραμματοσειρά"},
				{"OPT_tijdsLimiet" , "Όριο χρόνου (sec)"},
				{"OPT_formTimes" , "Οι τύποι σε γραμματοσειρά Times Roman"},
				{"OPT_navigatieFormaat" , "Μέγεθος γραμμής πλοήγησης"},
				{"OPT_margesLabel" , "Περιθώρια:"},
				{"OPT_margeLinksLabel" , "Αριστερά"},
				{"OPT_margeRechtsLabel" , "Δεξιά"},
				{"OPT_margeBovenLabel" , "Πάνω"},
				{"OPT_margeOnderLabel" , "Κάτω"},
				{"OPT_fToets" , "F-πλήκτρα για τύπους"},
				{"OPT_globalParam" , "Γενικές παράμετροι"},
				{"OPT_voortgangKnop", "'Πρόοδος' αντί για 'Σύνολο'"},
				{"OPT_conditionalNav" , "Πλοήγηση με προϋποθέσεις"},
				{"OPT_conditionalPercLabel" , "Ποσοστό"},
				{"OPT_voorwaarden", "Πορϋποθέσεις ανά σελίδα"},
				{"OPT_allesCorrect", "Επόμενη σελίδα αν όλα είναι σωστά (πράσινο)"},
				{"OPT_deelOpdr" , "Item numbers a,b,c etc"},
				{"OPT_zelftoetsGeenCorr" , "No correction self test"},
				{"OPT_eerderGeenCorr" , "Καμία διόρθωση σε προηγούμενες σελίδες"},
				{"OPT_zelftoetsGeschiedenis" , "self-test history"},
				{"OPT_zelftoetsHighScore" , "highscore"},
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_significantie" , "Check option significant numbers"},
				{"OPT_objectives" , "Στόχοι"},
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_fontOvererving" , "Font-inheritance text boxes"},
				{"OPT_fontOverervingForm" , "Font-inheritance formula boxes"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Use styles"},
				{"OPT_importStyles" , "Import"},
				{"OPT_exportStyles" , "Export"},
				{"OPT_layers" , "Use layers"},
				{"OPT_pageLabel" , "Page:"},
                {"OPT_docWidthLabel" , "Page: Width"},
                {"OPT_docHeightLabel" , "Height (min)"},
                {"OPT_combCompNav" , "Combined components"},
                {"OPT_stylesWarnDialog" , "All styles will be lost. Ok?"},
                
                {"OPT_styleInteractionsLabel" , "Style answerboxes"},
                {"OPT_TemplateBasisLabel" , "Template Basic style"},
                {"OPT_TemplateNumworxLabel" , "Template Numworx style"},
				
				{"OBJ_leerdoel", "Στόχος"},
				{"OBJ_categorie", "Κατηγορία"},
				{"OBJ_categorieBox", "Στόχοι σε πολλαπλές κατηγορίες"},
				{"OBJ_kolomMeerButton", "Προσθήκη στήλης"},
				{"OBJ_kolomMinderButton", "Αφαίρεση στήλης"},
				{"MCC_misconception", "Misconception"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "Μεταβλητές των συναρτήσεων"},
				{"GEP_assenLabel" , "Εμφάνιση αξόνων"},
				{"GEP_grafiekOptiesLabel" , "Επιλογές εργαλείου γραφήματος"},
				
				{"GEP_varXLabel" , "Μεταβλητή χ άξονα"},
				{"GEP_varYLabel" , "Μεταβλητή y άξονα"},
				
				{"GEP_assenOptie" , "Άξονες"},
				{"GEP_roosterOptie" , "Grid"},
				{"GEP_roosterGrofOptie" , "wide"},
				{"GEP_schaalverdelingOptie" , "Axis numbers"},
				{"GEP_piOptie" , "Grid for Pi"},				
				
				{"GEP_zoomOptie" , "Zoom-option"},
				{"GEP_traceOptie" , "Trace-option"},
				{"GEP_dragOptie" , "Drag-option"},
				{"GEP_tekenOptie" , "Graph-drawing tool"},
				
				{"GEP_tabelOptie" , "Table-tool"},
				{"GEP_zoomInTabelOptie" , "Zoom in στον πίνακα"},
				{"GEP_tabelTekenToolOptie" , "Ο πίνακας ως εργαλείο ζωγραφικής"},

				{"GEP_functieEditOptie" , "Επεξεργαστής συναρτήσεων"},
				{"GEP_grafiekKleurenOptie" , "Διαφορετικά χρώματα"},
				
				{"GEP_formeleFunctieNotatieOptie" , "Επίσημος συμβολισμός συναρτήσεων f(x), g(x) κτλ."},
				
				{"GEP_popupWeergave" , "Εμφάνιση μέσα από pop-up"},
				
				{"GEP_xPositief" , "x θετικό"},
				{"GEP_yPositief" , "y θετικό"},
				{"GEP_xEditable" , "x επεξεργάσιμο"},
				{"GEP_yEditable" , "y επεξεργάσιμο"},
				
				
				{"GEP_opdrachten" , "εργασίες"},
				
				{"GEP_kiesOpdracht" , "επιλογή είδους εργασίας"},
				{"GEP_opdracht1" , "βρείτε τον τύπο για μια δεδομένη γραμμή του γραφήματος"},
				{"GEP_opdracht2" , "find the formula for a number of graph points"},
				{"GEP_opdracht3" , "draw a number of points for a given formula"},
				{"GEP_opdracht4" , "draw the points from the table in the graph"},
				
				{"GEP_antwoordFormule" , "enter the solution formula in the function editor below"},
				{"GEP_tabelPuntenX" , "enter the x-values of the graph points in the table below" },
				{"GEP_tabelPunten" , "enter the points in the table below" },
				
				{"GEP_nauwkeurigheid" , "Ακρίβεια (pixels)"},
				{"GEP_minimumPunten" , "Ελάχιστος αριθμός σημείων"},
				{"GEP_maximumScore" , "Μέγιστη βαθμολογία"},
				{"GEP_leerlingZietTabel" , "Pupil can see table"},
				
				{"GE_kijkNa" , "Επιβεβαίωση" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "Κείμενο"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "Πλάτος παραθύρου"},
				{"LEP_vensterHoogte" , "Ύψος παραθύρου"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "Προσθήκη"},
				{"IEP_verwijderen" , "Αφαίρεση"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "Άκυρο"},
				{"editImageKnopLabel" , "Image checkButton"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "Περιθώριο"},
				{"TVEP_achtergrondKleurAanwezig" , "Χρώμα παρασκηνίου"},
				{"TVEP_zwevend" , "Floating above text"},
				{"TVEP_anderFont" , "Άλλη γραμματοσειρά"},
				{"TVEP_rondingHoeken" , "Στρογγύλεμα γωνιών"},
				{"TVEP_rotatieHoek" , "Γωνία περιστροφής"},
				{"TVEP_centreerHor" , "Οριζόντιο κεντράρισμα"},
				{"TVEP_centreerVert" , "Κάθετο κεντράρισμα"},
				{"TVEP_pasAanH" , "Προσαρμογή ύψους"},
				{"TVEP_pasAanB" , "Προσαρμογή πλάτους"},
				{"TVEP_aantalRijen" , "Αριθμός σειρών"},
				{"TVEP_aantalKolommen" , "Αριθμός στηλών"},
				{"TVEP_tabelRanden" , "Περιγράμματα πίνακα"},
				{"TVEP_celMarge" , "Αριστερό περιθώριο"},
				{"TVEP_bovenMarge" , "Περιθώριο πάνω"},
				{"TVEP_fontType" , "Γραμματοσειρά"},
				{"TVEP_achtergrondKleur" , "Χρώμα"},
				{"TVEP_interlinie" , "Διάστιχο μεταξύ γραμμών"},
				{"TVEP_cellSpaceColumn" , "Κενό"},
				{"TVEP_cellSpaceRow" , "Κενό"},
				{"TVEP_layoutLabel" , "Περίγραμμα πλαισίου κειμένου"},
				{"TVEP_gebruikersInteractieLabel" , "User interaction"},
				{"TVEP_selectieObject" , "Επιλογή αντικειμένου"},
                {"TVEP_selectieKleur" , "Χρώμα"},
                {"TVEP_selectieKleurKnopLabel" , "Selection color"},
                {"TVEP_sleepObject" , "Σύρσιμο αντικειμένου"},
                {"TVEP_draaiObject" , "Rotating object"},
                {"TVEP_sleepDoel" , "Σύρσιμο στόχου"},
                {"TVEP_sleepHandle" , "χειρισμός"},
                {"TVEP_selectieSleepWaarde" , "τιμή    ("},
                {"TVEP_fgKleurKnopLabel" , "χρώμα"},
                {"TVEP_zichtbaarNaNakijken" , "Visible after check test"},
                {"TVEP_balansVergCom" , "Balance-Equation box communication"},
                {"TVEP_aftrekPopup" , "Decrease score using popup"},
                {"TVEP_callOut" , "Call out box"},
                {"TVEP_vulHoogte" , "Fill height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "Βήματα"},
                {"TVEP_random" , "random"},
                {"TVEP_linkObject" , "Σύνδεση αντικειμένου"},
                {"TVEP_editLink" , "Επεξεργασία σύνδεσης"},
                {"TVEP_defaultBijNull" , "εξ ορισμού  )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
                {"TVEP_noStyleChoiceLabel", "No Style"},
                {"TVEP_styleSettingsLabel", "Settings"},
                {"TVEP_stylesLabel", "Style:"},
                {"TVEP_editStylesButton", "Edit"},
                
                {"TVEP_lineText_OpmaakTekst", "Layout text"},
                {"TVEP_lineText_OpmaakVak", "Layout box"},
                {"TVEP_lineText_OpmaakTabel", "Layout table"},
                {"TVEP_lineText_OpmaakExtra", "Layout extra"},
                {"TVEP_lineText_InteractieKenmerken", "Interaction attributes"},
                {"TVEP_lineText_InteractieSoorten", "Interaction types"},
                {"TVEP_lineText_InteractieVerwerking", "Interaction processing"},
                
                {"TVEP_respToggleWidthLabel", "minimum total width"},
                {"TVEP_respMinLabel", "min"},
                {"TVEP_respMaxLabel", "max"},
                {"TVEP_respConstantLabel", "constant"},
                {"TVEP_respFactorLabel", "factor"},
                
                //Style Manager
                {"SM_titelLabel", "Manage Styles"},
                {"SM_addStyleButton", "Save settings as new style"},
                {"SM_saveStyleButton", "Save style"},
                {"SM_removeStyleButton", "Remove style"},
                {"SM_closeButton", "Close"},
                {"SM_addStyleAction", "Give style name"},
                
              //Text Editor tooltips
                {"TE_formuleButtonTooltip", "Add Formula"},
                {"TE_graphButtonTooltip", "Add graph tool"},
                {"TE_linkButtonTooltip", "Add link"},
                {"TE_imageButtonTooltip", "add image"},
                {"TE_answerboxButtonTooltip", "add answer box"},
                {"TE_widgetButtonTooltip", "Add widget"},
                {"TE_geogebraButtonTooltip", "Add GeoGebra"},
                {"TE_tekstVakButtonTooltip", "Add text box"},
                {"TE_compositeButtonTooltip", "Add composite component"},
                {"TE_templateCompButtonTooltip", "Add component with template skin"},
                {"TE_templateButtonTooltip", "Choose template page"},
                {"TE_x-widgetButtonTooltip", "Cross-widget connections"},
                {"TE_parameterButtonTooltip", "Use random parameters"},
                {"TE_opsommingButtonTooltip", "Add list"},
                {"TE_vormenButtonTooltip", "Add shape"},
				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "Αποθήκευση επιλογής"},
				{"GEP_alsTool" , "Ως εργαλείο"},
				{"GEP_rand" , "Περίγραμμα"},
				{"GEP_resetIcon" , "Επαναφορά επιλογών"},
				{"GEP_checkMetCheckDWO" , "Using checkDWO"},
				{"GEP_checkMetObjecten" , "Χρήση αντικειμένων που έχουν δημιουργηθεί"},
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "Ελάχιστη τιμή"},
				{"GSEP_maxValue" , "Μέγιστη τιμή"},
				{"GSEP_eenheden" , "Μονάδες ορατές"},
				{"GSEP_getallen" , "Αριθμοί"},
				{"GSEP_10tallen" , "Mark for tens"},
				{"GSEP_5tallen" , "Marh for fives"},
				{"GSEP_nul" , "Μηδέν"},
				{"GSEP_pijl" , "Βέλος ορατό"},
				{"GSEP_pijlTerug" , "Βέλος πίσω"},
				{"GSEP_horizontaal" , "Οριζόντια"},
				{"GSEP_eenheid" , "Μονάδα"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "Γραμμή μενού"},
				{"TEEP_rekenToolOptie" , "Υπολογιστής"},
				{"TEEP_grafToolOptie" , "Εργαλείο γραφήματος"},
				{"TEEP_titleStartLabel", "Tekst-answer-box"},
				{"TEEP_checkDocentCBLabel", "Check (by teacher)"},
				{"TEEP_maxScoreLabel", "Maximum score"},
				{"TEEP_editorOptiesLabel", "Editor options"},
				
				//Ideas
				
				{"ideasTip",		"στοιχείο βοήθειας"},
				{"ideasHelp",		"βοήθεια"},
				{"ideasStap",		"βήμα"},
				{"ideasLosop",		"επίλυση"},
				{"ideasWordtDan",		"γίνεται"},
				
				{"algebra.equations.coverup.denominator"		,"cover up the denominator"	},
				{"algebra.equations.coverup.minus-left"			,"μετακινείστε τις σταθερές στα δεξιά"	},
				{"algebra.equations.coverup.minus-right"		,"use the coverup method"	},
				{"algebra.equations.coverup.negate"				,"διαίρεση με -1"	},
				{"algebra.equations.coverup.numerator"			,"cover up the nominator"	},
				{"algebra.equations.coverup.plus"				,"μετακινειστε τις σταθερές στα δεξιά"	},
				{"algebra.equations.coverup.power"				,"χρήση της τετραγωνικής ρίζας"	},
				{"algebra.equations.coverup.sqrt"				,"βάλτε και τις δύο πλευρές στο τετράγωνο"	},
				{"algebra.equations.coverup.times"				,"απομονώστε τη μεταβλητή με διαίρεση και στις δύο πλευρές"	},
				{"algebra.equations.coverup.times-positive"		,"απομονώστε τη μεταβλητή με διαίρεση και στις δύο πλευρές"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"move constant terms to the right by adding a number to both sides"	},
				{"algebra.equations.coverup.onevar.plus"		,"move constant terms to the right by subtracting a number from both sides"	},
				
				{"algebra.equations.linear.distr-times"		,"αφαιρέστε τις παρενθέσεις"	},
				{"algebra.equations.linear.flip"			,"swap the equation"	},
				{"algebra.equations.linear.merge"			,"simplify by taking expression together or calculation"	},
				{"algebra.equations.linear.remove-div"		,"αφαιρέστε τα κλάσματα με πολλαπλασιασμό με έναν αριθμό"	},
				{"algebra.equations.linear.var-left"		,"μετακίνείστε τις μεταβλητές στα αριστερά"	},
				
				{"algebra.equations.buggy.cancel-minus"				,"δεν μπορείτε να διαγράψετε όρους επειδή δεν έχουν το ίδιο πρόσημο"	},
				{"algebra.equations.buggy.distr-times-denom"		,"σφάλμα στην αφαίρεση παρενθέσεων: ένας από τους όρους είναι κλάσμα, και ο factor έχει πολλάπλασιαστεί με τον αριθμητή του κλάσματος."	},
				{"algebra.equations.buggy.distr-times-plus"			,"όταν αφαιρέθηκαν οι παρενθέσεις, ένα όρος δεν πολλαπλασιάστηκε"	},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"όταν αφαιρέθηκαν οι παρενθέσεις, ξεχάστηκε ένας όρος"	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"θυμηθείτε τα πρόσημα όταν αφαιρείτε παρενθέσεις"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"όταν αφαιρείτε παρενθέσεις, πολλαπλασιάστε μόνο τους όρους μέσα στις παρενθέσεις"	},
				{"algebra.equations.buggy.divide-negate"			,"προσοχή στο πρόσημο όταν διαιρείτε"	},
				{"algebra.equations.buggy.divide-numdenom"			,"αντιστροφή κλάσματος. Think about the number you have to use for dividing"	},
				{"algebra.equations.buggy.flip-negate-one-side"		,"χρειάζετε να αλλάζετε το πρόσημο και τις δύο πλευρές"	},
				{"algebra.equations.buggy.multiply-one-side"		,"χρειάζετε να πολλαπλασιάσετε και τις δύο πλευρές"	},
				{"algebra.equations.buggy.minus-minus"				,"όταν αφαιρείτε παρανθέσεις: ο πολλαπλασιασμός δύο αρνητικών αριθμών δίνει ένα θετικό"	},
				{"algebra.equations.buggy.multiply-forget-one"		,"ξεχάσατε έναν όρο όταν πολλαπλασιάσατε και τις δύο πλευρές"	},
				{"algebra.equations.buggy.negate-all"				,"ξεχάσατε έναν όρο όταν αλλάξατε πρόσημο"	},
				{"algebra.equations.buggy.negate-one-side"			,"one of the sides has been forgotten when changing the sign"	},
				{"algebra.equations.buggy.plus"						,"think about the sign when you move a term from one side to the other"	},
				{"algebra.equations.buggy.priority-times"			,"remember rules for priorities and parentheses"	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"in the square formula D=b^2-4ac and not D=b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"not the negation in front of b: "	},
				{"algebra.equations.buggy.abc.one-solution"				,"there is a second solution"	},
				{"algebra.equations.buggy.abc.two-a"					,"divide by 2a and not a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"you have forgotten the other (negative) square root"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"before taking square roots you need to perform another action"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"before taking square roots you need to perform another action"	},
				{"algebra.equations.buggy.coverup.square-minus"			,"δεν μπορείτε να βάλετε ρίζα σε έναν αρνητικό αριθμό"	},
				{"algebra.equations.buggy.coverup.times-mul"			,"αντί για να διαιρείτε την δεξιά πλευρά, την πλλαπλασιάζετε"	},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"όταν διαιρείτε, χρειάζεται να διαιρείτε όλους τους όρους"	},
				{"algebra.equations.buggy.distr-square"					,"when taking the square of two terms you have forgotten the two cross products"	},
				{"algebra.equations.buggy.distr-square-forget"			,"when taking the square of two terms you have forgotten one of the terms"	},
				{"algebra.equations.buggy.square-multiplication"		,"incorrect square of two terms"	},
				{"algebra.equations.buggy.division-by-var-both"		,"when dividing by a variable you lose the solution var=0"	},
				{"algebra.equations.buggy.division-by-var-zero"		,"when dividing by a variable you lose the solution var=0"	},
				
				{"algebra.equations.linear.balance.collect"			,"συνδυάστε"	},
				{"algebra.equations.linear.balance.calculate"		,"υπολογίστε"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"γράψτε τη διαίρεση ώς πολλαπλασιασμό με κλάσμα"	},
				{"algebra.equations.linear.balance.smart-div"		,"divide by a common factor"	},
				{"algebra.equations.linear.balance.con-right-minus"	,"αφαιρέστε {?} και από τις δύο πλευρές"	},
				{"algebra.equations.linear.balance.con-left-minus"	,"αφαιρέστε {?} και από τις δύο πλευρές"	},
				{"algebra.equations.linear.balance.var-right-minus"	,"αφαιρέστε {?} και από τις δύο πλευρές"	},
				{"algebra.equations.linear.balance.var-left-minus"	,"αφαιρέστε {?} και από τις δύο πλευρές"	},
				{"algebra.equations.linear.balance.con-right-plus"	,"προσθέστε {?} και στις δύο πλευρές"	},
				{"algebra.equations.linear.balance.con-left-plus"	,"προσθέστε {?} και στις δύο πλευρές"	},
				{"algebra.equations.linear.balance.var-right-plus"	,"προσθέστε {?} και στις δύο πλευρές"	},
				{"algebra.equations.linear.balance.var-left-plus"	,"προσθέστε {?} και στις δύο πλευρές"	},
				{"algebra.equations.linear.balance.distribute"		,"αφαιρέστε παρενθέσεις"	},
				{"algebra.equations.linear.balance.remove-div"		,"πολλαπλασιάστε και τις δύο πλευρές με {?}"	},
				{"algebra.equations.linear.balance.scale-to-one"	,"διαιρέστε και τις δύο πλευρές με {?}"	},
				{"algebra.equations.linear.balance.negate"    ,"αλλάξτε το πρόσημο και στις δύο πλευρές"  },
				{"algebra.equations.linear.balance.intro-false"    ,"αδύνατο"  },
				{"algebra.equations.linear.balance.intro-true"    ,"πάντοτε αληθές"  },
                
               
				{"algebra.equations.quadratic.abc"				,"use the quadratic formula"	},
				{"algebra.equations.quadratic.approx"			,"approximate"	},
				{"algebra.equations.quadratic.cancel"			,"remove expressions from both sides of the =-symbol"	},
				{"algebra.equations.quadratic.common-factor"	,"factorize using the common factor"	},
				{"algebra.equations.quadratic.distr-div"		,"διαιρέστε"	},
				{"algebra.equations.quadratic.distr-square"		,"υπολογίστε το τετράγωνο"	},
				{"algebra.equations.quadratic.left-square"		,"γράψτε την αριστερή πλευρά ώς τετράγωνο"	},
				{"algebra.equations.quadratic.move-left"		,"μετακινείστε τα πάντα αριστερά"	},
				{"algebra.equations.quadratic.nice-factors"		,"factorize the three expressions"	},
				{"algebra.equations.quadratic.no-lin"			,"write as square=number"	},
				{"algebra.equations.quadratic.prepare-split"	,"complete to a square"	},
				{"algebra.equations.quadratic.product-zero"		,"product=0, equate factors to 0"	},
				{"algebra.equations.quadratic.same-con-factor"	,"διαιρέστε και τις δύο πλευρές με έναν κοινό παρονομαστή"	},
				{"algebra.equations.quadratic.same-factor"		,"το Α*Β=Α*Γ υπονοεί ότι A=0 ή Β=Γ"	},
				{"algebra.equations.quadratic.simpler-poly"		,"απλοποιήστε διαιρώντας με κοινό παρονομαστή"	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"απλοποιείστε τις τετραγωνικές ρίζες"	},
				{"algebra.equations.quadratic.square-both"		,"βάλτε στο τετράγωνο και οι δύο πλευρές"	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"apply the substitution backwards"	},
				{"algebra.equations.polynomial.expose-factor"		,"απονομώστε τον κοινό παράγοντα"	},
				{"algebra.equations.polynomial.power-factors"		,"κοινός παράγοντας x"	},
				{"algebra.equations.polynomial.subst"				,"use substitution"	},
				{"algebra.equations.polynomial.def-power-nat"   	,"γράψτε τη δύναμη ώς συνεχόμενο πολλαπλασιασμό"},
				
				
				{"algebra.equations.rational.check-solution"	,"επιβεβαίωση της λύσης"	},
				{"algebra.equations.rational.cross-multiply"	,"πολλαπλασιάστε χιαστί"	},
				{"algebra.equations.rational.division-one"		,"όταν το κλάσμα είναι=1 έχουμε αριθμητή = παρονομαστή"	},
				{"algebra.equations.rational.division-zero"		,"όταν το κλάσμα είναι=0 έχουμε αριθμητή=0 (αν ο παρονομαστής δεν είναι μηδέν)"	},
				{"algebra.equations.rational.multiply-one-div"	,"πολλάπλασιάστε και τις δύο πλευρές με τον παρονομαστή του κλάσματος"	},
				{"algebra.equations.rational.same-dividend"		,"το Α/Β=Α/Γ υπονοεί ότι Α=0 ή Β=Γ"	},
				{"algebra.equations.rational.same-divisor"		,"οι παρονομαστές είναι ίδιοι, εξισώστε τους αριθμητές"	},
				
				{"algebra.inequalities.flip-sign"		,"αλλάξετε το σύμβολο"	},
				{"algebra.inequalities.give-solution"	,"λύστε την ανίσωση"	},
				{"algebra.inequalities.to-equation"		,"μετατρέψετε την πρώτα σε εξίσωση"	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"πολλαπλασιάστε τις δυνάμεις προσθέτοντας τους εκθέτες"	},
				{"algebra.manipulation.exponents.factor-as-power"		,"write (parts) as a power"	},
				{"algebra.manipulation.exponents.mul-exponents"			,"μια δύναμη σε δύναμη: πολλαπλασιάστε τους εκθέτες"	},
				{"algebra.manipulation.exponents.reciprocal"			,"write 1/expression as expression^-1"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"write as a power by adding exponents"	},
				{"algebra.manipulation.exponents.sub-exponents"			,"divide the powers by subtracting the exponents"	},
				{"algebra.manipulation.exponents.write-as-power"		,"write as power"	},
				{"algebra.manipulation.exponents.distr-power"			,"use power of a product is a product of powers"	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"write the power expression^-1 as a fraction: 1/expression"	},
				{"algebra.manipulation.exponents.write-as-root"			,"write as square root"	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"write 1/power as another power in which the sign of the exponent has changed"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"move the negation out of the power (when exponent is odd)"	},
				{"algebra.manipulation.exponents.root"					,"give square root"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"η δύναμη=1 υπονοεί εκθέτης=0"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"ίδιος αριθμός βάσης"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"approximate this power or square root"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"κοινή δύναμη"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"γράψτε χρησιμοποιώντας τηε μέγιστη κοινή δύναμη"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"ν-στή τετραγωνική ρίζα"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		,"use the definition glog(x)=a implies x=g^a"	},
				
				{"calculus.differentiation.deriv-of-poly"		,"differentiate a power function"	},
				{"calculus.differentiation.min"		,"apply the rule for subtraction"	},
				{"calculus.differentiation.negate"		,"move the negation out before differentiating"	},
				{"calculus.differentiation.plus"		,"apply the sum rule"	},
				{"calculus.differentiation.product"		,"apply the product rule"	},
				{"calculus.differentiation.quotient"		,"apply the quotient rule"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"αφαιρείτε {?} από τα αριστερά αλλά προσθέτετε {?} στα δεξιά"	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"προσθέτετε {?} στα αριστερά αλλά αφαιρείτε {?} από τα δεξιά"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"αφαιρείτε {?} από τα δεξιά αλλά προσθέτετε {?} στα αριστερά"	},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"προσθέτετε {?} στα δεξιά άλλα αφαιρείετε {?} από τα αριστερά"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"you subtract {?} από τα αριστερά αλλά δεν το κάνετε αυτό από τα δεξιά"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"προσθέτετε {?} στα αριστερά αλλά δεν το κάνετε αυτό στα δεξιά"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"αφαιρείτε {?} από τα αριστερά αλλά προσθέτετε {?} στα δεξιά"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"προσθέτετε {?} στα αριστερά αλλά αφαιρείτε {?} από τα δεξιά"} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"αφαιρείτε {?} από τα δεξιά αλλά προσθέτετε {?} στα αριστερά"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"προσθέτετε {?} στα δεξιά αλλλά αφειρείτε {?} από αριστερά"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"αφαιρείτε {?} από τα δεξιά αλλά δεν το κάνετε αυτό από τα αριστερά"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"προσθέτετε {?} στα δεξιά αλλά δεν το κάνετε αυτό στα αριστερά"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"αφαιρείτε {?} από τα αριστερά αλλά δεν το κάνετε αυτό στα δεξιά"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"προσθέτετε {?} στα αριστερά αλλά δεν το κάνετετε αυτό στα δεξιά"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"αφαιρείτε {?} από τα δεξιά αλλά δεν το κάνετε από τα αριστερά"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"προσθέτετε {?} στα δεξιά αλλά δεν το κάνετε στα αριστερά"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"not only have you swapped the left and right-hand sides, but also changed the sign in one side"	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"αφαιρείτε στα δεξιά, κάνετε το ίδιο και στα αριστερά;"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"πολλαπλασιάζετε με έναν αριθμό multiply with a number, but not the complete left-hand side"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"you negate, but not the complete left-hand side"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"διαιρείτε με έναν αριθμό, αλλά όχι ολόκληρη την αριστερή πλευρά"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"διαιρείτε την αριστερή πλευρά με {?}, αλλά την δεξιά με τον αντίστροφο"	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"πολλαπλασιάζετε the left-hand and right-hand sides with different numbers"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"πολλαπλασιάζετε the left-hand side with {?}, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"διαιρείτε the left-hand side by {?}, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"you negate the left-hand side, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"διαιρείτε one side by {?}, but not the other side"	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"σφάλμα πολλαπλασιασμού (1)"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"σφάλμα πολλαπλασιασμού (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"σφάλμα πολλαπλασιασμού, you loose the minus symbol"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"σφάλμα πολλαπλασιασμού, ο πολλαπλασιαμός με αρνητικό δίνει θετικό"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"σφάλμα διαίρεσης, διαιρείτε με αρνητικό αριθμό"	},
				{"algebra.equations.linear.balance.buggy.par1"		,"σφάλμα στην αφαίρεση παρενθέσεων, πολλαπλασιάστε και τους δύο όρους μέσα στις παρενθέσεις (1)"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"θυμηθείτε τους κανόνες προτεραιότητας: πρώτα πολλαπλασιασμός, μετά πρόσθεση"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"το σύμβολο του μείον δεν μετακινήθηκε σωστά μέσα στις παρενθέσεις"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"σφάλμα στην αφαίρεση παρενθέσεων, πολλαπλασιάστε και τους δύο όρους μέσα στις παρενθέσεις (2)"	},
				{"algebra.equations.linear.balance.buggy.par4"		,"σφάλμα στην αφαίρεση παρενθέσεων, σφάλμα πολλαπλασιασμού (1)"	},
				{"algebra.equations.linear.balance.buggy.par5"		,"σφάλμα στην αφαίρεση παρενθέσεων, πολλαπλασιάστε και τους δύο όρους μέσα στις παρενθέσεις (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		,"σφάλμα στην αφαίρεση παρενθέσεων, πολλαπλασιάστε και τους δύο όρους μέσα στις παρενθέσεις (4)"	},
				{"algebra.equations.linear.balance.buggy.par7"		,"σφάλμα στην αφαίρεση παρενθέσεων, πολλαπλασιάστε και τους δύο όρους μέσα στις παρενθέσεις με -1"	},
				{"algebra.equations.linear.balance.buggy.par8"		,"σφάλμα στην αφαίρεση παρενθέσεων, δείτε προσεκτικά που είναι οι παρενθέσεις"	},
				{"algebra.equations.linear.balance.buggy.par9"		,"σφάλμα στην αφαίρεση παρενθέσεων, σφάλμα πολλαπλασιασμού (2)"	},
				
				//conditionele navigatie-panels
				{"CN_voorwaarden", "Conditions"},
				{"CN_vanPagina","Από τη σελίδα"},
				{"CN_naarPagina","Μέχρι τη σελίδα"},
				{"CN_scorePagina","Pages for score"},
				{"CN_grensPercentage","Cut-off perc."},
				{"CN_sorteer","Sort"},
				{"CN_regelMeer", "Προσθήκη Γραμμής line"},
				{"CN_regelMinder", "Αφαίρεση Γραμμής"},
				
				// crossswidget commands
				{"CBA_input", "input"},
				{"CBA_int.index", "choice" },
				{"CBA_balansvergelijking", "balance equation"},
				{"CBA_zetOplossing", "set solution" },
				{"CBA_maakStap", "make step" },
				{"CBA_vergelijking", "equation" },
				{"CBA_double", "numerical value"},
				{"CBA_expression", "expression"},
				{"CBA_equation", "equation"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Action: 2x incorrect answer"},
				{"CBA_action.half", "Action: partial-correct answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				{"CBA_action.check", "Action: check"},
				{"CBA_action.click", "Action: click"},
				{"CBA_action.popup", "Action: popup"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_haak", "Bracket"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				{"Steps_statistics", "Domain reasoner statistics"},
                {"Steps_action", " Action"},
                {"Steps_nrOfSteps", "Number of different steps"},
                {"Steps_name", "Step name"},
                {"Steps_content", "Step content"},
                
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},
				
				// shareAction
                { ShareAction.SHARE_KEY, "Shared key" },
                { ShareAction.SHARE_MAP, "Shared components" },
// tablet opties
                { "Tablet keyboard", "Tablet keyboard" },
                { "Onderbouw-keyboard", "Middle school keyboard" },
                { "Algebra-keyboard", "Algebra keyboard" },
                { "Gonio-keyboard", "Gonio keyboard" },
                { "Statistiek-keyboard", "Statistics keyboard" },
                { "Meetkunde-keyboard", "Geometry keyboard" },
                { "Tablet handschriftset", "Tablet handwriting" },
                { "Basis", "Basic" },
                { "Uitgebreid", "Extended" },
                
                { "needsPremium", "For this activity you need a premium subscription."},

                { "LinkType_FALSE", "default (new window)" },
                { "LinkType_TRUE", "embedded" },
                { "LinkType_PLAYER", "own window"},
                { "LinkType_CLIENT", "parent window"},
                { "LinkType_TOP", "top window"},
                
                { "TCOMP_list" , "List"},
                { "TCOMP_list_settings" , "List settings"},
                { "TCOMP_list_rowCount" , "Number of items"},
                { "TCOMP_list_numberType" , "Item number type"},
                { "TCOMP_list_chooseType" , "Choose type"},
                { "TCOMP_list_tabWidth" , "Tab width"},
                { "TCOMP_list_rowSpace" , "Space between items"},
                
                { "TCOMP_multip" , "Multiple Choice"},
                { "TCOMP_multip_settings" , "Multiple Choice settings"},
                { "TCOMP_multip_rowCount" , "Number of items"},
                { "TCOMP_multip_numberType" , "Item number type"},
                { "TCOMP_multip_chooseType" , "Choose type"},
                { "TCOMP_multip_tabWidth" , "Tab width"},
                { "TCOMP_multip_rowSpace" , "Space between items"},
                { "TCOMP_multip_hasPrefix" , "Item number"},
                
                { "TCOMP_drag" , "Drag and Drop"},
                { "TCOMP_drag_settings" , "Drag and drop settings"},
                { "TCOMP_drag_rowCount" , "Number of drag objects"},
                { "TCOMP_drag_itemWidth" , "Width drag object"},
                { "TCOMP_drag_itemHeight" , "Height drag object"},
                { "TCOMP_drag_rowSpace" , "Distance items"},
                { "TCOMP_drag_descrWidth" , "Text width"},
                
                { "TCOMP_edit" , "Edit"},
                { "TCOMP_addItem" , "Add item"},
                { "TCOMP_removeItem" , "Remove item"},
                { "TCOMP_decompose" , "Decompose"},
		};
}




