package fi.wiskopdr.text;

public class Text_de extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "Zurück" },
				
				{ "terugKnopToolTip" , "Zurück" },
				{ "gelijkwaardigKnopToolTip" , "Geben Sie einen äquivalenten Ausdruck an" }, //CHECK THIS
				{ "opdrachtToolTip" , "Aufgabe auswählen" },
				{ "zelfKnopToolTip" , "Eigenen Ausdruck eingeben und vereinfachen" },
				
				
				{ "haakjesLabel0" , "  ausmultiplizieren" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "   vereinfachen" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  faktorisieren" },
				{ "wortelLabel0" , "  Wurzel" },
				{ "splitsLabel0" , "  split" },  // what is this? - Ulli
				{ "hulpKnopLabel" , "Help" },
				{ "gelijkwaardigLabel0" , "  equal" },
				{ "gelijkwaardigLabel1" , "    with:" },
				{ "ofLabel" , "or" },
				{ "enLabel" , "and" },
				{ "subLabel" , "Substitute:" },
                { "meerLabel" , "more" },
				
                { "klaarKnopLabel" , "Überprüfen" },
				{ "nakijkKnopLabel" , "Überprüfen" },
				{ "checkExternal" , "External check" },
				{ "eindeKnopLabel", "Ende" },
				{ "nakijkLabel1" , "Überprüft: " },
				{ "nakijkLabel2" , " mal " },
				{ "opnieuwKnopLabel" , "Noch einmal" },
				{ "allesOpnieuwKnopLabel" , "Alles noch einmal" },
				{ "zelftoetsGeschiedenisKnopLabel", "score history"},
				{ "opdrachtLabel" , "Aufgabe:" },
				{ "paginaLabel" , "Seite:" },
				{ "onderdeelLabel" , "Teil:" },
				{ "scoreLabel" , "Punkte:" },
				{ "score" , "Punkte: " },
				{ "totaal", "Gesamt: " },
				{ "voortgang" , "Fortschritt: "},
				{ "deelscores", "Teilpunkte"},
				{ "optiesButtonLabel" , "Optionen" },
				{ "standaardActiviteitNaam" , "Stufe" },
				{ "standaardOpdrachtNaam" , "Aufgabe" },
				{ "opnieuwPanelTekstMW" , "Deine bisherigen Ergebnisse gehen verloren.\n\nMöchtest Du wirklich neu starten?"},
				{ "opnieuwPanelTekst" , "Deine bisherigen Ergebnisse gehen verloren.\n\nMöchtest Du wirklich neu starten?"},
				{ "opnieuwPanelTitel" , "Noch einmal?"},
				{ "lockToetsCBLabel" , "Test schützen"},
				{ "lockToetsLabel" , "Test schützen"},
				{ "newPageMenuItem" ,  "New (insert)"},
				{ "deletePageMenuItem" ,  "Delete"},
				{ "copyPageMenuItem" ,  "Copy"},
				{ "cutPageMenuItem" ,  "Cut"},
				{ "pastePageMenuItem" ,  "Paste (insert)"},
				{ "insertCopyMenuItem" ,  "Copy (insert)"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
								
				{ "choiceOefenen" , "Üben" },
				{ "choiceOefenenEindloos" , "Endlos üben" },
				{ "choiceOefenenStraf" , "Übungsspiel" },
				{ "choiceZelfToets" , "Selbsttest" },
				{ "choiceEindToets" , "Test" },
				
				{ "opdrachtTitelLabel" , "Titel:" },
				{ "opdrachtTekstLabel" , "Text:" },
				{ "randVarLabel" , "Variablen für Zufallswerte:" },
				{ "startExpLabel" , "Ausgangsausdruck:" },
				{ "startVergLabel" , "Ausgangsgleichung:" },
				{ "antwoordLabel" , "Antwortmodell:" },
				{ "scoringLabel" , "Antwort bewerten:" },
				{ "puntenLabel" , "Punkte:" },
				{ "checkTotaalLabel" , "Achtung! Gesamtpunktzahl 10" },
				{ "gelijkwaardigCBLabel" , "Äquivalent" },
				{ "herleidingCBLabel" , "Vereinfachen" },
				{ "exactCBLabel" , "Exakt" },
				{ "significantCBLabel" , "Signigikant" },
				{ "stappenCBLabel" , "Mehr Schritte verwenden" },
				{ "bewerkingKnoppenCBLabel" , "Bearbeitungs-Taster" },
				{ "bewerkingKnoppenExtraCBLabel" , "Extra Bearbeitungs-Taster" },
                { "abcCBLabel" , "discr" }, //?
				{ "subKnopCBLabel" , "subst." }, //?
				{ "subKnopExtraCBLabel" , "subst. erweitert" }, //?
				
				{ "grafiekToolCBLabel" , "Funktionsplotter" },
				{ "grafiekToolKnopLabel" , "Funktionsplotter" },
				{ "vergelijkingCBLabel" , "Gleichung" },
				{ "eindOplossingCBLabel" , "Antwort benötigt" },
				{ "checkCBLabel" , "Überprüfbar" },
				{ "teltMeeCBLabel" , "In Bewertung einbeziehen" },
				{ "logCBLabel" , "logID" },
				{ "rmCBLabel" , "Rechner" },
				{ "pijlCBLabel" , "Pfeil" },
				{ "substitutiesButtonLabel" , "Ersetzungen" },
				{ "functiesButtonLabel" , "defined functions" },
				{ "strategieVersieLabel" , "Strategie-Version" },
				{ "oefenVersieLabel" , "Strategie+ Version" },
				{ "bordjesVersieLabel" , "Aufdeck-Methoden-Version" },
				
				{ "herleidingKeuze_0" , "Keine" },
				{ "herleidingKeuze_1" , "Ausmultipliziertes und vereinfachtes Polynom" },
				{ "herleidingKeuze_2" , "Ein Exponent" },
				{ "herleidingKeuze_3" , "Ohne negative or gebrochene Exponenten" },
				{ "herleidingKeuze_4" , "Ein Bruch" },
				{ "herleidingKeuze_5" , "Ein Logarithmus" },
				{ "herleidingKeuze_6" , "Als einfache Logarithmen geschrieben (z.B. log(x)+log(3))" },
				
				{ "feedbackTekst01" , "Dieser Schritt enthält richtige und falsche Teile. Ändere oder lösche die Teile, die nicht korrekt sind." },
				{ "feedbackTekst02" , "Nicht alle Lösungen erfüllen die ursprüngliche Gleichung. Lösche die Lösung(en), die die Gleichung nicht erfüllen." },
				{ "feedbackTekst03" , "Die Ungleichung wurde korrekt gelöst." },
				{ "feedbackTekst04" , "Die Gleichung wurde korrekt gelöst." },
				{ "feedbackTekst05" , "Gebe die gewünschte Näherung an." },
				{ "feedbackTekst06" , "Gebe die Lösungen der Ungleichung an." },
				{ "feedbackTekst07" , "Es fehlen ein oder mehrere Lösungen. Füge die fehlende(n) hinzu." },
				{ "feedbackTekst08" , "Benutze keine |- Markierungen." },
				{ "feedbackTekst09" , "Die Schreibweise ist nicht korrekt." },
				{ "feedbackTekst10" , "Die Lösung ist richtig, aber noch in der gewünschten Form." },
				{ "feedbackTekst11" , "Dies ist eine richtige Näherung." },
				{ "feedbackTekst12" , "Die Antwort ist richtig." },
				{ "feedbackTekst13" , "Die Antwort ist äquivalent zur gesuchten Antwort, hat aber nicht die gewünschte Form." },
				{ "feedbackTekst14" , "Syntaxfehler in der Antwort." },
                { "feedbackTekst15" , "Richtige Antwort." },
                { "feedbackTekst16" , "Dies ist eine korrekte Gleichung." },
                { "feedbackTekst17" , "Diese Gleichung hat noch nicht die richte Form." },
                { "feedbackTekst18" , "Die Antwort ist richtig, aber die Anzahl der signifikaten Stellen ist nicht richtig." },
                { "feedbackTekst19" , "Die Antwort ist richtig, hat aber weder die richtige Form noch die richtige Anzahl signifikanter Stellen." },
                { "feedbackTekst20" , "Die Antwort ist richtig mit der gewünschten Anzahl signifikanter Stellen, aber die Form stimmt nicht." },
                { "xVarMessage1" , "Die unabhängige Variable ist immer\n" 
									+ "ein Buchstabe.\n " 
									+ "Falls mehrbuchstabige Variablennamen verwendet werden\n" 
									+ "ist der erste Buchstabe des Namens\n" 
									+ "immer ein Buchstabe." },
				{ "xVarMessage2" , "Die unabhängige Variable kann nur mit einem\n" 
									+ "einzelnen Buchstaben geschrieben werden.\n" 
									+ "Nur wenn die Option \"mehrbuchstabige Variablen\" \n" 
									+ "kann die unabhängige Variable durch\n" 
									+ "mit mehreren Buchstaben benannt werden." },
				{ "xVarMessage3" , "Der Buchstabe e ist für die \n" 
									+ "Exponentialfunktion reserviert.\n" 
									+ "Dieser Buchstabe kann nicht als Variablenname\n" 
									+ "verwendet werden." },									
				{ "xVarMessage4a" , "Der Text  \"" },
				{ "xVarMessage4b" , "\" steht für eine mathematische Funktion und\n," 
									+ "kann daher nicht als Variablenname verwendet werden."},
									
				{ "gelijkwaardigKnopLabelGR" , "Nächste Zeile" },
				{ "terugKnopLabelGR" , "Vorherige Zeile" },
				
				{ "editorVersieKnopLabel1" , "Neue Editorversion" },
				{ "editorVersieKnopLabel2" , "Alte Editorversion" },
				
				{"antwoordVakLabel" , "Antwortfeld"},
				{"interactieVakLabel" , "Interaktive Komponente"},
				{"tekstVakLabel" , "Textfeld"},
				{"grafiekComponentLabel" , "Funktionsplotter"},
				
				
				
				{"interactieKeuzeLabel" , "Wähle den Typ von "},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "Abbruch"},
				{"breedteLabel" , "Breite:"},
				{"hoogteLabel" , "Höhe:"},
				{"volleBreedteLabel" , "Volle Breite"},
				{"popupLabel" , "Pop-Up"},
				
				{"feedbackCBLabel" , "Feedback"},
				{"uitwCBLabel" , "Schritte als Pop-Up"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "Eigene"},
				{"feedbackLabel" , "Feedback"},
				{"ideasButtonLabel" , "Optionen"},
				{"substitutiesButtonLabel" , "Ersetzungen"},
				{"antwoordmodelButtonLabel" , "Mögliche Antwort"},
				{"formuleInvoerModeCBLabel" , "Formeleingabemodus"},
				{"aantalKeuzesLabel" , "Auswahl-Anzahl"},
				{"aantalSelectieObjLabel" , "Anzahl der Auswahl-Objekte"},
				{"randomPosLabel" , "Positionen randomisieren"},
				{"meervSelectiesLabel" , "Mehrfachauswahl möglich"},
				{"checkViaFormuleLabel" , "Test durch Eingabe einer Formel"},
				{"aantalSleepObjLabel" , "Anzahl der Zug-Objekte"},
				{"aantalDoelObjLabel" , "Anzahl der Ziel-Objekte"},
				{"snapToTargetLabel" , "Auf Ziel einrasten"},
				{"snapMargeLabel" , "Fangradius"},
				{"checkVasteDoelenLabel" , "Feste Ziele für Zugobjekte überprüfen"},
				{"checkWaardeOpDoelLabel" , "Mit Werten der Zielobjekte überprüfen"},
				{"relocateCBLabel" , "Zurück"},
				{"viewCBLabel" , "Ansicht"},
				{"aantalValueObjectenLabel" , "Anzahl der Objekte"},
				{"checkAfzonderlijkLabel" , "Separat prüfen"},
				{"checkOpSamenhangLabel" , "Im Zusammenhang prüfen"},
				{"boxMetRand" , "Rahmen"},
				{"keuzeVakKiesLabel" , "Auswahl"},
				{"verzamelDoelCBLabel" , "Zielobjekt als Sammlung"}, //what's this?
                
				
				{"vormCBLabel" , "Formular"},
				{"formuleToolCBLabel" , "Formeleingabefeld"},
				{"goedLabel" , "Richtig"},
				{"doorLabel" , "Mach weiter"},
				{"foutLabel" , "Falsch"},
				{"halfLabel" , "Halb richtig"},
				
				{"geenOplossingen" , "keine Lösung"},
				{"allesOplossing" , "Alles ist Lösung"},
				{"antwoordModelGeen" , "keine"},
				{"abc" , "discr"}, // what's that?
				
				// TekstVakInteractiePanel
				{"formuleAntwVakLabel" , "Formel-Antwortfeld mit Zwischenschritten"},
                {"vergelijkingAntwVakLabel" , "Gleichungs-Antwortfeld mit Zwischenschritten"},
                {"simpelFormuleAntwVakLabel" , "Kleines Formel-Antwortfeld"},
                {"simpelVergelijkingAntwVakLabel" , "Kleines Gleichungs-Antwortfeld"},
                {"tekstAntwVakLabel" , "Text-Antwortfeld"},
                {"algebraPijlenLabel" , "Algebra-Pfeile"},
                {"blokkenbouwenLabel" , "Bauen mit Blöcken"},
                {"stroomdiagrammenLabel" , "Flussdiagramme"},
                {"grafiekenToolLabel" , "Funktionsplotter"},
                {"tekstVakLabelH" , "Textfeld"},
				{"geogebraIpLabel" , "GeoGebra 4 (in Vorbereitung)"},
				{"geogebra3IpLabel" , "GeoGebra 3"},
                {"fruitBalansIpLabel" , "Frucht-Waage"},
				{"checkSelectieUnitLabel" , "Auswahl-Überprüfung"},
				{"checkTekstAntwoordVakLabel" , "Textfeld mit Überprüfung"},
				{"keuzeAntwoordVakLabel" , "Auswahlfeld"},
				{"doorzienIpLabel" , "3D-Konstruktion"},
				{"checkSleepUnitLabel" , "Drag & Drop"},
				{"vergrotenIpLabel" , "PE Vergrößern"}, // what does "PE" mean?
				{"vangenIpLabel" , "PE Einfangen"},
				{"verknippenIpLabel" , "PE Ausschneiden"},
				{"geomAlgebra2dIpLabel" , "Geometrische Algebra 2d"},
				{"geomAlgebra1dIpLabel" , "Geometrische Algebra 1d"},
				{"normaleVerdelingIpLabel" , "Normalverteilung"},
				{"mp3PlayerIpLabel" , "MP3-Player"},
				{"binominaleVerdelingIpLabel" , "Binomialverteilung"},
				{"getallenlijnIpLabel" , "Zahlengerade (Sprünge)"},
				{"tekenVeelvlakIpLabel" , "Zeichnen im Raum"},
				{"mozaikIpLabel" , "Mosaik"},
				{"veelvlakkenIpLabel" , "Polyeder"},
				{"eerlijkVerdelenIpLabel" , "PE Gleichmäßig verteilen"},
				{"statistiekIpLabel" , "[test] Statistik-Darstellungen"},
				{"stroomdiagrammenIpLabel" , "[test] Flussdiagramme (neu)"},
				{"tegelsIpLabel" , "Parkettierungen"},
				{"checkWaardeUnitLabel" , "[test] Werte überprüfen"}, // Sind hier Größen gemeint? was heißt "unit" hier?
				{"omtrekAppletIpLabel" , "PE Umkreis-Applet"},
				{"algebraExpressiesIpLabel" , "[test] Algebra-Bäume"},
				{"oppervlakteAlgebraIpLabel" , "[test] Flächen-Algebra"},
				{"blokkenProgrammaIpLabel" , "[test] Block-Programme"},
				{"grafieken3DIpLabel" , "[test] 3D-Funktionsplotter"},
				{"spotProblemsIpLabel" , "[test] Spot-Probleme"}, // what's that?
				{"kladjeIpLabel" , "[test] Notizen"},
				{"kansbomenIpLabel" , "[test] Wahrscheinlichkeitsbäume"},
				{"rekenmachineIpLabel" , "[test] Taschenrechner"},
				{"formStructIpLabel" , "[test] FormStruct"},
				{"graphToolIpLabel" , "[test] GraphTool"},
				{"draabankIpLabel" , "[test] Drehbank"}, 
				{"waarmakersIpLabel" , "[test] Truemakers"},
				{"statSimIpLabel" , "[test] Statistics Simulations"},
				{"stelselVakLabel", "[test] Stelsel-antwoordvak"},
	            {"javaLogoIpLabel", "JavaLogo"},

	            //CheckButtonEditor
                {"CB_kijkNaOptieLabel", "Check" },
                {"CB_bewaarOptieLabel", "Save" },
                {"CB_rondAfOptieLabel", "set completed" },
                {"CB_nextPageOptieLabel", "To next page" },
                {"CB_eigenVakOptieLabel","All in same box"},
                {"CB_opPaginaOptieLabel","All on page"},
                {"CB_viaXWidgetOptieLabel","All connected via x-widget"},
                
				
								
				//InstellingenPanel
				{"OPT_wiskundeLabel" , "Mathematik"},
                {"OPT_navigatieLabel" , "Navigation"},
                {"OPT_layoutLabel" , "Layout"},
                {"OPT_nakijkenLabel" , "Überprüfen möglich"},
				{"OPT_vermenigvTeken" , "Multiplikationszeichen: X"},
				{"OPT_woordformules" , "Mehrbuchstabige Variablen "},
				{"OPT_tweeHoofdletterVars" , "Zweibuchstabige Variablen (Großbuchstaben)."},
				{"OPT_tempoToets" , "Zeitbeschränkung"},
				{"OPT_opnieuwKnop" , "'Zurücksetzen'-Taste"},
				{"OPT_itemOpnieuwKnop" , "'Noch einmal'-Taste"},
				{"OPT_checkPerOpdracht" , "Seitenweise überprüfen"},
				{"OPT_hoekInGraden" , "Winkeleinheit: Grad"},
				{"OPT_opdrachtBolletjes" , "Seitenauswahl"},
				{"OPT_volgendeKnop" , "'Nächste'-Taste"},	
				{"OPT_VorigeKnop" , "'Vorherige'-Taste"},
				{"OPT_paginaIpvOpdracht" , "Beschriftung: 'Seite' statt 'Aufgabe'"},
				{"OPT_fontFormaat" , "Größe "},
				{"OPT_fontNaam" , "Schriftart"},
				{"OPT_tijdsLimiet" , "Zeitbeschränkung (s)"},
				{"OPT_formTimes" , "Formeln in Times Roman setzen"},
				{"OPT_navigatieFormaat" , "Größe der Navigation"},
				{"OPT_margesLabel" , "Ränder:"},
				{"OPT_margeLinksLabel" , "Links"},
				{"OPT_margeRechtsLabel" , "Rechts"},
				{"OPT_margeBovenLabel" , "Oben"},
				{"OPT_margeOnderLabel" , "Unten"},
				{"OPT_fToets" , "F-Tasten für Formeln"},
				{"OPT_globalParam" , "Globale Einstellungen"},
				{"OPT_diffOperatoren" , "Differential operators"},
				{"OPT_voortgangKnop", "'Fortschritt' statt 'Gesamt'"},
				{"OPT_conditionalNav" , "Bedingte Navigation"},
				{"OPT_conditionalPercLabel" , "Prozentsatz"},
				{"OPT_voorwaarden", "Conditions per page"},
				{"OPT_allesCorrect", "Nächste Seite nur wenn alles richtig (grün)"},
				{"OPT_deelOpdr" , "Teile a,b,c usw."},
				{"OPT_zelftoetsGeenCorr" , "Bei Überprüfung keine Korrektur zeigen"},
				{"OPT_zelftoetsGeschiedenis" , "self-test history"},
				{"OPT_zelftoetsHighScore" , "highscore"},
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_eerderGeenCorr" , "Keine Korrektur vorhergehender Seiten"},
				{"OPT_significantie" , "Option für signifikatene Stellen"},
				{"OPT_objectives" , "Ziele"},
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_fontOvererving" , "Font-inheritance text boxes"},
				{"OPT_fontOverervingForm" , "Font-inheritance formula boxes"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Use styles"},
				{"OPT_importStyles" , "Import"},
				{"OPT_exportStyles" , "Export"},
				{"OPT_layers" , "Use layers"},
				
				{"OBJ_leerdoel", "Lernziel"},
				{"OBJ_categorie", "Kategorie"},
				{"OBJ_categorieBox", "Ziele in mehreren Kategorien"},
				{"OBJ_kolomMeerButton", "Spalte hinzufügen"},
				{"OBJ_kolomMinderButton", "Spalte entfernen"},
				{"MCC_misconception", "Misconception"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "Variablen der Funktion"},
				{"GEP_assenLabel" , "Achsen anzeigen"},
				{"GEP_grafiekOptiesLabel" , "Optionen Funktionenplotter"},
				
				{"GEP_varXLabel" , "Variable für vertikale Achse"},
				{"GEP_varYLabel" , "Variable für horizontale Achse"},
				
				{"GEP_assenOptie" , "Achsen"},
				{"GEP_roosterOptie" , "Kästchen"},
				{"GEP_roosterGrofOptie" , "Breite"},
				{"GEP_schaalverdelingOptie" , "Achseneinteilung"},
				{"GEP_piOptie" , "Gitter für Pi"},				
				
				{"GEP_zoomOptie" , "Zoom-Option"},
				{"GEP_traceOptie" , "Spur-Option"},
				{"GEP_dragOptie" , "Ziehen-Option"},
				{"GEP_tekenOptie" , "Funktion plotten"},
				
				{"GEP_tabelOptie" , "Tabellen-Werkzeug"},
				{"GEP_zoomInTabelOptie" , "Zoom für Tabelle"},
				{"GEP_tabelTekenToolOptie" , "Tabelle zum Zeichnen"},

				{"GEP_functieEditOptie" , "Funktionseingabe"},
				{"GEP_grafiekKleurenOptie" , "Verschiedene Farben"},
				
				{"GEP_formeleFunctieNotatieOptie" , "Formale Notation f(x), g(x) usw."},
				
				{"GEP_popupWeergave" , "Mit Pop-Up anzeigen"},
				
				{"GEP_xPositief" , "x positiv"},
				{"GEP_yPositief" , "y positiv"},
				{"GEP_xEditable" , "x veränderbar"},
				{"GEP_yEditable" , "y veränderbar"},
				
				
				{"GEP_opdrachten" , "Aufgaben"},
				
				{"GEP_kiesOpdracht" , "Aufgabentyp wählen"},
				{"GEP_opdracht1" , "Finde die Funktion für eine gegebene Gerade"},
				{"GEP_opdracht2" , "Finde eine Funktion für vorgegebene Punkte des Graphen"},
				{"GEP_opdracht3" , "Zeichne Punkte für eine gegebene Funktion"},
				{"GEP_opdracht4" , "Zeichne Tabellenwerte ein"},
				
				{"GEP_antwoordFormule" , "Lösungsformel in das Eingabefeld unten eingeben"},
				{"GEP_tabelPuntenX" , "Die x-Werte der Punkte bitte in der Tabelle unten eintragen." },
				{"GEP_tabelPunten" , "Die Punkte bitte in der Tabelle unten eintragen." },
				
				{"GEP_nauwkeurigheid" , "Genauigkeit (pixel)"},
				{"GEP_minimumPunten" , "Minimale Anzahl Punkte"},
				{"GEP_maximumScore" , "Maximale Anzahl Punkte"},
				{"GEP_leerlingZietTabel" , "Schüler können die Tabelle sehen"},
				
				{"GE_kijkNa" , "Überprüfen" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "Text"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "Fensterbreite"},
				{"LEP_vensterHoogte" , "Fensterhöhe"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "Hinzufügen"},
				{"IEP_verwijderen" , "Entfernen"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "Abbruch"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "Rand"},
				{"TVEP_achtergrondKleurAanwezig" , "Hintergrundfarbe"},
				{"TVEP_zwevend" , "Schwebend über Text"},
				{"TVEP_anderFont" , "Andere Schriftart"},
				{"TVEP_rondingHoeken" , "Abgerundete Ecken"},
				{"TVEP_rotatieHoek" , "Drehwinkel"},
				{"TVEP_centreerHor" , "Horizontal zentrieren"},
				{"TVEP_centreerVert" , "Vertikal zentrieren"},
				{"TVEP_pasAanH" , "Höhe anpassen"},
				{"TVEP_pasAanB" , "Breite anpassen"},
				{"TVEP_aantalRijen" , "Anzahl Zeilen"},
				{"TVEP_aantalKolommen" , "Anzahl Spalten"},
				{"TVEP_tabelRanden" , "Tabellenränder"},
				{"TVEP_celMarge" , "Rand links"},
				{"TVEP_bovenMarge" , "Rand oben"},
				{"TVEP_fontType" , "Schriftart"},
				{"TVEP_achtergrondKleur" , "Farbe"},
				{"TVEP_interlinie" , "Zeilenabstand"},
				{"TVEP_cellSpaceColumn" , "Spaltenabstand"},
				{"TVEP_cellSpaceRow" , "Zeilenabstand"},
				{"TVEP_layoutLabel" , "Textkastenlayout"},
				{"TVEP_gebruikersInteractieLabel" , "Benutzerinteraktion"},
				{"TVEP_selectieObject" , "Auswahlobjekt"},
                {"TVEP_selectieKleur" , "Farbe"},
                {"TVEP_selectieKleurKnopLabel" , "Selection color"},
                {"TVEP_sleepObject" , "Objekt ziehen"},
                {"TVEP_draaiObject" , "Rotating object"},
                {"TVEP_sleepDoel" , "Ziel ziehen"},
                {"TVEP_sleepHandle" , "Griff"},
                {"TVEP_selectieSleepWaarde" , "wert    ("},
                {"TVEP_fgKleurKnopLabel" , "Farbe"},
                {"TVEP_zichtbaarNaNakijken" , "Sichtbar nach Kontrolle"},
                {"TVEP_balansVergCom" , "Waage-Gleichung-Kasten Kommunikation"},
                {"TVEP_aftrekPopup" , "Popup zieht Punkte ab"},
                {"TVEP_callOut" , "Sprechblase"},
                {"TVEP_vulHoogte" , "Fill height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "Schritte"},
                {"TVEP_random" , "zufällig"},
                {"TVEP_linkObject" , "Objekt verknüpfen"},
                {"TVEP_editLink" , "Verknüpfung ändern"},
                {"TVEP_defaultBijNull" , "standard  )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "Abspeichern möglich"},
				{"GEP_alsTool" , "Als Werkzeug"},
				{"GEP_rand" , "Rand"},
				{"GEP_resetIcon" , "Reset möglich"},
				{"GEP_checkMetCheckDWO" , "checkDWO verwenden"},
				{"GEP_checkMetObjecten" , "erzeugte Objekte verwenden"},
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "Minimalwert"},
				{"GSEP_maxValue" , "Maximalwert"},
				{"GSEP_eenheden" , "Einheiten sichtbar"},
				{"GSEP_getallen" , "Zahlen"},
				{"GSEP_10tallen" , "Zehner markieren"},
				{"GSEP_5tallen" , "Fünfer markieren"},
				{"GSEP_nul" , "Null"},
				{"GSEP_pijl" , "Pfeil sichtbar"},
				{"GSEP_pijlTerug" , "Rückpfeil sichtbar"},
				{"GSEP_horizontaal" , "Horizontal"},
				{"GSEP_eenheid" , "Einheit"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "Menuleiste"},
				{"TEEP_rekenToolOptie" , "Rechner"},
				{"TEEP_grafToolOptie" , "Funktionsplotter"},
				
				//Ideas
				
				{"ideasTip",		"Hinweis"},
				{"ideasHelp",		"Hilfe"},
				{"ideasStap",		"Schritt"},
				{"ideasLosop",		"Lösen"},
				{"ideasWordtDan",		"wird"},
				
				{"algebra.equations.coverup.denominator"		,"Nenner verdecken"	},
				{"algebra.equations.coverup.minus-left"			,"Konstante Ausdrücke nach rechts bringen"	},
				{"algebra.equations.coverup.minus-right"		,"Verdeck-Methode verwenden"	},
				{"algebra.equations.coverup.negate"				,"durch -1 teilen"	},
				{"algebra.equations.coverup.numerator"			,"Zähler verdecken"	},
				{"algebra.equations.coverup.plus"				,"Konstante Ausdrücke nach rechts bringen"	},
				{"algebra.equations.coverup.power"				,"Wurzel ziehen"	},
				{"algebra.equations.coverup.sqrt"				,"Beide Seiten quadrieren"	},
				{"algebra.equations.coverup.times"				,"Variable durch Dividieren beider Seiten isolieren"	},
				{"algebra.equations.coverup.times-positive"		,"Variable durch Dividieren beider Seiten isolieren"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"Konstante Terme durch Addition einer Zahl auf beiden Seiten nach rechts bringen"	},
				{"algebra.equations.coverup.onevar.plus"		,"Konstante Terme durch Subtraktion einer Zahl auf beiden Seiten nach rechts bringen"	},
				
				{"algebra.equations.linear.distr-times"		,"Ausmultiplizieren"	},
				{"algebra.equations.linear.flip"			,"Gleichung umdrehen"	},
				{"algebra.equations.linear.merge"			,"Vereinfachen durch Zusammenfassen"	},
				{"algebra.equations.linear.remove-div"		,"Brüche durch Muliplikation mit Vielfachem der Nenner entfernen"	},
				{"algebra.equations.linear.var-left"		,"Ausdrücke mit Variablen nach links bringen"	},
				
				{"algebra.equations.buggy.cancel-minus"				,"Weil das Vorzeichen verschieden ist heben sich die Terme nicht auf."	},
				{"algebra.equations.buggy.distr-times-denom"		,"Fehler beim Weglassen von Klammern: Einer der Terme ist ein Bruch, und der Faktor wird mit dem Zähler des Bruchs multipliziert."	},
				{"algebra.equations.buggy.distr-times-plus"			,"Ein Term wurde nicht mit ausmultipliziert."	},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"Ein Term wurde beim ausmultiplizieren vergessen."	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"Achte beim Ausmultiplizieren auf die Vorzeichen!"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"Beim Ausmultiplizieren nur die Terme in der Klammer verwenden."	},
				{"algebra.equations.buggy.divide-negate"			,"Beim Dividieren auf das Vorzeichen achten"	},
				{"algebra.equations.buggy.divide-numdenom"			,"Das ist der Kehrbruch. Überlege durch welche Zahl du dividieren musst!"	},
				{"algebra.equations.buggy.flip-negate-one-side"		,"Das Vorzeichen muss auf beiden Seiten gewechselt werden."	},
				{"algebra.equations.buggy.multiply-one-side"		,"Beide Seiten müssen multipliziert werden."	},
				{"algebra.equations.buggy.minus-minus"				,"Fehler beim Weglassen von Klammern: Minus mal Minus ist Plus!"	},
				{"algebra.equations.buggy.multiply-forget-one"		,"Einer der Terme wurde beim Multiplizieren beider Seiten vergessen."	},
				{"algebra.equations.buggy.negate-all"				,"Einer der Terme wurde beim Vorzeichenwechsel vergessen."	},
				{"algebra.equations.buggy.negate-one-side"			,"Eine der Seiten wurde beim Vorzeichenwechsel vergessen."	},
				{"algebra.equations.buggy.plus"						,"Was passiert mit dem Vorzeichen wenn ein Term die Seite wechselt?"	},
				{"algebra.equations.buggy.priority-times"			,"Achte auf die Reihenfolge beim Rechnen."	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"Die Diskriminante ist b^2-4ac und nicht b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"not the negation in front of b: "	},
				{"algebra.equations.buggy.abc.one-solution"				,"Es gibt noch eine Lösung."	},
				{"algebra.equations.buggy.abc.two-a"					,"Teile durch 2a und nicht a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"Du hast die andere (negative) Wurzel vergessen."	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"Bevor du die Wurzel ziehst musst du noch etwas anderes machen."	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"Bevor du die Wurzel ziehst musst du noch etwas anderes machen."	},
				{"algebra.equations.buggy.coverup.square-minus"			,"Du kannst keine Wurzel aus einer negativen Zahl ziehen."	},
				{"algebra.equations.buggy.coverup.times-mul"			,"Statt durch die rechte Seite zu dividieren hast du multipliziert."	},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"Wenn du dividierst, dann musst du alle Terme dividieren!"	},
				{"algebra.equations.buggy.distr-square"					,"Es fehlt der gemischte Term in der binomischen Formel."	},
				{"algebra.equations.buggy.distr-square-forget"			,"Es fehlt ein Term in der binomischen Formel."	},
				{"algebra.equations.buggy.square-multiplication"		,"Das Quadrat der beiden Terme ist falsch."	},
				{"algebra.equations.buggy.division-by-var-both"		,"Wenn du durch eine Variable v teilst dann verlierst du die Lösung v=0."	},
				{"algebra.equations.buggy.division-by-var-zero"		,"Wenn du durch eine Variable v teilst dann verlierst du die Lösung v=0."	},
				
				{"algebra.equations.linear.balance.collect"			,"Zusammenfassen"	},
				{"algebra.equations.linear.balance.calculate"		,"Ausrechnen"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"Division als Multiplikation mit dem Kehrwert schreiben."	},
				{"algebra.equations.linear.balance.smart-div"		,"Durch gemeinsamen Faktor dividieren."	},
				{"algebra.equations.linear.balance.con-right-minus"	,"{?} von beiden Seiten abziehen."	},
				{"algebra.equations.linear.balance.con-left-minus"	,"{?} von beiden Seiten abziehen."	},
				{"algebra.equations.linear.balance.var-right-minus"	,"{?} von beiden Seiten abziehen."	},
				{"algebra.equations.linear.balance.var-left-minus"	,"{?} von beiden Seiten abziehen."	},
				{"algebra.equations.linear.balance.con-right-plus"	,"{?} zu beiden Seiten addieren."	},
				{"algebra.equations.linear.balance.con-left-plus"	,"{?} zu beiden Seiten addieren."	},
				{"algebra.equations.linear.balance.var-right-plus"	,"{?} zu beiden Seiten addieren."	},
				{"algebra.equations.linear.balance.var-left-plus"	,"{?} zu beiden Seiten addieren."	},
				{"algebra.equations.linear.balance.distribute"		,"Klammern auflösen"	},
				{"algebra.equations.linear.balance.remove-div"		,"Beide Seiten mit {?} multiplizieren." 	},
				{"algebra.equations.linear.balance.scale-to-one"	,"Beide Seiten durch {?} teilen."	},
				{"algebra.equations.linear.balance.negate"    ,"Vorzeichen auf beiden Seiten umkehren."  },
				{"algebra.equations.linear.balance.intro-false"    ,"Unmöglich"  },
				{"algebra.equations.linear.balance.intro-true"    ,"Immer wahr"  },
                
               
				{"algebra.equations.quadratic.abc"				,"Mitternachtsformel verwenden"	},
				{"algebra.equations.quadratic.approx"			,"Annäherung"	},
				{"algebra.equations.quadratic.cancel"			,"Ausdruck auf beiden Seiten des Gleichheitszeichen entfernen"	},
				{"algebra.equations.quadratic.common-factor"	,"Faktorisieren mit gemeinsamen Faktor"	},
				{"algebra.equations.quadratic.distr-div"		,"teilen"	},
				{"algebra.equations.quadratic.distr-square"		,"Quadrat berechnen"	},
				{"algebra.equations.quadratic.left-square"		,"Linke Seite als Quadrat schreiben."	},
				{"algebra.equations.quadratic.move-left"		,"Alles nach links bringen."	},
				{"algebra.equations.quadratic.nice-factors"		,"Die drei Ausdrücke faktorisieren."	},
				{"algebra.equations.quadratic.no-lin"			,"Als Quadrat=Zahl schreiben."	},
				{"algebra.equations.quadratic.prepare-split"	,"Quadratische Ergänzung."	},
				{"algebra.equations.quadratic.product-zero"		,"Produkt ist Null, auf Faktoren aufteilen"	},
				{"algebra.equations.quadratic.same-con-factor"	,"Beide Seiten durch das Gleiche teilen."	},
				{"algebra.equations.quadratic.same-factor"		,"Aus A·B=A·C folgt A=0 oder B=C"	},
				{"algebra.equations.quadratic.simpler-poly"		,"Vereinfachen durch Teilen durch gemeinsamen Faktor."	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"Wurzelausdruck vereinfachen."	},
				{"algebra.equations.quadratic.square-both"		,"Beide Seiten quadrieren."	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"Rückwärts-Substitution"	},
				{"algebra.equations.polynomial.expose-factor"		,"Gemeinsamen Faktor isolieren"	},
				{"algebra.equations.polynomial.power-factors"		,"Gemeinsamer Faktor x"	},
				{"algebra.equations.polynomial.subst"				,"Substitution verwenden"	},
				{"algebra.equations.polynomial.def-power-nat"   	,"Potenz als Multiplikation ausschreiben."},
				
				
				{"algebra.equations.rational.check-solution"	,"Lösung überprüfen"	},
				{"algebra.equations.rational.cross-multiply"	,"Über Kreuz multiplizieren"	},
				{"algebra.equations.rational.division-one"		,"Wenn der Bruch 1 ist, dann ist Zähler gleich Nenner."	},
				{"algebra.equations.rational.division-zero"		,"Wenn der Bruch 0 ist, dann ist der Zähler Null (falls der Nenner ungleich Null ist)."	},
				{"algebra.equations.rational.multiply-one-div"	,"Beide Seiten mit Nenner multiplizieren."	},
				{"algebra.equations.rational.same-dividend"		,"Aus A/B=A/C folgt A=0 oder B=C"	},
				{"algebra.equations.rational.same-divisor"		,"Nenner sind gleich, Zähler gleichsetzen."	},
				
				{"algebra.inequalities.flip-sign"		,"Vorzeichenwechsel"	},
				{"algebra.inequalities.give-solution"	,"Ungleichung lösen"	},
				{"algebra.inequalities.to-equation"		,"Zunächst als Gleichung schreiben"	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"Potenzen multiplizieren indem Exponenten addiert werden."	},
				{"algebra.manipulation.exponents.factor-as-power"		,"(Teilweise) als Potenz schreiben."	},
				{"algebra.manipulation.exponents.mul-exponents"			,"Potenz einer Potenz: Exponenten multiplizieren."	},
				{"algebra.manipulation.exponents.reciprocal"			,"1/Ausdruck als Ausdruck^(-1) schreiben"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"Als Potenz schreiben durch Addition der Exponenten."	},
				{"algebra.manipulation.exponents.sub-exponents"			,"Potenzen dividieren durch Subtraktion der Exponenten."	},
				{"algebra.manipulation.exponents.write-as-power"		,"Als Potenz schreiben"	},
				{"algebra.manipulation.exponents.distr-power"			,"Potenz eines Produkts ist Produkt der Potenzen."	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"Die Potenz Ausdruck^(-1) als Kehrbruch des Ausdrucks schreiben."	},
				{"algebra.manipulation.exponents.write-as-root"			,"Als Wurzel schreiben."	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"Kehrbruch einer Potenz ist die Potenz mit negiertem Exponenten."	},
				{"algebra.manipulation.exponents.push-negation-out"		,"Negation aus der Potenz ziehen, falls der Exponent ungerade ist."	},
				{"algebra.manipulation.exponents.root"					,"Wurzel ziehen"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"Aus Potenz=1 folgt Exponent=0"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"Gleiche Basis"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"Diese Potenz oder Wurzel annähern"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"Gemeinsame Potenz"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"Als größte gemeinsame Potenz schreiben"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"n-te Wurzel"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		,"Aus der Definition glog(x)=a folgt x=g^a"	},
				
				{"calculus.differentiation.deriv-of-poly"		,"Potenz ableiten"	},
				{"calculus.differentiation.min"		,"Subtraktionsregel anwenden"	},
				{"calculus.differentiation.negate"		,"Negation vor dem Ableiten herausziehen"	},
				{"calculus.differentiation.plus"		,"Summenregel anwenden"	},
				{"calculus.differentiation.product"		,"Produktregel anwenden"	},
				{"calculus.differentiation.quotient"		,"Quotientenregel anwenden"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"Du ziehst {?} links ab aber addierst {?} rechts"	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"Du addierst {?} links aber ziehst {?} rechts ab"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"Du ziehst {?} rechts ab aber addierst {?} links"	},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"Du addierst {?} rechts aber ziehst {?} links ab"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"Du ziehst {?} links ab aber machst das rechts nicht"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"Du addierst {?} links aber machst das rechts nicht"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"Du ziehst {?} links ab aber addierst {?} rechts"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"Du addierst {?} links aber ziehst {?} rechts ab"} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"Du ziehst {?} rechts ab aber addierst {?} links"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"Du addierst {?} rechts aber ziehst {?} links ab"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"Du ziehst {?} rechts ab aber machst das links nicht"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"Du addierst {?} rechts aber machst das links nicht"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"Du ziehst {?} links ab aber machst das rechts nicht"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"Du addierst {?} links aber machst das rechts nicht"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"Du ziehst {?} rechts ab aber machst das links nicht"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"Du ziehst {?} rechts ab aber machst das links nicht"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"Du hast nicht nur linke und rechte Seite vertauscht, sondern auch das Vorzeichen auf einer Seite gewechselt."	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"Du hast rechts etwas abgezogen, hast du das gleiche auch links gemacht?"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"Du hast mit einer Zahl multipliziert, aber nicht die gesamte linke Seite."	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"Du hast negiert, aber nicht nicht die gesamte linke Seite."	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"Du hast durch eine Zahl geteilt, aber nicht die gesamte linke Seite."	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"Du hast die linke Seite durch {?} geteilt, aber die rechte Seite durch den Kehrwert."	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"Du hast linke und rechte Seite mit verschiedenen Zahlen multipliziert."	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"Du hast die linke Seite mit {?} multipliziert, aber nicht die rechte Seite."	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"Du hast die linke Seite durch {?} dividiert, aber nicht die rechte Seite."	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"Du hast die linke Seite negiert, aber nicht die rechte Seite."	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"Du hast eine Seite durch {?} geteilt, aber nicht die andere Seite."	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"Fehler in der Multiplikation (1)"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"Fehler in der Multiplikation (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"Fehler in der Multiplikation, du hast das Minus verloren."	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"Fehler in der Multiplikation, Minus mal Minus ist Plus!"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"Fehler in der Division, du hast durch eine negative Zahl geteilt."	},
				{"algebra.equations.linear.balance.buggy.par1"		,"Fehler beim Ausmultiplizieren der Klammer, multipliziere mit beiden Termen in der Klammer (1)"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"Beachte die Rechenregeln - Punkt vor Strich!"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"Minuszeichen falsch in den Klammern bewegt"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"Fehler beim Ausmultiplizieren der Klammer, multipliziere mit beiden Termen in der Klammer (2)"	},
				{"algebra.equations.linear.balance.buggy.par4"		,"Fehler beim Ausmultiplizieren der Klammer, Multiplikation falsch (1)"	},
				{"algebra.equations.linear.balance.buggy.par5"		,"Fehler beim Ausmultiplizieren der Klammer, multipliziere mit beiden Termen in der Klammer (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		,"Fehler beim Ausmultiplizieren der Klammer, multipliziere mit beiden Termen in der Klammer (4)"	},
				{"algebra.equations.linear.balance.buggy.par7"		,"Fehler beim Ausmultiplizieren der Klammer, multipliziere beide Termen mit (-1)"	},
				{"algebra.equations.linear.balance.buggy.par8"		,"Fehler beim Ausmultiplizieren der Klammer, achte genau darauf, wo die Klammern stehen."	},
				{"algebra.equations.linear.balance.buggy.par9"		,"Fehler beim Ausmultiplizieren der Klammer, Multiplikation falsch (2)"	},
				
				//conditionele navigatie-panels
				{"CN_voorwaarden", "Vorgaben"},
				{"CN_vanPagina","Von Seite"},
				{"CN_naarPagina","bis Seite"},
				{"CN_scorePagina","Seiten für Bewertung"},
				{"CN_grensPercentage","Prozent zum Bestehen"},
				{"CN_sorteer","Sortieren"},
				{"CN_regelMeer", "Zeile hinzufügen"},
				{"CN_regelMinder", "Zeile entfernen"},
				
				// crossswidget commands
				{"CBA_input", "input"},
				{"CBA_int.index", "choice" },
				{"CBA_balansvergelijking", "balance equation"},
				{"CBA_zetOplossing", "set solution" },
				{"CBA_maakStap", "make step" },
				{"CBA_vergelijking", "equation" },
				{"CBA_double", "numerical value"},
				{"CBA_expression", "expression"},
				{"CBA_equation", "equation"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Actie: 2x incorrect answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_haak", "Bracket"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},
		};
}




