package fi.wiskopdr.text;

public class Text_jp extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "戻ります。" },
				
				{ "terugKnopToolTip" , "戻ります。" },
				{ "gelijkwaardigKnopToolTip" , "同等の表現を入力してください。" },
				{ "opdrachtToolTip" , "問題を選択してください。" },
				{ "zelfKnopToolTip" , "式を入力しなさい。\n そしてその式を簡単にしなさい。" },
				
				
				{ "haakjesLabel0" , "拡大してください。" },
				{ "haakjesLabel1" , "" },
				{ "herleidLabel0" , "簡単にしてください。" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "因数分解してください。" },
				{ "wortelLabel0" , "ルート" },
				{ "splitsLabel0" , "分割してください。" },
				{ "hulpKnopLabel" , "ヘルプ" },
				{ "gelijkwaardigLabel0" , "イコール" },
				{ "gelijkwaardigLabel1" , " と:" },
				{ "ofLabel" , "または" },
				{ "enLabel" , "そして" },
				{ "subLabel" , "代入してください。:" },
                { "meerLabel" , "さらに" },
				
                { "klaarKnopLabel" , "チェックCheck" },
				{ "nakijkKnopLabel" , "チェック" },
				{ "eindeKnopLabel", "終了" },
				{ "nakijkLabel1" , "チェック済み: " },
				{ "nakijkLabel2" , " 時間" },
				{ "opnieuwKnopLabel" , "もう一度" },
				{ "allesOpnieuwKnopLabel" , "やり直してください。" },
				{ "opdrachtLabel" , "問題:" },
				{ "paginaLabel" , "ページ:" },
				{ "onderdeelLabel" , "パート:" },
				{ "scoreLabel" , "得点:" },
				{ "score" , "得点: " },
				{ "totaal", "合計: " },
				{ "voortgang" , "発展: "},
				{ "deelscores", "一部の得点"},
				{ "optiesButtonLabel" , "オプション" },
				{ "standaardActiviteitNaam" , "レベル" },
				{ "standaardOpdrachtNaam" , "問題" },
				{ "opnieuwPanelTekstMW" , "\n\nもう一度始めると得点がなくなります。\n\nもう一度始めますか？"},
				{ "opnieuwPanelTekst" , "\n\nもう一度始めると得点がなくなります。\n\nもう一度始めますか？"},
				{ "opnieuwPanelTitel" , "やり直しますか？ "},
				{ "lockToetsCBLabel" , "テスト"},
				{ "lockToetsLabel" , "テストが確定されました"},
				{ "newPageMenuItem" ,  "新規（挿入します）"},
				{ "deletePageMenuItem" ,  "削除"},
				{ "copyPageMenuItem" ,  "コピー"},
				{ "cutPageMenuItem" ,  "カット"},
				{ "pastePageMenuItem" ,  "ペースト（挿入します）"},
				{ "insertCopyMenuItem" ,  "コピー（挿入します）"},
				{ "deelscoresKnopLabel", "Partial scores"},
				{ "misconceptionsKnopLabel", "Error analysis"},
								
				{ "choiceOefenen" , "練習" },
				{ "choiceOefenenEindloos" , "繰り返し練習します。" },
				{ "choiceOefenenStraf" , "練習問題" },
				{ "choiceZelfToets" , "自己確認" },
				{ "choiceEindToets" , "テスト" },
				
				{ "opdrachtTitelLabel" , "タイトル:" },
				{ "opdrachtTekstLabel" , "本文:" },
				{ "randVarLabel" , "ランダムな媒介変数:" },
				{ "startExpLabel" , "式の始まり:" },
				{ "startVergLabel" , "方程式の始まり:" },
				{ "antwoordLabel" , "模範解答:" },
				{ "scoringLabel" , "得点にします:" },
				{ "puntenLabel" , "ポイント:" },
				{ "checkTotaalLabel" , "注意！満点は10点です" },
				{ "gelijkwaardigCBLabel" , "同値" },
				{ "herleidingCBLabel" , "簡略してください。" },
				{ "exactCBLabel" , "正確には" },
				{ "significantCBLabel" , "重要" },
				{ "stappenCBLabel" , "ヒントを見ます。" },
				{ "bewerkingKnoppenCBLabel" , "操作ボタン" },
				{ "bewerkingKnoppenExtraCBLabel" , "操作ボタン(特別) " },
                { "abcCBLabel" , "discr" },
				{ "subKnopCBLabel" , "部分集合" },
				{ "subKnopExtraCBLabel" , "拡張された部分集合" },
				
				{ "grafiekToolCBLabel" , "グループツール" },
				{ "grafiekToolKnopLabel" , "グループツール" },
				{ "vergelijkingCBLabel" , "方程式" },
				{ "eindOplossingCBLabel" , "必要な答え" },
				{ "checkCBLabel" , "チェック可能" },
				{ "teltMeeCBLabel" , "採点を含みます。" },
				{ "logCBLabel" , "ログインID" },
				{ "rmCBLabel" , "計算機" },
				{ "pijlCBLabel" , "矢" },
				{ "substitutiesButtonLabel" , "代入" },
				{ "functiesButtonLabel" , "関数を定義します。" },
				{ "strategieVersieLabel" , "手順を示します。" },
				{ "oefenVersieLabel" , "手順を＋示します。" },
				{ "bordjesVersieLabel" , "順序を隠します。" },
				
				{ "herleidingKeuze_0" , "いずれでもありません。" },
				{ "herleidingKeuze_1" , "多項式の展開と簡略化" },
				{ "herleidingKeuze_2" , "一つのべき乗" },
				{ "herleidingKeuze_3" , "負の数もしくは分数を除きます。" },
				{ "herleidingKeuze_4" , "分数" },
				{ "herleidingKeuze_5" , "対数" },
				{ "herleidingKeuze_6" , "log(x)+log(3)のように簡略にしてください。" },
				
				{ "feedbackTekst01" , "正解・不正解の部分が含まれています。正しくなければ変更、もしくは削除してください。" },
				{ "feedbackTekst02" , "方程式に解答が当てはまっていません。正しくないところを変えるか、もしくは削除してください。" },
				{ "feedbackTekst03" , "不等式が正しく解かれました。" },
				{ "feedbackTekst04" , "方程式が正しく解かれました。" },
				{ "feedbackTekst05" , "必要な近似値を与えなさい。" },
				{ "feedbackTekst06" , "不等式の答えを与えなさい。" },
				{ "feedbackTekst07" , "答えが間違っています。足りない部分を加えなさい。" },
				{ "feedbackTekst08" , "マーク|-を使ってはいけません。" },
				{ "feedbackTekst09" , "配列が間違っています。" },
				{ "feedbackTekst10" , "正解です。しかし正しい表現形式ではありません。" },
				{ "feedbackTekst11" , "正しい近似値です。" },
				{ "feedbackTekst12" , "正解です。" },
				{ "feedbackTekst13" , "方程式は正しいですが、正しい表現形式ではありません。" },
				{ "feedbackTekst14" , "配列は正しくありません。" },
                { "feedbackTekst15" , "解答を訂正します。" },
                { "feedbackTekst16" , "正しい方程式です。" },
                { "feedbackTekst17" , "この方程式は未完成です。正しい表現形式ではありません。" },
                { "feedbackTekst18" , "正解ですが、重要な計算の数が正しくありません。" },
                { "feedbackTekst19" , "正解ですが、重要な計算の数と表現形式が正しくありません。" },
                { "feedbackTekst20" , "正解です。重要な計算の数は正しいですが、正しい表現形式ではありません。" },
                
                { "feedbackReactieVerg01" , ""},
                { "feedbackReactieVerg02" , ""},
                { "feedbackReactieVerg03" , ""},
                { "feedbackReactieVerg04" , ""},
                { "feedbackReactieVerg05" , "" },
                { "feedbackReactieVerg06" , ""},
                { "feedbackReactieVerg07" , ""},

                { "xVarMessage1" , "独立した変数は常に\n" 
									+ "\n定数" 
									+ "変数が文字の場合\n" 
									+ "変数の頭文字\n" 
									+ "常に定数" },
				{ "xVarMessage2" , "独立した変数は \n" 
									+ "一つの文字で表せられます。\n" 
									+ "変数オプションの場合だけ\"文字変換\" \n" 
									+ "選択され、関係性のない\n" 
									+ "他の文字が相当します。" },
				{ "xVarMessage3" , "定数は\nで使用される。 " 
									+ "模範的な作用　\n" 
									+ "この定数の名前に使われることはできません。\n" 
									+ "独立した変数の" },									
				{ "xVarMessage4a" , "テキスト:  \"" },
				{ "xVarMessage4b" , "\"知っている関数について　\n," 
									+ ""
									+ "だから変数とはいえません。"},
									
				{ "gelijkwaardigKnopLabelGR" , "次のライン" },
				{ "terugKnopLabelGR" , "前のライン" },
				
				{ "editorVersieKnopLabel1" , "新しいバージョン" },
				{ "editorVersieKnopLabel2" , "これまでのバージョン" },
				
				{"antwoordVakLabel" , "アンサーボックス"},
				{"interactieVakLabel" , "相互的な構成要素"},
				{"tekstVakLabel" , "テイストボックス"},
				{"grafiekComponentLabel" , "グラフの構成要素"},
				
				
				
				{"interactieKeuzeLabel" , "タイプを選びさない"},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "キャンセル"},
				{"breedteLabel" , "幅:"},
				{"hoogteLabel" , "高さ:"},
				{"volleBreedteLabel" , "最大の幅"},
				{"popupLabel" , "ポップアップ"},
				
				{"feedbackCBLabel" , "フィードバック"},
				{"feedbackSizeCBLabel" , "ポップアップサイズ"},
				{"uitwCBLabel" , "ポップアップ"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "あなた自身"},
				{"feedbackLabel" , "フィードバック"},
				{"ideasButtonLabel" , "オプション"},
				{"substitutiesButtonLabel" , "代入"},
				{"functiesButtonLabel" , "defined functions" },
				{"antwoordmodelButtonLabel" , "可能な解答"},
				{"formuleInvoerModeCBLabel" , "方法を埋め込む公式"},
				{"aantalKeuzesLabel" , "選択の数字"},
				{"aantalSelectieObjLabel" , "選択した物の数字"},
				{"randomPosLabel" , "無造作に抽出するポジション"},
				{"meervSelectiesLabel" , " 複数回答可能"},
				{"checkViaFormuleLabel" , "公式を使ってチェックします。"},
				{"aantalSleepObjLabel" , "ドラッグしたオブジェクトの数"},
				{"aantalDoelObjLabel" , "ターゲットオブジェクトの数"},
				{"snapToTargetLabel" , "ターゲットオブジェクトをスナップします。"},
				{"snapMargeLabel" , "余白をスナップします。"},
				{"checkVasteDoelenLabel" , "ドラッグしたオブジェクトへ固定されたターゲットをクリックします。"},
				{"checkWaardeOpDoelLabel" , "ドラッグしたオブジェクトの使っている数値をクリックします。"},
				{"relocateCBLabel" , "ジャンプして戻ります。"},
				{"viewCBLabel" , "見ます。"},
				{"aantalValueObjectenLabel" , "オブジェクトの数"},
				{"checkAfzonderlijkLabel" , "別々にクリックします。"},
				{"checkOpSamenhangLabel" , "一貫してクリックします。"},
				{"boxMetRand" , "ボックス"},
				{"keuzeVakKiesLabel" , "選びます。"},
				{"verzamelDoelCBLabel" , "回収した範囲としてのターゲットオブジェクト"},
                
				
				{"vormCBLabel" , "フォーム"},
				{"formuleToolCBLabel" , "公式を編集プログラムにインプットします。"},
				{"goedLabel" , "添削します。"},
				{"doorLabel" , "次へ進みます。"},
				{"foutLabel" , "間違っています。"},
				{"halfLabel" , "半分です"},
				
				{"geenOplossingen" , "解答無し"},
				{"allesOplossing" , "すべて解答"},
				{"antwoordModelGeen" , "無し"},
				{"abc" , "ディスク"},
				
				{"checkExternalCBLabel" , "外枠をチェックします。"},
				
				// TekstVakInteractiePanel
				{"formuleAntwVakLabel" , "公式の解答ボックス"},
                {"vergelijkingAntwVakLabel" , "等しい解答"},
                {"simpelFormuleAntwVakLabel" , "小さな公式の解答ボックス"},
                {"simpelVergelijkingAntwVakLabel" , "小さな等しい解答ボックス"},
                {"tekstAntwVakLabel" , "テキスト‐アンサーボックス"},
                {"algebraPijlenLabel" , "代数学の矢印"},
                {"blokkenbouwenLabel" , "ブロックを積み上げます。"},
                {"stroomdiagrammenLabel" , "フロー図"},
                {"grafiekenToolLabel" , "グラフを作成するツール"},
                {"tekstVakLabelH" , "テキストボックス"},
				{"geogebraIpLabel" , "Geogebra 4 (予定)"},
				{"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "果物の枝"},
				{"checkSelectieUnitLabel" , "選択したユニットをチェックします。"},
				{"checkTekstAntwoordVakLabel" , "テキストとアンサーボックスをチェック"},
				{"keuzeAntwoordVakLabel" , "アンサーボックスを選びます。"},
				{"doorzienIpLabel" , "３Dで作図する構成要素3D "},
				{"checkSleepUnitLabel" , "ユニットをドラッグ、またはドロップしてチェックします。PECheck drag/drop unit"},
				{"vergrotenIpLabel" , "PE拡大"},
				{"vangenIpLabel" , "PE掴み取ります。"},
				{"verknippenIpLabel" , "PEカッティング"},
				{"geomAlgebra2dIpLabel" , "Geom.algebra 2d"},
				{"geomAlgebra1dIpLabel" , "Geom.algebra 1d"},
				{"normaleVerdelingIpLabel" , "通常分布[区分] "},
				{"mp3PlayerIpLabel" , "Mp3-player"},
				{"binominaleVerdelingIpLabel" , "二通りの分布[区分]"},
				{"getallenlijnIpLabel" , "ナンバーライン（飛ぶ）"},
				{"tekenVeelvlakIpLabel" , "空いた場所に描きます。"},
				{"mozaikIpLabel" , ""},
				{"veelvlakkenIpLabel" , ""},
				{"eerlijkVerdelenIpLabel" , "PE平等にシェアします。"},
				{"statistiekIpLabel" , "[テスト]統計上の表現"},
				{"stroomdiagrammenIpLabel" , "[テスト]新しいフロー図"},
				{"tegelsIpLabel" , "タイルを張ります。"},
				{"checkWaardeUnitLabel" , "ユニット数値をチェックします。"},
				{"omtrekAppletIpLabel" , "PE円周アプレット"},
				{"algebraExpressiesIpLabel" , "[テスト]代数学の木々"},
				{"oppervlakteAlgebraIpLabel" , "[テスト]代数学の範囲"},
				{"blokkenProgrammaIpLabel" , "[テスト]プログラムをブロックします。"},
				{"grafieken3DIpLabel" , "[テスト]３Dグラフ"},
				{"spotProblemsIpLabel" , "[テスト]問題にスポットを当てます。"},
				{"kladjeIpLabel" , "[テスト]ノート"},
				{"kansbomenIpLabel" , "見通しの木々"},
				{"rekenmachineIpLabel" , "計算機"},
				{"formStructIpLabel" , "[テスト]形式構造"},
				{"graphToolIpLabel" , "グラフツール"},
				{"draabankIpLabel" , "[テスト]旋盤を回す"}, 
				{"waarmakersIpLabel" , "[テスト]トゥルーマーカーズ"},
				{"statSimIpLabel" , "[テスト] 統計的なシミュレーション"},
				{"stelselVakLabel", "[test] System of equations"},
	            {"javaLogoIpLabel", "JavaLogo"},
				
				//InstellingenPanel
				{"OPT_wiskundeLabel" , "数学"},
                {"OPT_navigatieLabel" , "ナビゲーション"},
                {"OPT_layoutLabel" , "レイアウト"},
                {"OPT_nakijkenLabel" , "チェック‐オプション"},
				{"OPT_vermenigvTeken" , "かけ算の記号：×"},
				{"OPT_woordformules" , "文字変数"},
				{"OPT_tweeHoofdletterVars" , "ABやBCなどの変数"},
				{"OPT_tempoToets" , "時間を限る"},
				{"OPT_opnieuwKnop" , "‘すべてをもう一度’ボタン "},
				{"OPT_itemOpnieuwKnop" , "‘アイテムをもう一度’ボタン"},
				{"OPT_checkPerOpdracht" , "ページごとにチェックする"},
				{"OPT_hoekInGraden" , "角度のユニット：度"},
				{"OPT_opdrachtBolletjes" , "アイテムセレクター"},
				{"OPT_volgendeKnop" , "次へ‐ボタン"},	
	
				{"OPT_VorigeKnop" , "直前のボタン"},
				{"OPT_paginaIpvOpdracht" , "ラベル：問題の代わりにページ"},
				{"OPT_fontFormaat" , "サイズ"},
				{"OPT_fontNaam" , "基本的なフォント"}, 
				{"OPT_tijdsLimiet" , "制限時間(秒)"}, 
				{"OPT_formTimes" , "Times Romanフォント"},
				{"OPT_navigatieFormaat" , "移動バーのサイズ"}, 
				{"OPT_margesLabel" , "余白"}, 
				{"OPT_margeLinksLabel" , "左"}, 
				{"OPT_margeRechtsLabel" , "右"}, 
				{"OPT_margeBovenLabel" , "上"}, 
				{"OPT_margeOnderLabel" , "下"},
				{"OPT_fToets" , "公式に関するF-keys "},
				{"OPT_globalParam" , "包括的な変数"}, 
				{"OPT_diffOperatoren" , "別の演算子"},
				{"OPT_voortgangKnop", "'合計の代わりに発展"}, 
				{"OPT_conditionalNav" , "条件付き移動"}, 
				{"OPT_conditionalPercLabel" , "パーセンテージ"},
				{"OPT_voorwaarden", "ページごとの条件"}, 
				{"OPT_allesCorrect", "全部正解なら、次ページへ(緑)"}, 
				{"OPT_deelOpdr" , " a,b,c等の数を表す記号"}, 
				{"OPT_zelftoetsGeenCorr" , "自己テストを訂正しません"}, 
				{"OPT_zelftoetsCorrAftrek" , "reduction score correction selftest"},
				{"OPT_eerderGeenCorr" , "前のページを訂正しません"}, 
				{"OPT_significantie" , "重要な数のオプションを確かめます"}, 
				{"OPT_objectives" , "目標"}, 
				{"OPT_fontOvererving" , "フォントをそのままにしたテキストボックス "},
				{"OPT_fontOverervingForm" , "フォントをそのままにした公式ボックス  "}, 
				{"OPT_misconceptions" , "Error analysis"},
				{"OPT_scoreZichtbaar" , "Scores visible for student"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Use styles"},
				{"OPT_importStyles" , "Import"},
				{"OPT_exportStyles" , "Export"},
				
				{"OBJ_leerdoel", "目標"}, 
				{"OBJ_categorie", "カテゴリー"}, 
				{"OBJ_categorieBox", "さまざまなカテゴリーの目標"}, 
				{"OBJ_kolomMeerButton", "列を追加します"}, 
				{"OBJ_kolomMinderButton", "列を消去します"}, 
				{"MCC_misconception", "Misconception"},
				{"MCC_categorie", "Category"},
				{"MCC_categorieBox", "Error analysis in multiple categories"},
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "関数の変化"}, 
				{"GEP_assenLabel" , "軸を表示します"},
				{"GEP_grafiekOptiesLabel" , "グラフツールのオプション"},
				
				{"GEP_varXLabel" , " x軸が定まりません"}, 
				{"GEP_varYLabel" , " y軸が定まりません"}, 
				
				{"GEP_assenOptie" , "軸"},

				{"GEP_roosterOptie" , "格子"}, 
				{"GEP_roosterGrofOptie" , "幅"}, 
				{"GEP_schaalverdelingOptie" , "軸の数"}, 
				{"GEP_piOptie" , "πの格子"},				
				
				{"GEP_zoomOptie" , "拡大のオプション"}, 
				{"GEP_traceOptie" , "見取り図のオプション"}, 
				{"GEP_dragOptie" , "ドラッグのオプション"},
				{"GEP_tekenOptie" , "グラフを描くオプション"},
				
				{"GEP_tabelOptie" , "表のツール"}, 
				{"GEP_zoomInTabelOptie" , "表を拡大します"}, 
				{"GEP_tabelTekenToolOptie" , "表を描くときのツール"}, 

				{"GEP_functieEditOptie" , "編集者の機能"},
				{"GEP_grafiekKleurenOptie" , "異なった色"}, 
				
				{"GEP_formeleFunctieNotatieOptie" , " f(x),g(x)といった形式的な関数表記"}, 
		
				{"GEP_popupWeergave" , "ポップアップメニューを通して見ます"},
				
				{"GEP_xPositief" , " xが正"}, 
				{"GEP_yPositief" , " yが正"}, 
				{"GEP_xEditable" , " xを編集します"}, 
				{"GEP_yEditable" , " yを編集します"}, 
				
				{"GEP_opdrachten" , "タスク"}, 
				
				{"GEP_kiesOpdracht" , "タスクのタイプを選びます"}, 
				{"GEP_opdracht1" , "与えられた直線のグラフについて式をかいてください"}, 
				{"GEP_opdracht2" , "グラフ上の点を通る式をかいてください"}, 
				{"GEP_opdracht3" , "与えられた式を満たす点をとってください"}, 
				{"GEP_opdracht4" , "表からグラフに点をとってください"}, 
				
				{"GEP_antwoordFormule" , "下の関数エディターに、答えの式を入力してください"},
				{"GEP_tabelPuntenX" , "下の表にグラフ上のxの値について記録します" },
				{"GEP_tabelPunten" , "表の下に点を記録します" },
				
				{"GEP_nauwkeurigheid" , "精度(ピクセル)"},
				{"GEP_minimumPunten" , "点の最小値"},
				{"GEP_maximumScore" , "最大得点"},
				{"GEP_leerlingZietTabel" , "生徒は表を見ることができます"},
				
				{"GE_kijkNa" , "チェック" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "テキスト"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "ウィンドウの広さ"},
				{"LEP_vensterHoogte" , "ウィンドウの高さ"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "追加します"},
				{"IEP_verwijderen" , "取り除きます"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "キャンセル"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "境界"},
				{"TVEP_achtergrondKleurAanwezig" , "背景の色"},
				{"TVEP_zwevend" , "テキストの上を動きます"},
				{"TVEP_anderFont" , "その他のフォント"},
				{"TVEP_rondingHoeken" , "角を丸めます"},
				{"TVEP_rotatieHoek" , "回転の角度"},
				{"TVEP_centreerHor" , "水平方向の中心"},
				{"TVEP_centreerVert" , "垂直方向の中心"},
				{"TVEP_pasAanH" , "高さを調節します"},
				{"TVEP_pasAanB" , "幅を調節します"},
				{"TVEP_aantalRijen" , "列の数"},
				{"TVEP_aantalKolommen" , "列の数"},
				{"TVEP_tabelRanden" , "表の境界"},
				{"TVEP_celMarge" , "余白の左へ"},
				{"TVEP_bovenMarge" , "余白の上へ"},
				{"TVEP_fontType" , "フォント"},
				{"TVEP_achtergrondKleur" , "色"},
				{"TVEP_interlinie" , "直線の間隔"},
				{"TVEP_cellSpaceColumn" , "間隔"},
				{"TVEP_cellSpaceRow" , "間隔"},
				{"TVEP_layoutLabel" , "テキストボックスのレイアウト"},
				{"TVEP_gebruikersInteractieLabel" , "ユーザーのふれあい"},
				{"TVEP_selectieObject" , "目標の選択"},
                {"TVEP_selectieKleur" , "色"},
                {"TVEP_selectieKleurKnopLabel" , "Selection color"},
                {"TVEP_sleepObject" , "オブジェクトをドラッグします"},
                {"TVEP_sleepDoel" , "ターゲットをドラッグします"},
                {"TVEP_sleepHandle" , "操作します"},
                {"TVEP_selectieSleepWaarde" , "値    ("},
                {"TVEP_fgKleurKnopLabel" , "色"},
                {"TVEP_zichtbaarNaNakijken" , "テストのあと見えるようにします"},
                {"TVEP_balansVergCom" , "バランスの均一な箱のコミュニケーション"},
                {"TVEP_aftrekPopup" , "ポップアップを使ってスコアを減らします"},
                {"TVEP_callOut" , "箱から呼び出します"}, 
                {"TVEP_vulHoogte" , "Fill height"},
                {"TVEP_inklapbaar" , "Fold/unfold"},
                {"TVEP_knopLinks" , "Button left"},
                {"TVEP_knopRechts" , "Button right"},
                {"TVEP_knopAchterTekst" , "Button behind text"},
                {"TVEP_knopIsRegel1" , "Button invisible"},
                {"TVEP_uitwerkingenPopup" , "段階"},
                {"TVEP_random" , "ランダム"},
                {"TVEP_linkObject" , "目的を結びつけます"},
                {"TVEP_editLink" , "リンクを編集します"},
                {"TVEP_defaultBijNull" , "デフォルト}"},
                {"TVEP_checkUitklapVak" , "調べます"},
                {"TVEP_logIDLabelLabel" , "ラベル"},
                {"TVEP_visible", "Visible"},
                {"TVEP_styles", "Styles"},
                {"TVEP_templateMode", "Template mode"},
				
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "オプションを保存します"},
				{"GEP_alsTool" , "ツールとして"},
				{"GEP_rand" , "境界"},
				{"GEP_resetIcon" , "オプションをリセットします"},
				{"GEP_checkMetCheckDWO" , "チェックDWOを使うこと"},
				{"GEP_checkMetObjecten" , "　対象を設定して使用すること"},
				
				//GetallenLijnSprongEditPanel　　
				{"GSEP_minValue" , "最小値"},
				{"GSEP_maxValue" , "最大値"},
				{"GSEP_eenheden" , "明らかな単位"},
				{"GSEP_getallen" , "数"},
				{"GSEP_10tallen" , "10点"},
				{"GSEP_5tallen" , "Marh for fives"},
				{"GSEP_nul" , "０"},
				{"GSEP_pijl" , "見えている矢印"},
				{"GSEP_pijlTerug" , "戻る矢印"},
				{"GSEP_horizontaal" , "水平な"},
				{"GSEP_eenheid" , "単位"},

				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "メニューバー"},
				{"TEEP_rekenToolOptie" , "計算機"},
				{"TEEP_grafToolOptie" , "グラフツール"},
				
				//Ideas
				
				{"ideasTip",		"ヒント"},
				{"ideasHelp",		"ヘルプ"},
				{"ideasStap",		"ステップ"},
				{"ideasLosop",		"解く"},
				{"ideasWordtDan",		"成り立ちます"},
				
				{"algebra.equations.coverup.denominator"		," 分母を消します"	},
				{"algebra.equations.coverup.minus-left"		,"右辺に定数を移項します"	},
				{"algebra.equations.coverup.minus-right"		," 隠れた手段を使います"	},
				{"algebra.equations.coverup.negate"				," 1でわるdivide by -1"	},
				{"algebra.equations.coverup.numerator"			," 指定を隠します"	},
				{"algebra.equations.coverup.plus"				," 右辺に定数を移項します"	},
				{"algebra.equations.coverup.power"				," 平方根を求めます"	},
				{"algebra.equations.coverup.sqrt"				,"両辺を二乗します"	}, 
				{"algebra.equations.coverup.times"			," 両辺を割って変数だけにします"}, 
				{"algebra.equations.coverup.times-positive"		," 両辺を割って変数だけにします"}, 
				{"algebra.equations.coverup.onevar.minus-left"	," 両辺に同じ数を加えて、右辺に定数項を移項します"	},
										
				{"algebra.equations.coverup.onevar.plus"		," 両辺から同じ数をひいて、右辺に定数項を移項します"	},
										
				{"algebra.equations.linear.distr-times"		," かっこを外します"	}, 
				{"algebra.equations.linear.flip"			," 等式を入れかえます"	},
				{"algebra.equations.linear.merge"		," 式を計算して簡単にします"	}, 
				{"algebra.equations.linear.remove-div"		,"同じ数をかけて分数を消去します"}, 
				{"algebra.equations.linear.var-left"		," 変数を伴う式を左辺に移項します"	},
				{"algebra.equations.buggy.cancel-minus"		," 符号が同じではないので、項を消せません"}
,										
				{"algebra.equations.buggy.distr-times-denom"		," かっこを取り外す際に間違いがあります：項の一つが分数なので、その分母に約数をかけます"	},
				{"algebra.equations.buggy.distr-times-plus"			, "かっこを外した際に、一方の項にかけていません"},
				{"algebra.equations.buggy.distr-times-plus-forget"	, "かっこが外された際に、一つの項が抜け落ちています"	},
				{"algebra.equations.buggy.distr-times-plus-sign"	, "かっこを外す際には符号をつけるようにします"	},
				{"algebra.equations.buggy.distr-times-too-many","かっこを外す際には、かっこ内の項にだけかけ算を行います"	},
				{"algebra.equations.buggy.divide-negate","わる際には符号に注意します"	},
				{"algebra.equations.buggy.divide-numdenom","分数の逆数。わるときには数に注意します"	},
				{"algebra.equations.buggy.flip-negate-one-side","両辺の符号を変えなければいけません"	},
				{"algebra.equations.buggy.multiply-one-side","両辺にかけ算を行わなければいけません"	},
				{"algebra.equations.buggy.minus-minus","かっこを外す際：負の数どうしのかけ算は正の数になります"	},
				{"algebra.equations.buggy.multiply-forget-one","かけ算を両辺に行う際に、項の一つがかけ忘れられています"	},
				{"algebra.equations.buggy.negate-all","符号を変える際に一つの項が忘れられています"	},
				{"algebra.equations.buggy.negate-one-side","符号を変える際に、辺の一つが忘れられています"	},
				{"algebra.equations.buggy.plus","移項を行う際には、符号に注意します"	},
				{"algebra.equations.buggy.priority-times","先に計算するきまりや、かっこを忘れないようにします"	},
				
				{"algebra.equations.buggy.abc.minus-4ac","判別式はD=b^2-4ac であり、かつD=b^2+4ac ではありません"	},
				{"algebra.equations.buggy.abc.minus-b","bの前は否定されない"	},
				{"algebra.equations.buggy.abc.one-solution"	,"第２の解法があります"	},
				{"algebra.equations.buggy.abc.two-a","2aでわるのであって、aでは割りません "	},
				{"algebra.equations.buggy.coverup.even-power"	,"負の平方根を忘れています"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"平方根をとる時に別の操作を行う必要があります"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"平方根をとる前に別の操作を行う必要があります"	},
				{"algebra.equations.buggy.coverup.square-minus","負の数の平方根はありません"	},
				{"algebra.equations.buggy.coverup.times-mul"	,"右辺をわる代わりにそれをかけます"	},
				{"algebra.equations.buggy.coverup.times-with-plus","わるときには、すべての項をわるようにしなければいけません"	},

				{" algebra.equations.buggy.distr-square"					,"二つの項を二乗するとき、その積を忘れています。"	},
				{"algebra.equations.buggy.distr-square-forget","二つの項の平方根をとるとき、一方の項を忘れている。when taking the square of two terms you have forgotten one of the terms"},
				{".algebra.equations.buggy.square-multiplication"		,"二つの項の間違った二乗"	},
				{" algebra.equations.buggy.division-by-var-both"		,"変数でわると解がなくなります。"	},
				{" algebra.equations.buggy.division-by-var-zero"		," 変数でわると解がなくなります"	},
				
				{" algebra.equations.linear.balance.collect"			,"結合"	},
				{" algebra.equations.linear.balance.calculate"		," 計算"	},
				{" algebra.equations.linear.balance.div-to-fraction"		,"わり算を分数のかけ算としてかきます"	},
				{" algebra.equations.linear.balance.smart-div"		,"共通因数でわります"	},
				{" algebra.equations.linear.balance.con-right-minus"	," 両辺から{?}をひきます"	},
				{" algebra.equations.linear.balance.con-left-minus"	," 両辺から{?}をひきますsubtract "	},
				{" algebra.equations.linear.balance.var-right-minus"	," 両辺から{?}をひきます"	},
				{" algebra.equations.linear.balance.var-left-minus"	," 両辺から{?}をひきます"	},
				{" algebra.equations.linear.balance.con-right-plus"	,"両辺に{?}を加えます"	},
				{" algebra.equations.linear.balance.con-left-plus"	," 両辺に{?}を加えます"	},
				{" algebra.equations.linear.balance.var-right-plus"	," 両辺に{?}を加えます"	},
				{" algebra.equations.linear.balance.var-left-plus"	, "両辺に{?}を加えます"	},
				{" algebra.equations.linear.balance.distribute"		,"かっこをはずします。"	},
				{"algebra.equations.linear.balance.remove-div"		,"両辺に{?}をかけます"	},
				{" algebra.equations.linear.balance.scale-to-one"	,"両辺を{?}でわりますdivide}"	},
				{" algebra.equations.linear.balance.negate"    ,"両辺の符号を変えます"  },
				{" algebra.equations.linear.balance.intro-false"    ,"不可能"  },
				{" algebra.equations.linear.balance.intro-true"    ,"常に正しい"  },
                
               
				{".abc algebra.equations.quadratic.abc"				,"二次方程式の解の公式を使うuse the quadratic formula"	},
				{" algebra.equations.quadratic.approx"			,"近似"	},
				{" algebra.equations.quadratic.cancel"			,"等号＝の両辺から式を削除します"	},
				{" algebra.equations.quadratic.common-factor"	,"共通因数をつかって因数分解します"	},
				{" algebra.equations.quadratic.distr-div"		,"わり算"	},
				{" algebra.equations.quadratic.distr-square"		,"二乗を計算します"	},
				{" algebra.equations.quadratic.left-square"		,"左辺を二乗の形でかきます"	},
				{" algebra.equations.quadratic.move-left"		,"すべてを左辺へ動かします"	},
				{" algebra.equations.quadratic.nice-factors"		,"3つの式を因数分解します"	},
				{" algebra.equations.quadratic.no-lin"			," square=numberとしてかきます"	},
				{" algebra.equations.quadratic.prepare-split"	,"平方完成します"	},
				{" algebra.equations.quadratic.product-zero"		,"積＝0, 因数は0とします"	},
				{" algebra.equations.quadratic.same-con-factor"	,"両辺を共通因数でわります"	},
				{" algebra.equations.quadratic.same-factor"		,"A×B=A×CはA=0またはB=C "	},
				{" algebra.equations.quadratic.simpler-poly"		,"共通因数でわって簡単にします。"	},
				{" algebra.equations.quadratic.simpler-sqrt"		,"平方根を簡単にします。"	},
				{" algebra.equations.quadratic.square-both"		,"両辺を二乗します。"	},
				
				
				
				{" algebra.equations.polynomial.back-subst"			,"後方置換を使います"	},
				{" algebra.equations.polynomial.expose-factor"		,"共通因数を分離しますr"	},
				{" algebra.equations.polynomial.power-factors"		,"共通因数X "	},
				{" algebra.equations.polynomial.subst"				,"置換しますuse substitution"	},
				{" algebra.equations.polynomial.def-power-nat"   	,"かけ算の繰り返しをべき乗としてかきます。"},
				
				
				{"algebra.equations.rational.check-solution"	,"解を吟味します"	},
				{" algebra.equations.rational.cross-multiply"	,"たすきがけをしますy"	},
				{" algebra.equations.rational.division-one"		,"分数が1のとき、分子＝分母"	},
				{" algebra.equations.rational.division-zero"		,"分数が0のとき、分子＝0(もし分母が0でなければ) "	},
				{".algebra.equations.rational.multiply-one-div"	,"両辺に分数の分母をかけます。"	},
				{".algebra.equations.rational.same-dividend"		,"A/B=A/C implies A=0 or B=C"	},
				{".algebra.equations.rational.same-divisor"		,"分母が等しい、分子が一致します。"	},
				
				{" algebra.inequalities.flip-sign"		,"符号を変えます。"	},
				{" algebra.inequalities.give-solution"	,"不等式を解きます"	},
				{" algebra.inequalities.to-equation"		,"方程式の最初に回します"	},
				
				{" algebra.manipulation.exponents.add-exponents"	,"指数をたすことによって累乗をかけます。"	},
				{" algebra.manipulation.exponents.factor-as-power"		,"累乗を使ってかきます"	},
				{" algebra.manipulation.exponents.mul-exponents"			,"累乗の累乗a power of a power: multiply the exponents"	},
				{" algebra.manipulation.exponents.reciprocal"			,"1でわるを-1乗しますと表現します。write 1/expression as expression^-1"	},
				{" algebra.manipulation.exponents.simple-add-exponents"	,"指数をたすことで累乗を使ってかきます。"	},
				{" algebra.manipulation.exponents.sub-exponents"			,"指数をひきますことで累乗をわる。divide the powers by subtracting the exponents"	},
				{"algebra.manipulation.exponents.write-as-power"		,"累乗を使ってかきます"	},
				{"algebra.manipulation.exponents.distr-power"			,"???use power of a product is a product of powers"	},
				{".algebra.manipulation.exponents.reciprocal-inverse"	,"をとしてかきます"	},
				{"algebra.manipulation.exponents.write-as-root"			,"平方根としてかく。write as square root"	},
				{" algebra.manipulation.exponents.reciprocal-var"		,"1/累乗は符号を変えた累乗でかきます。"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"マイナスの符号を累乗の前にだします。(指数が奇数の時) "	},
				{"algebra.manipulation.exponents.root"					,"平方根をあたえる。give square root"	},
				
				{" algebra.manipulation.exponents.equation.equals-one"		,"累乗=1は指数が0であること意味します。power=1 implies exponent=0"	},
				{" algebra.manipulation.exponents.equation.same-base"		,"同じ基数same base number"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"累乗か平方根で近似します。approximate this power or square root"	},
				{" algebra.manipulation.exponents.equation.common-power"		,"一般的累乗common power"	},
				{" algebra.manipulation.exponents.equation.greatest-power"	," write using the greatest common power"	},
				{".algebra.manipulation.exponents.equation.nth-root"			,"n番目の平方根nth square root"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		,"glog(x)=aはx=g^aであるという定義を使います。"	},
				
				{"calculus.differentiation.deriv-of-poly"		,"指数関数を微分します。"	},
				{"calculus.differentiation.min"		,"ひき算のきまりを適用します。"	},
				{"calculus.differentiation.negate"		,"微分する前にマイナスの符号を前に出します　"	},
				{"calculus.differentiation.plus"		,"和のきまりを適用します。"	},
				{"calculus.differentiation.product"		,"積のきまりを適用します。"	},
				{"calculus.differentiation.quotient"		,"商のきまりを適用します。"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"左辺から{?}をひきました。しかし右辺に{?}をたしました。y "	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"左辺に{?} をたしました。しかし右辺から{?} をひきました。"	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"右辺から{?} をひきました。しかし左辺に{?} をたしました。"},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"右辺に{?} をたしました。しかし左辺から{?} をひきました。"	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"左辺から{?} をひきました。しかし右辺に何もしていません。"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"あんたは左辺に{?} をたしました。しかし右辺に何もしていません。"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"左辺から{?} をひきました。しかし右辺に{?} をたしました。"},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"左辺に{?} をたしました。しかし右辺から{?} をひきました。"},
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"右辺から{?} をひきました。しかし左辺に{?} をたしました。"},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"右辺に{?} をたしました。しかし左辺から{?} をひきました。"},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"右辺から{?} をひきました。しかし左辺に何もしていません。"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"右辺に{?} をたしました。しかし左辺に何もしていません。"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"あんたは左辺から{?} をひきました。しかし右辺何もしていません。"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"左辺に{?} をたしました。しかし右辺に何もしていません。"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"右辺から{?} をひきました。しかし左辺に何もしていません。"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"右辺に{?} をたしました。しかし左辺に何もしていません。"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"左辺と右辺を交換するだけでなく、一方の符号を変えます。"	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"右辺でひき算をしました。右辺でも同じことをしましたか？ "	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"かけ算をします。しかし左辺が間違っている。"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"負にします、しかし左辺はまだ不完全です。　"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"数でわります。しかし左辺は不完全です。"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"左辺を{?}でわります。しかし右辺は逆数でわります。"	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"左辺と右辺にそれぞれ異なる数をかけています。"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"左辺に{?}をかけました。しかし右辺に何もかけていません。"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"左辺を{?}でわります。しかし右辺はわっていません。"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"you negate the left-hand side, but not the right-hand side"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"片方を{?}でわります。しかしもう一方をわっていません。y "	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"(1)のかけ算を間違えています。"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"(2)のかけ算を間違えています。"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"かけ算を間違えています。―を付け忘れています。"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"かけ算を間違えています。―×―は正"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"わり算を間違えています。負の数でわっています。"	},
				{"algebra.equations.linear.balance.buggy.par1"		,"括弧の削除でエラー、error in removing parentheses, (1)括弧の中の両方の条件をかける。"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"かけ算をたし算より先に行うというきまりを思い出しましょう。"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"括弧の間でマイナスを正しく動かしていません。"	},
				{"algebra.equations.linear.balance.buggy.par2"		, "括弧の削除でエラー(2)括弧の中の両方の条件をかけます。)"	},
				{"algebra.equations.linear.balance.buggy.par4"		," 括弧の削除でエラー、(1)のかけ算で間違えています。"	},
				{"algebra.equations.linear.balance.buggy.par5"		," 括弧の削除でエラー、(3)括弧の中の両方の条件をかけますerror in removing parentheses, multiply both terms in between parentheses (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		," 括弧の削除でエラー、(4)括弧の中の両方の条件をかけます"	},
				{"algebra.equations.linear.balance.buggy.par7"		," 括弧の削除でエラー、括弧の中の両方の数に-1をかけます"	},
				{"algebra.equations.linear.balance.buggy.par8"		," 括弧の削除でエラー、どこに括弧があるか注意してみます"	},
				{"algebra.equations.linear.balance.buggy.par9"		," 括弧の削除でエラー、(2)のかけ算で間違えています。"	},
				
				//conditionele navigatie-panels
				{"CN_voorwaarden", "条件"},
				{"CN_vanPagina","ページから"},
				{"CN_naarPagina","ページへ"},
				{"CN_scorePagina","スコアページ"},
				{"CN_grensPercentage","分ける"},
				{"CN_sorteer","ソート"},
				{"CN_regelMeer", "行の追加"},
				{"CN_regelMinder", "行の削除"},
				
				// crossswidget commands
				{"CBA_input", "入力"},
				{"CBA_int.index", "選択" },
				{"CBA_balansvergelijking", "等式"},
				{"CBA_zetOplossing", "解をセットします。" },
				{"CBA_maakStap", "段階を踏む" },
				{"CBA_vergelijking", "方程式" },
				{"CBA_double", "数値"},
				{"CBA_expression", "式"},
				{"CBA_equation", "方程式"},
				{"CBA_text", "text"},
				{"CBA_text.choice", "choice"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "content"},
				{"CBA_action.setNotEditable", "Action: set not editable"},
				{"CBA_action.unfold", "Action: unfold"},
				{"CBA_action.fold", "Action: fold"},
				{"CBA_action.correct", "Action: correct answer"},
				{"CBA_action.false", "Action: incorrect answer"},
				{"CBA_action.false_2", "Actie: 2x incorrect answer"},
				{"CBA_action.setVisible", "Action: set visible"},
				{"CBA_action.setNotVisible", "Action: set not visible"},
				{"CBA_action.select", "Action: select"},
				{"CBA_action.deselect", "Action: deselect"},
				
				{"oplossingenLabel", "Solutions"},
				{"executeLabel", "Execute"},
				
				//symbolen
				{"SYM_kiesSymbool", "Choose symbol"},
				{"SYM_lijn", "Line"},
				{"SYM_pijl", "Arrow"},
				{"SYM_accolade", "Curly bracket"},
				{"SYM_ellips", "Ellipse"},
				{"SYM_kiesEerstSymbool", "Choose symbol first"},
				{"SYM_dikte", "Line width"},
				{"SYM_kleur", "Color"},
				{"SYM_kiesKleur", "Choose color"},
				{"SYM_vulHoogte", "Fill height"},
								
				{"SYM_horizontaal", "Horizontal"},
				{"SYM_verticaal", "Vertical"},
				{"SYM_diagonaalOmhoog", "Diagonal up"},
				{"SYM_diagonaalOmlaag", "Diagonal down"},
				{"SYM_links", "Left"},
				{"SYM_rechts", "Right"},
				{"SYM_boven", "Up"},
				{"SYM_beneden", "Down"},
				{"SYM_rechtsboven", "Right up"},
				{"SYM_rechtsonder", "Right down"},
				{"SYM_linksonder", "Left down"},
				{"SYM_linksboven", "Left up"},
				{"SYM_geenRichting", "No direction"},
				
				// opdr nav struct
				{"ONS_timeisup", "The time is up"},
				{"ONS_timeready", "Ready in time"},
				{"ONS_timesChecked", "{0} times checked"},
				{"ONS_1timeChecked", "first time checked"},
		};
}

				


