package fi.wiskopdr.text;

import javax.swing.Box;
import javax.swing.JComboBox;
import javax.swing.JLabel;

import fi.wiskopdr.WiskOpdr;
import fi.wiskopdr.tekstobjects.ShareAction;

public class Text_nl extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            	{ "terugKnopLabel" , "Terug" },
				
				{ "terugKnopToolTip" , "Stap terug" },
				{ "gelijkwaardigKnopToolTip" , "Geef een gelijkwaardige formule" },
				{ "opdrachtToolTip" , "Kies opdracht" },
				{ "zelfKnopToolTip" , "Maak zelf een opdracht. \n Vul een eigen formule in." },
				
				{ "haakjesLabel0" , "  haakjes" },
				{ "haakjesLabel1" , "    weg" },
				{ "herleidLabel0" , "   herleid" },
				{ "herleidLabel1" , "" },
				{ "ontbindLabel0" , "  ontbind" },
				{ "splitsLabel0" , "  splits" },
				{ "wortelLabel0" , "  wortels" },
				{ "gelijkwaardigLabel0" , "  gelijkwaardig" },
				{ "gelijkwaardigLabel1" , "    met:" },
				{ "ofLabel" , "of" },
				{ "enLabel" , "en" },
				{ "subLabel" , "Substitueer:" },
                { "meerLabel" , "meer" },
				
                { "klaarKnopLabel" , "klaar" },
				{ "nakijkKnopLabel" , "kijk na" },
				{ "checkExternal" , "extern controleren" },
				{ "eindeKnopLabel", "Einde"},
				{ "nakijkLabel1" , "Nagekeken: " },
				{ "nakijkLabel2" , " keer " },
				{ "opnieuwKnopLabel" , "opnieuw" },
				{ "allesOpnieuwKnopLabel" , "alles opnieuw" },
				{ "zelftoetsGeschiedenisKnopLabel", "scoregeschiedenis"},
				{ "opdrachtLabel" , "Opdracht:" },
				{ "paginaLabel" , "Pagina:" },
				{ "onderdeelLabel" , "Onderdeel:" },
				{ "scoreLabel" , "Score:" },
				{ "score" , "Score: " },
				{ "totaal" , "Totaal: "},
				{ "voortgang" , "Voortgang: "},
				{ "deelscores", "Deelscores"},
				{ "misconceptions", "Foutenanalyse"},
				{ "optiesButtonLabel" , "Instellingen activiteit" },
				{ "standaardActiviteitNaam" , "Niveau" },
				{ "standaardOpdrachtNaam" , "Opdracht" },
				{ "opnieuwPanelTekstMW" , "Je verliest je huidige score als je opnieuw begint.\n\nWeet je zeker dat je opnieuw wilt beginnen?"},
				{ "opnieuwPanelTekst" , "Je verliest je huidige scores als je opnieuw begint.\n\nWeet je zeker dat je opnieuw wilt beginnen?"},
				{ "opnieuwPanelTitel" , "Opnieuw?"},
				{ "lockToetsCBLabel" , "Verzegel toets"},
				{ "lockToetsLabel" , "Toets verzegeld"},
				{ "newPageMenuItem" ,  "Nieuw (invoegen)"},
				{ "deletePageMenuItem" ,  "Verwijder"},
				{ "copyPageMenuItem" ,  "Kopieer"},
				{ "cutPageMenuItem" ,  "Knip"},
				{ "pastePageMenuItem" ,  "Plak (invoegen)"},
				{ "insertCopyMenuItem" ,  "Kopie (invoegen)"},
				{ "deelscoresKnopLabel", "Deelscores"},
				{ "misconceptionsKnopLabel", "Analyse"},
				{ "imagesButtonLabel", "Afbeeldingen"},
				{ "settingsLabel", "Instellingen"},
				
				
				{ "choiceOefenen" , "Oefenen" },
				{ "choiceOefenenEindloos" , "Oefenen eindeloos" },
				{ "choiceOefenenStraf" , "Oefenen strafpunten" },
				{ "choiceZelfToets" , "Zelftoets" },
				{ "choiceEindToets" , "Eindtoets" },
				
				{ "opdrachtTitelLabel" , "Titel:" },
				{ "opdrachtTekstLabel" , "Tekst:" },
				{ "randVarLabel" , "Random parameters:" },
				{ "startExpLabel" , "Startexpressie:" },
				{ "startVergLabel" , "Startvergelijking:" },
				{ "variabelenLabel", "Variabelen (gescheiden door komma's): "},
				{ "antwoordLabel" , "Antwoordmodel:" },
				{ "antwoordLabelStelsel", "(tupels getallen, bijv (0,0),(1,1))"},
				{ "scoringLabel" , "Scoring van het antwoord:" },
				{ "puntenLabel" , "Punten:" },
				{ "checkTotaalLabel" , "Let op! Totaal 10" },
				{ "gelijkwaardigCBLabel" , "Gelijkwaardig" },
				{ "herleidingCBLabel" , "Herleiding" },
				{ "exactCBLabel" , "Exact" },
				{ "significantCBLabel" , "Significant" },
				{ "stappenCBLabel" , "Stappen mogelijk" },
				{ "bewerkingKnoppenCBLabel" , "Bewerkingknoppen" },
				{ "bewerkingKnoppenExtraCBLabel" , "Bewerkingknoppen extra" },
                { "abcCBLabel" , "Gebruik abc-formule" },
				{ "subKnopCBLabel" , "Substituties" },
				{ "subKnopExtraCBLabel" , "Substituties extra" },
				{ "grafiekToolCBLabel" , "Grafiekentool" },
				{ "grafiekToolKnopLabel" , "Grafiekentool" },
				{ "vergelijkingCBLabel" , "Vergelijking" },
				{ "eindOplossingCBLabel" , "Eindoplossing" },
				{ "onafhankelijkCBLabel", "Onafhankelijk"},
				{ "checkCBLabel" , "Nakijken actief" },
				{ "teltMeeCBLabel" , "Telt mee in score" },
				{ "logCBLabel" , "LogID" },
				{ "rmCBLabel" , "Rekenmachine" },
				{ "pijlCBLabel" , "Pijl" },
				{ "substitutiesButtonLabel" , "Substituties" },
				{ "functiesButtonLabel" , "Gedefinieerde functies" },
				{ "strategieVersieLabel" , "Strategieversie" },
				{ "oefenVersieLabel" , "Strategie-oefenversie" },
				{ "bordjesVersieLabel" , "Bordjesmethodeversie" },
				
				{ "herleidingKeuze_0" , "Geen" },
				{ "herleidingKeuze_1" , "Veelterm herleid zonder haakjes" },
				{ "herleidingKeuze_2" , "Als één macht" },
				{ "herleidingKeuze_3" , "Zonder gebroken of negatieve exponenten" },
				{ "herleidingKeuze_4" , "Als één breuk" },
				{ "herleidingKeuze_5" , "Als één log" },
				{ "herleidingKeuze_6" , "Met alleen enkelvoudige log's (bv log(x)+log(3))" },
				
				{ "feedbackTekst01" , "Deze stap bevat correcte en niet correcte onderdelen. Verwijder of vervang de delen die niet correct zijn." },
				{ "feedbackTekst02" , "Niet alle oplossingen voldoen aan de oorspronkelijke vergelijking. Verwijder de oplossingen die niet voldoen." },
				{ "feedbackTekst03" , "De ongelijkheid is correct opgelost." },
				{ "feedbackTekst04" , "De vergelijking is correct opgelost." },
				{ "feedbackTekst05" , "Geef de gevraagde afronding." },
				{ "feedbackTekst06" , "Geef nu de oplossing(en) van de ongelijkheid." },
				{ "feedbackTekst07" , "Er ontbreken oplossingen. Vul aan." },
				{ "feedbackTekst08" , "Gebruik geen absoluut strepen ( bv: |x-3| )." },
				{ "feedbackTekst09" , "De notatie van de vergelijking of oplossingen is niet juist." },
				{ "feedbackTekst10" , "Oplossing is goed, maar nog niet in de juiste vorm." },
				{ "feedbackTekst11" , "Deze benadering is een goede oplossing." },
				{ "feedbackTekst12" , "Dit antwoord is juist." },
				{ "feedbackTekst13" , "Is gelijkwaardig maar heeft nog niet de juiste vorm." },
				{ "feedbackTekst14" , "De notatie van het antwoord klopt niet." },
                { "feedbackTekst15" , "Correct antwoord." },
                { "feedbackTekst16" , "Dit is een correcte vergelijking" },
                { "feedbackTekst17" , "Deze vergelijking heeft niet de gevraagde vorm" },
                { "feedbackTekst18" , "De oplossing is goed, maar het aantal significante cijfers klopt niet." },
                { "feedbackTekst19" , "Oplossing is goed, maar nog niet in de juiste vorm en de significantie klopt niet." },
                { "feedbackTekst20" , "Oplossing is goed, significantie klopt maar heeft nog niet de juiste vorm." },
                { "feedbackTekst21a" , "Je hebt alle oplossingen gevonden, vul ze onderaan in."},
                { "feedbackTekst21b" , "Je hebt alle oplossingen gevonden."},
                { "feedbackTekst22" , "Je hebt de oplossingen in deze tak gevonden, ga verder met een andere tak."},
                	
                
                { "feedbackReactieVerg01a" , "Je reactievergelijking bevat nog niet de juiste beginstoffen."},
                { "feedbackReactieVerg01b" , "Je reactievergelijking bevat nog niet de juiste reactieproducten."},
                { "feedbackReactieVerg02" , "Je hebt de juiste moleculen, maar de elementenbalans van je reactievergelijking klopt nog niet."},
                { "feedbackReactieVerg03" , "Je hebt de juiste moleculen, maar de ladingen bij de moleculen kloppen nog niet."},
                { "feedbackReactieVerg04" , "Je hebt de juiste moleculen, maar de ladingenbalans van je reactievergelijking klopt nog niet."},
                { "feedbackReactieVerg05" , "Is het een evenwichtsreactie of een aflopende reactie?" },
                { "feedbackReactieVerg06" , "Je kunt de vergelijking eenvoudiger schrijven."},
                { "feedbackReactieVerg07" , "Dit is een kloppende reactie, maar niet die waar om werd gevraagd."},
                { "feedbackReactieVerg08" , "Je hebt de beginstoffen en reactieproducten verwisseld."},
                
                { "rvScoreCorrect" , "Score voor correcte vergelijking: "},
                { "rvAftrekVereenvoudigbaar", "Aftrek als vereenvoudigbaar:"},
                { "rvAftrekPijl", "Aftrek bij onjuiste pijl:"},
                { "rvLossePunten", "Als niet correct, geef punten voor (punten hieronder zijn cumulatief): "},
                { "rvScoreBeginstoffen", "Beginstoffen correct:"},
                { "rvScoreProducten", "Reactieproducten correct:"},
                { "rvScoreElementen", "Elementenbalans klopt:"},
                { "rvScoreLadingen", "Ladingenbalans klopt:"},
                
               
                { "xVarMessage1" , "De onafhankelijk variabele is altijd\n" 
									+ "een letter.\n " 
									+ "In het geval er met woordformules\n" 
									+ " wordt gewerkt, is het eerste teken\n" 
									+ "van de woordvariabele altijd een letter." },
                { "xVarMessage2" , "De onafhankelijk variabele kan uit\n" 
									+ "slechts één letter bestaan.\n" 
									+ "Alleen als de optie \"woordformule\" \n" 
									+ "is geselecteerd, dan kan de onafhankelijke\n" 
									+ "variabele uit meer letters bestaan." },
				{ "xVarMessage3" , "De letter e is gereserveerd als teken \n" 
									+ "voor het grondtal van de natuurlijke.\n" 
									+ "logaritme.\n" 
									+ "Deze letter kan dus niet gebruikt worden\n" 
									+ "als naam voor de onafhankelijke variabele." },
				{ "xVarMessage4a" , "De tekst:  \"" },
				{ "xVarMessage4b" , "\" is gereserveerd voor\n" 
									+ "de betreffende wiskundige functie en mag dus\n"
									+ "niet gebruikt worden in de naam van de variabele"},
				
				{ "gelijkwaardigKnopLabelGR" , "Volgende regel" },
				{ "terugKnopLabelGR" , "Vorige regel" },
				
				{ "editorVersieKnopLabel1" , "Nieuwe editorversie" },
				{ "editorVersieKnopLabel2" , "Oude editorversie" },
				
				{"antwoordVakLabel" , "antwoordvak"},
				{"interactieVakLabel" , "interactievak"},
				{"tekstVakLabel" , "tekstvak"},
				{"grafiekComponentLabel" , "grafiekcomponent"},
				
				
				
				{"interactieKeuzeLabel" , "Kies soort "},
				{"okKnopLabel" , "OK"},
				{"annuleerKnopLabel" , "Annuleer"},
				{"sluitKnopLabel" , "Sluit"},
				{"verwijderKnopLabel" , "Verwijder"},
				{"wijzigKnopLabel" , "Wijzig"},
				{"fileKnopLabel" , "Bestand"},
				{"editUrlLabel" , "URL van de afbeelding"},
				{"kiesAfbeeldingLabel" , "Kies een afbeelding"},
				{"afbeeldingenBeherenLabel" , "Afbeeldingen beheren"},
				{"urlKnopLabel" , "URL"},
				{"bewerkenLabel" , "Bewerken"},
				{"toevoegenLabel" , "Toevoegen"},
				{"breedteLabel" , "Breedte:"},
				{"hoogteLabel" , "Hoogte:"},
				{"volleBreedteLabel" , "Volle breedte"},
				{"popupLabel" , "Popup"},
				
				{"feedbackCBLabel" , "Feedback / deelscores"},
				{"feedbackSizeCBLabel" , "popup aanpasbaar"},
				{"uitwCBLabel" , "Popup voor uitwerking"},
				{"casAntwCBLabel" , "CAS"},
				{"eigenOpdrCBLabel" , "Eigen opdracht"},
				{"feedbackLabel" , "Feedback"},
				{"ideasButtonLabel" , "options"},
				{"substitutiesButtonLabel" , "Substituties"},
				{"antwoordmodelButtonLabel" , "mogelijk antwoordmodel"},
				{"formuleInvoerModeCBLabel" , "Formule invoer modus"},
				{"aantalKeuzesLabel" , "Aantal keuzes"},
				{"aantalSelectieObjLabel" , "Aantal selectie-objecten"},
                {"randomPosLabel" , "Randomiseer posities"},
                {"meervSelectiesLabel" , "Meervoudige selecties mogelijk"},
                {"checkViaFormuleLabel" , "Check m.b.v. een formule"},
                {"aantalSleepObjLabel" , "Aantal sleepobjecten"},
                {"aantalDoelObjLabel" , "Aantal doelobjecten"},
                {"snapToTargetLabel" , "Springt naar doelobject"},
                {"snapMargeLabel" , "Springt met marge"},
                {"checkVasteDoelenLabel" , "Check op vaste doelen voor sleepobjecten"},
                {"checkWaardeOpDoelLabel" , "Check met waarden sleepobjecten"},
                {"relocateCBLabel" , "Springt terug"},
                {"viewCBLabel" , "Toon foute objecten"},
                {"aantalValueObjectenLabel" , "Aantal objecten"},
				{"checkAfzonderlijkLabel" , "Check afzonderlijk"},
				{"checkOpSamenhangLabel" , "Check op samenhang"},
				{"boxMetRand" , "Rand zichtbaar"},
				{"keuzeVakKiesLabel" , "Kies"},
				{"verzamelDoelCBLabel" , "Doelobject als verzamelgebied"},
				{"oplossingenRegelZichtbaar", "Oplossingenregel zichtbaar"},
				{"rekenVakZichtbaar", "Rekenvak zichtbaar"},
				
				{"vormCBLabel" , "Vorm"},
				{"formuleToolCBLabel" , "Formule-invoer editor"},
				{"goedLabel" , "Goed"},
				{"doorLabel" , "Doorgaan"},
				{"foutLabel" , "Fout"},
				{"halfLabel" , "Half"},
				
				{"geenOplossingen" , "geen oplossingen"},
				{"allesOplossing" , "alles is een oplossing"},
				{"antwoordModelGeen" , "geen"},
				{"abc" , "abc"},
				
				{"checkExternalCBLabel" , "Extern controleren"},
				{"contextVarCBLabel", "Contextvariabelen gebruiken"},
				{"rmAantalDecLabel", "Aantal decimalen"},
				
				{"FEV_titleStartLabel", "Startvergelijking"},
				{"FEF_titleStartLabel", "Startexpressie"},
				{"FEV_titleAntwoordLabel", "Juiste antwoord"},
				{"FEV_titleAntwoordNrLabel", "Antwoord"},
				{"FEV_titleContextLabel", "Contextvariabelen"},
				{"FEV_titleFeedbackLabel", "Feedbacktekst"},
				{"FEV_titleVerificatieLabel", "Verificatie"},
				{"FEV_titleHulpLabel", "Hulp bij oplossen"},
				{"FEV_titleOpmaakLabel", "Opmaak"},
				{"FEV_titleLoggingLabel", "Nakijken / logging"},
				{"FEV_titleScoringLabel", "Score"},
				{"FEV_titleVormLabel", "Juiste vormen"},
				
				{"AKV_titleTekstenLabel", "Teksten keuzelijst"},
				
				
				
				// TekstVakInteractiePanel
				{"titleFormuleAntwVakLabel" , "Instellingen formulevak met stappen"},
                {"titleVergelijkingAntwVakLabel" , "Instellingen vergelijkingvak met stappen"},
                {"titleSimpelFormuleAntwVakLabel" , "Instellingen simpel formulevak"},
                {"titleSimpelVergelijkingAntwVakLabel" , "Instellingen simpel vergelijkingvak"},
				{"formuleAntwVakLabel" , "Formulevak met stappen"},
                {"vergelijkingAntwVakLabel" , "Vergelijkingvak met stappen"},
                {"simpelFormuleAntwVakLabel" , "Simpel formulevak"},
                {"simpelVergelijkingAntwVakLabel" , "Simpel vergelijkingvak"},
                {"tekstAntwVakLabel" , "Tekstantwoordvak uitgebreid"},
                {"algebraPijlenLabel" , "Algebrapijlen"},
                {"blokkenbouwenLabel" , "Blokken bouwen"},
                {"stroomdiagrammenLabel" , "Stroomdiagrammen"},
                {"grafiekenToolLabel" , "Grafiekentool"},
                {"tekstVakLabelH" , "Tekstvak"},
                {"geogebraIpLabel" , "Geogebra 4"},
                {"geogebra3IpLabel" , "Geogebra 3"},
                {"fruitBalansIpLabel" , "Fruitbalans"},
                {"checkSelectieUnitLabel" , "Nakijkknop selectieopdracht"},
                {"checkTekstAntwoordVakLabel" , "Tekstantwoordvak met controle"},
                {"keuzeAntwoordVakLabel" , "Keuzelijst (uitklapbaar)"},
                {"doorzienIpLabel" , "Doorzien"},
                {"checkSleepUnitLabel" , "Nakijkknop sleepopdracht"},
                {"vergrotenIpLabel" , "PO Vergroten"},
                {"vangenIpLabel" , "PO Vangen"},
                {"verknippenIpLabel" , "Verknippen"},
                {"geomAlgebra2dIpLabel" , "Geometrische algebra 2D"},
                {"geomAlgebra1dIpLabel" , "Geometrische algebra 1D"},
                {"normaleVerdelingIpLabel" , "Normale verdeling"},
                {"mp3PlayerIpLabel" , "Mp3-player"},
                {"binominaleVerdelingIpLabel" , "Binomiale verdeling"},
                {"getallenlijnIpLabel" , "Getallenlijn (sprong)"},
                {"tekenVeelvlakIpLabel" , "Teken veelvlak"},
                {"mozaikIpLabel" , "Mozaïek"},
                {"veelvlakkenIpLabel" , "Veelvlakken"},
                {"eerlijkVerdelenIpLabel" , "PO Eerlijk verdelen"},
                {"statistiekIpLabel" , "Statistische representaties"},
                {"stroomdiagrammenIpLabel" , "Stroomdiagrammen"},
                {"tegelsIpLabel" , "Tegels"},
                {"checkWaardeUnitLabel" , "Nakijkknop invulopdracht"},
                {"omtrekAppletIpLabel" , "PO Omtrek applet"},
                {"algebraExpressiesIpLabel" , "Algebra-expressies"},
                {"oppervlakteAlgebraIpLabel" , "Oppervlakte-algebra"},
                {"blokkenProgrammaIpLabel" , "Blokkenprogramma"},
                {"grafieken3DIpLabel" , "Grafieken 3D"},
                {"spotProblemsIpLabel" , "Stippelalgebra"},
                {"kladjeIpLabel" , "Kladje"},
                {"kansbomenIpLabel" , "Kansbomen"},
                {"rekenmachineIpLabel" , "Rekenmachine"},
                {"formStructIpLabel" , "FormStruct"},
                {"graphToolIpLabel" , "GraphTool"},
                {"draaibankIpLabel" , "Draaibank"},
                {"waarmakersIpLabel" , "Waarmakers"},
                {"statSimIpLabel" , "Statistieksimulaties"},
                {"stelselVakLabel", "Stelselantwoordvak"},
                {"javaLogoIpLabel", "Programmeren JavaLogo"},
                {"symboolIpLabel", "Vorm"},
                {"samengesteldeStappenIpLabel", "Samengestelde stappen"},
                {"checkButtonIpLabel", "Nakijkknop"},
                {"sliderIpLabel", "Schuifknop"},
                {"heksIpLabel", "Heks"},
                {"geoDefinerIpLabel", "GeoDefiner"},
                {"javaLogo3DIpLabel", "Programmeren JavaLogo 3D"},
                
                {"checkButtonsMenuLabel", "Nakijkknoppen"},
                
                {"kiesKoppelingLabel", "Kies een koppeling"},
                {"koppelingLabel", "Koppeling"},
                
                //CheckButtonEditor
                {"CB_kijkNaOptieLabel", "Kijk na" },
                {"CB_bewaarOptieLabel", "Bewaar" },
                {"CB_rondAfOptieLabel", "Rond af" },
                {"CB_nextPageOptieLabel", "Naar volgende pagina" },
                {"CB_eigenVakOptieLabel","Alles in eigen vak"},
                {"CB_opPaginaOptieLabel","Alles op pagina"},
                {"CB_viaXWidgetOptieLabel","Alles verbonden via x-widget"},
                
				//InstellingenPanel
                {"OPT_wiskundeLabel" , "Wiskunde"},
                {"OPT_navigatieLabel" , "Navigatie"},
                {"OPT_layoutLabel" , "Opmaak"},
                {"OPT_nakijkenLabel" , "Nakijken (algemeen)"},
				{"OPT_vermenigvTeken" , "Vermenigvuldigingsteken ×"},
				{"OPT_woordformules" , "Woordformules "},
				{"OPT_tweeHoofdletterVars" , "Twee-hoofdletter variabelen "},
				{"OPT_tempoToets" , "Tempotoets"},
				{"OPT_opnieuwKnop" , "'Alles opnieuw' mogelijk"},
				{"OPT_itemOpnieuwKnop" , "'Item opnieuw' mogelijk"},
				{"OPT_checkPerOpdracht" , "Check-knop per opdracht"},
				{"OPT_hoekInGraden" , "Hoekberekeningen in graden"},
				{"OPT_opdrachtBolletjes" , "Opdrachtnummers zichtbaar"},
				{"OPT_volgendeKnop" , "Volgende-knop zichtbaar"},	
				{"OPT_VorigeKnop" , "Vorige-knop zichtbaar"},
				{"OPT_paginaIpvOpdracht" , "Pagina ipv opdracht"},
				{"OPT_fontFormaat" , "Formaat"},
				{"OPT_fontNaam" , "Basis lettertype"},
				{"OPT_tijdsLimiet" , "Tijdslimiet (sec)"},
				{"OPT_formTimes" , "Formules in Times Roman"},
				{"OPT_navigatieFormaat" , "Maat navigatiebalk"},
				{"OPT_margesLabel" , "Marges:"},
				{"OPT_margeLinksLabel" , "Links"},
				{"OPT_margeRechtsLabel" , "Rechts"},
				{"OPT_margeBovenLabel" , "Boven"},
				{"OPT_margeOnderLabel" , "Onder"},
				{"OPT_fToets" , "F-toetsen voor formules"},
				{"OPT_globalParam" , "Globale parameters"},
				{"OPT_diffOperatoren" , "Differentiaaloperatoren"},
				{"OPT_voortgangKnop", "'Voortgang' in plaats van 'Totaal'"},
				{"OPT_conditionalNav" , "Voorwaardelijke navigatie"},
				{"OPT_conditionalPercLabel" , "Percentage"},
				{"OPT_voorwaarden", "Voorwaarden per pagina"},
				{"OPT_allesCorrect", "Pas door als alles correct (groen)"},
				{"OPT_deelOpdr" , "Deelopdrachten a,b,c etc"},
				{"OPT_zelftoetsGeenCorr" , "Geen correctiemogelijkheid zelftoets"},
				{"OPT_zelftoetsCorrAftrek" , "Puntenaftrek bij correctie zelftoets"},
				{"OPT_zelftoetsGeschiedenis" , "Zelftoets geschiedenis"},
				{"OPT_zelftoetsHighScore" , "Highscore"},
				{"OPT_eerderGeenCorr" , "Geen correctiemogelijkheid eerdere pagina's"},
				{"OPT_significantie" , "Checkmogelijkheid significante getallen"},
				{"OPT_objectives" , "Leerdoelen"},
				{"OPT_pilotObjectives", "Pilot"},
				{"OPT_misconceptions" , "Foutenanalyse"},
				{"OPT_fontOvererving" , "Font-overerving tekstvakken"},
				{"OPT_fontOverervingForm" , "Font-overerving formulevakken"},
				{"OPT_scoreZichtbaar" , "Scores zichtbaar voor leerling"},
				{"OPT_templateEditor" , "Template editor"},
				{"OPT_styles" , "Gebruik stijlen"},
				{"OPT_importStyles" , "Importeer"},
				{"OPT_exportStyles" , "Exporteer"},	
				{"OPT_layers" , "Gebruik lagen"},
				{"OPT_pageLabel" , "Pagina:"},
				{"OPT_docWidthLabel" , " Breedte"},
				{"OPT_docHeightLabel" , "Hoogte (min)"},
				{"OPT_combCompNav" , "Gedeelde componenten"},
				
				
				{"OBJ_leerdoel", "Leerdoel"},
				{"OBJ_categorie", "Vul naam in van categorie"},
				{"OBJ_categorieBox", "Leerdoelen in meerdere categorieen"},
				{"OBJ_kolomMeerButton", "Voeg kolom toe"},
				{"OBJ_kolomMinderButton", "Verwijder kolom"},
				{"MCC_misconception", "Foutenanalyse"},
				{"MCC_categorie", "Vul naam in van categorie"},
				{"MCC_categorieBox", "Foutenanalyse in meerdere categorieen"},
				
				
				//grafiekenEditPanel
				{"GEP_varLabel" , "Variabelen van de functie"},
				{"GEP_assenLabel" , "Weergave assenstelsel"},
				{"GEP_grafiekOptiesLabel" , "Opties grafiekentool"},
				
				{"GEP_varXLabel" , "Variabele x-as"},
				{"GEP_varYLabel" , "Variabele y-as"},
				
				{"GEP_assenOptie" , "Assen zichtbaar"},
				{"GEP_roosterOptie" , "Rooster"},
				{"GEP_roosterGrofOptie" , "grof"},
				{"GEP_schaalverdelingOptie" , "Schaalverdeling"},
				{"GEP_piOptie" , "Weergave Pi"},				
				
				{"GEP_zoomOptie" , "Zoom-optie"},
				{"GEP_traceOptie" , "Trace-optie"},
				{"GEP_dragOptie" , "Drag-Optie"},
				{"GEP_tekenOptie" , "Grafiek-tekentool"},
				
				{"GEP_tabelOptie" , "Tabel-tool"},
				{"GEP_zoomInTabelOptie" , "Zoom in tabel"},
				{"GEP_tabelTekenToolOptie" , "Tabel als tekentool"},
				
				{"GEP_functieEditOptie" , "FunctieEditor"},
				{"GEP_grafiekKleurenOptie" , "Verschillende kleuren"},
				{"GEP_formeleFunctieNotatieOptie" , "Formele functienotatie f(x), g(x) enz."},
				
				{"GEP_popupWeergave" , "Weergave via pop-up"},
				
				{"GEP_xPositief" , "x positief"},
				{"GEP_yPositief" , "y positief"},
				{"GEP_xEditable" , "x editable"},
				{"GEP_yEditable" , "y editable"},
				
				{"GEP_opdrachten" , "opdrachten"},
				
				{"GEP_kiesOpdracht" , "kies het type opdracht"},
				{"GEP_opdracht1" , "vind de formule bij een gegeven lijngrafiek"},
				{"GEP_opdracht2" , "vind de formule bij een aantal grafiekpunten"},
				{"GEP_opdracht3" , "teken een aantal punten bij een gegeven formule"},
				{"GEP_opdracht4" , "teken de punten uit de tabel in de grafiek"},
				
				{"GEP_antwoordFormule" , "voer in de funktie-editor hierbeneden de antwoordformule in"},
				{"GEP_tabelPuntenX" , "vul in de tabel de x-waarden van de grafiekpunten in" },
				{"GEP_tabelPunten" , "voer in de tabel hierbeneden de punten in" },
				
				{"GEP_nauwkeurigheid" , "Nauwkeurigheid (pixels)"},
				{"GEP_minimumPunten" , "Minimum aantal punten"},
				{"GEP_maximumScore" , "Maximum score"},
				{"GEP_leerlingZietTabel" , "Leerling ziet tabel"},
				
				{"GE_kijkNa" , "Kijk na" },
				
				//linkEditPanel
				{"LEP_linkTekst" , "Tekst"},
				{"LEP_url" , "URL"},
				{"LEP_vensterBreedte" , "Breedte van het window"},
				{"LEP_vensterHoogte" , "Hoogte van het window"},
				
				//ImageEditPanel
				{"IEP_toevoegen" , "Toevoegen"},
				{"IEP_verwijderen" , "Verwijderen"},
				{"IEP_ok" , "OK"},
				{"IEP_cancel" , "Annuleer"},
				{"editImageKnopLabel" , "Afbeelding nakijkknop"},
				
				//TekstVakEditPanel
				{"TVEP_randZichtbaar" , "Rand zichtbaar"},
				{"TVEP_achtergrondKleurAanwezig" , "Achtergrondkleur"},
				{"TVEP_zwevend" , "Zwevend boven de tekst"},
				{"TVEP_anderFont" , "Ander font"},
				{"TVEP_rondingHoeken" , "Ronding hoeken"},
				{"TVEP_rotatieHoek" , "Rotatiehoek"},
				{"TVEP_centreerHor" , "Centreer horizontaal"},
				{"TVEP_centreerVert" , "Centreer verticaal"},
				{"TVEP_pasAanH" , "Past hoogte aan"},
				{"TVEP_pasAanB" , "Past breedte aan"},
				{"TVEP_aantalRijen" , "Aantal rijen"},
				{"TVEP_aantalKolommen" , "Aantal kolommen"},
				{"TVEP_tabelRanden" , "Tabelranden"},
				{"TVEP_celMarge" , "Marge links"},
				{"TVEP_bovenMarge" , "Marge boven"},
				{"TVEP_fontType" , "Lettertype"},
				{"TVEP_achtergrondKleur" , "Kleur"},
				{"TVEP_interlinie" , "Interlinie"},
				{"TVEP_cellSpaceColumn" , "tussenr."},
				{"TVEP_cellSpaceRow" , "tussenr."},
				{"TVEP_layoutLabel" , "Opmaak tekstvak"},
                {"TVEP_gebruikersInteractieLabel" , "Interactie"},
                {"TVEP_selectieObject" , "Selectieobject"},
                {"TVEP_selectieKleur" , ""},
                {"TVEP_selectieKleurKnopLabel" , "Kleur"},
                {"TVEP_sleepObject" , "Sleepobject"},
                {"TVEP_draaiObject" , "Draaiobject"},
                {"TVEP_sleepDoel" , "Sleepdoel"},
                {"TVEP_sleepHandle" , "handvat"},
                {"TVEP_selectieSleepWaarde" , "waarde   ("},
                {"TVEP_fgKleurKnopLabel" , "Kleur"},
                {"TVEP_zichtbaarNaNakijken" , "Zichtbaar na nakijken toets"},
                {"TVEP_balansVergCom" , "Balans-Vergelijkingvak communicatie"},
                {"TVEP_aftrekPopup" , "Detectie gebruik popup-uitklapvak"},
                {"TVEP_callOut" , "Commentaarballon"},
                {"TVEP_vulHoogte" , "Hoogte opvullen"},
                {"TVEP_inklapbaar" , "In-/uitklapbaar"},
                {"TVEP_knopLinks" , "Knop links"},
                {"TVEP_knopRechts" , "Knop rechts"},
                {"TVEP_knopAchterTekst" , "Knop achter tekst"},
                {"TVEP_knopIsRegel1" , "Knop weg"},
                {"TVEP_uitwerkingenPopup" , "Uitwerking"},
                {"TVEP_random" , "random"},
                {"TVEP_linkObject" , "Linkobject"},
                {"TVEP_editLink" , "Edit link"},
                {"TVEP_defaultBijNull" , "default )"},
                {"TVEP_checkUitklapVak" , "check"},
                {"TVEP_logIDLabelLabel" , "label"},
                {"TVEP_puntenaftrek", "Puntenaftrek"},
                {"TVEP_visible", "Zichtbaar"},
                {"TVEP_styles", "Stijlen"},
                {"TVEP_manageStyles", "Manage Styles"},
                {"TVEP_ideasStatistiek", "Ideas Statistiek"},
                {"TVEP_templateMode", "Template modus"},
                {"TVEP_backButton", "Terugknop"},
                {"TVEP_hintButton", "Hintknop"},
                
                {"TVEP_noStyleChoiceLabel", "Geen"},
                {"TVEP_styleSettingsLabel", "Instellingen"},
                {"TVEP_stylesLabel", "Stijl:"},
                {"TVEP_editStylesButton", "Bewerk"},
                
                //Style Manager
                {"SM_titelLabel", "Stijlen beheren"},
                {"SM_addStyleButton", "Instellingen opslaan als nieuwe stijl"},
                {"SM_saveStyleButton", "Stijl opslaan"},
                {"SM_removeStyleButton", "Stijl verwijderen"},
                {"SM_closeButton", "Sluiten"},
                {"SM_addStyleAction", "Geef stijlnaam"},
                
                //Text Editor tooltips
                {"TE_formuleButtonTooltip", "Formule invoegen"},
                {"TE_graphButtonTooltip", "Grafiek invoegen"},
                {"TE_linkButtonTooltip", "Link invoegen"},
                {"TE_imageButtonTooltip", "Afbeelding invoegen"},
                {"TE_answerboxButtonTooltip", "Antwoordvak invoegen"},
                {"TE_widgetButtonTooltip", "Widget invoegen"},
                {"TE_geogebraButtonTooltip", "GeoGebra invoegen"},
                {"TE_tekstVakButtonTooltip", "Tekstvak invoegen"},
                {"TE_compositeButtonTooltip", "Samengesteld component invoegen"},
                {"TE_templateCompButtonTooltip", "Component met templateopmaak invoegen"},
                {"TE_templateButtonTooltip", "Templatepagina kiezen"},
                {"TE_x-widgetButtonTooltip", "Koppelingen tussen componenten"},
                {"TE_parameterButtonTooltip", "Random parameter gebruiken"},
                {"TE_opsommingButtonTooltip", "Opsomming invoegen"},
                {"TE_vormenButtonTooltip", "Vorm invoegen"},
                {"TE_geodefinerButtonTooltip", "GeoDefiner invoegen"},
                
                
				//GeogebraEditPanel
				{"GEP_bewaarOptie" , "Bewaaroptie"},
				{"GEP_alsTool" , "Als tool"},
				{"GEP_rand" , "Rand"},
				{"GEP_resetIcon" , "Reset-optie"},
				{"GEP_checkMetCheckDWO" , "m.b.v checkDWO"},
				{"GEP_checkMetObjecten" , "m.b.v objecten"},
				
				
				//GetallenLijnSprongEditPanel
				{"GSEP_minValue" , "Kleinste waarde"},
				{"GSEP_maxValue" , "Grootste waarde"},
				{"GSEP_eenheden" , "Eenheden zichtbaar"},
				{"GSEP_getallen" , "Getallen"},
				{"GSEP_10tallen" , "10-tallen zichtbaar"},
				{"GSEP_5tallen" , "5-tallen zichtbaar"},
				{"GSEP_nul" , "Nul"},
				{"GSEP_pijl" , "Pijl zichtbaar"},
				{"GSEP_pijlTerug" , "Pijl terug"},
				{"GSEP_horizontaal" , "Horizontaal"},
				{"GSEP_eenheid" , "Eenheid"},
				
				
				
				//TekstEditorEditPanel
				{"TEEP_menuBalkOptie" , "Formule-editor"},
				{"TEEP_rekenToolOptie" , "Rekenmachine"},
				{"TEEP_grafToolOptie" , "Grafiekentool"},
				{"TEEP_titleStartLabel", "Tekstantwoordvak bij opstarten"},
				{"TEEP_checkDocentCBLabel", "Nakijken (door docent)"},
				{"TEEP_maxScoreLabel", "Maximale score"},
				{"TEEP_editorOptiesLabel", "Editoropties"},
				
				//Ideas
				{"ideasTip",		"tip"},
				{"ideasHelp",		"help"},
				{"ideasStap",		"stap"},
				{"ideasLosop",		"losop"},
				{"ideasWordtDan",		"wordt dan"},
				
				{"algebra.equations.coverup.denominator"		,"bordjesmethode toepassen (bordje op de noemer)"	},
				{"algebra.equations.coverup.minus-left"			,"constante termen naar rechts brengen"	},
				{"algebra.equations.coverup.minus-right"		,"bordjesmethode toepassen"	},
				{"algebra.equations.coverup.negate"				,"delen door -1"	},
				{"algebra.equations.coverup.numerator"			,"bordjesmethode toepassen (bordje op de teller)"	},
				{"algebra.equations.coverup.plus"				,"constante termen naar rechts brengen"	},
				{"algebra.equations.coverup.power"				,"worteltrekken"	},
				{"algebra.equations.coverup.sqrt"				,"kwadrateren"	},
				{"algebra.equations.coverup.times"				,"variabele vrijmaken door beide kanten te delen"	},
				{"algebra.equations.coverup.times-positive"		,"variabele vrijmaken door beide kanten te delen"	},
				{"algebra.equations.coverup.onevar.minus-left"	,"constante termen naar rechts brengen door aan beide kanten een getal op te tellen"	},
				//{"algebra.equations.coverup.onevar.minus-right"	,""	},
				{"algebra.equations.coverup.onevar.plus"		,"constante termen naar rechts brengen door aan beide kanten een getal af te trekken"	},
				
				{"algebra.equations.linear.distr-times"		,"haakjes uitwerken"	},
				{"algebra.equations.linear.flip"			,"de vergelijking omdraaien"	},
				{"algebra.equations.linear.merge"			,"vereenvoudigen door samenvoegen of uitrekenen"	},
				//{"algebra.equations.linear.norm-mixed"		,""	},
				//{"algebra.equations.linear.norm-rational"	,""	},
				{"algebra.equations.linear.remove-div"		,"breukvormen verwijderen door te vermenigvuldigen met een getal"	},
				{"algebra.equations.linear.var-left"		,"termen met variabele naar links brengen"	},
				
				{"algebra.equations.buggy.cancel-minus"				,"termen kunnen niet weggestreept worden want het teken verschilt"	},
				{"algebra.equations.buggy.distr-times-denom"		,"haakjes verkeerd uitgewerkt: een van de termen is een breuk en de factor is vermenigvuldigd met de noemer van de breuk."	},
				{"algebra.equations.buggy.distr-times-plus"			,"bij haakjes wegwerken is een van de termen niet vermenigvuldigd"	},
				{"algebra.equations.buggy.distr-times-plus-forget"	,"bij haakjes wegwerken is een van de termen vergeten"	},
				{"algebra.equations.buggy.distr-times-plus-sign"	,"Let op de tekens bij haakjes wegwerken"	},
				{"algebra.equations.buggy.distr-times-too-many"		,"bij haakjes wegwerken alleen de termen tussen de haakjes vermenigvuldigen"	},
				{"algebra.equations.buggy.divide-negate"			,"Let op het teken bij delen"	},
				{"algebra.equations.buggy.divide-numdenom"			,"breuk omgekeerd. Bedenk door welk getal je moet delen"	},
				{"algebra.equations.buggy.flip-negate-one-side"		,"Bij teken veranderen moet dit aan beide kanten"	},
				{"algebra.equations.buggy.multiply-one-side"		,"Bij vermenigvuldigen aan beide kanten is een kant vergeten"	},
				{"algebra.equations.buggy.minus-minus"				,"Bij haakjes wegwerken: min maal min is plus"	},
				{"algebra.equations.buggy.multiply-forget-one"		,"Bij vermenigvuldigen aan beide kanten is een van de termen vergeten"	},
				{"algebra.equations.buggy.negate-all"				,"bij alle termen van teken veranderen is een term vergeten"	},
				{"algebra.equations.buggy.negate-one-side"			,"bij beide kanten van teken veranderen is een kant vergeten"	},
				{"algebra.equations.buggy.plus"						,"let op het teken als je een term naar de andere kant brengt"	},
				{"algebra.equations.buggy.priority-times"			,"let op de voorrangsregels of haakjes"	},
				
				{"algebra.equations.buggy.abc.minus-4ac"				,"let op: D=b^2-4ac en geen D=b^2+4ac"	},
				{"algebra.equations.buggy.abc.minus-b"					,"let op het minteken voor de b: "	},
				{"algebra.equations.buggy.abc.one-solution"				,"er is nog een tweede oplossing"	},
				{"algebra.equations.buggy.abc.two-a"					,"delen door 2a en niet a"	},
				{"algebra.equations.buggy.coverup.even-power"			,"je vergeet de ander (negatieve) wortel"	},
				{"algebra.equations.buggy.coverup.even-power-forget"	,"Voordat je wortels trekt is eerst nog een andere bewerking nodig"	},
				{"algebra.equations.buggy.coverup.even-power-too-early"	,"Voordat je wortels trekt is eerst nog een andere bewerking nodig"	},
				{"algebra.equations.buggy.coverup.square-minus"			,"je kunt geen wortel trekken uit een negatief getal"	},
				{"algebra.equations.buggy.coverup.times-mul"			,"in plaats van de rechterkant te delen vermenigvuldig je deze"	},
				{"algebra.equations.buggy.coverup.times-with-plus"		,"als je deelt moet je alle termen delen"	},
				{"algebra.equations.buggy.distr-square"					,"bij kwadrateren van een tweeterm is het dubbel product vergeten"	},
				{"algebra.equations.buggy.distr-square-forget"			,"bij kwadrateren van een tweeterm een van de termen vergeten"	},
				{"algebra.equations.buggy.square-multiplication"		,"term met twee factoren niet juist gekwadrateerd"	},
				{"algebra.equations.buggy.division-by-var-both"		,"bij delen door een variabele verlies je de oplossing var=0"	},
				{"algebra.equations.buggy.division-by-var-zero"		,"bij delen door een variabele verlies je de oplossing var=0"	},
				{""		,""	},
				
				

				
				
				{"algebra.equations.linear.balance.collect"			,"samenvoegen"	},
				{"algebra.equations.linear.balance.calculate"		,"berekenen"	},
				{"algebra.equations.linear.balance.div-to-fraction"		,"schrijf deling als vermenigvuldiging met een breuk"	},
				{"algebra.equations.linear.balance.smart-div"		,"deel door een gemeenschappelijke factor"	},
				{"algebra.equations.linear.balance.con-right-minus"	,"van beide kanten {?} aftrekken"	},
				{"algebra.equations.linear.balance.con-left-minus"	,"van beide kanten {?} aftrekken"	},
				{"algebra.equations.linear.balance.var-right-minus"	,"van beide kanten {?} aftrekken"	},
				{"algebra.equations.linear.balance.var-left-minus"	,"van beide kanten {?} aftrekken"	},
				{"algebra.equations.linear.balance.con-right-plus"	,"aan beide kanten {?} erbij optellen"	},
				{"algebra.equations.linear.balance.con-left-plus"	,"aan beide kanten {?} erbij optellen"	},
				{"algebra.equations.linear.balance.var-right-plus"	,"aan beide kanten {?} erbij optellen"	},
				{"algebra.equations.linear.balance.var-left-plus"	,"aan beide kanten {?} erbij optellen"	},
				{"algebra.equations.linear.balance.distribute"		,"haakjes uitwerken"	},
				{"algebra.equations.linear.balance.remove-div"		,"beide kanten vermenigvuldigen met {?}"	},
				{"algebra.equations.linear.balance.scale-to-one"	,"beide kanten delen door {?}"	},
				{"algebra.equations.linear.balance.negate"    ,"maak beide kanten tegengesteld"  },
				{"algebra.equations.linear.balance.intro-false"    ,"kan niet"  },
				{"algebra.equations.linear.balance.intro-true"    ,"klopt altijd"  },
                //{"algebra.equations.linear.balance.var-left"		,"van beide kanten {?} aftrekken"	},
				
				{"algebra.equations.quadratic.abc"				,"de abc-formule toepassen"	},
				{"algebra.equations.quadratic.approx"			,"een benadering geven"	},
				{"algebra.equations.quadratic.cancel"			,"termen wegstrepen aan beiden kanten van het =-teken"	},
				{"algebra.equations.quadratic.common-factor"	,"factor buiten haakjes halen"	},
				{"algebra.equations.quadratic.distr-div"		,"uitdelen"	},
				{"algebra.equations.quadratic.distr-square"		,"kwadraat uitwerken"	},
				{"algebra.equations.quadratic.left-square"		,"schrijf linkerkant als kwadraat"	},
				{"algebra.equations.quadratic.move-left"		,"alles naar links brengen"	},
				{"algebra.equations.quadratic.nice-factors"		,"drieterm ontbinden"	},
				{"algebra.equations.quadratic.no-lin"			,"schrijf als kwadraat=getal"	},
				{"algebra.equations.quadratic.prepare-split"	,"aanvullen tot een kwadraat"	},
				{"algebra.equations.quadratic.product-zero"		,"product=0, factoren nul stellen"	},
				{"algebra.equations.quadratic.same-con-factor"	,"beide kanten delen door een gemeenschappelijke factor"	},
				{"algebra.equations.quadratic.same-factor"		,"A*B=A*C geeft A=0 of B=C"	},
				//{"algebra.equations.quadratic.scale"			,""	},
				{"algebra.equations.quadratic.simpler-poly"		,"vereenvoudigen door een factor uitdelen"	},
				{"algebra.equations.quadratic.simpler-sqrt"		,"wortels vereenvoudigen"	},
				{"algebra.equations.quadratic.square-both"		,"kwadrateer beide kanten"	},
				
				
				
				{"algebra.equations.polynomial.back-subst"			,"substitutie terugbrengen"	},
				{"algebra.equations.polynomial.expose-factor"		,"maak gemeenschappelijk factor zichtbaar"	},
				{"algebra.equations.polynomial.power-factors"		,"gemeenschappelijke factor x"	},
				{"algebra.equations.polynomial.subst"				,"substitutie gebruiken"	},
				//{"algebra.equations.polynomial.factor-varpower"		,""	},
				//{"algebra.equations.polynomial.simpler-linfactor"	,""	},
				{"algebra.equations.polynomial.def-power-nat"   	,"schrijf de macht als herhaalde vermenigvuldiging"},
				
				
				{"algebra.equations.rational.check-solution"	,"controleer de oplossing"	},
				{"algebra.equations.rational.cross-multiply"	,"kruislings vermenigvuldigen"	},
				{"algebra.equations.rational.division-one"		,"bij breuk=1 geldt teller = noemer"	},
				{"algebra.equations.rational.division-zero"		,"bij breuk=0 geldt teller=0 (indien noemer ongelijk nul)"	},
				{"algebra.equations.rational.multiply-one-div"	,"bemenigvuldig beide kanten met de noemer van de breuk"	},
				{"algebra.equations.rational.same-dividend"		,"A/B=A/C geeft A=0 of B=C"	},
				{"algebra.equations.rational.same-divisor"		,"zelfde noemer, stel tellers aan elkaar gelijk"	},
				
				{"algebra.inequalities.flip-sign"		,"teken omkeren"	},
				{"algebra.inequalities.give-solution"	,"geef oplossing van de ongelijkheid"	},
				{"algebra.inequalities.to-equation"		,"maak er eerst een vergelijking van"	},
				//{"algebra.inequalities.trivial"			,""	},
				
				{"algebra.manipulation.exponents.add-exponents"			,"vermenigvuldig de machten door de exponenten op te tellen"	},
				{"algebra.manipulation.exponents.factor-as-power"		,"schrijf (onderdelen) als macht "	},
				{"algebra.manipulation.exponents.mul-exponents"			,"een macht tot de macht: vermenigvuldig de exponenten"	},
				{"algebra.manipulation.exponents.reciprocal"			,"schrijf 1/getal als getal^-1"	},
				{"algebra.manipulation.exponents.simple-add-exponents"	,"schrijf als macht door exponenten op te tellen"	},
				{"algebra.manipulation.exponents.sub-exponents"			,"deel de machten door exponenten van elkaar af te trekken"	},
				{"algebra.manipulation.exponents.write-as-power"		,"schrijf als macht"	},
				//{"algebra.manipulation.exponents.calc-power.minus"		,""	},
				//{"algebra.manipulation.exponents.calc-power.plus"		,""	},
				{"algebra.manipulation.exponents.distr-power"			,"gebruik: macht van een product is product van de machten"	},
				//{"algebra.manipulation.exponents.distr-power-div"		,""	},
				//{"algebra.manipulation.exponents.power-zero"			,""	},
				{"algebra.manipulation.exponents.reciprocal-inverse"	,"schrijf de macht getal^-1 als breuk: 1/getal"	},
				{"algebra.manipulation.exponents.write-as-root"			,"schrijf als wortel"	},
				{"algebra.manipulation.exponents.reciprocal-var"		,"schrijf 1/macht als nieuwe macht met tegengestelde exponent"	},
				{"algebra.manipulation.exponents.push-negation-out"		,"minteken buiten de macht brengen (bij oneven exponent)"	},
				//{"algebra.manipulation.exponents.power-ratio"			,""	},
				{"algebra.manipulation.exponents.root"					,"geef wortel"	},
				
				{"algebra.manipulation.exponents.equation.equals-one"		,"macht=1 geeft exponent=0"	},
				{"algebra.manipulation.exponents.equation.same-base"		,"zelfde grondtal"	},
				{"algebra.manipulation.exponents.equation.approx-power"		,"benader deze macht of wortel"	},
				{"algebra.manipulation.exponents.equation.common-power"		,"gemeenschappelijke macht"	},
				{"algebra.manipulation.exponents.equation.greatest-power"	,"schrijf met grootste gemeenschappelijke macht"	},
				{"algebra.manipulation.exponents.equation.nth-root"			,"n-de wortel"	},
				
				{"algebra.manipulation.logarithmic.logarithm"		,"gebruik log definitie: glog(x)=a geeft x=g^a"	},
				
				//{"arithmetic.operation.rational.power"				,""	},
				
				{"calculus.differentiation.deriv-of-poly"		,"differentieer machtsfunctie"	},
				{"calculus.differentiation.min"		,"verschilregel toepassen"	},
				{"calculus.differentiation.negate"		,"minteken naar buiten halen voor differentieren"	},
				{"calculus.differentiation.plus"		,"somregel toepassen"	},
				{"calculus.differentiation.product"		,"productregel toepassen"	},
				{"calculus.differentiation.quotient"		,"quotientregel toepassen"	},
				{""		,""	},
				
				{"algebra.equations.linear.balance.buggy.addbal1"		,"addbal1. Je trekt er links {?} vanaf maar rechts tel je {?} erbij op."	},
				{"algebra.equations.linear.balance.buggy.addbal2"		,"addbal2. Je telt er links {?} bij op maar rechts trek je {?} ervan af."	},
				{"algebra.equations.linear.balance.buggy.addbal3"		,"addbal3. Je trekt er rechts {?} vanaf, maar links tel je {?} erbij op."	},
				{"algebra.equations.linear.balance.buggy.addbal4"		,"addbal4. Je telt er rechts {?} bij op, maar links trek je {?} er vanaf."	},
				{"algebra.equations.linear.balance.buggy.addbal5"		,"addbal5. Je trekt er links {?}  vanaf, maar rechts doe je dat niet"	},
				{"algebra.equations.linear.balance.buggy.addbal6"		,"addbal6. Je telt er links {?} bij op, maar rechts doe je dat niet"	},
				{"algebra.equations.linear.balance.buggy.addbal7"		,"addbal7. Je trekt er links {?} vanaf maar rechts tel je {?} erbij op."},
				{"algebra.equations.linear.balance.buggy.addbal8"		,"addbal8. Je telt er links {?} bij op maar rechts trek je {?} ervan af."} ,
				{"algebra.equations.linear.balance.buggy.addbal9"       ,"addbal9. Je trekt er rechts {?} vanaf, maar links tel je {?} erbij op."},
                {"algebra.equations.linear.balance.buggy.addbal10"      ,"addbal10. Je telt er rechts {?} bij op, maar links trek je {?} er vanaf."},
                {"algebra.equations.linear.balance.buggy.addbal11"      ,"addbal11. Je trekt er rechts {?}  vanaf, maar links doe je dat niet"},
                {"algebra.equations.linear.balance.buggy.addbal12"      ,"addbal12. Je telt er rechts {?} bij op, maar links doe je dat niet"},
                {"algebra.equations.linear.balance.buggy.addbal13"      ,"addbal13. Je trekt er links {?}  vanaf, maar rechts doe je dat niet"},
                {"algebra.equations.linear.balance.buggy.addbal14"      ,"addbal14. Je telt er links {?} bij op, maar rechts doe je dat niet"},
                {"algebra.equations.linear.balance.buggy.addbal15"      ,"addbal15. Je trekt er rechts {?}  vanaf, maar links doe je dat niet"},
                {"algebra.equations.linear.balance.buggy.addbal16"      ,"addbal16. Je telt er rechts {?} bij op, maar links doe je dat niet"},
                {"algebra.equations.linear.balance.buggy.flip1"		,"flip1. links en rechts niet alleen verwisseld, maar aan een kant het teken veranderd"	},
				{"algebra.equations.linear.balance.buggy.misc1"		,"misc1. rechts heb je er iets van afgetrokken, maar doe je dat links ook?"	},
				{"algebra.equations.linear.balance.buggy.misc2"		,"misc2. je vermenigvuldigt met een getal, maar niet de hele linkerkant"	},
				{"algebra.equations.linear.balance.buggy.misc3"		,"misc3. je neemt het tegengestelde, maar links niet volledig"	},
				{"algebra.equations.linear.balance.buggy.misc4"		,"misc4. je deelt door een getal, maar niet de hele linkerkant"	},
				{"algebra.equations.linear.balance.buggy.mulbal1"		,"mulbal1. je deelt door {?}, maar rechts keer je de deling om"	},
				{"algebra.equations.linear.balance.buggy.mulbal2"		,"mulbal2. de linkerkant vermenigvuldig je met {1} en de rechterkant met {2}"	},
				{"algebra.equations.linear.balance.buggy.mulbal3"		,"mulbal3. de linkerkant vermenigvuldig je met {?}, de rechterkant niet"	},
				{"algebra.equations.linear.balance.buggy.mulbal4"		,"mulbal4. de linkerkant deel je door {?}, de rechterkant niet"	},
				{"algebra.equations.linear.balance.buggy.mulbal5"		,"mulbal5. de linkerkant maak je tegengesteld, de rechterkant niet"	},
				{"algebra.equations.linear.balance.buggy.mulbal6"		,"mulbal6. de ene kant deel je door {?}, de andere kant niet"	},
				{"algebra.equations.linear.balance.buggy.multiply1"		,"multiply1. fout bij het vermenigvuldigen (1)"	},
				{"algebra.equations.linear.balance.buggy.multiply2"		,"multiply2. fout bij het vermenigvuldigen (2)"	},
				{"algebra.equations.linear.balance.buggy.multiply3"		,"multiply3. fout bij het vermenigvuldigen, je raakt de min kwijt"	},
				{"algebra.equations.linear.balance.buggy.multiply4"		,"multiply4. fout bij het vermenigvuldigen, min maal min is plus"	},
				{"algebra.equations.linear.balance.buggy.multiply5"		,"multiply5. fout bij delen, je deelt door een negatief getal"	},
				{"algebra.equations.linear.balance.buggy.par1"		,"par1. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (1)"	},
				{"algebra.equations.linear.balance.buggy.par10"		,"par10. denk aan de voorrangsregels, eerst vermenigvuldigen, dan optellen"	},
				{"algebra.equations.linear.balance.buggy.par11"		,"par11. minteken niet op de juiste manier binnen de haakjes gebracht"	},
				{"algebra.equations.linear.balance.buggy.par2"		,"par2. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (2)"	},
				{"algebra.equations.linear.balance.buggy.par4"		,"par4. fout bij haakjes wegwerken, rekenfout bij vermenigvuldigen (1)"	},
				{"algebra.equations.linear.balance.buggy.par5"		,"par5. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (3)"	},
				{"algebra.equations.linear.balance.buggy.par6"		,"par6. fout bij haakjes wegwerken, vermenigvuldig beide termen tussen de haakjes (4)"	},
				{"algebra.equations.linear.balance.buggy.par7"		,"par7. fout bij haakjes wegwerken, beide termen tussen de haakjes maal -1"	},
				{"algebra.equations.linear.balance.buggy.par8"		,"par8. fout bij haakjes wegwerken, kijk goed waar de haakjes staan"	},
				{"algebra.equations.linear.balance.buggy.par9"		,"par9. fout bij haakjes wegwerken, rekenfout bij vermenigvuldigen (2)"	},
				
				//conditionele navigatie-panels
				{"CN_voorwaarden", "Voorwaarden"},
				{"CN_vanPagina","Van pagina"},
				{"CN_naarPagina","Naar pagina"},
				{"CN_scorePagina","Pagina's voor score"},
				{"CN_grensPercentage","Grenspercentage"},
				{"CN_sorteer", "Sorteer"},
				{"CN_regelMeer", "Voeg regel toe"},
				{"CN_regelMinder", "Verwijder regel"},
					
				//layer panels
				{"L_layers", "Lagen"},
				{"L_layerName", "Laag-naam"},
				{"L_layerVisible","Zichtbaar"},
				
				{"CBA_input", "invoer"},
				{"CBA_int.index", "keuze" },
				{"CBA_balansvergelijking", "balansvergelijking"},
				{"CBA_zetOplossing", "zet oplossing" },
				{"CBA_maakStap", "maak stap" },
				{"CBA_vergelijking", "vergelijking" },
				{"CBA_double", "numerieke waarde"},
				{"CBA_double.solution", "oplossing"},
				{"CBA_expression", "expressie"},
				{"CBA_equation", "vergelijking"},
				{"CBA_double.xcoordinate", "x-coordinaat"},
				{"CBA_double.ycoordinate", "y-coordinaat"},
				{"CBA_text", "tekst"},
				{"CBA_text.choice", "keuze"},
				{"CBA_text.feedback", "feedback"},
				{"CBA_text.content", "inhoud"},
				{"CBA_action.setNotEditable", "Actie: zet tekstinvoer uit"},
				{"CBA_action.unfold", "Actie: uitklappen"},
				{"CBA_action.fold", "Actie: inklappen"},
				{"CBA_action.correct", "Actie: correct antwoord"},
				{"CBA_action.false", "Actie: fout antwoord"},
				{"CBA_action.false_2", "Actie: 2x fout antwoord"},
				{"CBA_action.half", "Actie: halfgoed antwoord"},
				{"CBA_action.setVisible", "Actie: maak zichtbaar"},
				{"CBA_action.setNotVisible", "Actie: maak onzichtbaar"},
				{"CBA_action.select", "Actie: selecteer"},
				{"CBA_action.deselect", "Actie: deselecteer"},
				{"CBA_action.check", "Actie: kijk na"},
				{"CBA_action.click", "Actie: klik"},
				{"CBA_action.popup", "Actie: popup"},
				
				{"oplossingenLabel", "Oplossingen"},
				{"executeLabel", "Uitvoeren"},
				
				//symbolen
				{"SYM_kiesSymbool", "Kies vorm"},
				{"SYM_lijn", "Lijn"},
				{"SYM_pijl", "Pijl"},
				{"SYM_accolade", "Accolade"},
				{"SYM_ellips", "Ellips"},
				{"SYM_haak", "Haak"},
				{"SYM_kiesEerstSymbool", "Kies eerst symbool"},
				{"SYM_dikte", "Dikte"},
				{"SYM_kleur", "Kleur"},
				{"SYM_kiesKleur", "Kies kleur"},
				{"SYM_vulHoogte", "Vul hoogte"},
								
				{"SYM_horizontaal", "Horizontaal"},
				{"SYM_verticaal", "Verticaal"},
				{"SYM_diagonaalOmhoog", "Diagonaal omhoog"},
				{"SYM_diagonaalOmlaag", "Diagonaal omlaag"},
				{"SYM_links", "Links"},
				{"SYM_rechts", "Rechts"},
				{"SYM_boven", "Boven"},
				{"SYM_beneden", "Beneden"},
				{"SYM_rechtsboven", "Rechtsboven"},
				{"SYM_rechtsonder", "Rechtsonder"},
				{"SYM_linksonder", "Linksonder"},
				{"SYM_linksboven", "Linksboven"},
				{"SYM_geenRichting", "Geen richting"},
				
				{"Steps_statistics", "Domain reasoner statistiek"},
				{"Steps_action", " Actie"},
				{"Steps_nrOfSteps", "Aantal verschillende stappen"},
				{"Steps_name", "Stapnaam"},
				{"Steps_content", "Stapinhoud"},
				{"Steps_required", "Vereist"},
				
				// opdr nav struct
				{"ONS_timeisup", "De tijd is om"},
				{"ONS_timeready", "Op tijd klaar"},
				{"ONS_timesChecked", "{0} keer nagekeken" },
				{"ONS_1timeChecked", "één keer nagekeken"},
				
				// shareAction
				{ ShareAction.SHARE_KEY, "gedeelde sleutel"},
				{ ShareAction.SHARE_MAP, "Gedeelde componenten" },
// tablet opties
				{ "Tablet keyboard", "Tablet toetsenbord" },
				{ "Onderbouw-keyboard", "Onderbouw-toetsenbord" },
				{ "Algebra-keyboard", "Algebra-toetsenbord" },
				{ "Gonio-keyboard", "Gonio-toetsenbord" },
				{ "Statistiek-keyboard", "Statistiek-toetsenbord" },
				{ "Meetkunde-keyboard", "Meetkunde-toetsenbord" },
				{ "Tablet handschriftset", "Tablet handschriftset" },
				{ "Basis", "Basis" },
				{ "Uitgebreid", "Uitgebreid" },
		
				{ "needsPremium", "Voor deze activiteit is een premium abonnement nodig." },
				
				{ "LinkType_FALSE", "default (nieuw window)" },
				{ "LinkType_TRUE", "embedded" },
				{ "LinkType_PLAYER", "eigen window"},
				{ "LinkType_CLIENT", "applicatie window"},
				{ "LinkType_TOP", "top window"},
				
				{ "TCOMP_list" , "Opsomming"},
				{ "TCOMP_list_settings" , "Instellingen opsomming"},
				{ "TCOMP_list_rowCount" , "Aantal items"},
				{ "TCOMP_list_numberType" , "Type opsommingsteken"},
				{ "TCOMP_list_chooseType" , "Kies type"},
				{ "TCOMP_list_tabWidth" , "Inspringing"},
				{ "TCOMP_list_rowSpace" , "Afstand items"},
				{ "TCOMP_first_list_number" , "Startnummer"},
				
				{ "TCOMP_multip" , "Meerkeuzeopdracht"},
				{ "TCOMP_multip_settings" , "Instellingen meerkeuzeopdracht"},
				{ "TCOMP_multip_rowCount" , "Aantal keuzes"},
                { "TCOMP_multip_numberType" , "Type opsommingsteken"},
                { "TCOMP_multip_chooseType" , "Kies type"},
                { "TCOMP_multip_tabWidth" , "Inspringing"},
                { "TCOMP_multip_rowSpace" , "Afstand items"},
				{ "TCOMP_multip_hasPrefix" , "Opsommingsteken"},
				
				{ "TCOMP_drag" , "Sleepopdracht"},
				{ "TCOMP_drag_settings" , "Instellingen sleepopdracht"},
				{ "TCOMP_drag_rowCount" , "Aantal sleepobjecten"},
				{ "TCOMP_drag_itemWidth" , "Breedte sleepobject"},
				{ "TCOMP_drag_itemHeight" , "Hoogte sleepobject"},
				{ "TCOMP_drag_rowSpace" , "Afstand items"},
				{ "TCOMP_drag_descrWidth" , "Breedte tekst"},
				
				{ "TCOMP_edit" , "Bewerk"},
				{ "TCOMP_addItem" , "Item toevoegen"},
				{ "TCOMP_removeItem" , "Item verwijderen"},
				{ "TCOMP_decompose" , "Ontbinden"},
				
				// Helpteksten (URL's)
				{ "HELP_0_URL_0" , "https://app.dwo.nl/dwo/apps/player.html?t=0&profile=106&locale=nl#670053"},
				{ "HELP_0_URL_2" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#670047"},
				{ "HELP_0_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#670050"},
				{ "HELP_0_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#670051"},
				{ "HELP_0_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#670052"},
				{ "HELP_0_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#670057"},
				{ "HELP_0_URL_REKENMACHINE" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#670058"},
				{ "HELP_0_URL_SUBSTITUTIES" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#670059"},
				{ "HELP_0_URL_CONTEXTVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#670060"},
				{ "HELP_0_URL_EIGENOPDR" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#670061"},
				{ "HELP_0_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#670062"},
				{ "HELP_0_URL_UITWERKING" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#670063"},
				{ "HELP_0_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#670064"},
				{ "HELP_0_URL_VERIFICATIE" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#671063"},
				{ "HELP_0_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671064"},
				{ "HELP_0_URL_STARTEXPRESSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671065"},
				{ "HELP_0_URL_SCORE" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=106&locale=nl#671066"},
				{ "HELP_0_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671067"},
				
				{ "HELP_1_URL_3" , "https://app.dwo.nl/dwo/apps/player.html?t=0&profile=106&locale=nl#671144"},
				{ "HELP_1_URL_1" , "https://app.dwo.nl/dwo/apps/player.html?t=1&profile=106&locale=nl#671145"},
				{ "HELP_1_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671146"},
				{ "HELP_1_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671147"},
				{ "HELP_1_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671148"},
				{ "HELP_1_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671149"},
				{ "HELP_1_URL_LINSTRATEGIEVERSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#671150"},
				{ "HELP_1_URL_LINSTARTEGIEOEFENVERSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#671151"},
				{ "HELP_1_URL_BORDJESVERSIE" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671152"},
				{ "HELP_1_URL_BEWERKINGSKNOPPEN" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671153"},
				{ "HELP_1_URL_UITWERKINGSKNOPPENEXTRA" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671154"},
				{ "HELP_1_URL_SUBSTITUTIES" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671156"},
				{ "HELP_1_URL_ABC" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671155"},
				{ "HELP_1_URL_CONTEXTVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=13&profile=106&locale=nl#671157"},
				{ "HELP_1_URL_EIGENOPDR" , "https://app.dwo.nl/dwo/apps/player.html?t=14&profile=106&locale=nl#671158"},
				{ "HELP_1_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=15&profile=106&locale=nl#671159"},
				{ "HELP_1_URL_UITWERKING" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=106&locale=nl#671160"},
				{ "HELP_1_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671161"},
				{ "HELP_1_URL_PIJL" , "https://app.dwo.nl/dwo/apps/player.html?t=18&profile=106&locale=nl#671162"},
				{ "HELP_1_URL_VERIFICATIE" , "https://app.dwo.nl/dwo/apps/player.html?t=19&profile=106&locale=nl#671163"},
				{ "HELP_1_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=20&profile=106&locale=nl#671164"},
				{ "HELP_1_URL_BEREKENANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=21&profile=106&locale=nl#671168"},
				{ "HELP_1_URL_STARTVERGELIJKING" , "https://app.dwo.nl/dwo/apps/player.html?t=22&profile=106&locale=nl#671165"},
				{ "HELP_1_URL_SCORE" , "https://app.dwo.nl/dwo/apps/player.html?t=16&profile=236&locale=nl#671166"},
				{ "HELP_1_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=24&profile=106&locale=nl#671167"},
				
				{ "HELP_53_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671209"},
				{ "HELP_53_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671210"},
				{ "HELP_53_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671211"},
				{ "HELP_53_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671212"},
				{ "HELP_53_URL_REKENVAKZICHTBAAR" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671213"},
				{ "HELP_53_URL_OPLOSSINGREGEL" , "https://app.dwo.nl/dwo/apps/player.html?t=6&profile=106&locale=nl#671214"},
				{ "HELP_53_URL_CONTEXTVAR" , "https://app.dwo.nl/dwo/apps/player.html?t=7&profile=106&locale=nl#671215"},
				{ "HELP_53_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671216"},
				{ "HELP_53_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671217"},
				{ "HELP_53_URL_VERIFICATIE" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671218"},
				{ "HELP_53_URL_VARIABELEN" , "https://app.dwo.nl/dwo/apps/player.html?t=11&profile=106&locale=nl#671219"},
				{ "HELP_53_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671220"},
				
				{ "HELP_13_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671323"},
				{ "HELP_13_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671307"},
				{ "HELP_13_URL_TELTMEE" , "https://app.dwo.nl/dwo/apps/player.html?t=3&profile=106&locale=nl#671308"},
				{ "HELP_13_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671309"},
				{ "HELP_13_URL_FEEDBACK" , "https://app.dwo.nl/dwo/apps/player.html?t=5&profile=106&locale=nl#671310"},
				{ "HELP_53_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671311"},
				{ "HELP_53_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671312"},
				{ "HELP_13_URL_ANTWOORD" , "https://app.dwo.nl/dwo/apps/player.html?t=10&profile=106&locale=nl#671313"},
				{ "HELP_13_URL_FEEDBACKTITLE" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671314"},
				
				{ "HELP_4_URL" , "https://app.dwo.nl/dwo/apps/player.html?t=17&profile=106&locale=nl#671325"},
				{ "HELP_4_URL_CHECK" , "https://app.dwo.nl/dwo/apps/player.html?t=2&profile=106&locale=nl#671326"},
				{ "HELP_4_URL_LOGID" , "https://app.dwo.nl/dwo/apps/player.html?t=4&profile=106&locale=nl#671327"},
				{ "HELP_4_URL_FORMINVOER" , "https://app.dwo.nl/dwo/apps/player.html?t=8&profile=106&locale=nl#671328"},
				{ "HELP_4_URL_REKENMACHINE" , "https://app.dwo.nl/dwo/apps/player.html?t=12&profile=106&locale=nl#671329"},
				{ "HELP_4_URL_RAND" , "https://app.dwo.nl/dwo/apps/player.html?t=9&profile=106&locale=nl#671330"},
		};
}





