<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
	<parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>WiskOpdrParent</artifactId>
	  <version>1.0.1-SNAPSHOT</version>
	  <relativePath>../WiskOpdrParent</relativePath>
	</parent>
  <groupId>fi.statistiek</groupId>
  <artifactId>statistiek</artifactId>
  <version>1.0.1-SNAPSHOT</version>
  <properties>
	<project.build.sourceEncoding>ISO-8859-1</project.build.sourceEncoding>
	<maven.compiler.source>1.8</maven.compiler.source>
	<maven.compiler.target>1.8</maven.compiler.target>
	<jarsigner.skip>true</jarsigner.skip>
	<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
	<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
  </properties>
  <build>
  	<finalName>${project.artifactId}</finalName>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>test</testSourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
      </plugin>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
 				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>fi.statistiek.Statistiek</Bundle-SymbolicName>
 				<Main-Class>fi.statistiek.Statistiek</Main-Class>
				<Trusted-Only>true</Trusted-Only>
				<Permissions>all-permissions</Permissions>
				<Codebase>*.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl *.noordhoff.nl *.schoolwise.nl *.epn.nl localhost dme.mathhouse.org</Codebase>
				<Application-Name>Statistiek</Application-Name>
				<Bundle-Name>Statistiek Widget</Bundle-Name>
				<Caller-Allowable-Codebase>*.science.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl *.noordhoff.nl *.schoolwise.nl *.epn.nl localhost dme.mathhouse.org</Caller-Allowable-Codebase>
				<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
 				<Private-Package>*</Private-Package>
 				<Export-Package>fi.statistiek,fi.statistiek.types</Export-Package>
 				<Import-Package>fi.beans.wiskopdrbeans,!org.knowm.*,*</Import-Package>
 				<Fragment-Host>fi.wiskopdr.WiskOpdr</Fragment-Host>
          	</instructions>
          </configuration>
         </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>       
                    <plugin>
                        <groupId>com.github.wvengen</groupId>
                        <artifactId>proguard-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>proguard</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <options>
                                <option>-verbose</option>
                                <option>-dontwarn</option> 
                                <option>-printconfiguration ${project.build.directory}/mapping.txt</option>
                            </options>
                            <obfuscate>true</obfuscate>                    
                            <inputDirectory>${project.build.directory}</inputDirectory>
                            <injar>${project.build.finalName}-jar-with-dependencies.jar</injar>
                            <proguardInclude>toolfiles/config.pro</proguardInclude>
                            <libs>
                                <lib>${proguard.lib}</lib>
                            </libs>
                            <addMavenDescriptor>false</addMavenDescriptor>
                        </configuration>
                   </plugin>
                    <plugin>
                        <groupId>com.github.batkinson.plugins</groupId>
                        <artifactId>maven-pack200-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                             <execution>
                                <id>pack-jars</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>pack</goal>
                                </goals>
                                <configuration>
                                    <normalizeOnly>false</normalizeOnly>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <processMainArtifact>false</processMainArtifact>
                            <includeClassifiers>
                                <includeClassifier>jar-with-dependencies</includeClassifier>
                            </includeClassifiers>
                        </configuration>                
                    </plugin>        
    </plugins>
  </build>
  <dependencies>
  	<dependency>
  		<groupId>org.knowm.xchart</groupId>
  		<artifactId>xchart</artifactId>
  		<version>3.5.0</version>
  	</dependency>
  	<dependency>
  		<groupId>org.knowm.xchart</groupId>
  		<artifactId>xchart-demo</artifactId>
  		<version>3.5.0</version>
  	</dependency>
  	<dependency>
  		<groupId>org.c-book</groupId>
  		<artifactId>cbookif</artifactId>
  		<version>1.0.2</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.12</version>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
		<groupId>fi.wiskopdr</groupId>
		<artifactId>wiskopdr</artifactId>
		<version>0.3.0</version>
		<scope>provided</scope>
  	</dependency>
  </dependencies>
</project>
