<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.ivmdraw</groupId>
    <artifactId>IVMdraw-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>ivmdraw</artifactId>
  <dependencies>
  	<dependency>
  		<groupId>fi.ivmdraw</groupId>
  		<artifactId>ivmdraw-common</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
  	<dependency>
  		<groupId>fi.wiskopdr</groupId>
  		<artifactId>wiskopdr</artifactId>
  		<version>0.0.2</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.12</version>
  		<scope>test</scope>
  	</dependency>
  </dependencies>
  <packaging>bundle</packaging>
  <properties>
  		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  		<maven.compiler.source>1.8</maven.compiler.source>
  		<maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <build>
  	<finalName>${project.artifactId}</finalName>
    <plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>3.5.0</version>
				<extensions>true</extensions>
				<configuration>
					<createDependencyReducedPom>true</createDependencyReducedPom>
					<niceManifest>true</niceManifest>
					<dependencyReducedPomLocation>${basedir}/small-pom.xml</dependencyReducedPomLocation>
					<instructions>
						<Export-Package>fi.ivmdraw</Export-Package>
						<Require-Bundle>fi.wiskopdr.WiskOpdr</Require-Bundle>
						<Main-class>fi.ivmdraw.IVMdraw</Main-class>
						<Trusted-Only>true</Trusted-Only>
						<Permissions>all-permissions</Permissions>
						<Codebase>*.uu.nl *.dwo.nl localhost dme.mathhouse.org</Codebase>
						<Caller-Allowable-Codebase>*.uu.nl *.dwo.nl localhost</Caller-Allowable-Codebase>
						<Application-Name>IVMdraw</Application-Name>
						<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
						<Embed-Transitive>true</Embed-Transitive>
 						<Embed-Dependency>*;scope=compile;type=!pom;inline=true</Embed-Dependency>
					</instructions>
				</configuration>
			</plugin>
    </plugins>
  </build>
</project>