<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
  	<groupId>fi.euclides</groupId>
  	<version>2.5.51-SNAPSHOT</version>
  	<artifactId>euclides-parent</artifactId>
  	<relativePath>..</relativePath>
  </parent>
  <groupId>gwt.geom</groupId>
  <artifactId>gwt-geom</artifactId>
  <properties>
	<maven.test.skip>true</maven.test.skip>
	<maven.compiler.source>1.8</maven.compiler.source>
	<maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <build>
  	<finalName>geom</finalName>
  	<sourceDirectory>src</sourceDirectory>
	<testSourceDirectory>test</testSourceDirectory>
    <resources>
    	<resource>
    	   <directory>src</directory>
    	</resource>
    </resources>
  </build>
  <dependencies>
  	<dependency>
  		<groupId>com.google.gwt</groupId>
  		<artifactId>gwt-user</artifactId>
		<version>2.10.0</version>
  		<scope>provided</scope>
  	</dependency>
	<dependency>
		<groupId>com.google.gwt</groupId>
		<artifactId>gwt-dev</artifactId>
		<version>2.10.0</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>3.8.2</version>
		<scope>test</scope>
	</dependency>
  </dependencies>
</project>

