<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>wiskopdr-parent</artifactId>
	  <version>2.5.48</version>
	  <relativePath>../WiskOpdrParent</relativePath>
	</parent>
	<groupId>fi.kladje</groupId>
	<artifactId>kladje</artifactId>
	<name>Kladje</name>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<jarsigner.skip>true</jarsigner.skip>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
	</properties>
	<build>
		<finalName>kladje</finalName>
		<sourceDirectory>src</sourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
			</plugin>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>fi.kladje.Kladje</Bundle-SymbolicName>
 				<Main-Class>fi.kladje.Kladje</Main-Class>
				<Bundle-Name>Kladje</Bundle-Name>
 				<Private-Package>*</Private-Package>
 				<Export-Package>fi.kladje</Export-Package>
 				<Import-Package>fi.beans.mainframe,fi.beans.scorm,fi.beans.wiskopdrbeans,*</Import-Package>
          	</instructions>
          </configuration>
         </plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
        		<version>2.4</version>
				<configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<options>
						<option>-verbose</option>
						<option>-dontwarn</option>
						<option>-printconfiguration ${project.build.directory}/mapping.txt</option>
					</options>
					<obfuscate>true</obfuscate>
					<inputDirectory>${project.build.directory}</inputDirectory>
					<injar>${project.build.finalName}.jar</injar>
					<proguardInclude>toolfiles/config.pro</proguardInclude>
					<libs>
						<lib>${proguard.lib}</lib>
					</libs>
					<addMavenDescriptor>false</addMavenDescriptor>
				</configuration>
			</plugin>
                    <plugin>
                        <groupId>com.github.batkinson.plugins</groupId>
                        <artifactId>maven-pack200-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <id>pack-jars</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>pack</goal>
                                </goals>
                                <configuration>
                                    <normalizeOnly>false</normalizeOnly>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <processMainArtifact>true</processMainArtifact>
                        </configuration>                
                    </plugin>        
 		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>fi.wiskopdr.beans</groupId>
			<artifactId>wiskopdrbeans</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
<!-- FIXME, make a dependency to the real uncompressed thing -->
		<dependency>
			<groupId>fi.wiskopdr</groupId>
			<artifactId>wiskopdr</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwo-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>numworxlf</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
