<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>fi.balansfruitapplet</groupId>
	<artifactId>balansfruitapplet</artifactId>
	<name>BalansFruitApplet</name>
	<parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>wiskopdr-parent</artifactId>
	  <version>2.5.49</version>
	  <relativePath>../WiskOpdrParent</relativePath>
	</parent>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<finalName>${project.artifactId}</finalName>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
   				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>fi.balansfruit.BalansFruit</Bundle-SymbolicName>
 				<Main-Class>fi.balansfruit.BalansFruitApplet</Main-Class>
				<Trusted-Only>true</Trusted-Only>
				<Permissions>all-permissions</Permissions>
				<Codebase>*.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl *.noordhoff.nl *.schoolwise.nl *.epn.nl localhost dme.mathhouse.org</Codebase>
				<Application-Name>BalansFruitApplet</Application-Name>
				<Bundle-Name>BalansFruit Applet</Bundle-Name>
				<Caller-Allowable-Codebase>*.science.uu.nl *.fi.uu.nl dme.colorado.edu *.appspot.com *.dwo.nl *.noordhoff.nl *.schoolwise.nl *.epn.nl localhost dme.mathhouse.org</Caller-Allowable-Codebase>
				<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
 				<Private-Package>*</Private-Package>
 				<Export-Package>fi.balansfruit</Export-Package>
 				<Import-Package>fi.beans.mainframe,fi.beans.scorm,fi.beans.wiskopdrbeans,*</Import-Package>
 				<Fragment-Host>fi.wiskopdr.WiskOpdr</Fragment-Host>
          	</instructions>
          </configuration>
         </plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwo-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.c-book</groupId>
			<artifactId>cbookif</artifactId>
			<version>1.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdr.beans</groupId>
			<artifactId>wiskopdrbeans</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
	</dependencies>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
	</properties>
</project>
