<?xml version='1.0' ?>
<project name='lwmobjects' basedir='../../../..' default='cpjc' >
	<description>
Deze ant build kan je gebruiken voor het automatiseren van de
referentie omgeving.
Nog zelf in te vullen: project en main-class
en verder de lijst met used_jars
Let ook op de 'includes' van beans voor de &lt;target name='jar' &gt;.
	</description>
	<property name='project' value='lwmobjects' />
	<property name='prefix' value='fi.beans' />
	<property name='fileprefix' value='fi/beans' />
	<property name='main-class' value='${prefix}.${project}.MyAppletApplication' />


<!-- standaard output directory -->
	<property name='bin' value='output/classes'  />
	<property name='jar' value='output/jar' />
	<property name='exe' value='output/exe' />
	<property name='scm' value='output/scorm' />
	<property name='src' value='src'  />

<!-- afgeleide properties -->
	<property name='project.jar' value='${jar}/${project}.jar' />

<!-- zorg voor standaard directories -->
	<target name='init'>
	    	<condition property='drive' value='N:'>
		    <os family='dos' />
	    	</condition>
	    	<condition property='drive' value=''  >
		    <os family='unix' />
	    	</condition>

	    	<property name='javaclasses' value='${drive}/home/www-dev/InfoGroups/javaclasses' />
	    	<property name='src.final' value='${drive}/home/java/src.final' />
	   	<property name='jars' value='${javaclasses}/jars' />
<!-- Vul hier je used_jars in -->
		<property name='used_jars' value='${jars}/xxx.jar;${jars}/yyy.jar' />

		<mkdir dir="${bin}"/>
		<mkdir dir="${jar}" />
		<mkdir dir='${exe}' />
		<mkdir dir='${scm}' />
	</target>
<!-- copieer classes en jar naar javaclasses -->
	<target name='cpjc'  depends='jar' >
		<copy todir='${javaclasses}' verbose='true'>
			<fileset dir='${bin}' includes='${fileprefix}/${project}/**' />
		</copy>
	</target>
<!-- copieer sources naar src.final -->
	<target name='cpsrc' depends='init' >
		<copy todir='${src.final}' verbose='false' >
			<fileset dir='${src}'  />
		</copy>
	</target>
<!-- compileren: -->
	<target name='compile' depends="init">
		<javac
			target="1.1"
			destdir="${bin}"
			srcdir="${src}"
			includes='${fileprefix}/${project}/**.java'
			classpath="${used_jars};${javaclasses};${bin}"
		/>
	</target>

	<target name='resources' depends='init' >
	</target>
<!-- testen -->
	<target name='test' depends='compile, resources' >
		<java	fork='true'
			classname='${main-class}'
			classpath='${javaclasses}:${bin}:${used_jars}'
		>
			<arg value='language=nl' />
		</java>
	</target>
<!-- in een jar zetten -->
	<target name='jar' depends='compile, resources' >
	</target>


</project>
