package fi.beans.lwmobjects_swing;

import java.awt.*;
import java.awt.event.*;

/**
 * A LWMPileObject is a LWMObject that is in fact a pile of copies of itself.
 * This means: when you drag it, you don't take the entire pile, but you just take away
 * the copy that is on top and move that copy around. The pile itself cannot be moved.
 * The copy is also an instance of LWMPileObject, with a boolean isCopy set at true.
 * <br>
 * The object has a pileCount, which is decreased whenever a copy is taken off the pile.
 * When pileCount reaches zero, the pile becomes invisible.
 * The copies act as ordinary LWMObjects, with one difference: when they are moved to the
 * Container containing the original pile, they return to the pile, increasing the pileCount.
 * To facilitate 'finding the original pile' you must use setHomeContainer(LWMContainer)
 * and setName(String). The name is used to recognize the original pile!
 * <br>
 * Technical note: to avoid difficulties in mouse-event handling, the pile does not generate
 * a copy that will be dragged. This is troublesome because the mouseDragged-events will
 * continue to be delivered to the pile where mousePressed began.
 * Instead, the pile changes itself to a copy (allowing drags) and will create e new pile and
 * put it in its old position. Therefore, 'finding the original pile' is done by reference to the name,
 * not by reference to an object.
 * 
 * @author Paul Bergervoet
 *
 * @version 0, 11 september 2000
 */

public class LWMPileObject extends LWMObject
	implements Cloneable
	// implements MouseListener, MouseMotionListener: ok because of 'extends LWMObject'
{	// variables
	boolean isCopy;
	boolean isCountShowing;
	LWMContainer homeContainer;
	int pileCount;
	static Font defaultfont = new Font("SansSerif", Font.PLAIN, 12);
	
/**
 * Constructs a LWMPileObject with the specified background color, dimension and pile count.
 * <br>
 * You can only construct true piles, copies are generated by dragging only.
 *
 * @param c The background Color
 * @param w Width (int)
 * @param h Height (int)
 * @param c The count, number of copies on the pile
 */
	public LWMPileObject(Color c, int w, int h, int cnt)
	{	super(c, w, h);
		pileCount = cnt;
		isCopy = false;
		isCountShowing = false;
	}
	
/**
 * Constructs a LWMPileObject with the specified background image, dimension and pile count.
 * <br>
 * You can only construct true piles, copies are generated by dragging only.
 *
 * @param i The background Image
 * @param w Width (int)
 * @param h Height (int)
 * @param c The count, number of copies on the pile
 */
	public LWMPileObject(Image i, int w, int h, int cnt)
	{	super(i, w, h);
		pileCount = cnt;
		isCopy = false;
		isCountShowing = false;
	}

/**
 * Constructs a LWMPileObject with the specified background image and pile count and unknown dimension.
 * <br>
 * You can only construct true piles, copies are generated by dragging only.
 *
 * @param i The background Image
 * @param c The count, number of copies on the pile
 */
	public LWMPileObject(Image i, int cnt)
	{	super(i);
		pileCount = cnt;
		isCopy = false;
		isCountShowing = false;
	}

/**
 * Yields true if the number of objects in the pile is showing on the LWMPileObject
 *
 * @return boolean
 */	
	public boolean isCountShowing()
	{	return isCountShowing;
	}
	
/**
 * Show the number of objects on the pile or don't.
 *
 * @param b True if number must show.
 */	
	public void setCountShowing(boolean b)
	{	isCountShowing = b;
	}
	
/**
 * Yields true if the object is a copy that has been taken off the pile.
 *
 * @return boolean
 */	
	public boolean isCopy()
	{	return isCopy;
	}
	
/**
 * Yields the number of copies on the pile.
 * Relevant only for the pile itself, copies that have been taken off may return any number.
 *
 * @return int
 */	
	public int getPileCount()
	{	return pileCount;
	}
	
/**
 * Gets the 'homecontainer' of a pile-object or copy taken from the pile, that is the
 * (fixed) Container where the original LWMPile is located.
 * Used by copies to find their way back to the pile. 
 *
 * @return The LWMContainer that is 'home' of the pile.
 */	
	public LWMContainer getHomeContainer()
	{	return homeContainer;
	}
	
/**
 * Sets the homecontainer, MUST be set to the pile's Container immediately after construction.
 * Note: HomeContainer MUST equal the Container where the pile is put into, if you fail to do this,
 * you will get runtime-exceptions.
 *
 * @param c The homecontainer
 */	
	public void setHomeContainer(LWMContainer c)
	{	homeContainer = c;
	}
	
/**
 * Increase the number of objects on the pile.
 */	
	private void increasePileCount()
	{	pileCount++;
		isMovable = true;		// after increase always >0 copies on pile!
	}
	
/**
 * Paint-method for empty pile.
 * Don't override paint(g), override this method and/or paintNonempty(g). The normal paint-method
 * will decide which of the two will de done (and add pileCount, if countshowing is on).
 * Default: doesn't paint anything
 */
	protected void paintEmpty(Graphics g)
	{
	}
	
/**
 * Paint-method for nonempty pile AND copies.
 * Don't override paint(g), override this method and/or paintEmpty(g). The normal paint-method
 * will decide which of the two will de done.
 * Default: super.paint(g), the ordinary paint for lwmobjects
 */
	protected void paintNonempty(Graphics g)
	{	super.paint(g);
	}

/**
 * Override of LWMObject.paint(g). The pile will not be visible if there are no copies left.
 */
	public void paint(Graphics g)
	{	if ( isCopy )				// always paint copies
		{	paintNonempty(g);
		} else
		{	if ( pileCount > 0 )		// paint pile only if copies left
			{	paintNonempty(g);
			} else
			{	paintEmpty(g);
			}
			if ( isCountShowing )
			{	g.setColor(Color.black);
				g.setFont(defaultfont);
				g.drawString(String.valueOf(pileCount), 2, 14);
			}
		}
	}

/**
 * Overrides LWMComponent.pickupLWMComponent(Point ap) to create a copy when the pile itself is being dragged.
 *
 * @param ap The absolute location of the LWMComponent in the LWMRootContainer.
 */
	protected void pickupLWMComponent(Point ap)
	{	if ( isCopy )				// just move a copy like any LWMObject
		{	super.pickupLWMComponent(ap);
		} else
		{	mybox.removeLWMComponent(this);
			try
			{	pileCount--;						// decrease pileCount
				LWMPileObject remains = (LWMPileObject)clone();
				isCopy = true;						// 'this' will be the copy
				remains.isCopy = false;				// 'clone' will be put back

// later OK maken?				
//				remains.removeMouseListener(this);		// let clone listen to its own MouseEvents
//				remains.removeMouseMotionListener(this);
//				remains.addMouseListener(remains);
//				remains.addMouseMotionListener(remains);
				
				remains.dragging = false;				// clone is NOT being dragged!
				if ( pileCount == 0 )					// pile has zero copies left
				{	remains.setMovable(false);			// no further pickups!
				}		
												// put new pile in previous position
				previousContainer.addLWMComponent(remains,previousLocation.x, previousLocation.y, 0);
			} catch ( CloneNotSupportedException e)
			{	System.out.println("Geen kloon!!!!!");
			}									// move around old object, which is now copy
			allbox.addLWMComponent(this, ap.x, ap.y, 0);
		}
	}

/**
 * Overrides LWMComponent.dropLWMComponent(dest, ap) to return a copy to the pile.
 * <br>
 * This method replaces the default dropping of components, because the drop operation itself
 * changes: we will be looking for the pile instead of just adding the component.
 * <br>
 * Note: dropped LWMPileObject always is a copy!
 *
 * @param dest The destination LWMContainer.
 * @param ap The absolute location of the LWMComponent in the LWMRootContainer.
 */
	protected void dropLWMComponent(LWMContainer dest, Point ap)
	{	if ( dest != homeContainer )		// not the homeContainer: nothing special
		{	super.dropLWMComponent(dest, ap);
		} else						// find pile!
		{	int n = dest.getComponentCount();
			int i = 0;
			LWMComponent c;
			LWMPileObject p = null;
			String s;
			while ( p == null )		// don't check index, it must be there!
			{	c = (LWMComponent)(dest.getComponent(i));
				s = c.getName();
				if ( s != null )
				{	if ( s.equals(getName()) )
					{	p = (LWMPileObject)c;
					}
				}
				i++;
			}
			p.increasePileCount();
		}
	}

}
