<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.wiskopdr</groupId>
    <artifactId>wiskopdr-parent</artifactId>
    <version>2.5.50</version>
    <relativePath>../WiskOpdrParent</relativePath>
  </parent>
  <groupId>nl.numworx.geogebra</groupId>
  <artifactId>geogebra4widget</artifactId>
 	<dependencies>
		<dependency>
			<groupId>fi.wiskopdr.beans</groupId>
			<artifactId>wiskopdrbeans</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
<!-- FIXME, make a dependency to the real uncompressed thing -->
		<dependency>
			<groupId>fi.wiskopdr</groupId>
			<artifactId>wiskopdr</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwo-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>numworxlf</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra</artifactId>
			<version>${geogebraVersion}</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra_cas</artifactId>
			<version>${geogebraVersion}</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra_main</artifactId>
			<version>${geogebraVersion}</version>
		</dependency>
	</dependencies>
	<build>
   		<finalName>${project.artifactId}</finalName>
   	 <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
      </plugin>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
   				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>nl.numworx.geogebra4.Geogebra4Widget</Bundle-SymbolicName>
 				<Main-Class>nl.numworx.geogebra4.Geogebra4Widget</Main-Class>
				<Bundle-Name>Geogebra4Widget</Bundle-Name>
 				<Private-Package>*</Private-Package>
 				<Export-Package>nl.numworx.geogebra4</Export-Package>
 				<Import-Package>fi.beans.mainframe,fi.beans.scorm,fi.beans.wiskopdrbeans,*</Import-Package>
				<Class-Path>geogebra.jar</Class-Path>
         	</instructions>
          </configuration>
         </plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
    </plugins>
	</build>
	<properties>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
		<geogebraVersion>2.5.46</geogebraVersion>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>

	</properties>
</project>
