<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.wiskopdr</groupId>
    <artifactId>WiskOpdrParent</artifactId>
    <version>1.0.3-SNAPSHOT</version>
    <relativePath>../WiskOpdrParent</relativePath>
  </parent>
  <groupId>nl.numworx.repl</groupId>
  <artifactId>repl</artifactId>
  <version>0.0.4-SNAPSHOT</version>
 	<dependencies>
		<dependency>
			<groupId>fi.wiskopdr</groupId>
			<artifactId>wiskopdr</artifactId>
			<version>0.3.0</version>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>DWO-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>numworxlf</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
   		<finalName>${project.artifactId}</finalName>
	</build>
	<properties>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.source>1.8</maven.compiler.source>
	</properties>
</project>