<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.wiskopdr</groupId>
    <artifactId>author-parent</artifactId>
    <version>3.0.1-SNAPSHOT</version>
    <relativePath>..</relativePath>
  </parent>
  <artifactId>dwogwtprint</artifactId>
  <groupId>nl.uu.fi.dwo</groupId>
  <packaging>bundle</packaging>
  <name>DWO GWT Printer</name>
  <properties>
  		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
  </properties>
  <dependencies>
    <dependency>
    	<groupId>fi.beans</groupId>
    	<artifactId>numworxlf</artifactId>
    	<scope>provided</scope>
    </dependency>
		<dependency>
		    <groupId>nl.numworx.swingbrowser</groupId>
		    <artifactId>swingbrowser-jxb</artifactId>
		    <scope>runtime</scope>
		</dependency>
		<dependency>
		    <groupId>nl.numworx.swingbrowser</groupId>
		    <artifactId>swingbrowser-api</artifactId>
		    <scope>provided</scope>
		</dependency>
		<dependency>
		   <groupId>nl.uu.fi.dwo.rest</groupId>
    	   <artifactId>dwo-jclient-lib</artifactId>
    	   <scope>test</scope>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo.rest</groupId>
			<artifactId>dwo-rest-lib</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.promise</artifactId>
			<version>6.0.0</version>
			<scope>provided</scope>
		</dependency>
  </dependencies>
  <build>
	  <finalName>${project.artifactId}</finalName>	  
	  <plugins>	  
		  <plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>5.1.9</version>
				<extensions>true</extensions>
				<configuration>
       	    		<niceManifest>true</niceManifest>
					<instructions>
						<_snapshot>${osgi.qualifier}</_snapshot>
						<Bundle-SymbolicName>fi.dwo.dwogwtprint.DWOGWTPrint</Bundle-SymbolicName>
						<Export-Package>fi.dwo.dwogwtprint</Export-Package>
						<Main-class>fi.dwo.dwogwtprint.DWOGWTPrint</Main-class>
					</instructions>
				</configuration>
		  </plugin>
                  <plugin>
                        <groupId>com.github.batkinson.plugins</groupId>
                        <artifactId>maven-pack200-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <id>pack-jars</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>pack</goal>
                                </goals>
                                <configuration>
                                    <normalizeOnly>false</normalizeOnly>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <processMainArtifact>true</processMainArtifact>
                        </configuration>                
                    </plugin>        
	  </plugins>
  </build>
</project>
