<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>author-parent</artifactId>
	  <version>3.0.0-SNAPSHOT</version>
	  <relativePath>../..</relativePath>
    </parent>
  <artifactId>uploadwidgetrm</artifactId>
  <name>Upload Widget Resource Manager</name>
	<properties>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
  <dependencies>
		<dependency>
    		<groupId>javax.activation</groupId>
    		<artifactId>activation</artifactId>
    		<version>1.1.1</version>
    		<optional>true</optional>
    		<scope>provided</scope>
		</dependency>
  	<dependency>
  		<groupId>org.c-book</groupId>
  		<artifactId>cbookif</artifactId>
  		<version>1.0.2</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.13.1</version>
  		<scope>test</scope>
  	</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwo-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
  	<dependency>
		<groupId>fi.wiskopdr.beans</groupId>
		<artifactId>wiskopdrbeans</artifactId>
		<version>${project.version}</version>
		<scope>provided</scope>
  	</dependency>
  	  </dependencies>
  <build>
  	<finalName>${project.artifactId}</finalName>
		<plugins>
        <plugin>   
		  <groupId>org.apache.felix</groupId>
		  <artifactId>maven-bundle-plugin</artifactId>
          <version>2.5.3</version>
		  <executions>
		    <execution>
		      <id>bundle-manifest</id>
		      <phase>process-classes</phase>
		      <goals>    
		        <goal>manifest</goal>
		      </goals>   
		    </execution>
		  </executions>
       	  <configuration>
       	    <niceManifest>true</niceManifest>
          	<instructions>
 				<_snapshot>${osgi.qualifier}</_snapshot>
          		<Bundle-SymbolicName>nl.numworx.uploadwidget.rm</Bundle-SymbolicName>
 				<Export-Package>nl.numworx.uploadwidget.rm</Export-Package>
          	</instructions>
          </configuration>
         </plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifestFile>target/classes/META-INF/MANIFEST.MF</manifestFile>
					</archive>
				</configuration>
			</plugin>
		</plugins>
  </build>
       <repositories>  
        <repository>    
          <id>com.teamdev</id>
          <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
        </repository>   
    <repository>
        <id>numworx-dwo-project</id>
        <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>       
    <repository>        
        <id>numworx-vendor-jxbrowser</id>
        <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-jxbrowser</url>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>       
    <repository>        
        <id>numworx-vendor-cbook</id>
        <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-cbook</url>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>       
                
        </repositories>
</project>
