#nooit, gebruikt serialized objects in launchdata
#fi.verknippen
#fi.mozarch
#fi.tegels
#fi.geomalgebra
#fi.stroomdiagrammen
#fi.statistiek
#fi.doorziendwo.DoorzienDWO: doorziendwo.jar
#fi.flowdiagrams.FlowDiagrams: flowdiagrams.jar
#fi.statistiek.Statistiek: statistiek.jar
#fi.stroomdiagrammen.Stroomdiagrammen: stroomdiagrammen.jar
#fi.dataplot.DataPlot:
#deze geen serialized objects in launchdata
nl.numworx.geodefiner.GeoDefiner: geodefiner.jar
fi.algebrapijlenopdr.AlgebraPijlenOpdr: algebrapijlenopdr.jar
fi.binomverdeling.BinomVerdeling: binomverdeling.jar
fi.figuursnijden.Snijden: figuursnijden.jar
fi.geodefull.GeodeFull: geodefull.jar
fi.geomalgebra1d.GeomAlgebra1d: geomalgebra1d.jar
fi.javalogoweb3d.JavaLogoWeb3d: javalogoweb3d.jar
fi.nabouwenaanzichten.NabouwenAanzichten: nabouwenaanzichten.jar
fi.normaleverdeling.NormaleVerdeling: normaleverdeling.jar
fi.omtrekapplet.OmtrekApplet: omtrekapplet.jar
fi.oppervlaktealgebra.OppervlakteAlgebra: oppervlaktealgebra.jar
fi.sliderwidget.SliderWidget: sliderwidget.jar
fi.tekenveelvlakopdr.TekenVeelvlakOpdr: tekenveelvlakopdr.jar
fi.vangen.Vangen: vangen.jar
fi.vergroten.Vergroten: vergroten.jar
fi.doorziendwo.DoorzienDWO: doorziendwo.jar
fi.geomalgebra.GeomAlgebra: geomalgebra.jar
fi.tinyplayerapplet.TinyPlayerApplet: tinyplayerapplet.jar
fi.binomverdeling.BinomVerdeling: binomverdeling.jar
fi.algebraexpressies.AlgebraExpressies:algebraexpressies.jar
fi.blokkenprogramma.BlokkenProgramma:blokkenprogramma.jar
fi.grafiek3dtest.Grafiek3DTest:grafiek3dtest.jar
fi.spot_problems_dwo.Spot_Problems_dwo:spot_problems_dwo.jar
fi.kladje.Kladje:kladje.jar
fi.kansbomen.Kansbomen:kansbomen.jar
fi.calculatordwo.CalculatorDwo:calculatordwo.jar
fi.formstruct.FormStruct:formstruct.jar
fi.draaibank.Draaibank:draaibank.jar
fi.waarmakersdwo.WaarmakersDwo:waarmakersdwo.jar
fi.statsim.StatSim:statsim.jar
fi.javalogoweb.JavaLogoWeb:javalogoweb.jar
fi.heks.Heks:heks.jar
fi.ivmdraw.IVMdraw: ivmdraw.jar
fi.mathscratch.MathScratch: mathscratch.jar
nl.numworx.uploadwidget.UploadWidget: uploadwidget.jar
nl.numworx.notebook.Notebook: notebook.jar
nl.numworx.repl.Repl: repl.jar
nl.numworx.aimodel.AIModel: aimodel.jar
nl.numworx.sqlite.SQLite: sqlite.jar
nl.numworx.geogebra3.Geogebra3Widget: geogebra3widget.jar
nl.numworx.geogebra4.Geogebra4Widget: geogebra4widget.jar
