<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.wiskopdr</groupId>
    <artifactId>WiskOpdrParent</artifactId>
    <version>1.0.3-SNAPSHOT</version>
    <relativePath>../WiskOpdrParent</relativePath>
  </parent>
  <groupId>fi.wiskopdr.beans</groupId>
  <artifactId>wiskopdrbeans</artifactId>
  <dependencies>
    <dependency>
     <artifactId>cbookif</artifactId>
     <groupId>org.c-book</groupId>
     <version>1.0.2</version>
    </dependency>
    <dependency>
       <groupId>nl.uu.fi.dwo</groupId>
       <artifactId>DWO-commons-lib</artifactId>
       <scope>provided</scope>
       <version>2.5.47-SNAPSHOT</version>
    </dependency>
  </dependencies>
</project>
