<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.wiskopdr</groupId>
    <artifactId>WiskOpdrParent</artifactId>
    <version>1.0.3-SNAPSHOT</version>
    <relativePath>../WiskOpdrParent</relativePath>
  </parent>
	<groupId>fi.euclides</groupId>
	<artifactId>euclides-parent</artifactId>
	<version>0.0.8-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>Euclides Multi module</name>
	<modules>
		<module>gwt-geom</module>
		<module>euclides-core</module>
		<module>euclides-expr</module>
		<module>euclides-util</module>
		<module>euclides-gwt</module>
		<module>euclides-resources</module>
	</modules>
	  <dependencyManagement>
	  	<dependencies>
	  			<dependency>
				<groupId>fi.euclides</groupId>
				<artifactId>euclides-core</artifactId>
				<version>0.0.8-SNAPSHOT</version>
			</dependency>
	  			<dependency>
				<groupId>fi.euclides</groupId>
				<artifactId>euclides-expr</artifactId>
				<version>0.0.8-SNAPSHOT</version>
			</dependency>
	  		<dependency>
				<groupId>fi.euclides</groupId>
				<artifactId>euclides-core</artifactId>
				<version>0.0.8-SNAPSHOT</version>
				<classifier>sources</classifier>
			</dependency>
		  	<dependency>
		  		<groupId>fi.euclides</groupId>
		  		<artifactId>euclides-util</artifactId>
		  		<version>0.0.8-SNAPSHOT</version>
		  		<optional>true</optional>
		  	</dependency>
	  	</dependencies>
	  </dependencyManagement>
	<properties>
		<euclidesVersion>${project.version}</euclidesVersion>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<autoVersionSubmodules>true</autoVersionSubmodules>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
</project>
