<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.wiskopdr</groupId>
    <artifactId>wiskopdr-parent</artifactId>
    <version>2.5.49-SNAPSHOT</version>
    <relativePath>../WiskOpdrParent</relativePath>
  </parent>
  <groupId>nl.numworx.fsm</groupId>
  <artifactId>fsm</artifactId>
  <dependencies>
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>${gwtVersion}</version>
		</dependency>  		<dependency>
			<groupId>org.c-book</groupId>
			<artifactId>cbookif</artifactId>
			<version>1.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.c-book</groupId>
			<artifactId>cbookeditor</artifactId>
			<version>0.0.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.c-book</groupId>
			<artifactId>cbookeditor</artifactId>
			<version>0.0.1</version>
			<scope>test</scope>
		</dependency>
			<dependency>
				<groupId>fi.wiskopdr.beans</groupId>
				<artifactId>wiskopdrbeans</artifactId>
				<scope>provided</scope>
				<optional>true</optional>
			</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-util</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-expr</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>fi.euclides</groupId>
			<artifactId>euclides-resources</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<version>1</version>
		</dependency>
		<dependency>
			<groupId>com.google.dagger</groupId>
			<artifactId>dagger</artifactId>
			<version>${daggerVersion}</version>
		</dependency>
		<dependency>
			<groupId>com.google.dagger</groupId>
			<artifactId>dagger-compiler</artifactId>
			<version>${daggerVersion}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>fi.beans</groupId>
			<artifactId>numworxlf</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
	       <groupId>nl.uu.fi.dwo</groupId>
	       <artifactId>dwo-commons-lib</artifactId>
	       <scope>provided</scope>
	    </dependency>

	</dependencies>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<jarsigner.skip>true</jarsigner.skip>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<daggerVersion>2.42</daggerVersion>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
		<gwtVersion>2.10.0</gwtVersion>
	</properties>
	<build>
		<plugins>
            <plugin> <!-- attach-sources voor GWT -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>         
		</plugins>
	</build>
</project>