<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>wiskopdr-parent</artifactId>
	  <version>2.5.48</version>
	  <relativePath>../WiskOpdrParent</relativePath>
    </parent>
  <groupId>fi.mathscratch</groupId>
  <artifactId>mathscratch-parent</artifactId>
  <packaging>pom</packaging>
  <name>MathScratch parent</name>
  <modules>
  	<module>mathscratch-common</module>
  	<module>mathscratch</module>
  	<module>MathScratchGWT</module>
  </modules>
  <properties>
  	<maven.compiler.target>1.8</maven.compiler.target>
  	<maven.compiler.source>1.8</maven.compiler.source>
  </properties>
</project>
