package fi.statsim.text;

public class Text_nl extends java.util.ListResourceBundle
{
        public Object [] [] getContents() { return contents; }
        static final Object [] [] contents =
        {
            {	"settings" , "Instellingen" },
            {	"oneCoin" , "Een munt" },
            {	"twoCoins", "Twee munten" },
            {   "numberOfRounds", "Aantal worpen" },
            {   "chanceOfTails", "Kans op munt" },
            {   "start", "Start" },
            {   "next", "Volgende" },
            {   "stop", "Stop" },
            {   "results", "Resultaten" },
            {   "mean", "Gemiddelde" },
            {   "minimum", "Minimum" },
            {   "maximum", "Maximum" },
            {   "numberOfHeads", "Aantal kop" },
            {   "percentageHeads", "Percentage kop" },
            {   "noHeads", "0 kop" },
            {   "oneHeads", "1 kop" },
            {   "twoHeads", "2 kop" },
            {   "exp", "exp." },
            {   "numberOfTails", "Aantal munt" },
            {   "frequency", "Frequentie" },
            {   "heads", "Kop" },
            {   "tails", "Munt" },
            {   "percentageHeads", "Percentage kop" },
            {   "eyes", "Ogen" },
            {   "sumEyes", "Som ogen" },
            {   "numberOfDices", "Aantal dobbelstenen" },
            {   "one", "Een" },
            {   "two", "Twee" },
            {   "three", "Drie" },
            {   "showSum", "Toon som" },
            {   "outcome", "Uitkomst" },
            {   "numberOfDraws", "Aantal trekkingen" },
            {   "chance", "Kans" },
            {   "times", "keer uit" },
            {   "so", "wel" },
            {   "notso", "niet" },
            {   "step", "Stap" },
            {   "graph", "Grafiek" },
            {   "grid", "Rooster" },
            {   "execute", "Voer uit" },
            {   "erase", "Wis resultaten" },
            {   "execute1", "Voer" },
            {   "coins", "Munten" },
            {   "table", "Tabel" },
            {   "dice", "Dobbelstenen" },
            {   "binominalDraw", "Binominale trekking" },
            {   "grid", "Rooster" },
            {   "CBA_text.sample", "CSV Steekproeven" },
            {   "CBA_text.sampleProportion", "CSV Streekproefproporties" },
            {   "CBA_text.sampleCollection", "CSV Steekproef verzameling" },
            {   "sample", "Steekproef" },
            {   "sampleSize", "Steekproefgrootte" },
            {   "getSample", "Voer uit"},
            {   "getSample100Times", "Doe 100 keer" },
            {   "value", "Waarde" },
            {   "leftTable", "Linker tabel" },
            {   "rightTable", "Rechter tabel" },
            {   "steekproefInstellingenZichtbaar", "Instellingen zichtbaar"},
            {   "scheveVerdeling", "Voorbeeld scheve verdeling"},
            {   "populationProportion", "Populatieproportie" },
            {   "extraLabel", "Extra" },
            //{   "sampleSize", "Steekproeflengte" }
            //	{	"button1Label" , "text1_nl" },
		//	{ 	"button2Label" , "text2_nl" },
		//	....
		
		};
}


