<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.mathscratch</groupId>
    <artifactId>MathScratch-parent</artifactId>
    <version>0.0.4-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>
  <artifactId>mathscratch</artifactId>
  <name>MathScratch applet</name>
  <dependencies>
  	<dependency>
  		<groupId>fi.mathscratch</groupId>
  		<artifactId>mathscratch-common</artifactId>
  		<version>0.0.4-SNAPSHOT</version>
  	</dependency>
  	<dependency>
		<groupId>fi.wiskopdr.beans</groupId>
		<artifactId>wiskopdrbeans</artifactId>
		<version>1.0.3-SNAPSHOT</version>
  		<scope>provided</scope>
  	</dependency>
<!-- FIXME, make a dependency to the real uncompressed thing -->
		<dependency>
			<groupId>fi.wiskopdr</groupId>
			<artifactId>wiskopdr</artifactId>
			<version>2.0.3-SNAPSHOT</version>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.13.1</version>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
    		<groupId>fi.beans</groupId>
    		<artifactId>numworxlf</artifactId>
    		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo</groupId>
  		<artifactId>dwo-commons-lib</artifactId>
  		<scope>provided</scope>
  	</dependency>
  </dependencies>
  <packaging>bundle</packaging>
  <properties>
  		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  		<maven.compiler.source>1.8</maven.compiler.source>
  		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
  </properties>
  <build>
  	<finalName>${project.artifactId}</finalName>
    <plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>3.5.0</version>
				<extensions>true</extensions>
				<configuration>
					<createDependencyReducedPom>true</createDependencyReducedPom>
					<niceManifest>true</niceManifest>
					<dependencyReducedPomLocation>${basedir}/small-pom.xml</dependencyReducedPomLocation>
					<instructions>
   						<_snapshot>${osgi.qualifier}</_snapshot>
						<Bundle-SymbolicName>fi.mathscratch.MathScratch</Bundle-SymbolicName>
						<Export-Package>fi.mathscratch</Export-Package>
						<Require-Bundle>fi.wiskopdr.WiskOpdr</Require-Bundle>
						<Main-class>fi.mathscratch.MathScratch</Main-class>
						<Trusted-Only>true</Trusted-Only>
						<Permissions>all-permissions</Permissions>
						<Codebase>*.uu.nl *.dwo.nl localhost dme.mathhouse.org</Codebase>
						<Caller-Allowable-Codebase>*.uu.nl *.dwo.nl localhost</Caller-Allowable-Codebase>
						<Application-Name>MathScratch</Application-Name>
						<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
						<Embed-Transitive>true</Embed-Transitive>
 						<Embed-Dependency>*;scope=compile;type=!pom;inline=true</Embed-Dependency>
					</instructions>
				</configuration>
			</plugin>
    </plugins>
  </build>
</project>