package fi.statistiek.text;

public class Text_en extends java.util.ListResourceBundle
{
	public Object[][] getContents()
	{
		return contents;
	}

	static final Object[][] contents =
		{
				{ "addaviewKnopTekst", "Add a view: " },
				{ "chooseaviewOption", "Choose a view" },
				{ "changeviewnameDialog", "Change view name" },
				{ "enternameLabel", "Enter a new name" },
				{ "namealreadyinuseLabel",
					"This name is already in use. Enter a different name" },
				{ "dataeditableCheckBox", "Data is editable" },
				{ "viewseditableCheckBox", "Views are editable" },
				{ "viewsaddableCheckBox", "Views are addable" },
				{ "closetabToolTip", "close this tab" },
				{ "splitoptionsDialog", "Choose split options" },
				{ "splitoptionsButton", "Split" },
				{ "removeSplitoptionsButton", "Remove split" },
				{ "splitvariableLabel", "Split variable" },
				{ "splitsLabel", "Split" },
				{ "noneItem", "None" },
				{ "chooseItem", "Choose" },
				{ "doneButton", "Done" },
				{ "classDivisionLabel", "Bin properties" },
				{ "noClassesLabel", "Number of bins" },
				{ "labelBetweenBinsRadio", "labels between bins" },
				{ "labelUnderBinRadio", "labels under middle of bin" },
				{ "classesLabel", "Bins" },
				{ "autoButton", "Determine automatically" },
				{ "rowsLabel", "rows" },
				{ "columnsLabel", "columns" },
				{ "swapLabel", "Swap" },
				{ "swapTooltip", "Swap row and column variable" },
				{ "startvalueLabel", "Start value" },
				{ "minValueLabel", "Minimum value" },
				{ "maxValueLabel", "Maximum value" },
				{ "classwidthLabel", "Bin width" },
				{ "boundariesintervals", "Boundaries intervals: " },
				{ "boundariesintervalsLabel", "Boundaries intervals: " },
				{ "observationsLabel", "Observations" },
				{ "numberLabel", "No. of measurements: " },
				{ "minLabel", "Minimum: " },
				{ "minimum", "Minimum" },
				{ "maxLabel", "Maximum: " },
				{ "maximum", "Maximum" },
				{ "mean", "Mean" },
				{ "standardDeviation", "Standard deviation" },
				{ "median", "Median" },
				{ "mode", "Mode" },
				{ "minimumIs", "minimum = " },
				{ "tukeyMinimumIs", "smallest non-outlier = " },
				{ "firstQuartileIs", "1st quartile = " },
				{ "medianIs", "median = " },
				{ "thirdQuartileIs", "3rd quartile = " },
				{ "maximumIs", "maximum = " },
				{ "tukeyMaximumIs", "largest non-outlier = " },
				{ "valueIs", "value = " },
				{ "sortItem", "Sort" },
				{ "editcolumnItem", "Edit column" },
				{ "deletecolumnItem", "Delete column" },
				{ "infocolumnItem", "Column info" },
				{ "markOutlierCell", "Mark value as outlier" },
				{ "markOutlierRow", "Mark row as outlier" },
				{ "demarkOutlierCell", "Demark value as outlier" },
				{ "demarkOutlierRow", "Demark row as outlier" },
				{ "addrowButton", "Add a row" },
				{ "addcolumnButton", "Add a column" },
				{ "deleteselectedrowsButton", "Delete selected rows" },
				{ "pasteclipboardButton", "Paste from clipboard" },
				{ "resetButton", "Reset" },
				{ "importButton", "Open file" },
				{ "error", "Error" },
				{ "warning", "Warning" },
				{ "importWarning",
					"The table contains data. Opening a file will overwrite this data and delete the views." },
				{ "importCSVformatWarning",
					"The CSV file contains columns with the same name. This is not allowed. Use unique column names." },
				{ "binboundariesDialog", "Define bin boundaries" },
				{ "setupDialog", "Set up" },
				{ "viewnameLabel", "View name: " },
				{ "variableLabel", "Variable" },
				{ "variableXLabel", "Variable x-axis" },
				{ "variableYLabel", "Variable y-axis" },
				{ "axisLabel", "Variable axis" },
				{ "amountLabel", "Amount" },
				{ "splitsingleviewCheckBox", "split in one view" },
				{ "addacolumn", "Add a column" },
				{ "editacolumn", "Edit column" },
				{ "columninfo", "Column info" },
				{ "columnname", "Column name:" },
				{ "choosetype", "Choose type:" },
				{ "addenumeration", "Add enumeration element: " },
				{ "removeselectedelement", "Remove selected" },
				{ "removeAllElements", "Remove all" },
				{ "sortElements", "A-Z" },
				{ "sortElementsTooltip", "Sort A-Z" },
				{ "moveElementUpTooltip", "Move up" },
				{ "moveElementDownTooltip", "Move down" },
				{ "uitlegbijkolom", "Explanation with column:" },
				{ "splitdataButton", "Split data" },
				{ "tukeyCheckbox", "Tukey boxplot" },
				{ "verticalboxplotsRadio", "vertical boxplots" },
				{ "horizontalboxplotsRadio", "horizontal boxplots" },
				{ "variablexaxisLabel", "Variable x-axis" },
				{ "variableyaxisLabel", "Variable y-axis" },
				{ "usecolorscaleCheckbox", "Use color scale" },
				{ "variablecolorscaleLabel", "Variable color scale" },
				{ "showcorrelationCheckbox", "Show correlation" },
				{ "showpercentageCheckbox", "show percentage" },
				{ "showfrequencyCheckbox", "show frequency" },
				{ "numberofbinsLabel", "Number of bins" },
				{ "BoundariesButton", "Boundaries" },
				{ "binsButton", "Bins" },
				{ "hideButtonLabel", "Hide" },
				{ "showcumulativefrequencyCheckbox",
					"show cumulative frequency" },
				{ "totalLabel", "Total" },
				{ "percentageRadio", "Percentage" },
				{ "stackfrequencypolygonsCheckbox", "Stack frequency polygons" },
				{ "optimizeScaleBox", "Optimize scale" },
				{ "optimizeScaleXBox", "Optimize scale x-axis" },
				{ "optimizeScaleYBox", "Optimize scale y-axis" },
				{ "cumulativeCheckbox", "cumulative" },
				{ "tableOption", "Table" },
				{ "histogramOption", "Bar chart" },
				{ "dotplotOption", "Dotplot" },
				{ "frequencytableOption", "Frequency table" },
				{ "frequencypolygonOption", "Frequency polygon" },
				{ "boxplotOption", "Boxplot" },
				{ "crosstabOption", "Cross tab" },
				{ "scatterplotOption", "Scatterplot" },
				{ "descriptivesOption", "Descriptive statistics" },
				{ "settingsButton", "Settings" },
				{ "nexttoeachotherCheckbox", "Next to each other" },
				{ "chooseStartVarLabel", "Choose variable: " },
				{ "chooseStartVarRowLabel", "Choose variable rows: " },
				{ "chooseStartVarColumnLabel", "Choose variable columns: " },
				{ "chooseStartVarXLabel", "Choose variable x-axis: " },
				{ "chooseStartVarYLabel", "Choose variable y-axis: " },
				{ "chooseAVariableOption", "Choose variable" },
				{ "absRelLabel", "Display" },
				{ "nextToEachOtherRadioItem", "bars next to each other" },
				{ "aboveEachOtherRadioItem", "bars stacked" },
				{ "separateFromEachOtherRadioItem", "separate diagrams" },
				{ "percentageLabel", "Percentage" },
				{ "frequentieLabel", "Frequency" },
				{ "percentage_endTotal", "Overall total is 100%" },
				{ "percentage_rowTotal", "Row total is 100%" },
				{ "percentage_columnTotal", "Column total is 100%" },
				{ "percentage_splitTotal", "Split total is 100%" },
				{ "integer", "Whole number" },
				{ "double", "Decimal number" },
				{ "string", "Text" },
				{ "enum", "Enumeration" },
				{ "messageNrRowsMoreThan", "Number of rows is more than " },
				{ "messageChooseOtherVar", "Choose another variable." },
				{ "correlationNoShow", "Correlation cannot be calculated" },
				{ "significanceNoShow", "significance cannot be calculated" },
				{ "notAvailable", "Not available" },
				{ "selection", "selection" },
				{ "CBA_text.csv", "CSV-data" },

		// { "button1Label" , "text1_en" },
		// { "button2Label" , "text2_en" },
		// ....

		};
}
