<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>fi.wiskopdr</groupId>
  <artifactId>wiskopdr-parent</artifactId>
  <packaging>pom</packaging>
  <name>WiskopdrParent</name>
  <description>parent van WiskOpdr en java widgets</description>
    <parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>author-parent</artifactId>
	  <version>2.5.48-SNAPSHOT</version>
    </parent>
    <properties>
    		<proguard.lib>${java.home}/lib/rt.jar</proguard.lib>
    </properties>
 	<repositories>	<!-- als de mirror uit staat -->
                    <repository>
                     <id>numworx-dwo-openmath</id>
                     <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-openmath</url>
                  </repository>
                    <repository>
                     <id>numworx-dwo-project</id>
                     <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
                  </repository>
				<repository>
					<id>numworx-vendor-cbook</id>
                    <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-cbook</url>
				</repository>
				<repository>
					<id>numworx-vendor-jxbrowser</id>
                    <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-jxbrowser</url>
				</repository>
                    <repository>
                     <id>numworx-dwo-author</id>
                     <snapshots>
                        <enabled>true</enabled>
                     </snapshots>
                     <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-author</url>
                  </repository>
           <repository>
             <id>vaadin-addons</id>
             <url>https://maven.vaadin.com/vaadin-addons/</url>
           </repository>
   	</repositories>
    <build>
    	<pluginManagement>
    		<plugins>
  			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<version>2.0.14</version>
				<configuration>
					<proguardVersion>6.1</proguardVersion>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>net.sf.proguard</groupId>
						<artifactId>proguard-base</artifactId>
						<version>6.1.0</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
  			</plugin>
    		</plugins>    	
    	</pluginManagement>
         <plugins>
    		<plugin>
            	<groupId>external.atlassian.jgitflow</groupId>
            	<artifactId>jgitflow-maven-plugin</artifactId>
            	<version>1.0-m5.1</version>
            	<configuration>
                	<!-- see goals wiki page for configuration options -->
                	<flowInitContext>
             			<developBranchName>develop</developBranchName>  
             			<masterBranchName>main</masterBranchName>    	
                	</flowInitContext>
                	<localOnly>false</localOnly>
                	<allowSnapshots>false</allowSnapshots>
                	<enableSshAgent>true</enableSshAgent>
            	</configuration>
			  <dependencies>
			    <dependency>
			      <groupId>com.jcraft</groupId>
			      <artifactId>jsch</artifactId>
			      <version>0.1.54</version>
			    </dependency>
				<dependency>
				  <groupId>net.java.dev.jna</groupId>
				  <artifactId>jna-platform</artifactId>
				  <version>5.12.1</version>
				</dependency>
			  </dependencies>
        	</plugin>
        </plugins>
   </build>
    <modules>
    <module>../aimodel</module>
	<module>../AlgebraPijlenOpdr</module>
    	<module>../BalansFruitApplet</module>
	<module>../BinomVerdeling</module>
	<module>../CalculatorDwo</module>
	<module>../DoorzienDWO</module>
	<module>../Draaibank</module>
	<module>../euclides-parent</module>
	<module>../geodefiner</module>
	<module>../geodefiner-common</module>
	<module>../GeomAlgebra</module>
	<module>../GraphTool</module>
        <module>../IVMdraw-parent</module>
	<module>../JavaLogoWeb</module>
	<module>../JavaLogoWeb3d</module>
	<module>../Kladje</module>
	<module>../MozArch</module>
        <module>../NabouwenAanzichten</module>
        <module>../NormaleVerdeling</module>
	<module>../MathScratch</module>
	<module>../PreviewHTML</module>
	<module>../Repl</module>
	<module>../SamlLogin</module>
	<module>../SliderWidget</module>
	<module>../Statistiek</module>
	<module>../Stroomdiagrammen</module>
	<module>../Tegels</module>
	<module>../TekenVeelvlakOpdr</module>
	<module>../Verknippen</module>
	<module>../wiskopdrbeans</module>
    	<module>../WiskOpdr</module>
    	<module>../WiskOpdr-obf</module>
    	<module>../SQLite</module>
    	
    	<module>../Geogebra4Widget</module>
    	<module>../Geogebra3Widget</module>
    	<module>../StatSim</module>
    	<module>../Kansbomen</module>
    	<module>../Heks</module>
    	<module>../Spot_Problems_dwo</module>
    	<module>../AlgebraExpressies</module>
    	<module>../Grafiek3DTest</module>
        <module>../GeodeFull</module>
    </modules>
    <dependencyManagement>
       <dependencies>
                <dependency>
                        <groupId>fi.wiskopdr</groupId>
                        <artifactId>wiskopdr</artifactId>
                        <version>2.5.48-SNAPSHOT</version>
                </dependency>
               <dependency>
                        <groupId>fi.wiskopdr.beans</groupId>
                        <artifactId>wiskopdrbeans</artifactId>
                        <version>2.5.48-SNAPSHOT</version>
                </dependency>
      </dependencies>
    </dependencyManagement>
    <profiles>
	<profile>
		<id>running11</id>
		<activation>
			<jdk>[9,)</jdk>
		</activation>
		<properties>
			<proguard.lib>${java.home}/jmods</proguard.lib>
		</properties>
	</profile>
    </profiles>
</project>
