# nums1
pi:nums1
e:nums1
i:nums1
infinity:nums1
# transc1
cos:transc1
sin:transc1
tan:transc1
exp:transc1
ln:transc1
# arith1
root:arith1
plus:arith1
minus:arith1
times:arith1
divide:arith1
abs:arith1
power:arith1
# fns1
lambda:fns1
# complex1
argument:complex1
real:complex1
imaginary:complex1
conjugate:complex1
# minmax1
max:minmax1
min:minmax1


# plangeo1
are_on_line:plangeo1
incident:plangeo1

# plangeo7
length:plangeo7
area:plangeo7

# plangeo3, all about distance
distance:plangeo3
angle:plangeo3
are_on_circle:plangeo3
is_midpoint:plangeo3
parallel:plangeo3
perpendicular:plangeo3
center:plangeo3
# radius_of, center_of, tangent
# plangeo2
 
# relation1
eq:relation1
neq:relation1
geq:relation1
leq:relation1
lt:relation1
gt:relation1
#logic1
true:logic1
false:logic1
# extra
x:euclides
y:euclides
sqrt:euclides
ratio:euclides
P:euclides
visible:euclides
#extra's voor geodefiner
point:geodefiner
line:geodefiner
segment: geodefiner
circle: geodefiner
arc: geodefiner
polygon: geodefiner
curve: geodefiner
text: geodefiner