<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.ivmdraw</groupId>
    <artifactId>ivmdraw-parent</artifactId>
    <version>2.5.51-SNAPSHOT</version>
  </parent>
  <artifactId>ivmdraw</artifactId>
  <dependencies>
  	<dependency>
  		<groupId>fi.ivmdraw</groupId>
  		<artifactId>ivmdraw-common</artifactId>
  		<version>${project.version}</version>
  	</dependency>
  	<dependency>
		<groupId>fi.wiskopdr.beans</groupId>
		<artifactId>wiskopdrbeans</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>4.13.1</version>
  		<scope>test</scope>
  	</dependency>
  	<dependency>
    		<groupId>fi.beans</groupId>
    		<artifactId>numworxlf</artifactId>
    	</dependency>
  	<dependency>
  		<groupId>nl.uu.fi.dwo</groupId>
  		<artifactId>dwo-commons-lib</artifactId>
  	</dependency>
  </dependencies>
  <packaging>bundle</packaging>
  <properties>
  		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  		<maven.compiler.source>1.8</maven.compiler.source>
  		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
  </properties>
  <build>
  	<finalName>${project.artifactId}</finalName>
    <plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>3.5.0</version>
				<extensions>true</extensions>
				<configuration>
					<createDependencyReducedPom>true</createDependencyReducedPom>
					<niceManifest>true</niceManifest>
					<dependencyReducedPomLocation>${basedir}/small-pom.xml</dependencyReducedPomLocation>
					<instructions>
   						<_snapshot>${osgi.qualifier}</_snapshot>
						<Export-Package>fi.ivmdraw</Export-Package>
                        <Bundle-SymbolicName>fi.ivmdraw.IVMdraw</Bundle-SymbolicName>
						<Require-Bundle>fi.wiskopdr.WiskOpdr</Require-Bundle>
						<Main-class>fi.ivmdraw.IVMdraw</Main-class>
						<Trusted-Only>true</Trusted-Only>
						<Permissions>all-permissions</Permissions>
						<Codebase>*.uu.nl *.dwo.nl localhost dme.mathhouse.org</Codebase>
						<Caller-Allowable-Codebase>*.uu.nl *.dwo.nl localhost</Caller-Allowable-Codebase>
						<Application-Name>IVMdraw</Application-Name>
						<Application-Library-Allowable-Codebase>*</Application-Library-Allowable-Codebase>
						<Embed-Transitive>true</Embed-Transitive>
 						<Embed-Dependency>*;scope=compile;type=!pom;inline=true</Embed-Dependency>
					</instructions>
				</configuration>
			</plugin>
                    <plugin>
                        <groupId>com.github.batkinson.plugins</groupId>
                        <artifactId>maven-pack200-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <id>pack-jars</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>pack</goal>
                                </goals>
                                <configuration>
                                    <normalizeOnly>false</normalizeOnly>
                            		<processMainArtifact>true</processMainArtifact>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>        
    </plugins>
  </build>
</project>
