<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>proguard</artifactId>
	<version>2.0.3-SNAPSHOT</version>
	<packaging>pom</packaging>
	<parent>
	  <groupId>fi.wiskopdr</groupId>
	  <artifactId>author-parent</artifactId>
	  <version>1.0.0-SNAPSHOT</version>
	</parent>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>stap1</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<phase>${extras.process}</phase>
						<configuration>
							<outputDirectory>${project.build.directory}</outputDirectory>
							<includeScope>compile</includeScope>
							<excludeArtifactIds>wiskopdr,balansfruitapplet,graphtool,geodefiner,statistiek,mathscratch,geogebra3widget,geogebra4widget</excludeArtifactIds>
							<stripVersion>true</stripVersion>
							<stripClassifier>true</stripClassifier>
						</configuration>
					</execution>
					<execution>
						<id>stap2</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<phase>process-classes</phase>
						<configuration>
							<includeScope>compile</includeScope>
							<includeArtifactIds>wiskopdr,balansfruitapplet,graphtool,geodefiner,statistiek,mathscratch,geogebra3widget,geogebra4widget</includeArtifactIds>
							<stripVersion>true</stripVersion>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<version>2.0.14</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<proguardVersion>6.1</proguardVersion>
					<options>
						<option>-verbose</option>
						<option>-dontwarn</option>
						<option>-printconfiguration target/mapping.txt</option>
					</options>
					<obfuscate>true</obfuscate>
					<!-- uncomment to change the output file <outputDirectory>${project.build.directory}</outputDirectory> 
						<outjar>${project.build.finalName}.jar</outjar> -->
					<exclusions>
						<exclusion>
							<groupId>fi.wiskopdr</groupId>
							<artifactId>wiskopdr</artifactId>
						</exclusion>
						<exclusion>
							<groupId>fi.graphtool</groupId>
							<artifactId>graphtool</artifactId>
						</exclusion>
						<exclusion>
							<groupId>fi.balansfruitapplet</groupId>
							<artifactId>balansfruitapplet</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.numworx.geodefiner</groupId>
							<artifactId>geodefiner</artifactId>
						</exclusion>
						<exclusion>
							<groupId>fi.statistiek</groupId>
							<artifactId>statistiek</artifactId>
						</exclusion>
						<exclusion>
							<groupId>fi.mathscrath</groupId>
							<artifactId>mathscratch</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.numworx.geogebra</groupId>
							<artifactId>geogebra3widget</artifactId>
						</exclusion>
						<exclusion>
							<groupId>nl.numworx.geogebra</groupId>
							<artifactId>geogebra4widget</artifactId>
						</exclusion>
					</exclusions>
					<proguardInclude>toolfiles/config.pro</proguardInclude>
					<libs>
						<lib>${proguard.lib}</lib>
					</libs>
					<addMavenDescriptor>false</addMavenDescriptor>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>net.sf.proguard</groupId>
						<artifactId>proguard-base</artifactId>
						<version>6.1.0</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.8</version>
				<executions>
					<execution>
						<goals>
							<goal>run</goal>
						</goals>
						<phase>${extras.phase}</phase>
						<configuration>
							<target>
								<jar destfile="${project.build.directory}/wiskopdr.jar" update="true" index="true">
									<indexjars>
										<fileset dir="${project.build.directory}" includes="*.jar" excludes="*proguard*" />
									</indexjars>
								</jar>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
		<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>attach-artifacts</id>
            <phase>${extras.phase}</phase>
            <goals>
              <goal>attach-artifact</goal>
            </goals>
            <configuration>
              <artifacts>
                <artifact>
                  <file>${project.build.directory}/wiskopdr.jar</file>
                  <type>jar</type>
                  <classifier>wiskopdr</classifier>
                </artifact>
                <artifact>
                  <file>${project.build.directory}/graphtool.jar</file>
                  <type>jar</type>
                  <classifier>graphtool</classifier>
                </artifact>
               <artifact>
                  <file>${project.build.directory}/balansfruitapplet.jar</file>
                  <type>jar</type>
                  <classifier>balansfruitapplet</classifier>
                </artifact>
                <artifact>
                  <file>${project.build.directory}/geodefiner.jar</file>
                  <type>jar</type>
                  <classifier>geodefiner</classifier>
                </artifact>
                <artifact>
                  <file>${project.build.directory}/statistiek.jar</file>
                  <type>jar</type>
                  <classifier>statistiek</classifier>
                </artifact>
                <artifact>
                  <file>${project.build.directory}/mathscratch.jar</file>
                  <type>jar</type>
                  <classifier>mathscratch</classifier>
                </artifact>
                <artifact>
                  <file>${project.build.directory}/geogebra3widget.jar</file>
                  <type>jar</type>
                  <classifier>geogebraold</classifier>
                </artifact>
                <artifact>
                  <file>${project.build.directory}/geogebra4widget.jar</file>
                  <type>jar</type>
                  <classifier>geogebranew</classifier>
                </artifact>
               </artifacts>
            </configuration>
          </execution>
        </executions>
      </plugin>
                    <plugin>
                        <groupId>com.github.batkinson.plugins</groupId>
                        <artifactId>maven-pack200-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <id>pack-jars</id>
                                <phase>${extras.verify}</phase>
                                <goals>
                                    <goal>pack</goal>
                                </goals>
                                <configuration>
                                    <normalizeOnly>false</normalizeOnly>
                                </configuration>
                            </execution>
                        </executions>
                        <configuration>
                            <processMainArtifact>false</processMainArtifact>
                            <includeClassifiers>
                                <includeClassifier>graphtool</includeClassifier>
                                <includeClassifier>wiskopdr</includeClassifier>
                                <includeClassifier>geodefiner</includeClassifier>
                                <includeClassifier>balansfruitapplet</includeClassifier>
                                <includeClassifier>statistiek</includeClassifier>
                                <includeClassifier>mathscratch</includeClassifier>
                                <includeClassifier>geogebraold </includeClassifier>
                                <includeClassifier>geogebranew </includeClassifier>
                            </includeClassifiers>
                        </configuration>                
                    </plugin>        
		</plugins>
	</build>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.test.skip>true</maven.test.skip>
		<extras.phase>package</extras.phase>
		<extras.verify>verify</extras.verify>
		<extras.process>process-classes</extras.process>
		<proguard.lib>${java.home}/lib/rt.jar</proguard.lib>
		<jxb>7.28.1</jxb>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
	</properties>
	<dependencies>
		<!-- #fi.verknippen #fi.mozarch #fi.tegels #fi.geomalgebra #fi.stroomdiagrammen 
			#fi.statistiek #fi.doorziendwo.DoorzienDWO: doorziendwo.jar #fi.dataplot.DataPlot: -->
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwo-commons-lib</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geodefiner</groupId>
			<artifactId>geodefiner</artifactId>
			<version>0.0.6-SNAPSHOT</version>	
		</dependency>
		<dependency>
			<groupId>fi.mozarch</groupId>
			<artifactId>mozarch</artifactId>
			<version>0.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.tegels</groupId>
			<artifactId>tegels</artifactId>
			<version>0.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
		  	<groupId>fi.wiskopdr</groupId>
	  		<artifactId>uploadwidgetrm</artifactId>
	  		<version>2.5.47-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.geomalgebra</groupId>
			<artifactId>geomalgebra</artifactId>
			<version>0.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.stroomdiagrammen</groupId>
			<artifactId>stroomdiagrammen</artifactId>
			<version>0.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.statistiek</groupId>
			<artifactId>statistiek</artifactId>
			<version>1.0.3-SNAPSHOT</version>
			<classifier>jar-with-dependencies</classifier>
			<exclusions>
				<exclusion>
					<groupId>org.knowm.xchart</groupId>
					<artifactId>xchart</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.knowm.xchart</groupId>
					<artifactId>xchart-demo</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.doorziendwo</groupId>
			<artifactId>doorziendwo</artifactId>
			<version>0.0.4-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>fi.balansfruitapplet</groupId>
			<artifactId>balansfruitapplet</artifactId>
			<version>0.0.4-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.graphtool</groupId>
			<artifactId>graphtool</artifactId>
			<version>0.0.4-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<groupId>fi.beans</groupId>
					<artifactId>lineairealgebra</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.wiskopdr</groupId>
			<artifactId>wiskopdr</artifactId>
			<version>2.0.3-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.verknippen</groupId>
			<artifactId>verknippen</artifactId>
			<version>0.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.mathscratch</groupId>
			<artifactId>mathscratch</artifactId>
			<version>0.0.4-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx.geogebra</groupId>
			<artifactId>geogebra3widget</artifactId>
			<version>1.0.3-SNAPSHOT</version>
		</dependency>
			<dependency>
			  	<groupId>nl.numworx.geogebra</groupId>
		  		<artifactId>geogebra4widget</artifactId>
		  		<version>1.0.3-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>fi.wiskopdr.beans</groupId>
				<artifactId>wiskopdrbeans</artifactId>
				<version>1.0.3-SNAPSHOT</version>
			</dependency>
	</dependencies>
	<name>WiskOpdr obfuscated</name>
	<profiles>
	<profile>
		<id>running11</id>
		<activation>
			<jdk>[9,)</jdk>
		</activation>
		<properties>
			<proguard.lib>${java.home}/jmods</proguard.lib>
		</properties>
	</profile>
	</profiles>
</project>
